### ISSUE TITLE
Consider rendering a single full-screen quad

### ISSUE THREAD

**Issue by Diggsey** [alacritty/alacritty#100]
It looks like you are creating the grid with vertexdata?

Since you are rendering a fixed size grid, you can achieve everything from the pixel shader:
- Bind two textures, the glyph atlas, and one other
- The other texture is the size of the grid and stores the UV coord of the glyph at that cell
- The pixel shader samples one texture, and uses the UV coordinates from that to sample the glyph atlas
- Changes to what's on-screen are as simple as a memory copy into a subregion of the grid texture

**Comment by jwilm** [comment]
This definitely sounds worth investigating. Thanks for the suggestion!

**Comment by jwilm** [comment]
As it turns out, this is basically what we're doing. Instead of a texture for glyph data, it gets loaded into a VBO in one call.

**Comment by jwilm** [comment]
Oh, nevvermind. I misunderstood. Leaving this open for now.

**Comment by jwilm** [comment]
Does this really help that much? Almost seems like it's more work for the GPU total. Current strategy with VBO just means that the vertex shader is running as well, but it means less work for fragment shader.

I have no idea how to think about how this would perform. Might be more memory to move to the GPU in total, and more work for fragment shader, but maybe it's better because vertex shader isn't doing anything.

**Comment by Diggsey** [comment]
No idea, it would need to be measured. However, it should reduce the amount of rasterization required (one quad instead of 10,000 or so) and it should be slightly faster to update, since texture data is simpler than vertex data (no position info required) and because you can easily update any sub-rectangle on the texture, which maps conveniently onto typical terminal operations, instead of having to update an entire vertex buffer. Not to mention being able to implement update common operations directly on the GPU, such as scrolling.

**Comment by unphased** [comment]
Should reduce bus bandwidth for vertex data (by eliminating the use of vertices altogether), clever. worth evaluating, and then also evaluating on a 4K window with a tiny font. 😋

**Comment by kchibisov** [comment]
We've tried that and the main issue is that you don't know exactly how to draw and you should support overlapping glyph. When you draw and cut everything within the cell boundaries it's fast, however when you start accounting for font drawing out of cell boundaries(emoji,italic font) the end performance start to become as an instancing approach if not worse, since the shader becomes very complex.

Not to mention that having large shaders won't work on very low end hardware, where you have 64 operations at max.
