### ISSUE TITLE
Scrollback Buffer Search

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#1017]
Once we have scrollback (#124), it's pretty reasonable to want to be able to search that. The challenge here is building something that works well, while still feeling simple, clean and lightweight. This is I believe the first "mode" proposed to alacritty. As in I hit some key binding and suddenly the rules for what my keys do has changed. I can't think of any other modes right now, but maybe that helps inspire the design.

Anyway sorry for getting ahead of things here, but this is a feature I'm dying to have. For now re-running the command and passing it to `rg` will have to suffice.

**Comment by alexozer** [comment]
A line must be drawn at some point though to delegate to tmux. I'm wondering if implementing scrollback search in a mode would be a slippery slope to implementing something like termite's entire selection mode, and whether that's in scope simplicity and performance-wise here.

**Comment by maximbaz** [comment]
Search is one of the reasons I will keep using tmux even after scrollback is merged, assuming #1000 is implemented too. 

I was considering to report this exact feature request myself a few days ago, but then I thought of what search capabilities I use today in tmux, and I realized that reimplementing them natively in alacritty would be too expensive, so I don't think vanilla alacritty will ever suffice my needs. 

I support the feature request, perhaps for many people that all they need, but here's for the reference the list of search capabilities that I identified as currently used by me with tmux:

- Incremental search (not type-then-search)
- Prepared search queries (e.g. `❯` is my prompt character, and I have a tmux shortcut that starts a search for the character `❯`, which allows me to jump to previous prompts in one key press)
- Visual selection (i.e. once you find something in the scrollback history (e.g. start of a log entry), use keyboard shortcuts to expand the selection (e.g. to select the entire log entry)
- Operations on the visual selection (via `tmux-yank` plugin):
    - Copy the selection to clipboard
    - Paste the selection to the prompt directly without copying it to clipboard
- Fuzzy-search + smart text blocks extraction (via `extrakto` plugin):
    - Open URL in browser
    - Open file path in the text editor
    - Copy to clipboard
    - and many more.

And after I saw this list, I realized that this is too much for alacritty, so I'll always be using tmux.

**Comment by chrisduerr** [comment]
I'm not saying something like a vim-mode might solve all of those. But it kinda would.

**Comment by maximbaz** [comment]
All of these a kinda _possible_ even with a simple scrollback search and then grabbing a mouse to select what you need, a simple vim-mode would allow to avoid reaching for the mouse, but the experience would still not be as nice/simple as the approach that I currently have, no incremental or fuzzy search, no prepared search queries, etc.

By the way, do you want to create a new feature request for the post-scrollback era: implement vim-mode? 😛

**Comment by chrisduerr** [comment]
Incremental search and fuzzy search would be no problem with a vim mode and a bit of regex.

I've actually never used vim mode much with termite. Imo it's useful for stuff like selection though.

**Comment by alexozer** [comment]
Maybe "implement vim mode" is worthy of being a RFC?

**Comment by maximbaz** [comment]
I think yes, please create the issue for it.

**Comment by jwilm** [comment]
We might consider using [ripgrep's internals](https://docs.rs/grep/0.1.7/grep/index.html) if we decide to add this. Primary challenges with supporting search:

- Scrollback history would need to have a `String` representation to make it searchable
- If we want to support searches across line breaks, we would need to map String bytes offsets to lines and columns
- Keeping active region in a searchable String would be expensive since it can be updated very frequently.

**Comment by nixpulvis** [comment]
I just want to mention that I have no plans on using tmux on a regular basis. I know that most people here use it, and that Alacritty was (at least originally) designed to work assumeing you were using tmux, but... I feel this terminal has great potential on its own, and for some features like this one (imo) the complexity gain is worth it.

**Comment by Klemetz** [comment]
Could someone point me in the direction if someone is already working on the Scrollback issue. It sounds intriguing and I feel like contributing. Because when I look at the issue for scrollback, I can't see that anyone has assigned themselves to it. It might just be my ignorance.

**Comment by chrisduerr** [comment]
@nixpulvis That would definitely be a possibility, however searching through the buffer itself shouldn't be extremely difficult either.

So the question is more which of these is simpler for the user and for maintenance. I think with these things considered just dumping the grid into a pager is a bit more straight-forward and doesn't introduce a lot of new things into Alacritty.

**Comment by WloHu** [comment]
I believe that "selection mode" was mentioned here: https://github.com/jwilm/alacritty/issues/262 and this would for sure solve that issue. IMO issue should be linked.

For similar reason as @maximbaz mentioned, I use `tmux` only because of "copy mode" search and modal scrolling. For that purpose I've 2 key bindings to enter that mode: regular and another which automaticly puts me in "seach-backward". For me this is crutial because otherwise I would drown myself in criptic keybindings just to manage separation for `alacritty`, `i3` and `vim`.

**Comment by lachesis** [comment]
@jwilm what about allowing rendering and export of the terminal scrollback to a file or piping to a process to do the search? Would that be easier and/or faster than trying to maintain a separate String representation? I am currently moving over from `termite` because Alacritty's lower latency is very attractive, but inability to search my scrollback (the only thing I use termite's vim-mode for) is very limiting.

**Comment by Ramkumar47** [comment]
is it possible to access scrollback history? so that i can use external scripts to do an external scroll-back-search and url dump

**Comment by kchibisov** [comment]
>is it possible to access scrollback history? so that i can use external scripts to do an external scroll-back-search and url dump

You can select and paste it to file, we have an issue about dumping scrollback here #3289

**Comment by Ramkumar47** [comment]
> You can select and paste it to file, we have an issue about dumping scrollback here #3289

oh ok.. thanks

**Comment by rishabh96b** [comment]
Awesome. I was looking for this feature and it is coming soon. Thanks @chrisduerr !
