### ISSUE TITLE
Flickering in neovim with completions

### ISSUE THREAD

**Issue by MaikKlein** [alacritty/alacritty#1084]
Which operating system does the issue occur on?

Arch

If on linux, are you using X11 or Wayland?

X11

I get flickering with alacritty when neovim draws the completion window. I tried to record it but the flickering does not appear in the gif below. This does not happen in urxvt.
![](https://i.imgur.com/VBalltx.gif)
Any ideas? It looks as if the completion window does not get drawn in the first frame after an redraw update.

**Comment by MaikKlein** [comment]
Actually if I am fast enough, the flicker will show in the gif

![](https://i.imgur.com/rB8uyuT.gif)

The two lines below the completions should always be hidden by the completion window, but sometimes they are not.

**Comment by admmasters** [comment]
Same issue on OSX

**Comment by cryptoeraser** [comment]
Same here. OSX / vim / YcM (for completion).

**Comment by Asheq** [comment]
For me, setting the `lazyredraw` option off in vim helps (use `:set nolazyredraw`). Does it help for the rest of you? If so, this may help pinpoint the problem.

I still think alacritty should be able to avoid flickering regarless of the value of the `lazyredraw` option in vim, because other terminals are able to do so.

**Comment by Karmenzind** [comment]
Same issue on Arch and Vim 8.1.
@Asheq `nolazyredraw` didn't help.

**Comment by darthdeus** [comment]
Same issue here on OSX / neovim / deoplete.vim ... `nolazyredraw` also didn't help.

**Comment by riteme** [comment]
Same issue on Ubuntu 18.04 / Neovim / YouCompleteMe.

But I think it may not be an issue with alacritty. Actually only "Gnome Terminal + Vim" works fine on my computer. Maybe alacritty is too fast ;)

**Comment by Karmenzind** [comment]
@riteme  I also use alacritty. I found there's no flickering while editing a single file with xfce terminal or other terminals. But the flickering still happened in huge projects no matter what terminal I use.

**Comment by cryptoeraser** [comment]
Hello Everyone!
Any updates on this issue? Thanks!

**Comment by chrisduerr** [comment]
@cryptoeraser If you're interested in staying up to date, please use github to watch this issue.

The only way to get something done asap is to work on it yourself. I'm always happy to help out if you want to look at it.

**Comment by cryptoeraser** [comment]
@chrisduerr Sure. Thanks. I am not good with `rust` and `system programming` :) So I guess I will wait. I just wanted to check for the possibility that this might have been fixed in the updates that followed after I have built and installed Alacritty. Watching this closely cause I love Alacritty and the only broken bit in my pipeline is the flickering with YouCompleteMe. Cheers.

**Comment by kchibisov** [comment]
I've never seen a flickering in vim/neovim with completion recently, in any way, this issue seems like vim/neovim don't write content during one write call, which is really hard to do, and since alacritty drawing things fast you can see some flicking some times. However there're some escapes proposed in terminal-wg to solve it and it tracked here #2919 .
