### ISSUE TITLE
setting decorations to false crashes Gnome under Linux

### ISSUE THREAD

**Issue by burningTyger** [alacritty/alacritty#1096]
When I'm setting `decorations: false` GNOME crashes.

Which operating system does the issue occur on?
I'm on Arch using the aur repo install

If on linux, are you using X11 or Wayland?
Yes, GNOME/Wayland

I'm happy to provide more info if necessary

**Comment by kakposoe** [comment]
@burningTyger Also experienced the same issue.  I'm on Ubuntu

**Comment by jwilm** [comment]
Can you provide any sort of debug information from the crash?

**Comment by passcod** [comment]
Right, ok, I can see this as well. I'll try to include all I can but for obvious reasons I don't want to repeat this all the time.

<details>
<summary>Gnome crashes</summary>
<pre><code>
Feb 14 12:04:32 kare-kun systemd-coredump[9050]: Process 1013 (gnome-shell) of user 1000 dumped core.

   Stack trace of thread 1013:
   #0  0x00007f9e950957cc n/a (libmozjs-52.so.0)
   #1  0x00007f9e954eff5d n/a (libmozjs-52.so.0)
   #2  0x00007f9e954f0f7f n/a (libmozjs-52.so.0)
   #3  0x00007f9e953bc3eb n/a (libmozjs-52.so.0)
   #4  0x00007f9e953bd074 n/a (libmozjs-52.so.0)
   #5  0x00007f9e954f8cad n/a (libmozjs-52.so.0)
   #6  0x00002183171da6d6 n/a (n/a)
   #7  0x0000560c63a1cbb0 n/a (n/a)
   #8  0x00002183171d0888 n/a (n/a)
   #9  0x00007f9e954f111f n/a (libmozjs-52.so.0)
   #10 0x00007f9e954f149b n/a (libmozjs-52.so.0)
   #11 0x00007f9e953bc454 n/a (libmozjs-52.so.0)
   #12 0x00007f9e953bd074 n/a (libmozjs-52.so.0)
   #13 0x00007f9e953bd528 n/a (libmozjs-52.so.0)
   #14 0x00007f9e95192116 _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE (libmozjs-52.so.0)
   #15 0x00007f9e9ca9d018 gjs_call_function_value (libgjs.so.0)
   #16 0x00007f9e9ca6cf89 gjs_closure_invoke (libgjs.so.0)
   #17 0x00007f9e9ca8ba6f n/a (libgjs.so.0)
   #18 0x00007f9e9dd99c5d g_closure_invoke (libgobject-2.0.so.0)
   #19 0x00007f9e9ddadb50 n/a (libgobject-2.0.so.0)
   #20 0x00007f9e9ddb6806 g_signal_emit_valist (libgobject-2.0.so.0)
   #21 0x00007f9e9ddb7240 g_signal_emit (libgobject-2.0.so.0)
   #22 0x00007f9e9c73e06d n/a (libmutter-clutter-1.so)
   #23 0x00007f9e9dda0849 g_object_run_dispose (libgobject-2.0.so.0)
   #24 0x00007f9e9c73189f clutter_actor_destroy (libmutter-clutter-1.so)
   #25 0x00007f9e982131c8 ffi_call_unix64 (libffi.so.6)
   #26 0x00007f9e98212c2a ffi_call (libffi.so.6)
   #27 0x00007f9e9ca72cab n/a (libgjs.so.0)
   #28 0x00007f9e9ca74607 n/a (libgjs.so.0)
   #29 0x00007f9e953bd211 n/a (libmozjs-52.so.0)
   #30 0x00007f9e953c2d81 n/a (libmozjs-52.so.0)
   #31 0x00007f9e953bc31e n/a (libmozjs-52.so.0)
   #32 0x00007f9e953bd074 n/a (libmozjs-52.so.0)
   #33 0x00007f9e953bd528 n/a (libmozjs-52.so.0)
   #34 0x00007f9e95147a43 n/a (libmozjs-52.so.0)
   #35 0x00002183171d5ab6 n/a (n/a)
   #36 0x00007f9e9506af3d n/a (libmozjs-52.so.0)
   #37 0x00007f9e953cf7a6 n/a (libmozjs-52.so.0)
   #38 0x00007f9e953bc31e n/a (libmozjs-52.so.0)
   #39 0x00007f9e953bd074 n/a (libmozjs-52.so.0)
   #40 0x00007f9e954f8cad n/a (libmozjs-52.so.0)
   #41 0x00002183171da6d6 n/a (n/a)
   #42 0x0000560c63a1cbb0 n/a (n/a)
   #43 0x00002183171d0888 n/a (n/a)
   #44 0x00007f9e954f111f n/a (libmozjs-52.so.0)
   #45 0x00007f9e954f149b n/a (libmozjs-52.so.0)
   #46 0x00007f9e953bc454 n/a (libmozjs-52.so.0)
   #47 0x00007f9e953bd074 n/a (libmozjs-52.so.0)
   #48 0x00007f9e953bd528 n/a (libmozjs-52.so.0)
   #49 0x00007f9e95192116 _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE (libmozjs-52.so.0)
   #50 0x00007f9e9ca9d018 gjs_call_function_value (libgjs.so.0)
   #51 0x00007f9e9ca6cf89 gjs_closure_invoke (libgjs.so.0)
   #52 0x00007f9e9ca8ba6f n/a (libgjs.so.0)
   #53 0x00007f9e9dd99c5d g_closure_invoke (libgobject-2.0.so.0)
   #54 0x00007f9e9ddadb50 n/a (libgobject-2.0.so.0)
   #55 0x00007f9e9ddb6806 g_signal_emit_valist (libgobject-2.0.so.0)
   #56 0x00007f9e9ddb7240 g_signal_emit (libgobject-2.0.so.0)
   #57 0x00007f9e9c73e06d n/a (libmutter-clutter-1.so)
   #58 0x00007f9e9dda0849 g_object_run_dispose (libgobject-2.0.so.0)
   #59 0x00007f9e9c73189f clutter_actor_destroy (libmutter-clutter-1.so)
   #60 0x00007f9e9bff42c2 meta_window_unmanage (libmutter-1.so.0)
   #61 0x00007f9e9c025f26 meta_wayland_surface_destroy_window (libmutter-1.so.0)
   #62 0x00007f9e9c02b40d n/a (libmutter-1.so.0)
   #63 0x00007f9e939b4c12 n/a (libwayland-server.so.0)

   Stack trace of thread 1016:
   #0  0x00007f9e9e8c297b __poll (libc.so.6)
   #1  0x00007f9e9dabfff3 n/a (libglib-2.0.so.0)
   #2  0x00007f9e9dac03b2 g_main_loop_run (libglib-2.0.so.0)
   #3  0x00007f9e9e0b46d8 n/a (libgio-2.0.so.0)
   #4  0x00007f9e9dae826a n/a (libglib-2.0.so.0)
   #5  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #6  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1018:
   #0  0x00007f9e9e8c297b __poll (libc.so.6)
   #1  0x00007f9e9dabfff3 n/a (libglib-2.0.so.0)
   #2  0x00007f9e9dac010e g_main_context_iteration (libglib-2.0.so.0)
   #3  0x00007f9e863e0b0e n/a (libdconfsettings.so)
   #4  0x00007f9e9dae826a n/a (libglib-2.0.so.0)
   #5  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #6  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1015:
   #0  0x00007f9e9e8c297b __poll (libc.so.6)
   #1  0x00007f9e9dabfff3 n/a (libglib-2.0.so.0)
   #2  0x00007f9e9dac010e g_main_context_iteration (libglib-2.0.so.0)
   #3  0x00007f9e9dac0162 n/a (libglib-2.0.so.0)
   #4  0x00007f9e9dae826a n/a (libglib-2.0.so.0)
   #5  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #6  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1062:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1058:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1056:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1060:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1057:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1053:
   #0  0x00007f9e9e8c297b __poll (libc.so.6)
   #1  0x00007f9e76a6c773 n/a (libpulse.so.0)
   #2  0x00007f9e76a5dbd0 pa_mainloop_poll (libpulse.so.0)
   #3  0x00007f9e76a5e271 pa_mainloop_iterate (libpulse.so.0)
   #4  0x00007f9e76a5e301 pa_mainloop_run (libpulse.so.0)
   #5  0x00007f9e76a6c6ae n/a (libpulse.so.0)
   #6  0x00007f9e7680b81c n/a (libpulsecommon-11.1.so)
   #7  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #8  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1061:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1059:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 1063:
   #0  0x00007f9e9eb9b3bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007f9e94fb24ad n/a (libmozjs-52.so.0)
   #2  0x00007f9e953d059a n/a (libmozjs-52.so.0)
   #3  0x00007f9e9539c49a n/a (libmozjs-52.so.0)
   #4  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #5  0x00007f9e9e8cce7f __clone (libc.so.6)

   Stack trace of thread 8907:
   #0  0x00007f9e9e8c7879 syscall (libc.so.6)
   #1  0x00007f9e9db06dcd g_cond_wait_until (libglib-2.0.so.0)
   #2  0x00007f9e9da93753 n/a (libglib-2.0.so.0)
   #3  0x00007f9e9da93d3e g_async_queue_timeout_pop (libglib-2.0.so.0)
   #4  0x00007f9e9dae8d81 n/a (libglib-2.0.so.0)
   #5  0x00007f9e9dae826a n/a (libglib-2.0.so.0)
   #6  0x00007f9e9eb9508c start_thread (libpthread.so.0)
   #7  0x00007f9e9e8cce7f __clone (libc.so.6)
</code></pre>
</details>

<details>
<summary>Gnome crashes because XWayland crashes</summary>
<pre><code>
Feb 14 12:04:25 kare-kun systemd-coredump[9062]: Process 1037 (Xwayland) of user 1000 dumped core.

   Stack trace of thread 1037:
   #0  0x00007fdc86993860 raise (libc.so.6)
   #1  0x00007fdc86994ec9 abort (libc.so.6)
   #2  0x000055b879806c6a OsAbort (Xwayland)
   #3  0x000055b87980c783 n/a (Xwayland)
   #4  0x000055b87980d5a5 FatalError (Xwayland)
   #5  0x000055b879698bdf n/a (Xwayland)
   #6  0x000055b8798047e1 n/a (Xwayland)
   #7  0x000055b8797fd68b WaitForSomething (Xwayland)
   #8  0x000055b8797c9493 n/a (Xwayland)
   #9  0x000055b8797cd730 n/a (Xwayland)
   #10 0x00007fdc8697ff4a __libc_start_main (libc.so.6)
   #11 0x000055b87969823a _start (Xwayland)

   Stack trace of thread 1040:
   #0  0x00007fdc86d233bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007fdc805ed5d4 n/a (swrast_dri.so)
   #2  0x00007fdc805ed428 n/a (swrast_dri.so)
   #3  0x00007fdc86d1d08c start_thread (libpthread.so.0)
   #4  0x00007fdc86a54e7f __clone (libc.so.6)

   Stack trace of thread 1041:
   #0  0x00007fdc86d233bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007fdc805ed5d4 n/a (swrast_dri.so)
   #2  0x00007fdc805ed428 n/a (swrast_dri.so)
   #3  0x00007fdc86d1d08c start_thread (libpthread.so.0)
   #4  0x00007fdc86a54e7f __clone (libc.so.6)

   Stack trace of thread 1038:
   #0  0x00007fdc86d233bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007fdc805ed5d4 n/a (swrast_dri.so)
   #2  0x00007fdc805ed428 n/a (swrast_dri.so)
   #3  0x00007fdc86d1d08c start_thread (libpthread.so.0)
   #4  0x00007fdc86a54e7f __clone (libc.so.6)

   Stack trace of thread 1039:
   #0  0x00007fdc86d233bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
   #1  0x00007fdc805ed5d4 n/a (swrast_dri.so)
   #2  0x00007fdc805ed428 n/a (swrast_dri.so)
   #3  0x00007fdc86d1d08c start_thread (libpthread.so.0)
   #4  0x00007fdc86a54e7f __clone (libc.so.6)
</code></pre>
</details>

<details>
<summary>Xwayland crashes because Gnome Shell crashes</summary>
<pre><code>
Feb 14 12:04:17 kare-kun gnome-session[991]: gnome-session-binary[991]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Feb 14 12:04:17 kare-kun gnome-session-binary[991]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Feb 14 12:04:17 kare-kun gnome-session-binary[991]: Unrecoverable failure in required component org.gnome.Shell.desktop
</code></pre>
</details>

<details open>
<summary>and Gnome Shell crashes because Alacritty does something wrong which causes the graphics to run out of memory or something like it</summary>
<pre><code>
Feb 14 12:04:13 ...alacritty is started here...
Feb 14 12:04:14 kare-kun gnome-shell[1013]: Could not import pending buffer: Out of memory
Feb 14 12:04:14 kare-kun Alacritty.desktop[8905]: wl_surface@11: error 2: Failed to create a texture for surface 11: Out of memory
Feb 14 12:04:14 kare-kun Alacritty.desktop[8905]: thread 'main' panicked at 'Wayland connection lost.: Error { repr: Os { code: 71, message: "Protocol error" } }', src/libcore/result.rs:906:4
Feb 14 12:04:14 kare-kun Alacritty.desktop[8905]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Feb 14 12:04:14 kare-kun kernel: gnome-shell[1013]: segfault at 0 ip 00007f9e950957cc sp 00007fff3448bd90 error 6 in libmozjs-52.so[7f9e94e2f000+9dc000]
Feb 14 12:04:14 kare-kun systemd[1]: Started Process Core Dump (PID 9049/UID 0).
</code></pre>
</details>

Built by the folks over at [archlinuxcn](https://github.com/archlinuxcn), which I believe is a straight build of the Arch Linux AUR pkgbuild. Full version: `0.1.0.732.g2466f81-1`, built on `Thu 01 Feb 2018 06:25:04 NZDT`.

**Comment by jwilm** [comment]
@passcod thank you so much for going to the troubles of collecting those logs.

@vberger do you have any intuition about what might be happening here? I'm not sure where to start on this one. The logs provided above don't include a full stack trace from Alacritty, but there is one error message that may be illuminating for someone more familiar with Wayland.

    wl_surface@11: error 2: Failed to create a texture for surface 11: Out of memory

**Comment by burningTyger** [comment]
I think it's the Arch repo. I built it myself, this time on Fedora and it works just fine. Alacritty has a proper window decoration (unlike the grey ASCII bar on Arch) and the arrow keys work as well. If I get a chance I will try building myself on the Arch machine too and see if the problem persists.

**Comment by vberger** [comment]
Running

(the "out of memory" can be misleading due to the way the wayland C libs handle errors, so I'm going to ignore it).

From what is see here:

```
Feb 14 12:04:14 kare-kun Alacritty.desktop[8905]: wl_surface@11: error 2: Failed to create a texture for surface 11: Out of memory
Feb 14 12:04:14 kare-kun Alacritty.desktop[8905]: thread 'main' panicked at 'Wayland connection lost.: Error { repr: Os { code: 71, message: "Protocol error" } }', src/libcore/result.rs:906:4
Feb 14 12:04:14 kare-kun Alacritty.desktop[8905]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Alacritty indeed does something that gnome considers wrong, resulting on a protocol error and get killed. We need to investigate it. But:

```
Feb 14 12:04:14 kare-kun kernel: gnome-shell[1013]: segfault at 0 ip 00007f9e950957cc sp 00007fff3448bd90 error 6 in libmozjs-52.so[7f9e94e2f000+9dc000]
```

After having (rightfully) killed alacritty, gnome-shell crashed with a segfault. This is definitely a bug that should be reported to gnome developers. Misbehaving clients should not make the server crash.

-----

To understand more clearly the alacritty bug, it'd be very helpful to have the wayland protocol log. To retrieve it, run alacritty with the env variable `WAYLAND_DEBUG=1` set, it'll generate a log of each wayland message on stderr. So something like:

```
$ WAYLAND_DEBUG=1 alacritty 2> log.txt
```

And upload the contents of `log.txt` here ?

Note that running alacritty with `decorations: false` on weston works fine, which leads me to think this is likely a Gnome bug.

**Comment by burningTyger** [comment]
@passcod that's slightly embarrassing, you're right. It does work and have a titlebar when started under XWayland. It also works setting decorations to false under XWayland. Also the cursor keys work as expected which was another issue under plain Wayland. I'm wondering why Fedora defaults to XWayland then under GNOME.

**Comment by passcod** [comment]
just modify or override your .desktop files for alacritty

**Comment by passcod** [comment]
Also you can use `env WINIT_UNIX_BACKEND=x11 alacritty` instead

**Comment by kchibisov** [comment]
Gnome on Wayland + Gnome on X11 works with recent version of alacritty fine without decorations.
