### ISSUE TITLE
When selecting to the top of the screen, alacritty should scroll

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#1173]
When the user makes a selection and the mouse reaches the top of the screen, the terminal should automatically scroll up to allow selecting lines outside of the current viewport.

**Comment by jwilm** [comment]
oh, nice. :100:

**Comment by alexozer** [comment]
It's great to see an initiative to really push forward the scrollback stuff. Thanks for opening a bunch of these issues.

**Comment by jwilm** [comment]
This is important to add, and I will keep it as a high priority item, but I don't want to block merging the scrollback branch on this feature.

**Comment by varac** [comment]
For me this is the most missing feature in alacritty - please consider moving this to an earlier milestone since it's already set as `P - high` for such a long time.

How do currently work around selecting output that spans over the size of the terminal then ? Using sth. like tmux for that task ? I sometime decrease the font size to a bare minimin in order to display more lines in alacritty, select/copy, and increase the font size again, which is rather annoying for huge chunks of text I'd like to select.

**Comment by kchibisov** [comment]
This is the problem only with touchpads iirc. With mouse you can just use your mouse wheel during selection or you can add bindings to scroll with keyboard (e.g. `ScrollLineUp`/`ScrollLineDown`) start selection with a mouse and hold the appropriate binding, the last one is very hard to use (I'm using it on my laptop though).

**Comment by varac** [comment]
@kchibisov Well yes, pressing down the left mouse button and using the scroll wheel works indeed, however all other terminals I used so far implemented selecting text (also ?) by pressing down the left mouse button and moving the mouse to the top of the terminal which allows to scroll up while selecting text. This is imho the default select+scroll behaviour, at least the one I'm used to, and it would be good to implement this in alacritty as well.

**Comment by valignatev** [comment]
Tbh I like that Alacritty doesn't scroll by default, because this way I can control the scrolling speed myself - e.g. by holding the touchpad button and scrolling with the speed that I prefer. Usually, you have to either wait patiently if the scrolling is too slow, or it's too fast and selects everything till the beginning of history, or, you have to shake the cursor for it to perform better.
