### ISSUE TITLE
No Wrap Mode

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#1386]
I frequently run commands that have outputs which wrap text onto newlines (as we all do), the way we handle this today is the correct default behavior, but it would be neat to have the ability to active a "no wrap mode" where the arrow keys (h,j,k,l too) would scroll around the text. This would remove a very common pattern of rerunning the last command piped to `less -S`.

I understand this project is resistant to new features (for good reason), so I won't be offended if this is closed in the name of complexity. I do think this would be a relatively small complexity add if we are already thinking of adding modes as in #262, and #1017.

**Comment by chrisduerr** [comment]
Besides the obvious complexity issues that might be out of scope of this project, this might conflict severely with the current way the storage buffer is designed.

Right now we store every cell in a 2D matrix that has a fixed number of cells in each row. So if you would want to have horizontal scrolling you'd need to have a pretty much infinite number of cells in each row. Otherwise there wouldn't be any place these could be stored. Then ofc there's the question how the current renderer would deal with that.

Even though this might not sound like a totally easy thing to implement, I can see this getting far more difficult than one might initially expect. And I'd say it's not unlikely that the abstractions that need to be added to make this work could slow down Alacritty even when the option is disabled.

I'm not trying to shoot down this proposal, just trying to give some context why adding this might be out of scope for the project. If someone else has an idea how to implement this without any of the issues I've mentioned, I'm open for this addition! :)

**Comment by Eyenseo** [comment]
Isn't this similar to #591? If we're able to reflow on resize, this option would only need to reflow to the longest line known. And I think that reflow is somewhat important, as "losing" shortend lines is painful.

**Comment by chrisduerr** [comment]
This is quite a bit different than #591, for scrolling we'd have to always store everything in infinitely long lines basically.

Reflowing properly instead of truncating is something Alacritty can definitely do when resizing, however reflowing when growing is not something that's easily done.
