### ISSUE TITLE
Missing keys

### ISSUE THREAD

**Issue by daurnimator** [alacritty/alacritty#140]
- Shift + F-keys
  - Ctrl + F-keys
  - Shift + tab
  - Numpad / * - +
  - Shift + backspace sends `\8` instead of `\127`

**Comment by jonhoo** [comment]
Alt + backspace also doesn't seem to be passed through to the underlying shell.

**Comment by sheychen290** [comment]
Any news from numpad + - support ?
It's could be perfect with action: IncreaseFontSize

**Comment by chrahunt** [comment]
Also

* Ctrl + tab
* Ctrl + Shift + tab

**Comment by DanielPower** [comment]
Also

- Ctrl + Left Mouse

**Comment by chrisduerr** [comment]
The remaining mappings should be fixed by https://github.com/tomaka/winit/pull/805.

**Comment by kchibisov** [comment]
Lot's of bindings were added there 9a14ca42d35e3b72ca254384ef7e4639aab0e100 . + upstream issue for numpad was is also solved, so if you have any desire to add some bindings, please open a separate issue and explain why curtain binding should be added(e.g. mentioning other terminals, functionality , wrong escapes from the current bindings), instead of just mentioning random things.
