### ISSUE TITLE
shaders not live reloading multiple times (with --features "live-shader-reload"). Config live reload works fine

### ISSUE THREAD

**Issue by towc** [alacritty/alacritty#1523]
`rx.recv` at https://github.com/jwilm/alacritty/blob/master/src/renderer/mod.rs#L595 seems to hang after a second update of the shader files

On freenode, UndeadLeech suggested I do a few things.
Here's what didn't work, if I applied the instructions correctly:
 - increasing `fs.inotify.max_user_instances` and `fs.inotify.max_user_watches` through `sysctl`
 - using nano to write to the shaders
 - increasing the delay to 3s on https://github.com/jwilm/alacritty/blob/master/src/renderer/mod.rs#L588

Here's what worked:
 - changing the code to watch based on file path and not inode
 - watching the res dir instead of the individual files

The confusing thing is that the watcher for the config live reload should be the same as the one for the shader live reload, so neither should work, or both should work, if it was a watcher issue

Which operating system does the issue occur on?
Ubuntu 16.04, i3, ext4, no DE

If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment]
The issue that seems most similar to this one on the `notify` crate is [this one](https://github.com/passcod/notify/issues/113). If the comment of the `notify` author is correct though, this doesn't seem to be the issue since `nano` also didn't work.

A potential solution would be to always use the `PollWatcher`, or use the `PollWatcher` as a config/compile-time flag. Alternatively watching the folder works, so this would make it possible to just watch `.../res` and the notifications would always be correct. This would also work nicely with `~/.config/alacritty/alacritty.yml`, however when the config file is in a more busy directory, this would cause issues.

**Comment by jwilm** [comment]
For the config watcher, it appears we watch the directory and not the files. The problem is that `vim` actually unlinks the file on a save for its atomic save behavior. To fix this, we should take the same approach in the shader watcher.

**Comment by chrisduerr** [comment]
Yeah that was my thought as well @jwilm, however we've tested `nano` too which according to an issue in `notify` doesn't exhibit this behavior.

It's always good to double-check though and maybe an other editor or straight-up `echo` does solve the problem.

**Comment by jwilm** [comment]
The reason `nano` works is because it's not doing an atomic save -- it's just writing directly over the previous file rather than writing to a temp file and swapping.

**Comment by chrisduerr** [comment]
That's exactly the issue. `nano` did not work when testing.

**Comment by kchibisov** [comment]
There's no such feature anymore.
