### ISSUE TITLE
Select with Shift + Click

### ISSUE THREAD

**Issue by elbaro** [alacritty/alacritty#1554]
example:

select a few characters, scrollback with pageUp or mouse wheel, and shift+click to extend the selection.

**Comment by chrisduerr** [comment]
Thanks for the suggestion.

There might be some issues with this though since `shift` is already used to disable mouse mode for selection.

One scenario where the behavior might be unexpected, would be this:
 * Enable mouse mode
 * Make selection with shift+drag
 * cancel selection with left click+shift
 * keep holding shift to start a new selection

In this scenario it wouldn't be certain if a new selection should be started, from the point where the selection was cancelled, to the new start, or if the first click was just to cancel the selection.
I think there should be a way to resolve this, in this case it's probably best to just assume the first click was just to cancel the selection, but this becomes more complicated when there is no selection currently visible (but still present in the history).

Do you have any examples for terminal emulators which already do this? It might be nice to capture their behavior to make sure if Alacritty should receive this feature, that the behavior would be consistent and battle-tested.

**Comment by elbaro** [comment]
gnome-terminal and OSX default Terminal app do this.
This is necessary when I have a huge output (>1000 lines) to select and copy.

**Comment by kvelicka** [comment]
`xterm` does the same by left clicking somewhere and right clicking somewhere else (everything in between gets selected).

I think that the general idea of "mark start/end and select in between" is the interesting suggestion, the keys/shortcuts to achieve that are just a minor detail.

**Comment by kchibisov** [comment]
We decided to go for right mouse button for selection expansion, since `Shift` is a bit overloaded with other implicit things already, and they were conflicting with each other.

**Comment by adsick** [comment]
> We decided to go for right mouse button for selection expansion, since `Shift` is a bit overloaded with other implicit things already, and they were conflicting with each other.

Does `Shift + Mouse Click` do something else (you mentioned "conflicting")? I was super surprised to find out about `Click + Right Click`, I don't know any other software that works like this. Right click usually opens a context menu (Copy, Paste, etc.)
