### ISSUE TITLE
Investigate using font-kit

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#1568]
@pcwalton just published [font-kit] which serves the same purposes as our built-in `font` crate. This may even allow us to start publishing `alacritty` on crates.io. From their README:

> font-kit provides a common interface to the various system font libraries and provides services such as finding fonts on the system, performing nearest-font matching, and rasterizing glyphs.

[font-kit]: https://crates.io/crates/font-kit

**Comment by chrisduerr** [comment]
This sounds like a great way to remove some complexity from Alacritty and fix the long-standing issue of getting Alacritty into crates.io.

I haven't looked at it my self at all yet, but I'd be mostly curious about how font metrics are calculated. Alacritty has had a bit of a history with getting all the font metrics on all operating systems just right, it would be a good test to try out font-kit and see how it performs here, since it's very easy to make some simple off-by-one errors.

Might be good to add some tests for checking font metrics before trying to make use of this crate. That would probably be the biggest pain point with getting any other font library to work. Making sure that there are no regressions in this area seems valuable, even though testing it without a fixed set of fonts seems troublesome, but thought it would still be worth a mention.

**Comment by kri5** [comment]
This seems like a good thing to delegate complexity to another crates, it improves maintainability and reduces codebase, which is good for having new contributors.

I see an issue that won't be solved if the move is made to use font-kit, on their documentation they state :

**Comment by sodiumjoe** [comment]
does this relate to #957 at all? At first glance, they seem fairly orthogonal, except maybe some of the more advanced proposals, like declaring fallback `range`s?

**Comment by jwilm** [comment]
@sodiumjoe this should be independent of the font handling RFC you linked. There may need to be a few patches to font-kit to fully support it.

**Comment by zacps** [comment]
An initial attempt of an implementation for the existing rasterizer trait (doesn't work yet): https://github.com/zacps/alacritty/tree/fontkit

**Comment by chrisduerr** [comment]
@zacps You could open a WIP PR. That way it would be easier to have one central place to discuss changes rather than multiple people forking that version and working on it independently.

**Comment by zacps** [comment]
Sure, in that case does it make sense to keep the branch in my fork or this repo?

**Comment by chrisduerr** [comment]
Just keep it in your fork and open a PR. That allows should allow collaborators (me) to push to it. If other people want to contribute it wouldn't make much difference if they send the PR to your branch or this repo. Either way would be fine, but that's the simplest way to get a WIP out quickly so that others can comment and contribute.

**Comment by chrisduerr** [comment]
Since our own font crate works very well for Alacritty's usecase and font-kit lacks significant features that are relevant to us, I don't think there's any value in switching to font-kit.

This has been the case for the past two years, should this ever change in the future we can create a new issue to investigate if it makes sense switching to something like font-kit or allsorts for example.

**Comment by pcwalton** [comment]
If you have time, I'd be interested to know what features you're missing from font-kit.

**Comment by kchibisov** [comment]
>If you have time, I'd be interested to know what features you're missing from font-kit.

Does it support font fallback with freetype + fontconifg?

**Comment by chrisduerr** [comment]
Just some rough guidelines based on the previous PR and what I know about font-kit:
 - Font fallback
 - IIRC weights/slants are limited to an enum(?)
 - Some platform specific issues/differences (these might be fixed upstream, I remember metrics)

There's also some things I'm not entirely sure about, but that look like they could cause incorrect behavior which we've had to patch ourselves over time in our library. Some things that stood out to me were metric rounding and hinting load flags, these might not be incorrect but a quick glance didn't give me a lot of confidence.

Of course I'm not taking a jab at the font-kit project in general here. Alacritty's library is specialized to care only about the things we need to care about, so we have more time to focus on exactly that. So based on my current estimation, switching would just introduce unnecessary extra work and regression which I do not want to impose on our users, even though I am very much in favor of ecosystem unification when it makes sense.

If a migration is ever just a simple drop-in replacement without severe risk of significant regressions, I'm definitely not opposed to the idea in general. But based on the development over the last few years this will probably take a bit of time.
