### ISSUE TITLE
Load colors from Xresources.

### ISSUE THREAD

**Issue by Kyle-Thompson** [alacritty/alacritty#1771]
Title is pretty self explanatory. It would be nice to be able to load colors from the Xresources file.

**Comment by alberdingk-thijm** [comment]
So I was also hoping to do this, and decided to write up a little API to load colours from Xresources.

I just published the very basic version of it on [crates.io](https://crates.io/crates/xcolors).
At the moment, essentially calling `xcolors::XColors::new(prefix)` returns a struct with fields populated according to the given prefixes, such that if you add "alacritty.foreground" to your `.Xresources` and use `"alacritty"` as your prefix, then you will get back whatever value was put in for the key.

I don't believe this would currently be ready to integrate into `alacritty`: I haven't really tested it to any meaningful extent and it also needs some `cfg` flags to handle how X is provided, but my hope is that it can be a first step into getting this functionality added.

**Comment by nixpulvis** [comment]
@alberdingk-thijm very cool. I haven't taken the time to read over the crate (I'm on mobile atm) but my first question is if it would make more sense to position your crate as an xrdb library (the `xrdb` crate name seems free), and then just provide some common helper types for things like colors, fonts, etc.

**Comment by alberdingk-thijm** [comment]
@nixpulvis That makes sense! I'll take a look into doing that and see if I can put something together.

**Comment by alberdingk-thijm** [comment]
[Here](https://github.com/alberdingk-thijm/xrdb) is the new `xrdb` crate! Some common features like fonts/Xft will be added shortly.

**Comment by nixpulvis** [comment]
@alberdingk-thijm very cool. I look forward to watching this crate develop.

**Comment by Kyle-Thompson** [comment]
Okay so now that we have this crate (https://docs.rs/xrdb/0.1.1/xrdb/) is there any blocker for this?

**Comment by alberdingk-thijm** [comment]
I would consider the `xrdb` crate to be fairly untested right now; I'm not sure where it breaks or whether the API should be changed. I'm not able to give it much attention right now but getting some more feedback on it would help with those lingering concerns.

Once the crate's in a stable form, though, then anyone's welcome to fork `alacritty` and see if that support can be added.

**Comment by C0DK** [comment]
What is the status of this? :) It seems like a really awesome feature, and i'd gladly throw some open-source hours at it if it's totally dead. I just don't know where to start :p

**Comment by chrisduerr** [comment]
I don't think a lot of people are interested in this and it has the potential to complicate things a lot, so that's probably the main reason why noone has been interested to work on this yet.

XResources also have serious limitations if what I recall is correct and it might not work on Wayland (iirc gnome doesn't load XResources on Wayland). So it's questionable if loading the XResources is a good idea to begin with.

**Comment by alberdingk-thijm** [comment]
> What is the status of this? :) It seems like a really awesome feature, and i'd gladly throw some open-source hours at it if it's totally dead. I just don't know where to start :p

I haven't really looked at this at all since February, but the existing xrdb crate can [extract a struct](https://docs.rs/xrdb/0.1.1/xrdb/struct.Colors.html) representing the colors from Xresources already, so it could be included as part of alacritty on the systems that support it (i.e. ones which use X). That being said, handling XResources would add a couple of dependencies and potential pitfalls to alacritty as a whole that might not be desirable (as @chrisduerr mentioned) so whoever wants to look into doing this would need to find a nice way of handling that.

I had initially imagined a flag in `alacritty.config` that simply indicated whether or not to use the colors given in the user's Xresources or not, defaulting to "no". This would leave it up to the user to know what they were doing and have the necessary colors loaded.

**Comment by MuntashirAkon** [comment]
For anyone looking for a way to load Xresources colors in alacrity, I've created a python3 script to just do that. Here's the script: https://github.com/MuntashirAkon/voidrice/blob/master/.local/bin/alacritty_xr_color_scheme

**Comment by jhonrocha** [comment]
Hey, guys! I have done a PR for this. I have been using it by myself here for a while. All good for now.
This is my first PR also I am very new to Rust.

**Comment by kchibisov** [comment]
We decided to move into escape sequences direction instead of relying on .Xresources, which can't even handle our coloring config section properly(we can't use indexed colors), due to its limitations and being too X11 specific(like one more source of config file, when we can just have multiple config files).
