### ISSUE TITLE
Problem with LC_CTYPE on wayland

### ISSUE THREAD

**Issue by Svadkos** [alacritty/alacritty#1785]
Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
Wayland

On Sway, if LC_CTYPE is empty Alacritty starting with error `xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device` and input isn't working except arrow keys.
When i set `LC_CTYPE=C` english layout works, but on russian layout symbols look like `<ffffffff>`.
Both layouts work properly if LC_CTYPE is set to `en_US.UTF-8`.

On xorg there is no such problem, and all layouts work regardless of LC_CTYPE.

**Comment by mazulo** [comment]
I'm having the same issue. Installed using `pacman` and when I tried to open it, doesn't allow me to input anything. When I ran on another terminal `alacritty` it showed up to me:
```bash
➜  ~ alacritty 
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
```

**Comment by chrisduerr** [comment]
This should be fixed in https://github.com/Smithay/client-toolkit/pull/75.

Generally, I'd say this indicates a broken system setup. Usually these values should be either set properly or unset, not set to an empty string.

If someone is experiencing this issue, I'd recommend fixing the system locale regardless of the smithay fix which works around this.

**Comment by kchibisov** [comment]
The fixed mentioned on this issue is included in alacritty for quite some time already.
