### ISSUE TITLE
Scrolling is slower on Wayland

### ISSUE THREAD

**Issue by Limero** [alacritty/alacritty#1909]
With Alacritty on Wayland, mouse scrolling is much slower than on xorg.

How to replicate:
1. Run a Wayland window manager
2. Open a regular Alacritty terminal (Wayland)
3. Open another terminal with the xorg version of Alacritty: `env WAYLAND_DISPLAY= alacritty`
4. Put them side by side and `cat` any big file in both
5. Scroll up and down in each of them and see that the version running native on Wayland is MUCH slower.

I'm using Arch Linux and have confirmed the bug on both Sway 1.0 and Gnome. Both running Wayland.

**Comment by chrisduerr** [comment]
Can you replicate this with the [vtebench](https://github.com/jwilm/vtebench) benchmarks?

Printing file content can be extremely inconsistent because of file caching, so that might cause some variations.

**Comment by Limero** [comment]
I don't know how to replicate it with vtebench. I tried running the example in that repo and the results are similar on both xorg and wayland. This example:
```
vtebench -w $(tput cols) -h $(tput lines) alt-screen-random-write \
    > /tmp/100mb.vte

time cat /tmp/100mb.vte
```

I think it's just the mouse scrolling that is slower. It's the same for any content, so running your package manager or anything and then scrolling up is slower on wayland. Using `cat` on a big file is just to fill the buffer.

**Comment by chrisduerr** [comment]
I was not aware you're talking about mouse scrolling. Mouse scrolling in XWayland and Wayland is handled differently, since one relies on X, while the other relies on Wayland. So a difference in scrolling speed is definitely possible.

If you want to achieve the same scrolling speed on both systems, you'd probably have to resolve that in the Wayland or X.Org configuration.

If the goal is to just increase/decrease the scrolling speed, you can make use of the `scrolling.multiplier` setting.

**Comment by ocehugo** [comment]
I'm experiencing the same issue. If I disable scrolling the problem is gone.
See below.


Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
Wayland, sway 1.0

How to reproduce:
```
while True; do echo A; done 
```
run the above inside alacritty until you fill the history scrolling limit.

After the above, resizing, maximizing is much slower than in a fresh session (or a session with history=0). The lag is noticeable with a relatively fast machine.

Under normal circumstances, resizing the screen from half-screen to full screen from keyboard keys is very fast (only requires 25% of my CPU when swapping fullscreen/half screen as fast as I can). If scrolling is active and the buffer is full, this goes to 100% and resizing/fullscreen is much slower ( I have to wait maybe two seconds until the text is redrawn).

**Comment by MyNameIsCosmo** [comment]
I cannot reproduce this using Sway 1.1.1 and Alacritty 0.3.3

**Comment by kchibisov** [comment]
@Limero I can't repro your issue with 100k lines of scrollback. `vtebench` also shows that our scrolling is as fast as on X11 for me.

As for the mouse part, I can't say much here, for me everything is the same, so if you still have this issue, feel free to reopen.

--
@ocehugo 

>After the above, resizing, maximizing is much slower than in a fresh session (or a session with history=0). The lag is noticeable with a relatively fast machine.

It seems like you're describing our old issue with reflow here.
