### ISSUE TITLE
ctrl+c does not work on Windows in cmd.exe

### ISSUE THREAD

**Issue by mqudsi** [alacritty/alacritty#1926]
Under Windows 10 (17763) when alacritty launches with cmd.exe by default, ctrl+c does not work (it is completely ignored). But after launching WSL, ctrl+c works.

Same issue described here, where it could not be worked around because of a upstream issue with the PTY. I hope it is not the same situation here: https://github.com/zeit/hyper/issues/1121

**Comment by chrisduerr** [comment]
@mqudsi This is probably fixed by #1762.

**Comment by zacps** [comment]
This is the same as the issue you linked. Relevant upstream issue: https://github.com/rprichard/winpty/issues/116.

**Comment by zacps** [comment]
After looking at it further it seems to be an issue in cmd, so https://github.com/PowerShell/Win32-OpenSSH/issues/914 may be more relevant.

**Comment by mqudsi** [comment]
Just tested, #1762 fixes this.

**Comment by zacps** [comment]
I don't want issues for winpty closed just because we have conpty support.

**Comment by chrisduerr** [comment]
@zacps Is this something that can actually be fixed in Alacritty? It looked like a winpty bug to me, where many are probably likely to never get fixed (similar to https://github.com/jwilm/alacritty/issues/1662).

Not sure if it makes a ton of sense to duplicate a big chunk of the WinPTY issue tracker when the solution is going to be 'fixed by ConPTY' anyways.

**Comment by mqudsi** [comment]
From my past experience with winpty with other terminal emulators, my advice here would be: you've done without Windows support this long and you have a much better replacement going forward. Unless you _need_ to support older versions of Windows, just commit to #1762 from now and not as a disabled-by-default-beta-option but rather as "this is what Alactritty under Windows looks like."

You don't want an unneeded dependency on a buggy and poorly maintained external library that is built around a giant hack to deal with the previous lack of a real pty. For the WinPTY issues that you *could* work around on your end, what's the point if you're going to deprecate them anyway? For other issues, are you committing to testing and fixing everything twice, once under WinPTY and again under ConPTY?

(But I agree, unless that decision is made it makes no sense to close bugs that are only fixed under an opt-in execution mode.)

**Comment by zacps** [comment]
In a year, maybe, but the update that introduces the feature only has [6.6% usage](https://reports.adduplex.com/#/r/2018-12) *among windows 10 users*.

**Comment by chrisduerr** [comment]
I'm definitely against completely deprecating (or even removing) WinPTY at this point. The question is just if we should fix and track bugs that are unlikely to ever get fixed. If there's no plan to fix a WinPTY issue, or it's simply not possible, I'd recommend closing that as wontfix.

I don't know how about this issue, since I'm not sure why it broke recently when it works in older Windows versions. But supporting just a gimped API for WinPTY is likely the only option based on all the missing features in WinPTY I've seen so far.

**Comment by chrisduerr** [comment]
WinPTY support has been removed.
