### ISSUE TITLE
Spawn new Alacritty instance in working directory on macOS using proc_pidinfo

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#1979]
The `SpawnNewInstance` action allows spawning the new Alacritty instance inside the current working directory of the child shell, however this is currently not supported on Windows since `/proc/*/cwd` is not available on non-unix systems.

For feature parity between platforms, this should also be supported on Windows.

The action was originally implemented in https://github.com/jwilm/alacritty/pull/1971.

**Comment by nixpulvis** [comment]
Possible hacking solution, or inspiration: https://github.com/Eugeny/terminus/blob/3aaf490f5790564d851c29a76c62ef5c5450a2d7/terminus-terminal/src/services/sessions.service.ts#L242

**Comment by davidhewitt** [comment]
I've been looking into this a little tonight for Windows. It seems really hard to do it reliably - most robust suggestions I can find involve using low level windows APIs: `CreateRemoteThread` to inject a DLL into the child cmd.exe process and from that DLL execute `GetCurrentDirectory` and send the result back to Alacritty. Seems awfully complicated. There's probably a better solution than that somewhere.

**Comment by cfiet** [comment]
@davidhewitt, @chrisduerr It seems that `CreateRemoteThread` trick is a lot more complex than just running `GetCurrentDirectory`, since the handler that starts the thread has to be in target process address space. For `cmd.exe`/`powershell.exe` that would be limited to WinAPI functions. So the actual code solution would be:
- Have a DLL on Windows that can be loaded into `cmd.exe` process that, when [initialising](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-entry-point-function) runs `GetCurrentDirectory` and sends a message back to Alacritty process
- Allacritty, after `cmd.exe` has started, runs `CreateRemoteThread` with a handler that would run [`LoadLibrary`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya) with that DLL path

Overall the entire process sounds very iffy and error prone and can potentially trigger some AV scanners.

There is also an [alternative hack](https://stackoverflow.com/questions/14018280/how-to-get-a-process-working-dir-on-windows) where by reading a specific section of process memory it is possible to get its cwd. There is a C# version somewhere that works for both 32b and 64b systems but both use [`NtQueryInformationProcess`](https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntqueryinformationprocess?redirectedfrom=MSDN) that is considered a private WinAPI method.

There might be something specific to `conhost.exe` that could potentially be used, but so far I haven't found a nice way of doing that, so while also not ideal, @davidhewitt solution might be the most practical solution to the problem.

**Comment by cfiet** [comment]
More detailed `CreateRemoteThread` [description](https://stackoverflow.com/a/218045)

**Comment by davidhewitt** [comment]
Thanks @cfiet. As well as being a hacky solution, `cargo install` doesn't deploy DLLs (as far as I'm aware) and it would create a whole pile of platform-specific code. And possible AV scanner issues so you point out. So I'm really not fond of the DLL approach.

You might be interested in #2937 which would create a simple cross-platform solution that's already implemented in some other terminal emulators. It would probably require you to opt in by modifying your `cmd.exe` prompt. I'd hope that maybe one day `powershell` would support it natively.

At the moment #2937 is blocked on some specification questions. The discussion is all on that thread.

**Comment by chrisduerr** [comment]
Yeah, this will be resolved with #2937, I don't think there's any interest in finding alternative solutions for Windows/macOS/BSD at the moment.

**Comment by chrisduerr** [comment]
For macOS this is fairly easy to resolve with the `proc_pid` service call. Using the `tcgetpgrp` call also gives a relatively reliable way to determine which process should be queried, which exists on all Unix platforms in some way afaik.

So I think the best option is to just go ahead with implementing that on Unix and blame Windows for not supporting the necessary kernel functionality here.

**Comment by chrisduerr** [comment]
I've created https://github.com/alacritty/alacritty/issues/4082 to track the `tcgetgrp` enhancements, while we can use this issue for the macOS implementation.
