### ISSUE TITLE
On Debian 9, package is uninstallable: Dependency is not satisfiable: libgcc1

### ISSUE THREAD

**Issue by feuGeneA** [alacritty/alacritty#2038]
```
gene@precision5510:~/Downloads$ sudo gdebi Alacritty-v0.2.7_amd64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libgcc1 (>= 1:8.2.0)
```

Strangely enough, I do already have `libgcc1` installed:
```
gene@precision5510:~/Downloads$ dpkg -l | grep libgcc1
ii  libgcc1:amd64                                               1:6.3.0-18+deb9u1                           amd64        GCC support library
```
-----
Which operating system does the issue occur on?
```
gene@precision5510:~/Downloads$ uname -a
Linux precision5510 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```
```
gene@precision5510:~/Downloads$ cat /etc/debian_version 
9.7
```

If on linux, are you using X11 or Wayland?
X11... I think!

**Comment by chrisduerr** [comment]
Bummer, looks like Debian is too outdated to support the pre-built binary here.

In theory it would be possible to fix this by adding another CI task for building manually for Debian instead of the latest Ubuntu LTS release.

However I'm not sure if this is worth it and where to draw the line here. Personally I think it would be fine to build at least Ubuntu, Debian and Fedora explicitly with their latest versions though.

The issue here is that this needs to be done with both architectures (x86 and x86_64). So building for Ubuntu, Debian and Fedora would mean that we'd have to build Alacritty 6 times for Linux releases. This will not provide any special binaries for OpenSUSE, Void, Arch, or any other distro. However many of those already have packages for Alacritty themselves.

Previously it was possible to run this on Debian stable (I've explicitly confirmed that), so it seems like Ubuntu must have updated the library here.

**Comment by feuGeneA** [comment]
Does alacritty actually depend on libgcc1 functionality that was released after 1.6.3?  Perhaps the dependency could be downgraded?  Just a stab in the dark; I'm certainly not dpkg savvy, and I'm not sure how explicit the dependencies are, or even if they're direct (perhaps they're indirect via rust?).

**Comment by chrisduerr** [comment]
The problem is not that Alacritty requires a specific version of libgcc, but that we're talking about pre-compiled binaries here and those are built against a specific version of libgcc.

**Comment by hyiltiz** [comment]
It is probably not fair to consider packaging for Debian stable, as packages need to first go through a few experimental/testing stages before they freeze into the stable branch. Hence the stable branch ships with old libraries.

AFAIK, Ubuntu pulls packages from Debian testing (a rolling-release) or even Debian experimental branch (usually buggy) for non-LTS versions, and pulls from stable for the LTS versions. So, how about targeting packages for Debian testing? This would ensure the package would also flow to Ubuntu/Mint/others as well.

**Comment by kchibisov** [comment]
>AFAIK, Ubuntu pulls packages from Debian testing (a rolling-release) or even Debian experimental branch (usually buggy) for non-LTS versions, and pulls from stable for the LTS versions. So, how about targeting packages for Debian testing? This would ensure the package would also flow to Ubuntu/Mint/others as well.

It'll unlikely work and you can only hope for such things. You can't just provide binary for distro X and also reliably target distro Y and distro Z. Also I'm not sure if our CI can even run Debian.

I don't like the idea of providing tons of binaries on our CI and maintain random package specs, etc, besides macOS and Windows. I'm not completely against adding Debian though, since we should just build the thing, since we already have a way to generate proper `deb`.
