### ISSUE TITLE
Triple Click Should Select Wrapped Lines

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#2302]
Currently, a triple click will select the single complete line underneath the cursor. However, now that we have reflow, a single logical "line" can span many grid lines. A logical line is the content the text printed to the terminal thinks is a line, a grid line is a row in Alacritty's grid. Triple clicking today will miss parts of logical lines.

Other terminals (tested Termite and Urxvt) select each full grid line with content from the logical line. This means that for a line with N wraps, there will be N+1 lines selected on triple click.

**Comment by ike** [comment]
Hey there! I'm new to Alacritty (it's the best thing that's happened to my dev env in a long time), and new to Rust. I'd love to help contribute.

I have Alacritty building on my machine (macos 10.14), and I've been poking around in the code base. Things look really well organized and clear to read, which is dope!

I am  assuming that this is the relevant file, and maybe the relevant lines? https://github.com/jwilm/alacritty/blob/72dfa477a9785289931e8e05dfc8244bb6a4e81c/alacritty_terminal/src/selection.rs#L117-L119 I'd love some direction on how best to tackle this issue.

Thanks a mil for a great project, I am loving it.
Isaac/ike/crossdiver

**Comment by chrisduerr** [comment]
Hello @ike, first of all thanks for your interest in contributing to Alacritty!

You're actually pretty close already, the place you're looking for is here:
https://github.com/jwilm/alacritty/blob/72dfa477a9785289931e8e05dfc8244bb6a4e81c/alacritty_terminal/src/selection.rs#L273-L281

As you can see, the `start.col` and `end.col` are set here to go from the first column to the last column, however what we would want in this PR is to check if the last column contains the `crate::term::cell::Flags::WRAPLINE` flag and if it does, we want to expand the selection to the last column of the following line. If the following line also contains the flag, we repeat that until we're either at the end of the terminal or no more flag is in the last line.

This sort of expansion is similar to the semantic expansion when double-clicking, so I think it makes sense to implement it in a similar fashion. You can take a look at the `semantic_search_right` method in the `alacritty_terminal/src/term/mod.rs` file for that. You'd want to add another method to the `Search` trait which gives you back the last point of the line selection based on an input point. You don't need to iterate over every cell though, you can just check if `grid[current_line][last_line].contains(flag)`.

Hopefully that should get you going in the right direction. If you need more information I can go into a bit more detail if you're interested, otherwise I'd just recommend to give it a shot and play around with things a bit and I can comment on possible improvements or help out once there's something to go from.

**Comment by ike** [comment]
Okay, I made a little progress. I have a working select that selects all the lines down the screen that contain the wrapline flag. Should I also search backward for the previous lines that contain a wrapline flag?

Here's the diff of my code: https://github.com/jwilm/alacritty/compare/master...ike:2302-triple-select-wraplines

I'm having tons of fun and learning a lot and I haven't attempted to burn the Rust compiler with fire yet! 😸 

~ike

**Comment by chrisduerr** [comment]
> Should I also search backward for the previous lines that contain a wrapline flag?

Yes, I think that would make sense.

> I'm having tons of fun and learning a lot and I haven't attempted to burn the Rust compiler with fire yet! smile_cat

Thanks for working on this. Glad you're having fun.

**Comment by ike** [comment]
PR is up: #2717. One test isn't passing -- haven't had much luck debugging it.

**Comment by Dav1dde** [comment]
@chrisduerr this is merged right, can be closed?

**Comment by chrisduerr** [comment]
Thanks for the bump, this was closed with https://github.com/alacritty/alacritty/pull/3207.
