### ISSUE TITLE
Blinking text is not working

### ISSUE THREAD

**Issue by uglywizkid** [alacritty/alacritty#2365]
I am using linux/X11 and I would like to have a blinking text in my terminal when entering ``echo -e "Normal \e[5mBlink"``, like it works on other terminal emulators like xterm.

**Comment by nixpulvis** [comment]
Related to #302.

**Comment by Hubro** [comment]
Anything preventing this from being implemented now? We have blinking cursors already :thinking:

**Comment by kchibisov** [comment]
See this https://github.com/alacritty/alacritty/pull/6055

**Comment by chrisduerr** [comment]
Going to close this as wontfix, since I have no plans encouraging anyone to add blinking text to their terminal applications.

**Comment by theS1LV3R** [comment]
I agree with you wholly, but at the same time it would be nice for alacritty to support common features that many other shells have. Blinking text is also a part of ANSI and VT100 escape codes, which are commonly used in scripting. Better to support all of it than some of it

**Comment by chrisduerr** [comment]
Alacritty is not a shell, blinking isn't commonly supported and it's not commonly used. It's certainly not better to support "all of it than some of it", saying every escape sequence should be supported is a complete waste of everyone's time.

**Comment by christianparpart** [comment]
I think @theS1LV3R meant not to include all ever existing sequences but to seriously consider at least what is part in ANSI and VT100. 
I can feel why devs prefer not to implement it. Yet another highly interactively state changing moving part that one may believe it's more perf hurting than useful. However, dinner users seem to like it, and that is choice over should respect. I don't see myself using blink in my prints myself, because it feels disturbing, but then again: blink did it's job: it got my attention. So a good think.

Just my two cents on that matter.

**Comment by chrisduerr** [comment]
I don't really care what "some users seem to like". If they want it, they can patch it in themselves.

**Comment by Horuyuki** [comment]
I personally want a blinking prompt.

Could you accept the merge request mentioned earlier and make this a user configurable option?

Terminals that do support blinking:
https://i.imgur.com/kwAh0R2.png

**Comment by J-MR-T** [comment]
Sidenote, it sounds like a few people here wouldn't want blinking because it could be annoying/it doesn't look nice. I'm looking for blinking *for that exact reason*. Specifically, I thought I might use it in git status info in a prompt, to show un-pushed/pulled commits more clearly, as I want to push/pull immediately in bascially all of these cases. Not saying that anyone should feel obliged to do anything about it, I'm glad to be able to use alacritty for free, and be able to prod around in the source myself.
I just wanted to give context on why I think there is reason for blinking to exist.

**Comment by mr-sihc** [comment]
> I don't really care what "some users seem to like". If they want it, they can patch it in themselves.

well they did, #6055, but you closed it, stupid

**Comment by kchibisov** [comment]
patch themselves as in their tree of the alacritty, not the upstream one.

**Comment by Indyandie** [comment]
I was hoping to use blink in the starship prompt on the battery module whenever it hits a threshold of 10%.

**Comment by carlanwray** [comment]
> Going to close this as wontfix, since I have no plans encouraging anyone to add blinking text to their terminal applications.

The logic in this issue is worse than what is in the pull request. 

What I can't understand is the gatekeeping on such an innocuous feature, one that is valuable in the right context. This is not 1999 Web 1.0 we are litigating, it's a feature that is invaluable in the correct netops or other TUI application where it is actually important to draw attention to something and not having \e[5m makes it suboptimal to implement.

At least Ghostty is open to the idea, just needs implemented.

New to Alacritty and I had such high hopes from my first impression. Oh well.
