### ISSUE TITLE
Enable Travis caching

### ISSUE THREAD

**Issue by CrackedP0t** [alacritty/alacritty#2376]
Currently, running all the targets on Travis CI takes about 30 minutes. However, a large part of that time is spent on external dependencies from Cargo, which Travis can cache.

I made a [branch](https://travis-ci.org/CrackedP0t/alacritty/builds) with the line `cache: cargo` added to `.travis.yml`, and the build time dropped from [29:39](https://travis-ci.org/CrackedP0t/alacritty/builds/525504051) to [18:49](https://travis-ci.org/CrackedP0t/alacritty/builds/525525903). Obviously build times fluctuate a lot, but think that's a definite improvement.

I can just open a pull request with the added `.travis.yml` line, but there might be more configuration necessary to make sure nothing's cached that actually needs to be rebuilt.

**Comment by chrisduerr** [comment]
I think I've actually removed caching in the past because at that time it didn't provide a significant performance improvement, but the generated caches were huge.

Alacritty has a lot of dependencies and caching everything makes little sense I think. A lot of depedencies get updated all the time and caching outdated dependencies after the lockfile has been updated will lead to massive cache bloat.

An option would be to clear the target directory whenever the lockfile is changed, however that increases the complexity by quite a bit.

A good read on this topic for a project which doesn't check in its lockfile can be found [here](https://levans.fr/rust_travis_cache.html). Since we have our own lockfile things are slightly different, but in my experience the cache size is still pretty significant.

Note that there likely is a better way than just disabling the cache, so some exploration would definitely make sense. But running a single cached build with perfect conditions and no changed dependencies is not a very good choice for comparing the build times of cached vs non-cached builds.

**Comment by chrisduerr** [comment]
I've actually taken the time to look at the travis times when the cache was removed and it did indeed improve the compile times to remove them.

You can see the last build before the cache has been disabled here:
https://travis-ci.org/jwilm/alacritty/jobs/449641457

The first untagged build after the change is here:
https://travis-ci.org/jwilm/alacritty/jobs/450357644

As far as I can tell, these builds are pretty much identical except for the presence of the cache, so removing it improved the compile times from 8 to 6.5 minutes.

Hopefully this should be a better comparison than your times, since they represent what actually happens when the cache is not just filled with the current and most recent data, but instead has the history of all the previous builds. Although things might have changed, so it might be better or worse now.

So in theory what we'd want is to have a small build cash which contains all relevant packages, without being so bloated that it slows down the build more than it speeds it up.
