### ISSUE TITLE
Alacritty should pass vttest

### ISSUE THREAD

**Issue by JasperWallace** [alacritty/alacritty#240]
Hi,

vttest is an old program for testing terminals and terminal emulators, it's in the vttest package on Debian (and presumably Ubuntu too).

Alacritty panics at the start of test 1, and part way through test 2 (just keep pressing enter).

vttest is probably useful for developing alacritty since it tests all kinds of odd edge cases in terminal handling.

**Comment by jwilm** [comment]
I hadn't heard of vttest. Thanks for the tip!

**Comment by klamonte** [comment]
I've written a terminal that passes vttest.  Its (somewhat) more readable descendent code is at https://github.com/klamonte/jexer/blob/master/src/jexer/tterminal/ECMA48.java .

Some things that might help you here:

* Tests 1, 2, 3.8 (VT100 character sets), 6, and 8 need to be passed before you have full coverage of nearly all terminfo-based applications.  For these you will need the rightmost margin VT100 line wrap behavior, and remember that cursor position commands reset that flag.
* Double-width / double-height (test 4), and VT52 (test 7) can wait.  No one uses them AFAIK.
* VAX / VMS systems rely on the default "no argument" forms of the sequences, e.g. things like "ESC [12;h".  EVERY sequence has a default argument that needs to be handled.
* Scrolling regions need to be honored/ignored as per the VT100 specification.
* Control characters must be handled separately from the rest of your parser.

There is also one spot where a vttest-compliant terminal conflicts with modern convention: SGR 38/48 (RGB colors, T.416 / ISO 8613-3).  I chose to go with vttest compliance which leads to ugly blinking sequences usually, but your users will probably prefer the RGB support instead.

**Comment by Aaron1011** [comment]
Alacritty no longer panics on tests 1 and 2, but there are still several CSI actions used by vtetest that aren't handled.

**Comment by jwilm** [comment]
Aside from not panicking on tests 1 and 2, what's actually needed? I don't think there's any point in implementing 80/132 columns mode. Maybe light/dark mode needs to be supported?

**Comment by jwilm** [comment]
Thanks for all the thoughts @klamonte. Somehow I had missed your comment in the past.

**Comment by chrisduerr** [comment]
I went through all basic tests that are necessary for most terminal features and Alacritty seems to pass them without any troubles. While it doesn't match XTerm, most of the deviations are intentional and match other terminals like VTE.

So while I wouldn't close this issue as completely resolved, since that's not desired anyways, I think there's not much value in keeping this open anymore.

If there are escape sequences desired that are covered by vttest, I would recommend to instead open separate issues with references to what they are used for. That should make fixing things much easier than a generic "vttest" issue.
