### ISSUE TITLE
Lacking Font Configuration for Text that is both Italic and Bold

### ISSUE THREAD

**Issue by smeikx** [alacritty/alacritty#2400]
Currently it’s not possible to display text that’s both bold *and* italic at the same time, as there is no option to specify a font for that case in the config file.

**Comment by chrisduerr** [comment]
It seems like a lot of terminal emulators aren't really sure how to handle this, Kitty seems to only render things italic and XTerm only renders things bold when both are specified.

Both URxvt and VTE do support this though, so I think it makes sense to follow their lead and apply both italic and bold styling when both escapes are present.

I'm not sure how this should be handled in the configuration, since we do not automatically generate bold or italic versions of the font, so it might be necessary to have a third bold and italic font. That definitely isn't ideal since it's likely never going to be used (applications can't really rely on this working properly), but it might be the only option.

**Comment by nixpulvis** [comment]
#957 is relevant here.

**Comment by kchibisov** [comment]
This thing was implemented here a7cf053c88a0e8a1cc8e1c0d60ceb717a4934858
