### ISSUE TITLE
Splits Cause unreasonable Performance

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#2435]
Which operating system does the issue occur on?
Ubuntu 19.x

If on linux, are you using X11 or Wayland?
Default ubuntu, i believe x11

Open vim and type `:vert help` and observe the slowdown.

**Comment by chrisduerr** [comment]
In which kind do they slow things down? I'm not able to reproduce any slowdown at all.

**Comment by kchibisov** [comment]
@kraythen What's your screen resolution and GPU ( the one, that is used in `Xorg` for rendering). Does performance change if you change size of `alacritty` (e.g fullscreen and small window)?

**Comment by kraythen** [comment]
My computer is a Razer Advanced RTX 1080 and full hd 1080p. The behavior is transient. I will let you know about resizing.

**Comment by kchibisov** [comment]
Are you using `nvidia` proprietary driver in `Xorg` (you can check `/var/log/Xorg.0.log` for strings like LoadModule: "intel" or run `glxinfo | grep -i vendor`)? Do you mean NVIDIA RTX 2080 ( `lspci | grep -e VGA -e 3D` can help you)? Could you share your vim configs and also whats your vim version?

I'm using `alacritty` with neovim (I have 3-4 active splits always, lots of plugins and autocmds) inside tmux session on a machine with  just `Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz` and `2560x1600@60` screen resolution, but I've never observed any slowdown. I'm also on X11 to make it clear.

I think it's something related to driver/compositor/vim configuration. I've asked you about screen resolution, because `alacritty` had ( and as far as I remember "has") problems with large grids (e.g. 4k screen) on some poor integrated GPUs due to memory usage.

**Comment by chrisduerr** [comment]
> I've asked you about screen resolution, because alacritty had ( and as far as I remember "has") problems with large grids (e.g. 4k screen) on some poor integrated GPUs due to memory usage.

I am not aware of this and I've been very successful running Alacritty even with full HD grids (1920x1080 cells).

In general I'd recommend testing with a default vim and default Alacritty configuration, to make sure no plugins might be getting in the way.

Also "slow" can mean a lot of things, so please be more specific.

**Comment by kchibisov** [comment]
offtopic.
@chrisduerr FYI #897 ( And I was able reproduce it on Linux/macOS in the past )

**Comment by chrisduerr** [comment]
Seems like the author is gone without providing further detail, so nothing that we can do here.
