### ISSUE TITLE
QoL: print currently used config file in config deprecation message

### ISSUE THREAD

**Issue by matthiaskrgr** [alacritty/alacritty#2444]
It would help if alacritty printed the location of the config file in use when warning about deprecated config attributes. :)

**Comment by chrisduerr** [comment]
I'm not 100% sure if I'm sold on this. I think in theory the user should know where his configuration files are located. If a platform like Windows is used where that might not be immediately obvious, then `alacritty -v` can be used to print the config file location.

The message bar itself should be kept to an absolute minimum I think. It's not uncommon for terminals to be quite small and it would be unfortunate if the message bar would take up so much space that the terminal itself wouldn't be usable anymore. Printing the error message itself was already tricky, but I'm not sure if loading even more into it is going to do any good.

On the other hand `alacritty -v` is not very discoverable. But I think I'd go for a different approach completely that would solve this problem without ever really touching it at all.

It has been discussed to stop spawning configuration files by default completely. I'm personally a huge proponent of this since I think that applications should cleanly install and uninstall without leaving anything behind if possible. I don't really like testing something and then having to look around for remaining config files.

So if we do not spawn configuration files by ourselves anymore, the only one who would spawn it would be the user. As a result he should always know exactly where he put his configuration file and there should not be any need for printing the location out anymore.

Do you think that would be a solution to your problem, or do you think there are other scenarios where it might be difficult to know about the configuration file location?

**Comment by nixpulvis** [comment]
Alternatively, could we add another button to the message bar to open a new terminal + `$EDITOR` (or another editor) with the errant config? I can see this being overly complex.

But I completely agree about not writing a default config, and also think that mostly solves this problem. Any button or other help would be icing.

**Comment by chrisduerr** [comment]
> I can see this being overly complex.

I feel like that's exactly the case. There are so many issues involved with this (we might not know the user's shell, just launching the editor without shell might not work, ...) that I don't think there's not much benefit in going for that route.

**Comment by chrisduerr** [comment]
I don't think this feature is justified given that we already have the option to log all configuration files if the user somehow has no idea what they are doing.
