### ISSUE TITLE
Cursor navigation in shell

### ISSUE THREAD

**Issue by vlovich** [alacritty/alacritty#2476]
Which operating system does the issue occur on?
Windows w/ WSL bash 4.4.19

In OSX terminal I'm used to be able to option-click to have the cursor automagically navigate to that spot in the shell command-line. Would a feature like this be possible in Alacritty? There's a few other useful navigation tricks like cmd-up/down that jump to the previous/next terminal input line. Or maybe there's already a setting that controls this?

**Comment by chrisduerr** [comment]
This is not possible without modifications to the shell and it's not standardized in any way. So there's really no good way for Alacritty to implement this.

**Comment by vlovich** [comment]
I don't understand this comment. OSX terminal implements this without any modifications to the shell.

From https://apple.stackexchange.com/questions/9016/how-to-jump-to-a-location-using-mouse-on-iterm-terminal

> The way Option-Click works is that it issues the equivalent of arrow key inputs. This works well in editors like emacs, but if you're at the bash command prompt, it interprets up/down as "previous/next command in history". So, if you Option-Click anywhere except the same row that contains the prompt, bash goes through your command history instead of moving

**Comment by chrisduerr** [comment]
The shell modifications are necessary to jump to the previous/next terminal input line, that's what I was referring to with that comment.

Jumping within the shell as a text navigation tool is a different matter. That would likely be possible to some degree, but would still be a bit of a tacked-on hack that would certainly cause troubles in some scenarios (there's no way around that really). So I'd personally question if that's worth it especially because there already are a lot of bindings for navigating within the shell, which are likely to be worth learning either way.

I think it makes sense to some degree as a feature request though and I think because of that it's a good idea to keep this around and gather some feedback to gauge interest. Based on this it should be easier to make an informed decision about how much trouble this change is worth.

**Comment by nixpulvis** [comment]
Heh, this actually explains a confusion I had at first when learning the macOS terminal (I'm not a macOS user anymore). I'm tempted to agree that this feature exists in the shell and should be configured there. I don't love overlapping features.

Some programs don't implement this however, so I can see more of a use case there, but it still seems like something we might not want to implement.

**Comment by vlovich** [comment]
Clicking on a spot to navigate to in the line is MUCH easier than any terminal shortcut I'm aware of and I know a lot of them. The power-usage of Terminal.app is MUCH more friendly than where Alacritty sits today regardless of whether that requires support from the shell or not.

**Comment by nixpulvis** [comment]
@vlovich FWIW, I personally go to great lengths to avoid "clicking" anything. Using my eyes and moving around a little pointer is just not my preferred style. I like writing and typing; but not much of both at the same time.

Still, I can appreciate that this this not the common practice amongst macOS (and Windows) users, though I'm not seeing a strong case here for implementing it ourselves.

**Comment by chrisduerr** [comment]
Shells like zsh and bash both support vim mode. That's usually way, way faster than having to switch to the mouse.

**Comment by chrisduerr** [comment]
This "feature" is a hack at best and terminals are not the right place to implement this.
