### ISSUE TITLE
Diacritics on letters are sometimes displayed separately

### ISSUE THREAD

**Issue by verhovsky** [alacritty/alacritty#2620]
Which operating system does the issue occur on?

Ubuntu 19.04, Linux 5.0.0-20-generic, x86-64

If on linux, are you using X11 or Wayland?

X11, version 1.20.4

To reproduce, in an alacritty window, do

    echo й й

Those are the same letter represented by a different binary sequence. 

On GitHub and GNOME Terminal both of those letters are correctly displayed as `й` but in alacritty the second letter is rendered as `и` followed by the breve. Although the cursor (correctly) only moves one width instead of 2.

**Comment by chrisduerr** [comment]
It works great on my system (Archlinux/i3/X11), which version of Alacritty are you running?

**Comment by kchibisov** [comment]
I think it's`font` related, since on my system (Archlinux/sway/Waylnad) it doesn't work.

![Screenshot_Sun 07 Jul 2019 02:14:27 PM MSK](https://user-images.githubusercontent.com/27620401/60767493-b0643400-a0c1-11e9-9c1e-956d67754a41.png)

**Comment by chrisduerr** [comment]
I just copy-pasted it from github to test. What the issue is here likely is that the unicode width lookup returns a width of 1 instead of 0 for this character. I mismatch with gnome-terminal could be due to #1295. However if the lookup value is 1 instead of 0, the font should be irrelevant.

However, the unicode-width crate (https://crates.io/crates/unicode-width) does not take locale or font into account I think, which is why in theory this should return the correct width (though it might make sense to double-check).

The alternative would be that it is correctly rendered in the position of the N as a zero-width character, however the glyph itself is as wide as two characters.

**Comment by verhovsky** [comment]
@chrisduerr `alacritty 0.3.3` that I installed with `add-apt-repository ppa:mmstick76/alacritty && apt install alacritty`. I haven't changed any settings in `alacritty.yml`.

@kchibisov that character appeared on my system from a file I `rsync -P -e ssh`'d from a macOS system. I think I typed it there because the [original file](https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/KB_Russian.svg/1024px-KB_Russian.svg.png) on wikipedia has an English filename.

**Comment by hlieberman** [comment]
@chrisduerr Strangely, I get a width of 0 for the detached brave character from the unicode-width crate, which is what I would expect.  The raw character `й` returns a width of 1, as does the one using the combining mark `й`.

**Comment by chrisduerr** [comment]
> Strangely, I get a width of 0 for the detached brave character from the unicode-width crate

That sounds right. So it might just be the font which is rendering it with additional whitespace at the left of it.

I'm using Fira Mono myself (not sure if that's what the character itself is using), could someone who's able to repro this tell me what they're running?

**Comment by kchibisov** [comment]
@chrisduerr I'm not able to reproduce with `Fira Mono` (your font). But I can repro with `DejaVu Sans Mono`(my font). Both fonts were installed from Arch repository.

**Comment by hlieberman** [comment]
> I'm using Fira Mono myself (not sure if that's what the character itself is using), could someone who's able to repro this tell me what they're running?

DejaVu Mono, which does have й and the combining breve.  Fira Mono, for the record, does appear to have both as well.

**Comment by chrisduerr** [comment]
Can you reproduce this in another terminal emulator with a 'broken' font? It seems to me that if the font has a glyph that is too wide, Alacritty shouldn't be the only one with this problem.

**Comment by kchibisov** [comment]
`kitty` renders it correctly, but it treats it like a ligature. So this character can be combined with others. 

![Screenshot_Tue 09 Jul 2019 11:20:43 AM MSK](https://user-images.githubusercontent.com/27620401/60871639-d1509480-a23b-11e9-9bc3-423855e63b87.png)

**Comment by egmontkob** [comment]
Probably relevant: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854149

**Comment by chrisduerr** [comment]
Alacritty does not do any unicode normalization or character combination like ligatures. So that would explain why others might handle this differently.

It seems like most cases in the issue that @egmontkob named work correctly for me, however that is likely related to the font.

Since these are zero-width characters, I'd expect the glyphs to render over a single character the way it does in Fira Mono. I'm not sure why these glyphs are rendered as double-width in some fonts.

**Comment by kchibisov** [comment]
After investigating on IRC with @chrisduerr we found out that some fonts report their `bitmap_left`(FreeType metric about your pen) position for zero-width characters positive, while the others in negative(this is correct thing tbh). So fonts like `Fira Code` uses `left: -9` for bitmap position of zero-width chars, which leads to correct rendering, however `DejaVu Sans Mono` uses the `left: 2` position for this thing. Firefox also fails here for example, however it's not really a fail, it just renders what font asked to do, same for alacritty.
 
So this results in a wrong resulted position. The `^` thing should be above `t` and not above `i`.

```
test̂ing123
```
