### ISSUE TITLE
Add line numbers to config error messages

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#2752]
Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
X11

I just updated alacritty after a few months and it's complaining about config problems.
`[2019-08-25 17:41] [ERROR] Problem with config: invalid type: unit value, expected a map; using default value`
The error log in /tmp really isn't very helpful and I have no idea where the error actually is. Please add line numbers so I can get _some_ idea of what is wrong easily.

**Comment by chrisduerr** [comment]
The problem is that `serde_yaml::Error` will report location on error, however only when directly deserializing from the file.

What we do is deserialize it to `serde_yaml::Value` first. If that fails, we get correct line error messages.

However, when deserializing the `serde_yaml::Value` to the specific type, the line information will never be present in the resulting Error, since it is lost after it has been successfully deserialized to the `serde_yaml::Value`.

So as far as I'm concerned, there's nothing we can do with the current API of `serde_yaml`. We could require `Clone` or `Copy` on all fields deserialized with `failure_default` and then deserialize everything twice, first to check if there's an error and if there is one we clone and deserialize it to get the line number. However that's extremely hacky and I don't think it's a good approach.

**Comment by martskins** [comment]
I managed to get the error line in everything but the types that are deserialized from both string or map (`window.class` and `shell`) by changing the `failure_default` implementation to not use a `serde_yaml::Value`, unless I'm missing something that should make things better for most of the cases.

Here's what it looks like for non string-or-map fields:

![explained-error](https://user-images.githubusercontent.com/4250565/65929125-2b926900-e3d7-11e9-948d-4c18e9b39c44.png)

As for the fields that deserialize from `string` or `map`, the error displays exactly the same:

![image](https://user-images.githubusercontent.com/4250565/65929182-64cad900-e3d7-11e9-8b11-dfb634c910fe.png)

If this means an improvement I can submit a (really small) PR for this :smile:

**Comment by nixpulvis** [comment]
@martskins yes this would be great. Even small QoL things like this are valuable.

**Comment by kchibisov** [comment]
@chrisduerr is toml any better for us here? I think it always will provide a line along the error?

**Comment by chrisduerr** [comment]
![tmp](https://github.com/alacritty/alacritty/assets/8886672/8f253756-4ffc-489d-a5d1-5dc600a25ee7)

I think we can consider this fixed. It will depend on the type of error, but I think at least syntax errors should be linted with line.
