### ISSUE TITLE
Change default draw_bold_text_with_bright_colors behavior

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#2779]
At the moment, Alacritty draws bold text with the bright colors by default. This can be extremely annoying when the goal is to just get some bold text with non-bright colors and it's not necessary to use this if you actually do want to use bright colors. To make each escape do one thing and do that well, the option `draw_bold_text_with_bright_colors` is currently available to change this behavior.

Generally, I think it makes more sense to have this option disabled by default, however a choice was made against that for compatibility with other terminal emulators and keeping up with user expectations.

Kitty has never had any way to get this mixed bold escape and it has come to my knowledge in #2776 that gnome has recently disconnected the bold and bright escapes by default too. With other terminal emulators changing this and offering the chance to make right what has been done wrong in the past, I think it would be a good choice to follow suit here.

However, we're talking about a default option here, so what really matters is how most people feel about this, so I'd like to take this opportunity to get some comments on this possible change. Maybe @kchibisov and @nixpulvis can chime in, however I'm really curious about all kinds of opinions (both for and against this).

**Comment by egmontkob** [comment]
In the 2nd & 3rd paragraphs you seem to have mixed up the "enabled" vs "disabled" states. I guess you had in mind _enabling "draw_blah = false"_, didn't you?

**Comment by nixpulvis** [comment]
My initial reaction is that this is a good idea. If I forget all the history, I'm having trouble coming up with a rational for why bold and bright would be tied together at all.

I'll be curious to see what examples @egmontkob digs up for negative feedback, but it's got to all be historical support. I'd hope applications would be able to adapt, generally. Though, we'd just be changing the default value of `draw_bold_text_with_bright_colors` so there'd be an easy solution for our users.

FWIW, I googled "ANSI Bold" and the first link I got was this one: http://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html, which makes it seem like "Bold" and "Bright" are the same thing, so it's pretty clear this is a confused topic in the wild.

I've had (most) of my bright colors set to the same color as the non-bright version, which I'm thinking was probably a result of me not knowing about this bright/bold option. Now I'm wondering if I can come up with a nice set of actual bright colors for my theme (One Dark). I'll change my setting and see how things go, just as another point of reference.

**Comment by kchibisov** [comment]
I also think, that it's a good idea, since a lot of people could be unfamiliar with this bold/bright story. The folks who are aware of such thing can always find this setting in a config in my opinion.

**Comment by egmontkob** [comment]
Here are some related links I could dig up. (I might edit the comment to extend the list later.)

They are roughly in decreasing order of relevance. The last couple ones are about adding this setting, or pre-requisite cleanups that we did in gnome-terminal; not about flipping the default.

Basically: there's not much buzz going on about it. No big outcry, no big praises either.  (As I said in https://github.com/jwilm/alacritty/issues/2776#issuecomment-528439444, I expected worse.)

https://bugzilla.gnome.org/show_bug.cgi?id=762247#c29 comments 29-33

https://bugs.launchpad.net/terminator/+bug/1820544

https://bugzilla.redhat.com/show_bug.cgi?id=1687141

https://github.com/kovidgoyal/kitty/issues/197
https://github.com/kovidgoyal/kitty/issues/1738

https://askubuntu.com/q/1156880

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910078
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931744

https://bugs.kde.org/show_bug.cgi?id=405345

**Comment by nixpulvis** [comment]
Thanks a bunch for digging all this up for us @egmontkob.

`alsamixer` is a good example of an application that doesn't handle this particularly well, so that could be a good application to check out with a variety of color schemes. I know I'll need to either patch `alsamixer`, or try not to care, since in this case, my non-bright white isn't designed to be used for readable text on top of my blue, as `alsamixer` is displaying.

Hopefully as more terminals push in this direction, applications will adjust as well. And again, for those that do not we have an option, though it's not possible to enable `draw_bold_text_with_bright_colors` for only specific applications.

**Comment by GiorgosXou** [comment]
**IMHO,** changing the default of `colors.draw_bold_text_with_bright_colors` to `false` was a mistake, and the default should be reverted to `true` for several reasons:

1. It breaks the appearance of ncurses-based dialogs.
2. It makes many older TUIs render incorrectly or inconsistently.
3. It only affects the 8 standard ANSI colors, so the impact on modern applications is literally none.

Many TUI applications built on ncurses rely on the historical convention that bold implies the bright variant of the 8 ANSI colors. When `draw_bold_text_with_bright_colors` is disabled, interfaces that were designed with this assumption become harder to read or visually incorrect. **For example:**

| Bright + Bold | Bold |
| :---: | :---: |
|![bold_bright](https://github.com/user-attachments/assets/2958df5b-34f7-4326-aca6-7fe5af3fd9ff)|![bold](https://github.com/user-attachments/assets/a1806c26-b726-4995-8e1d-4b5477cdae4a)|

`draw_bold_text_with_bright_colors` only changes the interpretation of the original 8 ANSI colors. Modern applications that use 256-color or direct\true-color output are completely unaffected. Reverting the default therefore restores compatibility with decades of existing TUI software without changing the appearance of the vast majority of modern terminal applications.

---

> @chrisduerr ... Kitty has never had any way to get this mixed bold escape and it has come to my knowledge in https://github.com/alacritty/alacritty/issues/2776 that gnome has recently disconnected the bold and bright escapes by default too.

Kitty has done alot of things right but also alot wrong. One of those things is this one. 

> @egmontkob ... Basically: there's not much buzz going on about it. No big outcry, no big praises either. (As I said in https://github.com/alacritty/alacritty/issues/2776#issuecomment-528439444, I expected worse.)

The average user unfortunatelly doesn't care about things like this. Take for example the fact that [until Jan 2 of 2026 kitty didn't even supported `A_DIM`](https://github.com/GiorgosXou/TUIFIManager/discussions/133#discussioncomment-15393190) and people were fine with it, simply because noone had told them this is the normal.

---

**And last but not least:** because something feels confusing, it doesn't mean it's not the right thing.

<sub>and for historical context: this behavior originated from the hardware they emulate tl;dr; the terminal increased the beam intensity (or otherwise emphasized the glyph), making bold text appear brighter [...] </sub>

**Comment by egmontkob** [comment]
> It breaks the appearance of ncurses-based dialogs.

I am not familiar with ncurses's dialog support. Does it work with a fixed set of colors? Or does it at least have some default colors that look broken?

In that case: Funny enough, ncurses and xterm are developed by the same person, and xterm also has an option not to brighten the letters, only typeset them with bold. So, these ncurses-based dialogs are also slightly broken there, arguably a bug in ncurses.

Or is it that apps using this feature pick unfortunate colors?

Then it's a bug in those apps.

By the way, ncurses's corresponding flag is also called `A_BOLD`, and _not_ `A_BOLD_BRIGHT`. I've linked above to a comment where I study the Linux kernel's "make menuconfig" and conclude that it asks ncurses to paint white on white with a bold flag and expects it to be visible. Isn't it ridiculous? Why should it be the platform's job to work around obviously broken apps?

> It makes many older TUIs render incorrectly or inconsistently.

Yes, that's true. But it's a bug in those apps, relying on an undocumented convention, whereas the written standards clearly allow for the current behavior. Please work on getting those apps updated.

> It only affects the 8 standard ANSI colors, so the impact on modern applications is literally none.

"literally none" is not true, there are still apps out there wishing to use the traditional 16 color slots; including users of Solarized or other "alternative" palettes who definitely need the new behavior. Even users of the "standard" 16 colors would prefer to pick their favorite shades once and let many apps share them, yet still be allow to toggle boldness independently. Please get familiar with the reports that resulted in Alacritty and VTE flip their defaults.

While I have no direct influence on whether Alacritty is going to revert this change, I can tell you that after the initial year or two (most of which I've linked above) I can't recall any complaints we received for VTE, it has been a good 5+ years when people are fine with this new behavior.

There's no _default_ value that would make everyone fully happy, that's why both Alacritty and VTE allow this setting to be flipped. Flip it yourself if you prefer the other behavior. The current default value is the clean, forward-looking one, the other is the backwards compatibility one.

> Take for example the fact that until Jan 2 of 2026 kitty didn't even supported A_DIM and people were fine with it

Utterly irrelevant. Dim is magnitudes more rarely used, and its desired behavior is [debated](https://gitlab.gnome.org/GNOME/vte/-/work_items/2462).

> the terminal increased the beam intensity (or otherwise emphasized the glyph), making bold text appear brighter

Making the text appear brighter and bolder. And for any color, so why would emulators only brigthen the first 8? Still makes no sense.

> because something feels confusing, it doesn't mean it's not the right thing.

When something is so limited that there's literally no way to achieve certain basic tasks (get a bold variant of a darker user-provided palette color), and is confusing to the extent that experienced developers write code that is semantically wrong _and_ does not conform to certain valid interpretations of the standard, then _maybe_ it's time to not call it the right behavior and move on. Alacritty, Kitty and VTE made this call and I'm glad we did. Two of these allow you to revert to the compatibility behavior, should you prefer that for whatever reason.

**Comment by GiorgosXou** [comment]
> There are still applications that rely on the traditional 16 ANSI color slots.

Applications that need custom color behavior can already use the `ccc` capability *(i.e. `can_change_color()`)* to redefine the palette as needed at runtime, rather than relying on non-standard interpretations of bold or brightness.

> including users of Solarized or other "alternative" palettes who definitely need the new behavior.

Terminal color schemes\\themes are not applications themselves. They are configurations that operate within the constraints of the terminal's intended model. They should work within the ANSI color and capability system as designed, rather than depending on reinterpretations of styling attributes like bold.

**Comment by GiorgosXou** [comment]
> While I have no direct influence on whether Alacritty is going to revert this change, I can tell you that after the initial year or two (most of which I've linked above) I can't recall any complaints we received for VTE, it has been a good 5+ years when people are fine with this new behavior.

Moreover, the fact that this did not generate meaningful user feedback over a long period suggests that the change does not significantly impact real-world usage. In practice, most modern terminal applications either explicitly use 256-color or truecolor escape sequences, or they already account for the distinction between bold and bright attributes.

This indicates that the "bold-as-bright" behavior is primarily relevant for legacy TUI software that assumes historical terminal semantics, rather than for contemporary applications. As such, preserving or restoring it tends to improve compatibility with existing ncurses-based interfaces without introducing noticeable regressions for modern workloads.

**Comment by egmontkob** [comment]
> Applications that need custom color behavior can already use the `ccc` capability _(i.e. `can_change_color()`)_ to redefine the palette as needed at runtime

That's a totally different concept. One that I don't recall ever seeing in use – luckily.

Apps redefining the color palette retroactively changes already existing contents in the terminal, including the scrollback buffer. And break the said app's colors upon exiting if it plays nicely and reverts the palette. So it's only suitable for full-screen apps to begin with. (And even then it breaks if the app crashes for whatever reason.)

And is still limited to 8/16/256 colors (however many the app uses) and still equally subjected to the bold vs. bright washup.

It's a terrible concept, luckily nowadays fully superseded by truecolor support.

This is absolutely not what I was referring to. I was referring to utilities that still wish to use the traditional 16 colors (or configurations where the user wishes to limit to them, typically the default config of such apps), but rather than the app controlling the exact shade, let the user choose the preferred shades via the terminal's setting. Without the further limitations arising from the legacy bold vs. bright confusion.

> rather than relying on non-standard interpretations of bold or brightness.

"non-standard": Not the most typical, probably. But an interpretation fully within the written standards.

About a decade ago I gathered some data and concluded that VTE's usage share within Linux was in the rough ballpark of 50% among all terminals. This has surely dropped since then, partially due to the rising popularity of newer players (such as Alacritty or Kitty which are on VTE's side here). There's also Mac and Windows terminals that shade the picture. VTE has had this mode as its default for 7+ years, Alacritty has had it as its default for 6+ years, Kitty has only ever implemented this mode. Without aiming to coming up with a number, the overall market share is still surely pretty significant. We're not some niche odd terminals.

> They should work within the ANSI color and capability system as designed

"as designed": As it used to work on hardware with very limited capabilities that by its very nature washed up these two concepts, and does not make any sense on today's modern systems other than for backwards compatibility.

> rather than depending on reinterpretations of styling attributes like bold.

"reinterpretations": Again, one possible interpretation clearly allowed by the relevant standards.

> Moreover, the fact that this did not generate meaningful user feedback over a long period suggests that the change does not significantly impact real-world usage.

This is probably true; on both sides.

> This indicates that the "bold-as-bright" behavior is primarily relevant for legacy TUI software that assumes historical terminal semantics, rather than for contemporary applications.

I don't see this conclusion of yours justified.

---

Look, these are opinions, your vs. mine vs. Alacritty's (which, from a thumbs up so far on my latest comment, is probably also on my side).

We changed the _default_ behavior from the legacy backward-compatible to the clean future-looking about 6-7 (sorry, no meme reference intended) years ago. Since then hardly anyone has complained, and when we explained the situation, people have happily accepted the new behavior. After years of silence, you come along and ask to revert to the backwards compatible behavior as the default. Surely I can't speak for Alacritty, but I really don't think you have good chances here.

(If you filed the same for VTE, I'd have another reason to reject the request. This was not a standalone change in VTE but rather one in a series revamping, simplifying and cleaning up color handling. We had a modern, consistent vision that we went for. It's probably irrelevant for Alacritty.)

**Comment by j4james** [comment]
> Since then hardly anyone has complained, and when we explained the situation, people have happily accepted the new behavior.

I think most people accepted the new default because they still had an option to restore the original behavior. There were definitely users that were _not_ happy with the change, and VTE-based terminals were forced to address that by hooking up the bold_as_bright option so their users could decide for themselves which behavior they preferred. I'm fairly sure some VTE terminals even have that option enabled by default. But as long as there is a choice, I don't think the default matters that much. Just don't kid yourself that the change was universally accepted.

**Comment by egmontkob** [comment]
> There were definitely users that were not happy with the change

In situations like these, when you have to pick from two different behaviors, there is no way you can make both camps happy. Of course there were pro and con users as well. But the amount of complaints we received for the change was extremely small, close to zero – honestly significantly smaller than I had expected.

> I'm fairly sure some VTE terminals even have that option enabled by default.

It's a good point that I have just missed; indeed some VTE -based terminals might default to (or only offer) the "bold is also bright" behavior. (I don't remember what any of them does here, and can't be bothered to check.)

> Just don't kid yourself that the change was universally accepted.

Don't worry, I don't.

I am adamant on calling our old default "SGR 1 is bold and for the first 8 colors it's also bright" the _legacy, kludgy, backwards compatible_ behavior, clearly arising from the limitations of the hardware a few decades ago, a behavior that no sane person would ever design on today's computers; and our new default "SGR 1 is bold typeface only" the _simple, cleaned up, sane, well-designed, modern, future-proof_ behavior; because obviously that's what they are.

If a piece of software switches from the legacy kludgy behavior to the cleaned up sane behavior _by default_ (retaining the option for the user to pick the other one), very few people care and after explaining the story they also accept the new default, and then after years and years of the software working just fine with this new default behavior suddenly someone comes and argues that this default should be reverted to the old kludgy behavior, well... I'm not convinced. But Alacritty is not my project, it won't be my decision.

**Comment by chrisduerr** [comment]
> very few people care and after explaining the story they also accept the new default, and then after years and years of the software working just fine with this new default behavior suddenly someone comes and argues that this default should be reverted to the old kludgy behavior, well... I'm not convinced. 

Yeah it's honestly no surprise people pushed back when this was originally introduced in terminal emulators. People don't like change (especially for terminals) and anything that works differently to the expectations is 'broken'. However I do think that if you asked a 'fresh mind' if it was a good idea to tie bold text to automatically always also change the text color, they'd look at you like you're insane (because it kinda is).

**Comment by nixpulvis** [comment]
We still support the `colors.draw_bold_text_with_bright_colors` config option right?

This seems like an argument about defaults, which let's be honest, we default to the sane modern value. Alacritty is hardly known for pushing away from tradition, but this is a case where I think it made sense.

**Comment by chrisduerr** [comment]
> We still support the colors.draw_bold_text_with_bright_colors config option right?

Yup.

> This seems like an argument about defaults, which let's be honest, we default to the sane modern value. Alacritty is hardly known for pushing away from tradition, but this is a case where I think it made sense.

Yup.
