### ISSUE TITLE
Alacritty starts from the terminal but crashes(doesn't open) when I'm using the application icon.

### ISSUE THREAD

**Issue by rednithin** [alacritty/alacritty#2781]
Which operating system does the issue occur on?
Manjaro KDE 18.04

If on linux, are you using X11 or Wayland?
X11

**Comment by nixpulvis** [comment]
@rednithin are there any error messages or logs you can share? Maybe somewhere in `journalctl | grep alacritty`?

**Comment by kchibisov** [comment]
@rednithin Also, how did you install alacritty? If you done it with `rustup` and build things yourself make sure that `alacritty` is in the `PATH` for "system" shell (the one you're seeing on `tty`).

**Comment by rednithin** [comment]
> @rednithin are there any error messages or logs you can share? Maybe somewhere in `journalctl | grep alacritty`?
There is nothing showing up.

**Comment by rednithin** [comment]
> @rednithin Also, how did you install alacritty? If you done it with `rustup` and build things yourself make sure that `alacritty` is in the `PATH` for "system" shell (the one you're seeing on `tty`).

I have installed it through pacman

**Comment by eprislac** [comment]
I have the same issue, installed via `brew cask install alacritty` on MacOS

**Comment by rednithin** [comment]
> I have the same issue, installed via `brew cask install alacritty` on MacOS

The version I am using is 0.3.3-3

**Comment by chrisduerr** [comment]
> I have the same issue, installed via brew cask install alacritty on MacOS

This might be a signing issue. But it's definitely unrelated to this issue so if you're interested in fixing it please open another issue.

@rednithin Could you compile the latest master? There have been a lot of updates since then especially because of the way the pacman version is packaged. So instead of just guessing for possible problems I think it would make sense to test this first.

**Comment by rednithin** [comment]
I installed "alacritty-git" from the AUR. The problem still persists.

**Comment by kchibisov** [comment]
What's your login shell?

**Comment by rednithin** [comment]
Zsh

**Comment by kchibisov** [comment]
Would you mind setting `persistent_logging` to `true` in `alacritty.yml` and clicking on the icon. It should create log file in `/tmp/Alacritty-<some_string>.log` and posting it here, make sure that you've grabbed the correct log, since `alacritty` creates one by default, but it erases it after quit.

**Comment by chrisduerr** [comment]
I don't think persistent logging will help with anything since it crashes. We'd need the stderr of the process, which will likely print a useful backtrace.

**Comment by kchibisov** [comment]
It can help with `Failed to spawn command: ` though.

**Comment by chrisduerr** [comment]
Version 0.3.3 has been release a long time ago and there was no reply to the latest comments. Since no other users have run into this issue since, I'd assume this is not a problem in the latest versions anymore.

**Comment by rednithin** [comment]
Duplicate of #2566

**Comment by chrisduerr** [comment]
That's a macOS issue. This issue is about Manjaro.

#2566 is completely unrelated.
