### ISSUE TITLE
Key repeat sluggish, take 2

### ISSUE THREAD

**Issue by for-coursera** [alacritty/alacritty#2876]
(As suggested [here](https://github.com/jwilm/alacritty/issues/1466#issuecomment-541315790) by @chrisduerr, I open this separate issue.)

**OS**: macOS 10.11
**Alacritty**: 3475e44 (the latest master)

**To reproduce**: For me, the easiest way to notice the problem was to scroll in Midnight Commander: 

  - start scrolling by pressing the `<Down>` arrow;
  - keep the `<Down>` arrow pressed, observe the cursor going down;
  - stop scrolling by releasing the `<Down>` arrow;
  - the cursor still goes down by one (or sometimes more) entries.

Another simple way to reproduce is to delete something with the `<Backspace>` key in Vim, for example. 

E.g., backspacing over this string `https://github.com/jwilm/alacritty/issues/1466#issuecomment-541315790` from the end till the `#` sign (releasing `<Backspace>` as soon as we see the `#` sign disappear), for me results in one or two additional characters being "eaten" (the result being like `https://github.com/jwilm/alacritty/issues/14`). 

In Terminal.app, both these scenarios don't seem to happen.

**Sidenote No. 1**: In general, scrolling in `mc` does take more time in Alacritty than in Terminal.app. For example, scrolling through my `/usr/local/bin` with 346 files by pressing the `<Down>` arrow from the first entry to the last one (`mc`'s panel set to `Brief file list with two columns`) takes approximately 39 secs, while doing the same in Terminal.app takes something like 29 secs (both fullscreen).

**Sidenote No. 2**:  As suggested [here](https://github.com/jwilm/alacritty/issues/2514#issuecomment-499597351), I also tried cloning https://github.com/rust-windowing/winit, and then running `cargo run --example window` to check if the output keeps going after the key has been released. The result is, it is not: as soon as I release a key in that example window, the output stops.

**Comment by chrisduerr** [comment]
Just to re-confirm in this issue, this is on the latest master, right?

**Comment by for-coursera** [comment]
Yes, as I said that in the description :)

**Comment by chrisduerr** [comment]
Oh, I missed that, sorry.

**Comment by for-coursera** [comment]
Just for the reference, still happens with a75e949 (the latest master).

**Comment by glostis** [comment]
Hi,

I've experienced the same issue as @for-coursera when "scrolling" in Vim by keeping `j/k` pressed down, it seems that Vim keeps scrolling for a few lines after I've physically released the key.

I've found a way to demonstrate the issue quite easily using [xdotool](https://github.com/jordansissel/xdotool) to send keys to the terminal in a controlled manner.

Running the following snippet in the terminal sends keys 0 through 9 ten times:
```
xdotool key --delay 0 $(for i in $(seq 1 10); do for j in $(seq 0 9); do echo -n "$j "; done; done)
```

Which looks like this in `alacritty` - you can see a significant lag before all keys are displayed:

![alac](https://user-images.githubusercontent.com/25295717/80474413-b7597d00-8947-11ea-89a3-6e0ad4a6cf15.gif)

And looks like this in `terminator` - all keys are displayed instantly (I've also tried it on GNOME terminal and XTerm and got the same result):

![terminator](https://user-images.githubusercontent.com/25295717/80474628-f8519180-8947-11ea-9088-1206cec98276.gif)

I am running `alacritty 0.4.1` installed from `ppa:mmstick76/alacritty` on Ubuntu 18.04, so I do not think this is a MacOS issue only.

I'm happy to open a separate issue if you prefer!

**Comment by for-coursera** [comment]
Thanks, @glostis, that's indeed a brilliant demonstration!

**Comment by chrisduerr** [comment]
@glostis Which Linux backend is that?

**Comment by glostis** [comment]
@chrisduerr what exactly do you mean by Linux backend? I'm running the default Ubuntu 18.04 flavour, with the GNOME Desktop Environment I believe.

**Comment by chrisduerr** [comment]
Wayland or X?

**Comment by glostis** [comment]
I have the environment variable `XDG_SESSION_TYPE=x11` so I guess that means it's using X

**Comment by glostis** [comment]
I was able to logout of my Ubuntu session and login with "Ubuntu Wayland", and it seems that the problem is not present with Wayland.

I was not able to reproduce the exact same demonstration since `xdotool` does not work with Wayland, but the problem is not noticeable anymore in Vim, which is good news!

Unfortunately, X is the default backend for Ubuntu 18.04 so I'd prefer not to have to change my backend.

**Comment by chrisduerr** [comment]
@glostis Could you share more about your system? I personally run i3+picom and cannot reproduce your specific issue at all for example.

Since the original issue is also about macOS and your issue is resolved on Wayland, it seems highly unlikely that these issues are related. So a separate issue would probably be better.

**Comment by chrisduerr** [comment]
Also to follow up on the original issue @for-coursera, if you're still interested in fixing this it might be useful to check if Alacritty's output keeps going after releasing a key when running it with `alacritty --print-events` and then holding a key.

Though it seems unlikely this will be figured out unless someone who is willing and capable to contribute code is able to reproduce it.

**Comment by calbrecht** [comment]
> I was not able to reproduce the exact same demonstration since `xdotool` does not work with Wayland, but the problem is not noticeable anymore in Vim, which is good news!

There is https://github.com/atx/wtype, which seems to do the job for this matter.

Now, with running `wtype $(for i in $(seq 1 2000); do echo -n "$i "; done)` in a `nix-shell -p wtype` i am able to crash alacritty quite reliably (the higher the iteration, the more reliable it seems)

Besides the crash, i cannot reproduce the lagging. :tada: 

```
% sway --version
sway version 1.4-59acc12b (May 01 2020, branch 'master')
% alacritty --version
alacritty 0.5.0-dev (2c2104a)
```

Got an strace of it, if that is helpful. Also, maybe https://github.com/alacritty/alacritty/issues/3363 is rather the place i should put this in.

**Comment by kchibisov** [comment]
Can you should the crash log, is it from clipboard?

**Comment by calbrecht** [comment]
@kchibisov, hm no clipboard involved. Only wtype. Should i open a new issue then?

**Comment by kchibisov** [comment]
Yeah, it'll help, but I guess it's on `connection to compositor lost` or something like that.

**Comment by lheckemann** [comment]
Maybe ydotool is helpful for testing.

**Comment by chrisduerr** [comment]
Just sending arbitrary text at high repeat rates to Alacritty really does nothing to help with identifying input latency problems.

The issue described by @glostis has nothing to do with Alacritty's repeat rate and is a separate problem that noone else I've talked to so far can reproduce.

**Comment by dnkl** [comment]
@calbrecht wtype has a `-s <ms>` option to control the delay between each faked key press, which should prevent the crash.

**Comment by up-to-you** [comment]
@chrisduerr The issue is simply reproducible on Macos:
`defaults write -g KeyRepeat -float 0.9`
`-> logout -> login`
You can open any text editor or browser (in my case it was VSCode and Chrome) and see crazy repeat rate.
Then open alacritty and see how much keystrokes terminal losses
To put everything back in place:
`defaults write -g KeyRepeat -int 1`
`-> logout -> login`

**Comment by dpacbach** [comment]
I am also experiencing this issue.  Here is my setup:

* Linux / Pop!_OS 20
* Alacritty 0.6.0
* High keyboard repeat rate enabled.
* 4k monitor.
* I have a powerful machine with many cores and advanced NVidia graphics card, so can't be due to under-powered system.
* Problem does not happen in gnome terminal on same system.

When I hold down j/k in vim and scroll, it keeps scrolling for a second after I let up the keys.

My guess as to what is happening is that Alacritty is probably redrawing the window on each cursor movement and is unable to keep up, causing keys to get buffered.

When I enable `render_timer` in the config, then open vim and start scrolling, it displays around ~3600 microseconds as the cursor is moving, which would seem to imply about ~270 fps which would seem to be enough, but somehow the lagging persists.

I tried making my text font a lot bigger to e.g. reduce the amount of text that is drawn, but that does not seem to help.  I suspect it might have to do with screen resolution.

**Comment by ebr** [comment]
Another confirmation of this issue over here, on multiple systems:

- Pop!_OS 20
- Fedora 33
- Alacritty 0.6.0
- high keyboard repeat rate
- 4k laptop screen, 4k external monitor, 1080p laptop screen, all present with this issue

This is most prominent when scrolling in Vim. Other terminal emulators (Gnome term, Terminator) don't have this issue.

**Comment by vyorkin** [comment]
Can confirm this is the case on Ubuntu 20.04:

```

vyorkin@shelter
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.8.0-43-generic
Uptime: 1d 1h 51m
Packages: 3359
Shell: zsh 5.8
Resolution: 3440x1440
DE: GNOME 3.36.5
WM: Mutter
WM Theme: Adwaita
GTK Theme: Yaru-dark [GTK2/3]
Icon Theme: Yaru
Font: Ubuntu 11
Disk: 315G / 462G (72%)
CPU: AMD Ryzen 5 3600 6-Core @ 12x 3.6GHz
GPU: GeForce GTX 1070 Ti
RAM: 7437MiB / 32107MiB

```

**Comment by dpacbach** [comment]
I just did another test where I set my keyboard repeat rate up significantly higher than 60/s, and the lagging in Alacritty got significantly worse in proportion, so I am convinced at this point that it is due to a keyboard repeat rate that is higher than 60/s while Alacritty can only move the cursor at most 60 times per second, so additional key motions get buffered and continue when the key is let up.  The same experiment with gnome-terminal on the same system shows no buffering at all.  @chrisduerr does this help you to reproduce it?  (This is on Linux (Pop!_OS))

**Comment by c02y** [comment]
> Hi,
> 
> I've experienced the same issue as @for-coursera when "scrolling" in Vim by keeping `j/k` pressed down, it seems that Vim keeps scrolling for a few lines after I've physically released the key.
> 
> I've found a way to demonstrate the issue quite easily using [xdotool](https://github.com/jordansissel/xdotool) to send keys to the terminal in a controlled manner.
> 
> Running the following snippet in the terminal sends keys 0 through 9 ten times:
> 
> ```shell
> xdotool key --delay 0 $(for i in $(seq 1 10); do for j in $(seq 0 9); do echo -n "$j "; done; done)
> ```
> 
> Which looks like this in `alacritty` - you can see a significant lag before all keys are displayed:
> 
> ![alac](https://user-images.githubusercontent.com/25295717/80474413-b7597d00-8947-11ea-89a3-6e0ad4a6cf15.gif)
> 
> And looks like this in `terminator` - all keys are displayed instantly (I've also tried it on GNOME terminal and XTerm and got the same result):
> 
> ![terminator](https://user-images.githubusercontent.com/25295717/80474628-f8519180-8947-11ea-9088-1206cec98276.gif)
> 
> I am running `alacritty 0.4.1` installed from `ppa:mmstick76/alacritty` on Ubuntu 18.04, so I do not think this is a MacOS issue only.
> 
> I'm happy to open a separate issue if you prefer!

Noticed that same scrolling problem, and running the command (`xdotool key --delay 0 $(for i in $(seq 1 10); do for j in $(seq 0 9); do echo -n "$j "; done; done)`) in my alacritty only output a few numbers and completely freezes my alacritty.

`alacritty 0.7.2 (5ac8060b)` + Manjaro-Linux here, looks like this issue hasn't been fixed for over 3 yeart(https://github.com/alacritty/alacritty/issues/723)

**Comment by c02y** [comment]
This key-repeat-sluggish issue is fixed for the version v0.10.0-dev (1d8bd73b)

Manjaro+Nvidia+Xorg here

But `xdotool key --delay 0 $(for i in $(seq 1 10); do for j in $(seq 0 9); do echo -n "$j "; done; done)` command prints nothing(only a new shell prompt) and freezes alacritty completely.

**Comment by chrisduerr** [comment]
@c02y Were you able to previously reproduce this issue and are you able to make it happen again by downgrading Alacritty?

**Comment by dpacbach** [comment]
@c02y do you know what the problem and/or fix was?

**Comment by c02y** [comment]
@dpacbach If you are asking about the code, no, I didn't analyze the code.

**Comment by kchibisov** [comment]
I don't think it's an issue anymore, it was an issue before due to vsync, but now we process input as fast as we can.

**Comment by no-more-secrets** [comment]
@kchibisov I just built the latest version:
```sh
alacritty --version
alacritty 0.6.0-dev (199c32b)
```
and it is still an issue.  Is there a setting that I can use to disable vsync syncing?  I looked in the config but did not see it.

**Comment by kchibisov** [comment]
>alacritty --version
>alacritty 0.6.0-dev (199c32b)

I'm not sure what you've built, the latest version is 
```
~ → alacritty --version
alacritty 0.13.0-dev
```

Even `0.12.2` should be fine here.

Vsync is not used at all anymore, we explicitly disable it.

**Comment by no-more-secrets** [comment]
@kchibisov Ok thanks, after using the proper latest version the issue does indeed appear to be fixed.  What went wrong in my build script is that the script say the tags of the form `v9.x` and assumed they were the latest when actually the `v0.12.x` are -- perhaps we should delete those `v9.x` tags to avoid confusion?  I can envision a lot of people incorrectly building the wrong version because of the presence of those tags.

**Comment by kchibisov** [comment]
@chrisduerr I think I've removed these tags in the past, but you might have pushed them again from your tree? Could you remove them?

**Comment by chrisduerr** [comment]
I don't know how they got there, I only push tags explicitly. They're gone now though.
