### ISSUE TITLE
Allow first click on unfocused windows to be passed through on macos

### ISSUE THREAD

**Issue by mivok** [alacritty/alacritty#2929]
In #1291, and later #1539 and #1540, changes were made to ignore the first click on an unfocused window on macos. At the time, this behavior was hardcoded per platform (pass through on non-macos, ignore first click on macos) on the belief that nobody would want the behavior to be different. After some discussion on #1540, it was requested that I open this issue to revisit this decision, gauge interest and ask for the ability to configure the first click behavior, at least on macos.

My use case is as follows:

I run tmux with multiple panes (2-up or 4-up) in a single, large terminal window. This is the recommended method for having splits/multiple windows in alacritty's README. I also have mouse support enabled in tmux, which allows (amongst other things) clicking to select the active pane.

What I would like is, when another application is focused, to be able to click on the alacritty window and have the pane underneath the mouse cursor to be the active one.

The current behavior of not passing the first click through means that I have to click on the window twice, or click on the window then use tmux keyboard commands to select the appropriate pane. Or, more likely what happens is that I click on the terminal window, start typing, but the correct pane wasn't selected and the input goes to the wrong pane.

The original issue (#1291) discussed that not passing through the first click matches iterm2's behavior. However, this is incorrect, as iterm2 allows the behavior to be configured. Discussion on this issue also claims that this is expected behavior for macos, however in tests I have found that the first click is sometimes passed through and sometimes not, depending on the application, and sometimes depending on what you click in the application (e.g. in chrome you can click on UI elements and the click is passed through, but click on the web page itself and the click isn't passed through).

I understand the rationale for wanting to change the behavior in the original change, but I believe it should be configurable without having to create a custom build.

**Comment by seeruk** [comment]
I have the same use-case. Struggling at the moment to find the part in the current source code to tweak to force the desired behaviour in the absence of a configuration option. If I knew Rust I'd submit a PR for the config change myself, but sadly, I have no experience with it.

**Comment by cfstras** [comment]
Same issue here, just switched to Alacritty only to realize it breaks with the (default) iTerm2 behavior of selecting the clicked pane when clicking on the unfocused window.
Remember that iTerm2 uses tmux under the hood, so my expectation was that Alacritty+tmux would behave the same here, but they don't.

It would be really cool to have this option configurable, assuming @jussi-kalliokoski's use case is still valid.
Is the issue here that the first click is actually a drag, which creates a selection? I tested without tmux, and clicking does not create a selection by itself. Handling it as a drag sounds like a different issue to me...

**Comment by cfstras** [comment]
Tried to hack this in and found 43f89a64c, so it seems this filter has been moved to winit.
I'm not sure whether this has anything to do with https://github.com/rust-windowing/winit/issues/942, but I'm pretty sure not sending through the first click event is a bug.

**Comment by chrisduerr** [comment]
> I'm not sure whether this has anything to do with rust-windowing/winit#942, but I'm pretty sure not sending through the first click event is a bug.

This behavior is pretty consistent with other applications, so I doubt it.

**Comment by cfstras** [comment]
I just did a few tests *clicking on unfocused windows*:
- Firefox:
  - clicking the URL bar selects it (I can start typing a URL), even if a website element was active previusly
  - clicking the website leaves the URL bar active
  - the first click into the website is generally ignored
- Chrome:
  - same behavior as Firefox, except clicking the URL bar places the cursor at that position instead of selecting the whole contents
- IntelliJ
  - clicking into a code window places the cursor at that position
  - clicking a button or a tab initiates the action
- App store
  - Clicking any UI element initiates the corresponding action on the first click
- System Settings
  - same thing as App store
- Terminal
  - clicking the tty activates it
  - clicking the tab bar activates that tab

Other than the web pane of browsers, I couldn't find a single application that ignores the first click event... So I can't really follow the reasoning for doing that.
I'd be happy to try adding a settings option if you could point me to a direction within winit :)

**Comment by kchibisov** [comment]
That should be pretty trivial to add https://docs.rs/winit/0.28.6/x86_64-apple-darwin/winit/platform/macos/trait.WindowBuilderExtMacOS.html#tymethod.with_accepts_first_mouse 

Just a simple `window` option only for macOS.

**Comment by to-json** [comment]
This appears to be 'fixed' as of 0.12.2; Steps to reproduce:

On macOS
- open Alacritty
- open tmux, configured with mouse support
- open a different application, without overlapping the Alacritty window
- create a split
- click into one of the panes (pane A)
- click on the other application, shifting OS level focus (verifiable by the macOS menu bar)
- click back on Alacritty, in the other pane (pane B)

expected behaviour according to this issue: tmux focus remains in pane A, until a second click, or some other focus shifting event

actual behaviour: tmux focus shifts to pane B in the same way it would have if Alacritty were already in focus

This issue may now be closable; tagging @mivok, @cfstras, and @seeruk to confirm it works for their use case.

**Comment by mivok** [comment]
This does indeed appear to be fixed for my use case. I'm currently using a different terminal emulator, but I loaded up alacritty and tmux and the behavior is now as I wanted in my initial request above.

From my point of view, this issue can be closed.

**Comment by cfstras** [comment]
Yep, seems fixed here as well!
