### ISSUE TITLE
Alacritty should provide option to completely turn off icon bouncing.

### ISSUE THREAD

**Issue by chakrit** [alacritty/alacritty#2950]
**Which operating system does the issue occur on?**
OS X

**If on linux, are you using X11 or Wayland?**
(n/a)

**Description**
This is somewhat related to #2492 but I think this is more Alacritty's job to provide a knob to turn off any kind of notification altogether. Think of this as having apps requesting your permission to send you notifications. Alacritty shouldn't just let any shell program cause the icon to bounce, it should be the one in-control (and thus let the user choose).

It is quite annoying to have to configure and re-configure each piece of software to handle signals correctly every time I re-install it or move between OSes/shells.

Something like this would be perfect:

```yaml
bell:
  enabled: false
  visual_bell:
    # maybe move visual bell option here?
```

**Comment by kchibisov** [comment]
>Alacritty shouldn't just let any shell program cause the icon to bounce, it should be the one in-control (and thus let the user choose).

We're just getting escapes, we don't know who is sending them etc, so it's nearly impossible to control things in the suggested way.

The question is whether we should allow disabling setting urgency flag on a window through the bell.

I personally don't mind adding something to toggle this kind of things, however I wonder who is responsible for silencing urgency requests in general. I think if you want to "disable icon jumping" for, let's say, `N` apps, you probably want to disable this behavior in one specific place (e.g. your WM settings), and not changing all application to fit your needs.

I also wondering about how other macOS terminal emulators behave in the mentioned use case (I don't have macOS machine to test things myself), but I feel like no one provides a toggle to alter this behavior (they're not setting urgency at all or setting it all the time like `alacritty`).

**Comment by chrisduerr** [comment]
There are two escape sequences which already exist that Alacritty currently does not implement:
 - DEC 1042 -> Enable Urgency window manager hint on bell
 - DEC 1043 -> Enable raising of the window on bell

**Comment by nixpulvis** [comment]
I'm copying the descriptions for these escapes below:

**`bellIsUrgent`**
> Ps = 1 0 4 2  ⇒  Enable Urgency window manager hint when Control-G is received, xterm. This enables the bellIsUrgent resource.
>
> bellIsUrgent (class BellIsUrgent)
Specifies whether to set the Urgency hint for the window manager when making a bell sound.  The default is "false".

**`popOnBell`**
> Ps = 1 0 4 3  ⇒  Enable raising of the window when Control-G is received, xterm.  This enables the popOnBell resource.
>
> popOnBell (class PopOnBell)
Specifies whether the window would be raised when Control-G is received.  The default is "false".
If the window is iconified, this has no effect.  However, the zIconBeep resource provides you with the ability to see which iconified windows have sounded a bell.

I'm mainly wondering how we should interpret "urgent" and "raising" for a window. Urgent to me (an i3 user) means that I can set my window to be outlined in red, I'd also think this maps to bouncing icons in the macOS dock. Raising a window, I'm less familiar with. Is this a way for an application to assert focus?

**Comment by chrisduerr** [comment]
> Urgent to me (an i3 user) means that I can set my window to be outlined in red, I'd also think this maps to bouncing icons in the macOS dock.

That is correct.

> Raising a window, I'm less familiar with. Is this a way for an application to assert focus? This thread I found makes it seem like it is.

Imagine having a thousand windows open, I think "raise" just means that no matter how "deep" below other windows it is, the application will be moved to the top of the stack to allow user interaction.

However, I mostly mentioned this for completeness sake. I don't think it's necessary for us to support this to finish this PR.

> We currently, always send an Urgent event whenever a bell is received, so we could check the state of bellIsUrgent before sending this event.

Yeah, I think that would be the best solution. It should be fairly straight-forward.

> The defaults for both, bellIsUrgent and popOnBell are false, making it seem like this issue would be resolved without extra configuration, and might break peoples expectations. Will users be aware of how to enable this?

We don't need to (and shouldn't imho) change the defaults. We would just add an option to disable it at runtime through an escape.

**Comment by juanibiapina** [comment]
There's a lot of very specific stuff here. What's the summary? Is this something doable? I'd love to have a configuration to disable any kind of icon bouncing.

**Comment by chrisduerr** [comment]
> There's a lot of very specific stuff here. What's the summary?

There's a standardized escape sequence and we just need to implement it.

> Is this something doable?

It is, given that someone has the time to implement it.

**Comment by jkp** [comment]
Another voice to the group who'd like to see this done - the behaviour is pretty annoying today :(

**Comment by qrasmont** [comment]
Hey @chrisduerr I think I can get this done. Can you assign this to me ?

**Comment by kchibisov** [comment]
@qrasmont one important note, is that this config option should be in a special section proposed [there](https://github.com/alacritty/alacritty/issues/3386), so you'll likely implement infrastructure for this issue as well in your PR, however you don't have to add any additional OSCs(DEC) into it, besides the one from Urgency.

**Comment by qrasmont** [comment]
@kchibisov  Ok since I'm new to the code base (and terminal emulators in general) I think what I had understood is not correct.

I taught supporting DEC 1042 would allows the user to enable/disable bell urgency at runtime.

But in fact DEC 1042  wouldn't be set by a user, it's just an escape sequence that could be received from any program and should be supported, allowing to define if the Urgent event should be send or not .

And the user can choose to never allow the bell to be urgent using the new config options you suggest in #3386 . Is that correct ?

**Comment by kchibisov** [comment]
>I taught supporting DEC 1042 would allows the user to enable/disable bell urgency at runtime.

This is correct, it could be triggered during runtime.

>But in fact DEC 1042 wouldn't be set by a user, it's just an escape sequence that could be received from any program and should be supported, allowing to define if the Urgent event should be send or not .

Yeah, but if you disable this escape(restrictions I'm talking in #3386) it should prevent urgent setting, and so we can don't set urgent if that setting was disabled by the user at all, leaving it enabled by default, and acting like it was enabled. Also, those escapes are pretty strange and unlikely are used.

>And the user can choose to never allow the bell to be urgent using the new config options you suggest in #3386 . Is that correct ?

Kind of, you can blacklist DEC 1042 in this options. However user could actually want to disable it and set resource to some value by default. So I feel like we should have a way to set default behavior for those escapes, what do you think @chrisduerr ? I feel like we need special syntax to describe each osc in a kind of unique way. Something like:

```yaml
escapes:
- { resource: UrgentOnBell, resource: enabled/disabled, toggle_with_escape: true/false }
```
I'm not sure where it should be an array, since you can't work with them generically, I also don't really like suggested naming, but it's just some idea, maybe we can have something like:
```yaml
- UrgentOnBell
  resource: enabled.
  toggle_with_escape: false
```

I'm really not sure what syntax should we use and how it should work together.

However you can at least implement DEC 1042 without those special option and any other config related option, since internal infrastructure to add this escape should be the same, regardless of new config options (e.g. toggling urgency, when we're getting this escape sequence).

**Comment by nixpulvis** [comment]
If I'm following this correctly, the steps are perhaps:

1. Start implementing `CSI ? Pm l` (and possibly `CSI ? Pm h` as well)
2. Implement a way to disable "toggle with escape", or maybe "toggle with command sequence"

These could be two separate PRs as far as I'm concerned. Though the feature wouldn't necessarily be reliable without a way to set this statically, I agree.

**Comment by chrisduerr** [comment]
I think you're needlessly over-complicating things.

All we need to do for now is implement the two escape sequences I've mentioned. These can then be set by users in their prompt or wherever they wish and that should solve this issue for most people.

I don't think many applications actively use this, so I don't see any requirements to implement escape sequence configuration for this.

**Comment by nixpulvis** [comment]
@chrisduerr this is why I mentioned two separate PRs. Since I agree just two escape sequences are most likely to solve most peoples use cases.

However, a solution for the issue of toggling or configuring escape sequences (is there an open issue for this, I can't seem to find it) would of course be a nice addition, but much more complex of a feature.

**Comment by qrasmont** [comment]
Ok that certainly clears thing up, thanks everyone! I had already done the work for 1042 on to 1043 🛫

**Comment by semanser** [comment]
Totally a newbie question, but where I can find more info about `DEC 1042` and `DEC 1043`? Is that ASCII escape characters or what? Thanks in advice!

**Comment by kchibisov** [comment]
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_

**Comment by ddnomad** [comment]
Any updates on this one?

Just recently switched to Alacritty on MacOS and when I'm in a nested Tmux session (remote Tmux in a local Tmux) Alacritty icon starts jumping each 2 minutes without seemingly anything happening that can trigger a bell. Really distracting :(

**Comment by ronakg** [comment]
Came here looking for a solution as well. I have long-running processes within tmux and any output in the running process triggers alacritty icon bounce.

**Comment by laktak** [comment]
> Just recently switched to Alacritty on MacOS and when I'm in a nested Tmux session (remote Tmux in a local Tmux) Alacritty icon starts jumping each 2 minutes without seemingly anything happening that can trigger a bell. Really distracting :(

Is there a workaround for this? I tried 

```
tmux set -g bell-action none
tmux set -g visual-bell off
tmux set -g monitor-bell off
```

but Alacritty keeps jumping...

**Comment by ttaylorr** [comment]
I added emulation for xterm's `bellIsUrgent` resource, which allows for toggling whether or not Alacritty bounces its dock icon on macOS when a bell occurs in a terminal that does not have the user's focus. If #4304 is merged, disabling the dock bouncing should be as simple as:

```ShellSession
$ printf "\e[?1042l"
```

(which you could easily stick in your `$HOME/.bash_profile`, or your prompt to disable dock bouncing permanently in all windows).

**Comment by chrisduerr** [comment]
> (which you could easily stick in your $HOME/.bash_profile, or your prompt to disable dock bouncing permanently in all windows).

It should be noted that the profile would be the wrong place, since that should only be executed on login. What you'd want is to emit it in the bashrc/zshrc/whateverrc, since that is executed every time a new terminal is started. Putting it in the prompt shouldn't be necessary, since I'm not aware of any application that changes this behavior.
