### ISSUE TITLE
characters rendering at wrong size?

### ISSUE THREAD

**Issue by matthiaskrgr** [alacritty/alacritty#3030]
Linux 5.3.11-1

x11
alacritty 94068956e6133ff24b1553eacdfa50e31351b8fd

Sometimes when looking at clippy output, I noticed that [ ] characters are not printed in the same size for some reason.

![alacritty](https://user-images.githubusercontent.com/476013/69634027-aed7e000-1051-11ea-8bac-d147c1510c2d.png)
Note that the last `]` seems to be smaller than the first `[`

**Comment by matthiaskrgr** [comment]
[alacritty.yml.txt](https://github.com/jwilm/alacritty/files/3891895/alacritty.yml.txt)

config

**Comment by chrisduerr** [comment]
This seems a bit strange to me, since Alacritty is not actually capable of rendering two instances of an ascii glyph at a different size, since all ascii characters are cached at startup and then rendered from a fixed pixel buffer.

There's two things I'd like to verify though, the first is obviously that these characters indeed have the same character value, I'd be strongly surprised if this wasn't the case, since that would be an extremely odd bug in the Rust compiler, but just copy-pasting it to check that this is indeed the correct ascii character seems like a trivial sanity check.

My other question is about a more realistic possibility, which is (sub)pixel alignment. Depending on how the pixel layout works out, I'd imagine it would be possible to have about a pixel difference of height between glyph depending on alignment. To be noticeable however, this would require the font size to be very small (I'd say 6.5 is!). So could you try increasing the font size (the bigger, the better) and verify if that resolves the issue? If there's any huge size where there are significant differences, that would without a doubt mean this can't be it.

The last thing is simply about the `.5`. Generally this shouldn't really make a difference, but can you repro with `6` and `7`? This should be a good check to make sure our fractional sizes are working correctly (they aren't actually fractional behind the scenes, which would make this odd).

**Comment by kchibisov** [comment]
In addition to @chrisduerr could you try to repro with `glyph_offset.y: 0` instead of `-1`.

**Comment by matthiaskrgr** [comment]
`glyph_offset.y: 0` does not seem to make a difference.
I checked different sizes:

same size of []: 5,6,8, 9
different size of []: 6.5,7

**Comment by chrisduerr** [comment]
Even `9` is still a pretty small font size. Can you get any difference between the glyphs with font sizes 20+?

**Comment by matthiaskrgr** [comment]
I can't seem to spot a difference with 20+
Also 9 seems like a rather normal font size on my system (similar in size to what github uses for example) 
![alacritty2](https://user-images.githubusercontent.com/476013/69650767-629b9880-106f-11ea-9796-07e31e4fe144.png)

**Comment by chrisduerr** [comment]
That sounds like this is a pixel alignment issue indeed, though I'm surprised it is different for the two different glyphs. Looking at it close-up, it's just a single pixel difference, so it might be a scaling issue with the font, or a rounding issue anywhere in the stack really.

I'm not quite sure if there's something we can do about this, or necessarily something wrong with it. Though `Hack` doesn't really seem like a hacked together font that would have problems with things like this.

Have you tried the font in other renderers like Firefox at equally tiny sizes?

**Comment by matthiaskrgr** [comment]
I'm not sure how to change the font on firefox but I tried a libreoffice doc with hack as font now and it looked fine there.

What is strange is that the yellow []s look off but the white ones a little earlier seem to be equal sized. Perhaps it is related to how alacritty renders colored glyphs?

**Comment by chrisduerr** [comment]
> What is strange is that the yellow []s look off but the white ones a little earlier seem to be equal sized. Perhaps it is related to how alacritty renders colored glyphs?

Colored glyphs are not rendered any differently, it's actually just done in the shader and the white glyph is scaled by RGB values. So the bitmap is not only identical, but it's coming from the exact same place.

If you move the window around your monitor, does that change things? I'd assume the difference is location inside of Alacritty. Maybe moving the window does anything, otherwise I'd assume that in one specific line, they will never match, regardless of color. And in non-broken lines, it will always work regardless of color. I would appreciate if you could test this.

**Comment by matthiaskrgr** [comment]
Moving the window around does not change the height of the character, it still looks the same as before.

**Comment by chrisduerr** [comment]
So does it depend on the position within the window, regardless of color?

**Comment by matthiaskrgr** [comment]
` while true; do; printf "\e[93m[]" ; done` looks fine on my machine, mmh.

**Comment by chrisduerr** [comment]
>  while true; do; printf "\e[93m[]" ; done looks fine on my machine, mmh.

I'd be curious if this is only the case because you've done it now with a window that potentially has a different size than a problematic one, or if it's because this generally doesn't show this problem.

So if you can see this problem (for example in cargo's output), then I'd be curious if clearing the screen and running that command again would show the problem.

**Comment by kchibisov** [comment]
It really seems like a hinting bug in Font, since I can repro that with a fractional point sizes with Fira Mono, the thing is that picking fractional font size isn't really possible in mostly all applications I'm aware of.

![picture](https://user-images.githubusercontent.com/27620401/101988444-ad07ab80-3caa-11eb-9a1f-d99f7a4c4420.png)


Since it's coming from the font itself there's nothing we can do about, if you still have a way to repro that try changing font size. And if you don't have enough granularity, try `WINIT_X11_SCALE_FACTOR=1 alacritty`, since DPI scaling could prevent from picking non-fractional font size.

**Comment by kchibisov** [comment]
The reason why 2 brackets are different, is because font styles are different, and hinting could differ from style to style in the same font, thus you have actually 2 different fonts here. And according to your config you've used `Hack` with bold style for warning, and Hack with regular style for normal messages. So it's nothing 'special' here.

**Comment by kchibisov** [comment]
![picture](https://user-images.githubusercontent.com/27620401/101988609-b5141b00-3cab-11eb-926a-fdff2f92ced4.png)
