### ISSUE TITLE
Windows: Refactoring & cleanups

### ISSUE THREAD

**Issue by davidhewitt** [alacritty/alacritty#3085]
I have the impression the windows code needs refactoring and work to bring it to parity with other platforms. Let's use this ticket to collect together what could be done. (I'd then be happy to steadily work through the list we create.)

Please add comments to suggest what needs working and I'll update this list below.

To spec out / create tickets for:
- [ ] Font ligatures (see linux WIP PR #2677)
- [ ] Reduce / remove unsafe code
- [ ] Reduce duplication, add cross-pty API
- [x] ~~Remove Arcs / resize handles because of the pain they cause. Probably needs #3086 to be done first.~~
- [ ] Improve the quality of the error messages (get as much information from the OS as possible)

Ticketed items:
- Emoji support (#3082)
- ~~Conpty by default (#2890)~~

**Comment by chrisduerr** [comment]
I think #3082 is largely unrelated to the main cause of headache which would be the Windows PTY code.

Since #3082 is solely about the directwrite implementation, things are a bit easier. I think this was implemented separately and is relatively small, so I don't feel like there are any issues with that code. Looking at it just to make sure, it seems very nice to me compared to some of the other code.

The ConPTY/WinPTY code is what I'd primarily address. Unfortunately due to issues with Windows there is no way we can just kill off WinPTY yet, but changing to ConPTY by default might be a first step. After that things like error handling, unsafety, duplication and cross-pty API unification are some of the things I'd like to see improve.

**Comment by chrisduerr** [comment]
Also I'd generally be wary of making this into just a 'fix windows' issue. While tracking issues might be nice in some cases, they have the tendency to never ever get closed.

So splitting stuff into issues that can actually get tackled and closed is desirable.

**Comment by davidhewitt** [comment]
> Also I'd generally be wary of making this into just a 'fix windows' issue. While tracking issues might be nice in some cases, they have the tendency to never ever get closed.
>
> So splitting stuff into issues that can actually get tackled and closed is desirable.

👍. What I'd like to do is use this issue to discuss what we don't like about the current situation, and then let's break those notes up into well-defined separate tickets and close this one.

**Comment by davidhewitt** [comment]
> After that things like error handling

Can you elaborate a little more what needs fixing about with the existing error handling? 

The alert box that pops up with a crash explicitly talks about panicking and then prints a debug representation of the error (I think?). This could be made to have friendlier error messages. Maybe there's other things you're thinking too?

**Comment by chrisduerr** [comment]
> Can you elaborate a little more what needs fixing about the existing error handling?

I'm mainly talking about issues like the startup problem you've been working on in https://github.com/jwilm/alacritty/pull/3080.

Since none of the Windows API bothers to provide any decent Rust-like errors, we are stuck with querying the OS about problems and that does not work out in every scenario.

So stuff like an incorrect shell at startup not giving any information about what's actually wrong should be kinda unacceptable.

**Comment by davidhewitt** [comment]
Another thought: `cargo install` on windows doesn't bundle `winpty-agent.exe`. On unix we have support for `cargo deb` - perhaps on windows we could support `cargo wix` ?

I know at the moment we do this in the ci already, so moving support for it into `Cargo.toml` seems reasonable to me.

In the future this might actually be useful for ConPTY too: the folks at [microsoft/terminal](https://github.com/microsoft/terminal) are planning to release ConPTY as a library, so that it can be decoupled from the Windows 10 OS version. This might be very useful to us, but it'll probably require (at least) packaging their `OpenConsole.exe` alongside Alacritty.

**Comment by chrisduerr** [comment]
> Another thought: cargo install on Windows doesn't bundle winpty-agent.exe. On unix we have support for cargo deb - perhaps on Windows we could support cargo wix ?

We have cargo deb to generate the .deb for distribution and the wix install does the same for us without having to put it in the Cargo.toml. I don't see why people would want to compile an installer on their machine, instead of just using the installer we provide?

> In the future this might actually be useful for ConPTY too: the folks at microsoft/terminal are planning to release ConPTY as a library, so that it can be decoupled from the Windows 10 OS version. This might be very useful to us, but it'll probably require (at least) packaging their OpenConsole.exe alongside Alacritty.

That's very unfortunate, but that's Windows for you I guess...

**Comment by davidhewitt** [comment]
> I don't see why people would want to compile an installer on their machine, instead of just using the installer we provide?

For people using releases, the provider installer is definitely the best option. For me building from source, I needed to copy winpty-agent.exe by hand because `cargo install` can't do that.

The Ubuntu / Debian manual builds suggest using `cargo deb --install -p alacritty` which will copy all the resource files. Using `cargo wix` to generate an installer would be the equivalent for windows users building from source.

> That's very unfortunate, but that's Windows for you I guess...

😄

**Comment by chrisduerr** [comment]
> smile . It does slightly complicate things. It also means that we can control the packaged ConPTY version rather than asking users to update their Windows 10 version to get upstream fixes!

We don't develop ConPTY though! That's a shared library! It's absolutely crazy that we would ship that. It's flatpak/snap all over again, what a mess.

> The Ubuntu / Debian manual builds suggest using cargo deb --install -p alacritty which will copy all the resource files. Using cargo wix to generate an installer would be the equivalent for windows users building from source.

The difference is that we get this for free though. While using wix would require a depedency on the cargo-wix depedency (which I have a lot less faith in than the official wix tools).

Generally my goal has been for a long time to get rid of everything but the source tarball. I don't think it does us much benefit at all to ship releases and generally that's something that should be done by distributions. Of course macOS and Windows suck here, so there's no way around that, but long-term I see the goal to get rid of `cargo-deb` too.

**Comment by davidhewitt** [comment]
With my new PR #3805, I thought I would take a moment to read through the list of remaining items here. The ConPTY code seems to be mostly as good as it can get with regards to error handling and usage of `unsafe`. Emoji support and ligatures are sitting in their own tickets.

So I'm not sure there's much more to offer here. I'm going to close out this ticket.
