### ISSUE TITLE
Mirror escape terminator for legacy support

### ISSUE THREAD

**Issue by AmaiKinono** [alacritty/alacritty#3091]
Use `$ emacs -nw -Q` to startup emacs in terminal.

In alacritty 0.3.3:

![3 3](https://user-images.githubusercontent.com/28714352/70713269-9558b880-1d20-11ea-84d1-360deadb9d07.gif)

In alacritty 0.4.0:

![4 0](https://user-images.githubusercontent.com/28714352/70713284-9c7fc680-1d20-11ea-9fb8-9711dbccc1c0.gif)

There's an obvious lag.

OS: Manjaro Linux 18.1.4 with kernel 4.19.88
Version: alacritty 0.4.0
Desktop: X11, i3wm, compton-tryone

**Comment by chrisduerr** [comment]
Can you confirm that after downgrading to 0.3.3, the startup is fixed again? Or is it possible that this was due to a separate change in your system?

**Comment by AmaiKinono** [comment]
I did exactly what you asked. I found Emacs startup slows down after a system upgrade, so I tried downgrading alacritty to 0.3.3 and it is fast again.

**Comment by chrisduerr** [comment]
If you start a selection while waiting for it to finish loading, does that cause Emacs to load immediately? If there's just an issue with Alacritty not redrawing, forcing a redraw like this might help.

**Comment by AmaiKinono** [comment]
Ah, I think that's exactly what happened. I can start typing or do any other thing immediately, and the content will show up.

**Comment by chrisduerr** [comment]
And `alacritty --version` confirms that you are on at least 0.4.0?

**Comment by AmaiKinono** [comment]
Yes. I'm at 0.4.0.

**Comment by chrisduerr** [comment]
Hm, that's unusual. Do you have a Rust toolchain installed? If so I think it would be worthwhile to test the latest master.

**Comment by AmaiKinono** [comment]
I just built alacritty manually (at commit e99057b), the problem is the same. I thought maybe the old `alacritty.yml` from 0.3.3 causes the problem, so I removed it, and Emacs starts up fast both in alacritty provided by my OS and built by myself. I'll look into it to find what's the reason.

**Comment by AmaiKinono** [comment]
It's caused by these 2 lines:

```
env:
  TERM: xterm-24bit
```

I can't think exactly why I did this, but it's for true color in terminal Emacs. If I comment out these lines, there will be only 8 colors. Btw, `xterm-256color` also causes the lag.

**Comment by chrisduerr** [comment]
Have you tried the `alacritty` terminfo?

**Comment by AmaiKinono** [comment]
Yes. `alacritty-terminfo` is installed, and if I don't set `TERM` in `alacritty.yml`, `$ echo $TERM` shows `alacritty`. Emacs can only use 8 colors in this case.

**Comment by chrisduerr** [comment]
The `alacritty` terminfo is 256color, the other supported terminfo is `alacritty-direct`. If Alacritty is having issues with any other terminfo, there is no support for that. We can only support the terminfos we control, so it's impossible to guarantee compatibility with anything else.

Having only 8 colors with the `alacritty` and `xterm-256color` terminfo sounds like your emacs might be messed up though. It has been a while since I've tried running emacs, but I don't think that was any problem for me.

**Comment by AmaiKinono** [comment]
> the other supported terminfo is `alacritty-direct`.

If I use `alacritty-direct`, Emacs says this when startup:

```
emacs: Terminal type "alacritty-direct" is not powerful enough to run Emacs.
It lacks the ability to position the cursor.
```

> Having only 8 colors with the `alacritty` and `xterm-256color` terminfo...

Maybe I'm not clear on that, but I can have 256 colors with `xterm-256color`, and true color with `xterm-24bit`. Only `alacritty` has the problem.

> It has been a while since I've tried running emacs, but I don't think that was any problem for me.

I've been using alacritty for several months, and I always remember that `alacritty` terminfo gives me 8 colors in Emacs, and I have to change the `TERM` to `xterm-24bit` or `xterm-256color` to have more colors. Could you test it again?

> The alacritty terminfo is 256color

 So, is Emacs supposed to have 256 colors if I use `alacritty` terminfo?

**Comment by chrisduerr** [comment]
> So, is Emacs supposed to have 256 colors if I use alacritty terminfo?

Yes. The `alacritty` terminfo is a fork of `xterm-256color`.

**Comment by chrisduerr** [comment]
Okay, I've tested it again by copying `xterm-256color` to the name `alacritty-256color` and started emacs using a 1:1 identical file, just under a different name.

Turns out that Emacs seems to depend on the name of the terminfo file, rather than the content of the file itself, which means this is an emacs problem. If emacs fixes that mess, everything will work properly just the way it works with xterm-256color.

**Comment by dnkl** [comment]
For 24-bit color, `TERM=alacritty-direct` is what should be used.

However, you need to convince Emacs to treat alacritty as an xterm clone, by doing `(add-to-list 'term-file-aliases '("alacritty" . "xterm"))` (having `alacritty` is enough and will cover both `TERM=alacritty` and `TERM=alacritty-direct`).

That said, you might still experience a delay. There are a couple of sequences where Alacritty's responses doesn't match what Emacs expects:

* `\e[>0c` - Emacs expects `\e[>N1;N2;N3c`, where N1 represents the terminal type (xterm responds with 41 - vt420), N2 is the xterm version (e.g. 347), and N3 is 0. Emacs' regex requires N3==0, but the other could be more or less anything, though is does use N2 to determine which features it should enable. It also special cases responses from e.g. Gnome Terminal and screen, but otherwise expects an "xterm-like" response.

* `\e]11;?\e\\` (report background color). Emacs expects an ST terminator in the response (`\e\\`), while Alacritty terminates with BEL (btw, xterm parrots the queries terminator in its responses). This _might_ be what causes the temporary hang; Emacs is waiting for an ST terminator that never comes, but thankfully times out after a while.

Note: using BEL as response terminator will **not** work with Emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36879#11

**Comment by dnkl** [comment]
> Note: using BEL as response terminator will not work with Emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36879#11

Specifically:

> Emacs uses BEL (C-g) as INTR char, which means that not
> only is special effort required to avoid having it quit the current
> elisp code -- this could have been done using inhibit-quit -- but when
> the pty receives the BEL from XTerm, it immediately discards unread
> characters and raises SIGINT.

**Comment by chrisduerr** [comment]
It might be worthwhile to mirror the terminator of the original request sequence, though as far as I know that would only be a pleasantry, since both should be properly understood by the application.

It seems that Emacs is doing its best not to play nicely with non-xterm terminfos, so I'm not sure if there's any point in bothering to play nice with it.

I don't think I've seen other applications complaining about this, so it would likely only slightly improve the situation with applications that already do not try to play nice.

**Comment by dnkl** [comment]
> It seems that Emacs is doing its best not to play nicely with non-xterm terminfos, so I'm not sure if there's any point in bothering to play nice with it.

It doesn't actually use the terminfo - it only uses the name to determine which lisp extension code to load to further query the terminal.

But yes, the querying code does make certain assumptions. However, in most cases, it wont matter that you reply with something it doesn't understand because the feature it is probing for is xterm specific.

> I don't think I've seen other applications complaining about this, so it would likely only slightly improve the situation with applications that already do not try to play nice.

Emacs is unusual, I think, in that it uses BEL (`C-g`) as INTR. The default is of course `C-c`.

I do believe that the only "required" change is to mirror the terminator. The rest can be configured in Emacs.

On a side note: even though you should recognize both BEL and ST, xterm calls BEL legacy and mirrors it simply to please "old" applications (or something to that effect - there's a comment about it in the xterm sources).

**Comment by chrisduerr** [comment]
> On a side note: even though you should recognize both BEL and ST, xterm calls BEL legacy and mirrors it simply to please "old" applications (or something to that effect - there's a comment about it in the xterm sources).

Yeah, fair enough. I guess support for super, super ancient applications that do not get any patches anymore might make this a relevant change. It's crazy that Emacs is one of those, but I guess that's just how it goes sometimes.

**Comment by dnkl** [comment]
> It's crazy that Emacs is one of those

Depends on how you look at it. It uses ST itself, and wants ST in the response, not BEL. so in that sense it is modern.

As to why it configures BEL to be the INTR character, _that_ is likely for super super ancient reasons ;)

**Comment by AmaiKinono** [comment]
@dnkl Thanks! But your solution:

``` emacs-lisp
(add-to-list 'term-file-aliases '("alacritty" . "xterm"))
```

doesn't work for me. I tried to put it at the beginning of `init.el`, or in `before-init-hook` (should be the earliest hook in the startup process), but `TERM=alacritty` still gives me 8 colors, and `TERM=alacritty-direct` give me that `not powerful enough to run Emacs` error.

**Comment by dnkl** [comment]
I'm on:
```sh
% emacs --version
GNU Emacs 26.3
```

**Comment by AmaiKinono** [comment]
> Have you verified those terminfo definitions have been installed?

Yes:

``` console
$ pacman -Qs alacritty-terminfo
local/alacritty-terminfo 0.4.0-1
    Terminfo files for the alacritty terminal emulator
$ ls /usr/share/terminfo/a | grep alacritty
alacritty
alacritty-direct
```

> Emacs version? Regular emacs?

``` console
$ emacs --version
GNU Emacs 26.3
```

It's installed from manjaro's official repo.

**Comment by AmaiKinono** [comment]
> can you post the output of `infocmp`?

Ah, this shows the reason. It is reconstructed from `~/.terminfo` directory. I think I customized the terminfo for true color in Emacs, but I forgot it was there. I removed it and things work now.  Sorry for being stupid.

Now the behavior is:

- without setting `term-file-aliases`: `TERM=alacritty` or `TERM=alacritty-direct` both give me 8 colors, but they look different.
- with setting `term-file-aliases`: `TERM=alacritty` gives me 256 colors, and `TERM=alacritty-direct` gives me true color.

**Comment by dnkl** [comment]
> It is reconstructed from ~/.terminfo directory.

I figured it was something like that :)

> In both cases there's the lag on startup.

Is it still true that you can "bypass" the delay/lag by starting typing or selecting something with the mouse?

If so, it sounds like it's related to the wm/compositor, rather than alacritty itself. What happens if you disable compton?

**Comment by dnkl** [comment]
>  In both cases there's the lag on startup.

Did you mean both when and when not setting `term-file-aliases`? Or **only** when setting `term-file-aliases`, but with **both** `TERM=alacritty` and `TERM=alacritty-direct`?

**Comment by dnkl** [comment]
It should be noted that **with** `term-file-aliases` set, you will hit the ST vs. BEL terminator issue. You can do
```lisp
(setq xterm-extra-capabilities nil)
```
where you set `term-file-aliases, to stop Emacs from probing Alacritty.

You can also explicitly set `xterm-extra-capabilities` to a list of features you want enabled. Not sure which of those that can be enabled and/or will work with Alacritty.

**Comment by dnkl** [comment]
@chrisduerr I was trying to see exactly what kind of response Alacritty was sending to `\e[>0c`. And as it turns out, it doesn't send **any at all**.

This is the `CSI > Ps c` sequence (_Send Device Attributes (Secondary DA)_). It's very similar to `CSI Ps c` (_Send Device Attributes (Primary DA)_), which you **do** respond to: https://github.com/jwilm/alacritty/blob/cb99fd4e4c16e8fe5c36e8be6062658842794ac3/alacritty_terminal/src/ansi.rs#L947

This is the reason Emacs hangs for a while when you set `term-file-aliases` - before querying for specific features, it sends this escape to try to figure out which terminal emulator it is running under.

Now, if you implement this, _then_ you'll hit the ST/BEL terminator issue...

(There's also `CSI = Ps c`, _Send Device Attributes (Tertiary DA)_ which also is unimplemented in Alacritty).

**Comment by dnkl** [comment]
(This will have worked in 0.3.x where you didn't enforce intermediates)

**Comment by AmaiKinono** [comment]
I mean only when setting `term-file-aliases` but with both `TERM=alacritty` and `TERM=alacritty-direct`.

I just found that `emacs -nw -Q` doesn't give me the lag, so that must be a problem of my own configuration, and that turns out to be the line setting `term-file-aliases`. If remove it, Emacs starts up fast, but then I have only 8 colors.

> `(setq xterm-extra-capabilities nil)`

I did this and the lag is gone, and I still have true colors!

> It should be noted that with `term-file-aliases` set, you will hit the ST vs. BEL terminator issue.

I don't know terminal emulator much so I don't know what's that issue. I'm assuming it's related to `C-c` and `C-g`. Both work well with or without `(setq xterm-extra-capabilities nil)`.

> You can also explicitly set `xterm-extra-capabilities` to a list of features you want enabled.

According to the docstring the value in this list can be:

- modifyOtherKeys  -- if supported, more key bindings work (e.g., "\C-,")
- reportBackground -- if supported, Xterm reports its background color
- getSelection     -- if supported, Xterm yanks text from the X selection
- setSelection     -- if supported, Xterm saves killed text to the X selection

The original value is `'check`, which means trying to check for extra capabilities. I found as long as I set it manually, the lag is gone. But if using `reportBackground`, Emacs rings a bell at startup, and show a `Qui` in `*messages*` buffer (Should be `Quit`?), and I can't use `emacs -nw filename` to open a file. So as you said, reporting background doesn't work well with Emacs.

**Comment by kchibisov** [comment]
>This is the CSI > Ps c sequence (Send Device Attributes (Secondary DA)). It's very similar to CSI Ps c (Send Device Attributes (Primary DA)), which you do respond to: 

@dnkl Oh, that make sense now. I guess we should add both of them.

**Comment by dnkl** [comment]
>> (setq xterm-extra-capabilities nil)

> I did this and the lag is gone, and I still have true colors!

Yay!

See post above. The real reason it lags unless you do this is because Emacs sends an escape sequence that Alacritty doesn't implement So emacs is waiting for a response that never comes.

**Comment by dnkl** [comment]
@AmaiKinono 

> But if using reportBackground, Emacs rings a bell at startup, and show a Quit in *messages* buffer, and I can't use emacs -nw filename to open a file

_This_ is the ST/BEL issue :)

**Comment by dnkl** [comment]
> getSelection -- if supported, Xterm yanks text from the X selection
> setSelection -- if supported, Xterm saves killed text to the X selection

These are buggy in the current Emacs release. They should be fixed in the next major release. See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36879

They require the terminal to support 'OSC 52', which I believe Alacritty does (but needs to be ST terminated... ;) ).

**Comment by AmaiKinono** [comment]
@dnkl I see. Thanks man, you are amazing!

**Comment by egmontkob** [comment]
> [dnkl] On a side note: even though you should recognize both BEL and ST, xterm calls BEL legacy and mirrors it simply to please "old" applications (or something to that effect - there's a comment about it in the xterm sources).

Indeed, the comment in xterm/misc.c is:

>     * Lines should be of the form <OSC> number ; string <ST>, however
>     * older xterms can accept <BEL> as a final character.  We will respond
>     * with the same final character as the application sends to make this
>     * work better with shell scripts, which may have trouble reading an
>     * <ESC><backslash>, which is the 7-bit equivalent to <ST>.

There's also a corresponding changelog entry from xterm patch 94 (year 1999):

> minor tweak to OSC responses, to use BEL if the application used that to end the request, rather than ST. This works better with shell scripts, which may not handle an `<ESC>backslash` very well.

Meanwhile ECMA-48 defines ST as the only terminator for an OSC, it doesn't mention BEL at all for this purpose. See its §8.3.89 (OSC), §8.3.143 (ST) and §8.3.3 (BEL).

So clearly ST is the "correct" terminator. While it's probably debatable how to respond if the query ends in a BEL, I think it's pretty clear that if the query ends in ST then so should the response.

**Comment by dnkl** [comment]
@AmaiKinono 
> modifyOtherKeys: `C-,`, `C-.` and `C-'` work like `,`, `.` and `'`.

Emacs tries to programatically enable an XTerm extension that enables special sequences to be sent when the user presses e.g `C-.`.  Alacritty doesn't support this, and thus you don't "see" control being pressed, just a regular `.`.

@chrisduerr @kchibisov the enabling sequence is `\e[>4;1m`. We briefly touched upon this here: https://github.com/jwilm/alacritty/issues/2688#issuecomment-516987534
