### ISSUE TITLE
Implement "modifyOtherKeys"

### ISSUE THREAD

**Issue by dnkl** [alacritty/alacritty#3101]
In short, enabling _modifyOtherKeys_ lets the client recognize e.g. `Ctrl-.`; i.e. to see modifiers for keys where modifiers are normally ignored.

Note that in XTerm, the user can also enable this by default via XResources.

The enabling/disabling sequence is:
> ```
> CSI > Pp m
>           Set/reset key modifier options, xterm.  Set or reset resource-
>           values used by xterm to decide whether to construct escape
>           sequences holding information about the modifiers pressed with
>           a given key.
> 
>           The first parameter Pp identifies the resource to set/reset.
>           The second parameter Pv is the value to assign to the
>           resource.
> 
>           If the second parameter is omitted, the resource is reset to
>           its initial value.  Values 3  and 5  are reserved for keypad-
>           keys and string-keys.
> 
>             Pp = 0  ⇒  modifyKeyboard.
>             Pp = 1  ⇒  modifyCursorKeys.
>             Pp = 2  ⇒  modifyFunctionKeys.
>             Pp = 4  ⇒  modifyOtherKeys.
> 
>           If no parameters are given, all resources are reset to their
>           initial values.
> ```

The values that can be "assigned" for _modiyOtherKeys_ are:

> ```
> modifyOtherKeys (class ModifyOtherKeys)
>                Like modifyCursorKeys, tells xterm to construct an escape
>                sequence for ordinary (i.e., "other") keys (such as "2") when
>                modified by Shift-, Control-, Alt- or Meta-modifiers.  This
>                feature does not apply to special keys, i.e., cursor-, keypad-,
>                function- or control-keys which are labeled on your keyboard.
>                Those have key symbols which XKB identifies uniquely.
>
>                For example, this feature does not apply to special control-
>                keys (e.g., Escape, Tab, Enter, Backspace) Other control keys
>                (e.g., Control-I, Control-M, Control-H) may send escape
>                sequences when this feature is enabled.
> 
>                The default is "0":
> 
>                0    disables this feature.
> 
>                1    enables this feature for keys except for those with well-
>                     known behavior, e.g., Tab, Backarrow and some special
>                     control character cases which are built into the X11
>                     library, e.g., Control-Space to make a NUL, or Control-3
>                     to make an Escape character.
> 
>                     Except for those special cases built into the X11 library,
>                     the Shift- and Control- modifiers are treated normally.
>                     The Alt- and Meta- modifiers do not cause xterm to send
>                     escape sequences.  Those modifier keys are interpreted
>                     according to other resources, e.g., the metaSendsEscape
>                     resource.
> 
>                2    enables this feature for keys including the exceptions
>                     listed.  Xterm ignores the special cases built into the
>                     X11 library.  Any shifted (modified) ordinary key sends an
>                     escape sequence.  The Alt- and Meta- modifiers cause xterm
>                     to send escape sequences.
> 
>                The Xterm FAQ has an extended discussion of this feature, with
>                examples:
>                https://invisible-island.net/xterm/modified-keys.html
> ```

Broken out from https://github.com/jwilm/alacritty/issues/3091#issuecomment-565715265, and https://github.com/jwilm/alacritty/issues/2688#issuecomment-516987534
@AmaiKinono

**Comment by chrisduerr** [comment]
Thanks for creating a separate issue for easier tracking.

> Note that in XTerm, the user can also enable this by default via XResources.

I think we should be good with skipping this. If there's an escape to set/unset it, I feel like we should be good without a dedicated config option.

**Comment by lonelykid** [comment]
Without this feature, Vim is taking longer to escape to Normal mode(1000ms by default!) because it does not whether it's a separate key or an escape sequence. And it leads to strange behavior when you want to manually map Meta key on Mac. I failed to find a way to make Vim working correctly in alacritty while it works just fine in iTerm2. Yes, nvim works better. But not everyone is switching to Nvim. I hope this FR would be reconsidered.

**Comment by Patryk27** [comment]
fyi, I'm starting to implement this feature 🙂

**Comment by kchibisov** [comment]
Given that kitty's protocol is quite common these days I don't think that  adding `modifyOtherKeys` will provide a value other than maintainance burden.

Is this xterm poorly documented option is really required if alacritty will have full kitty protocol support?

**Comment by pataquets** [comment]
Issue gardening:
#7125 has been merged, which I guess makes this issue obsolete.
/cc @dnkl

**Comment by linguisticmind** [comment]
I'm having problems using extended keys in Alacritty with tmux. I opened a [discussion](https://github.com/orgs/tmux/discussions/5555) on tmux page regarding this issue.

It seems that due to different views on which protocols are worth supporting and maintaining, problems like this arise.

I've been using Alacritty for years now, and the experience has been good, but I personally can't imagine using it without a multiplexer, so I've been using it with tmux. But as I have recently found out, tmux only supports XTerm's modifyOtherKeys protocol, not Kitty (at least yet). So now that I'm trying to use extended keys, I'm having problems.

Since Alacritty doesn't do any session management of its own, have it be able to interface well with tmux seems desirable, and perhaps a good reason to have support for XTerm's modifyOtherKeys protocol.

**Comment by linguisticmind** [comment]
@kchibisov I'm having problems using extended keys in Alacritty with tmux. I opened a [discussion](https://github.com/orgs/tmux/discussions/5555) on the tmux page regarding this issue.

I've been using Alacritty for years now, and the experience has been good, but I personally can't imagine using it without a multiplexer, so I've been using it with tmux. But as I have recently found out, tmux only supports XTerm's modifyOtherKeys protocol, not Kitty (at least yet). So now that I'm trying to use extended keys, I'm having problems.

Since Alacritty doesn't do any session management of its own, have it be able to interface well with tmux seems desirable, and perhaps a good reason to have support for XTerm's modifyOtherKeys protocol.
