### ISSUE TITLE
Don't Accept Empty URL

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#3168]
In `alacritty 0.4.1-rc1 (9970643)` we currently parse and highlight `https://` as a valid URL.

Despite the fact that it may actually be valid in some circumstances, we shouldn't parse this, since clicking on this kind of URL will not lead to a destination successfully.

**Comment by chrisduerr** [comment]
I've discussed this a bit with @kchibisov on IRC and there are a few intricacies to this problem.

Fundamentally, the problem is that we do not only have `https:` as URL scheme, but another valid scheme is `file:`. While `file://` is not a valid scheme, `file:/` and `file:///` are.

Since we want to be generic about schemes, instead of having different logic for each one, this makes things a bit complicated. We wouldn't want `file:/` to be a URL, then `file://` to not be a URL anymore and suddenly `file:///` to be a URL. If we didn't want `https://` as a URL, we likely also wouldn't want `https:/` or `https:///`.

So there are three solutions to this problem. One of them is to change our approach to parsing and treat different schemes differently. I think that introduces too much complexity and isn't worth the trouble.

Another solution would be to just block `file:/`, `file://` and `file:///` and treat them as invalid URLs. Or at least `file:/` and `file://`. This would mean that `https:/` and `https://` also wouldn't be URLs anymore and thus resolve this issue. The problem with that is, that we then do not highlight the valid `file:/` URL anymore, which raises the question if it's not worth it to highlight the invalid `file://`, `https://` just to make sure all valid URLs (`file:/`) are always highlighted. After all users can easily not-click on highlighted things, but if it's highlighted, that means there's no way to work around it.

The last solution would be to just keep things the way they are. This would entail highlighting all of `file:/`, `file://`, `file://` and their `https:` counterparts.

@kchibisov was in favor of just keeping things the way they are right now, which makes sense. So I'm curious how you feel about this @nixpulvis.

**Comment by kchibisov** [comment]
>@kchibisov was in favor of just keeping things the way they are right now, which makes sense.

The thing is, that our URL locator isn't a real world URL parser anyway, since it trying to work around corner cases where your URL is surrounded by chars, which could be part of URL in general, but it's the way to go for terminal emulators etc. So for such thing over detecting in edge cases is better than less detecting and also you should know that most URLs are valid, since intention is to send a valid thing, so file:/ is a valid URL and you'll likely face it more often then `https:/` or `https://`. So avoiding file:/ in favor of blocking https:/ isn't ideal for me. Adding more complexity to a urlocator isn't an option either, so everything points that we should just live with it.

**Comment by kchibisov** [comment]
ping @nixpulvis

**Comment by nixpulvis** [comment]
My only real pushback is that `https://` by itself is probably going to show up, and when it does it'll present itself as a valid URL, thus teaching users bad information. 

However, exactly how wrong this is, is unclear to me honestly. Rust's [`url`](https://docs.rs/url/2.1.1/url) crate gives an `Err(EmptyHost)`, while Ruby's `URI::regexp` happily accepts it. I've found more parsers accept this string than reject it.

Overall, while I generally like being as correct as possible with respect to standards, in this case I'm tempted to agree with you both.

**Comment by chrisduerr** [comment]
I definitely think that `https://` is incorrect and it would be better in this specific example to not accept it. However I don't think it's worth it considering that it would require a scheme specific parser. So I feel like it is a valid bug, just not one worth fixing because it causes more troubles than it helps in practice.
