### ISSUE TITLE
Unable to Install on Pop!_os

### ISSUE THREAD

**Issue by theAndrewCline** [alacritty/alacritty#3202]
I am having an issue installing Alacritty on Pop!_os using apt

I actually installed it recently a different computer with the same os. 

I saw #2685 which seems to be the same error but for ubuntu. But it didn't provide a clear way of fixing it.

### System

OS: Pop!_os

### Logs

```dpkg: error processing archive /var/cache/apt/archives/alacritty_0.4.0~1575415744~19.10~44c7c07_amd64.deb (--unpack):
 trying to overwrite '/usr/share/terminfo/a/alacritty', which is also in package ncurses-term 6.1+20190803-1ubuntu1
Errors were encountered while processing:
 /var/cache/apt/archives/alacritty_0.4.0~1575415744~19.10~44c7c07_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by chrisduerr** [comment]
Providing the version of Pop!_OS you're running would probably be helpful.

@mmstick We've recently released 0.4.1, so the PPA needs a bump anyways. Do you think you can look into that while bumping the version? I'm not sure about the different ncurses versions on the different Ubuntu versions, but if ncurses provides the Alacritty terminfo, just removing it from the package should be sufficient to fix it.

The terminfo currently is not completely up to date, but I'm working with ncurses to resolve that.

**Comment by theAndrewCline** [comment]
Oh yes, I'm on 19.10

**Comment by mmstick** [comment]
On 19.10, the package contains:

```
/usr/share/terminfo/a/alacritty+common
/usr/share/terminfo/a/alacritty-direct
```

It does not contain `../alacritty`

**Comment by chrisduerr** [comment]
Probably a good idea to make sure the system is up to date and to confirm it's actually running Pop_OS version 19.10.

**Comment by theAndrewCline** [comment]
Gnome settings says I'm on 19.10 and I have kept up with updates for my os. Anything else I should check?

**Comment by mmstick** [comment]
`ncurses-term_6.1+20190803-1ubuntu1` is the current version in 19.10. Unsure on why it would be conflicting with `alacritty_0.4.0~1575415744~19.10~44c7c07`, since many of us are using Alacritty here.

**Comment by chrisduerr** [comment]
@mmstick I'm not sure about Debian packaging, but will [this](https://github.com/pop-os/alacritty/blob/master/debian/rules#L46) line not create a `/usr/share/terminfo/a/alacritty` file?

I've checked the tar of the 19.10 PPA and it contains the same line.

**Comment by mmstick** [comment]
Yes. The file exists in alacritty's debian package, but not ncurses.

**Comment by chrisduerr** [comment]
> Yes. The file exists in alacritty's debian package, but not ncurses.

Assuming the `+20190803` stands for the ncurses version and not when it was updated in Ubuntu, it should though. Alacritty was added in `20181027` and later updated in `20190803`.

**Comment by mmstick** [comment]
If you run `dpkg -L ncurses-term`, it dumps the list of files contained in the package. It has `alacritty+common` and `alacritty-direct`, but not `alacritty`.

**Comment by chrisduerr** [comment]
> If you run dpkg -L ncurses-term, it dumps the list of files contained in the package. It has alacritty+common and alacritty-direct, but not alacritty.

That sounds very interesting and would be very surprising since there's no point in just shipping `alacritty-direct` without `alacritty` itself.

I'm unable to run that command since I do not have any Debian/Ubuntu systems and wasn't able to find the sources for the package easily readable online unfortunately.

What would happen if a package provides Alacritty's terminfo already and then `ncurses` suddenly starts shipping it itself? Would that cause the system update to fail? I'm just trying to make sure that the `ncurses` update didn't try to somehow correct the file conflict by not copying it to your system, keeping Alacritty's terminfo in use.

**Comment by mmstick** [comment]
A conflict would prevent the updated packages from being installed. So unless you're on the focal development branch, or Debian unstable, you won't be receiving rolling release updates to system packages like `ncurses-term`.

**Comment by kchibisov** [comment]
>So unless you're on the focal development branch, or Debian unstable, you won't be receiving rolling release updates to system packages like ncurses-term.

FWIW, on debian testing the output of `dpkg -L ncurses-term | grep -i alacritty` is

```
/usr/share/terminfo/a/alacritty
/usr/share/terminfo/a/alacritty+common
/usr/share/terminfo/a/alacritty-direct
```

not sure about stable though.

**Comment by chrisduerr** [comment]
Found a list with the installed packages of `ncurses-term` for 19.10:
https://packages.ubuntu.com/eoan/all/ncurses-term/filelist

That definitely seems to include just `alacritty` too.

**Comment by theAndrewCline** [comment]
I also have another computer with Pop that is also 19.10. it installed Alacritty just fine. It seems possible that it's localized to that installation. What steps should I take to try and fix it?

**Comment by chrisduerr** [comment]
@theAndrewCline I'd be curious which of these machines is more regularly up to date and at what point you installed Alacritty on the other machine. I feel like this might be a timing thing, since I can't imagine packages would be any different based on the system they're installed on.

As far as I can tell, **every** 19.10 installation with the latest `ncurses-term` should have the `alacritty` terminfo installed.

As mmstick has correctly pointed out though, I don't think packages like `ncurses-term` should be updated between versions. So that would exclude any kind of issue with updating the package itself.

The only thing I could imagine would be faulty packages in the archives, if they're different for each architecture. But based on the ubuntu package list, it seems like the same package is used for each architecture (which is fine for ncurses), so that shouldn't be a problem either.

It'll probably take someone who actually uses Ubuntu (which I do not), to clear this up.

**Comment by mmstick** [comment]
I'm pushing the packages for the new version now, which won't contain this file anymore.

**Comment by chrisduerr** [comment]
Thanks for your work @mmstick, hopefully that resolves the issue on all affected systems.

Though I'd imagine in the worst case that could leave people without `alacritty` terminfo, which seems better than not being able to install it at all though.

Still, this sounds like a very strange issue to me.

**Comment by theAndrewCline** [comment]
I was able to use the pop refresh installer and it resolved the issue for me. No clue if that was the right way to fix it, but it worked. I'll close the issue.

**Comment by chrisduerr** [comment]
It's probably been a coincidence that the pop refresh installer worked for you, since mmstick just published the latest version without the terminfo included. So assuming that your installed version is 0.4.1, it's all thanks to him. :)
