### ISSUE TITLE
Vim copy to system clipboard from alacritty

### ISSUE THREAD

**Issue by IgrauBezRuk** [alacritty/alacritty#3209]
Hey, really can't find answer on my questiion, thats why I ask it here. How can I copy from vim, using WSL with Alacritty to system clipboard? On linux I use "*y buffer to do this. How can I do same on WSL?

![image](https://user-images.githubusercontent.com/5683877/72422533-b4b98a00-3793-11ea-8f6c-2c577efe224a.png)

**Comment by DivineGod** [comment]
This seems like a vim on wsl issue and not an alacritty issue based on some very cursory internet searching

**Comment by chrisduerr** [comment]
There is only one way for Applications to write clipboard data through the terminal interface, which is the `OSC 52` escape. So to exclude potential issues with vim, which is probably not unlikely, could you run the following escape?

```
printf "\e]52;c;$(printf 'test' | base64)\a"
```

If this puts `test` in your clipboard, then Alacritty is doing everything it can.

**Comment by IgrauBezRuk** [comment]
I've run your sequence but unfortunately in the clipboard, I still have the sequence instead of the test string. Also have tested on the Linux, works as expected (obviously :) )

**Comment by chrisduerr** [comment]
@IgrauBezRuk Does normal copy and paste work as expected? If so, our clipboard should work...

It would be interesting to have a reftest recorded, to see exactly which escape sequences are sent to Alacritty. Could you run the following command?

```
alacritty --ref-test -e sh -c "sleep 2; printf \"\e]52;c;$(printf 'test' | base64)\a\"; sleep 2"
```

**Comment by IgrauBezRuk** [comment]
@chrisduerr Yes, normal copy paste works, if I select something with mouse and copy, everything alright.
about --ref-test, called it from git bash shell and received a file. Is it what you required?

[0m[0Ksleep: missing operand[0K[?25l
Try 'sleep --help' for more information.[0K
[0K[?25h

Something weird here :)

**Comment by kchibisov** [comment]
Ehm, I'm not sure about @chrisduerr suggestion, since it's a windows machine. Could you basically launch `alacritty` with `alacritty --ref-test` and then execute the  `printf "\e]52;c;$(printf 'test' | base64)\a"`. After you've done that close it, and post `alacritty.recording`(you can add `txt` extension to it, if github blows up) here? Don't inline its content like you did before, please.

**Comment by IgrauBezRuk** [comment]
[alacritty.recording.txt](https://github.com/alacritty/alacritty/files/4116498/alacritty.recording.txt)

**Comment by chrisduerr** [comment]
@IgrauBezRuk Could you describe what you've been doing in this recording? Based on what I can see, you executed the `printf "\e]52;c;$(printf 'test' | base64)\a` command, is that correct?

If so, the Windows PTY seems to filter that out, since we never actually receive the escape ourselves. Thus it wouldn't be an Alacritty, but a WinPTY/ConPTY issue.

Unfortunately the Windows PTYs are a bit notorious for filtering perfectly valid escapes out.

**Comment by chrisduerr** [comment]
Also, just to make sure, could you confirm you're indeed running `ConPTY` by looking at the `alacritty -v` output?

**Comment by IgrauBezRuk** [comment]
I open cmd.exe, put there `alacritty --ref-test`
After in alacritty I execute `printf "\e]52;c;$(printf 'test' | base64)\a"` and that's all.

**Comment by chrisduerr** [comment]
Sounds like it's a ConPTY issue then, nothing Alacritty can do about it. So you'll have to hope for Microsoft to fix this, sorry.
