### ISSUE TITLE
Process specific key bindings

### ISSUE THREAD

**Issue by n0ibe** [alacritty/alacritty#3228]
OS: macOS
Version: alacritty 0.4.1 (4d9253b)

I have no idea how (and if) this could be implemented, but is it possible to have process specific key-bindings? For example I have `cmd + w` mapped to `ctrl-w`, which in vim closes the current buffer. While this works fine in vim, I lose the ability to close the current windows with `cmd - w`.  A possible solution would be to tell alacritty to map `cmd - w` to `ctrl - w` iff the focused window has an instance of vim running, and if it doesn't it should close the focused window.

This is just an example, I think there are a lot of possible use cases for this.

**Comment by chrisduerr** [comment]
There is no way to do this and I don't think there is any desire to implement it either. This honestly sounds a bit like a problem you're making for yourself, by remapping all these bindings.

Even if you would be able to reach your goal, this would probably create a pretty big mess with keybindings that close either the current buffer or the entire terminal. If muscle memory ever sets in on this, I'd imagine accidentally closing things wouldn't be unlikely.

There is #62, which would allow you to remap all control bindings to command, which might be what you want?

Otherwise, I can just recommend to use the key that is intended to be used, instead of trying to remap all existing control bindings. Because there are a lot of them.
