### ISSUE TITLE
Font slightly too wide

### ISSUE THREAD

**Issue by pinpox** [alacritty/alacritty#3293]
Hello,

I've seen a few issues around here with font-width problems but counldn't find the solution. I just migrated from termite to alacritty, but my font (Roboto Mono) is too wide. I have included two screenshots showing the difference in widht between termite and alacritty. The height of the lines is the same.

Both terminals are using the same font, I have attached both config files for reference aswell.

I also experimented with the `offset` settings, but that doesn't get me the correct width either. I would like the font to be displayed correctly, please tell me if you need more information.

### System

OS: Linux Arch
Version: alacritty 0.4.1
Linux/BSD: X11 with i3-gaps WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 
```
Created log file at "/tmp/Alacritty-4038755.log"
[2020-02-05 12:00] [INFO] Welcome to Alacritty
[2020-02-05 12:00] [INFO] Configuration loaded from "/home/binaryplease/.config/alacritty/alacritty.yml"
[2020-02-05 12:00] [DEBUG] Estimated DPR: 1
[2020-02-05 12:00] [DEBUG] Estimated Cell Size: 9 x 17
[2020-02-05 12:00] [DEBUG] Estimated Dimensions: None
[2020-02-05 12:00] [INFO] Device pixel ratio: 1
[2020-02-05 12:00] [INFO] Initializing glyph cache...
[2020-02-05 12:00] [INFO] ... finished initializing glyph cache in 0.023835256s
[2020-02-05 12:00] [INFO] Cell Size: 9 x 17
[2020-02-05 12:00] [INFO] Padding: 7 x 7
[2020-02-05 12:00] [INFO] Width: 800, Height: 600
[2020-02-05 12:00] [INFO] PTY Dimensions: Line(34) x Column(87)
[2020-02-05 12:00] [INFO] Initialisation complete
[2020-02-05 12:00] [DEBUG] New num_cols is 67 and num_lines is 67
[2020-02-05 12:00] [INFO] Width: 622, Height: 1156
```
### Screenshots
![2020-02-05-120409_1920x1177_scrot](https://user-images.githubusercontent.com/1719781/73836471-a2b98d00-480f-11ea-8e5f-5a70176a310b.png)
![2020-02-05-120347_1919x1175_scrot](https://user-images.githubusercontent.com/1719781/73836475-a3522380-480f-11ea-8878-a9b3b94b39ec.png)

### Configuration files:
Alacritty: https://gist.github.com/binaryplease/d53a63855ac7914303bfc5da6ad8f0d2
Termite: https://gist.github.com/binaryplease/a22af9ca3e37e2e5ebeca30931001777

**Comment by kchibisov** [comment]
try to launch alacritty with `WINIT_HIDPI_FACTOR=1`.

**Comment by binaryplease** [comment]
> However the correct width is subjective.
Well, not really. I have set up that font around my whole system, also I tried it in various terminal emulators. The font looks everything the same, except for alacritty. I would like the font's to look the way they were designed.

**Comment by kchibisov** [comment]
Could you try changing font size in termite and alacritty, I wonder whether you can find a point where they are the same? Maybe there's off by one somewhere on our side or termite(gtk and friends basically) decides to use a bit smaller advance value? We're just using advance value from font we're getting from FreeType.

**Comment by chrisduerr** [comment]
> I also experimented with the offset settings, but that doesn't get me the correct width either. I would like the font to be displayed correctly, please tell me if you need more information.

What do you mean by this? Offsets certainly should have reduced your glyph's widths, right? How was that not working for you?

**Comment by binaryplease** [comment]
> Could you try changing font size in termite and alacritty, I wonder whether you can find a point where they are the same? Maybe there's off by one somewhere on our side or termite(gtk and friends basically) decides to use a bit smaller advance value? We're just using advance value from font we're getting from FreeType.

That's why I included the screenshot with the two terminals besides each other. As you can see the height of the lines is the same. I aligned the 20 line paragraph and both top and bottom line are at the same vertical position. It's a bit hard to describe but it's not really the size, but the ratio between height and width of the glyphs

**Comment by chrisduerr** [comment]
@binaryplease Using the `offset.x` you can change just the width of the glyph. Just set it to `-1` to decrease it by a single pixel and see if that works for you.

**Comment by kchibisov** [comment]
```
offset:
  x: -1
```

**Comment by binaryplease** [comment]
@kchibisov Yes, I tried that, but it messes up the line spacing. While I can get width and height of a paragraph to look the same with those two settings, the fonts don't look correct. I'll try to create a screenshot to show you what I mean

**Comment by kchibisov** [comment]
>That's why I included the screenshot with the two terminals besides each other. As you can see the height of the lines is the same.

You didn't understand me here. I've asked you to try different font sizes and check whether the issue is presented on all of them and not only one you're using. So start with 9 and go up to 20 for e.g.

**Comment by binaryplease** [comment]
Ok, sorry will do. I have noticed a strange behaviour that might be related (not sure): When zooming in (with Ctrl-+) multiple times, some of the "steps" just increase the height of the characters, reducing the line spacing but keeping the total of a paragraph the same height, while others will change the height of the glyphs *and* the spacing. I'll try different font sizes and report back.

**Comment by chrisduerr** [comment]
> @kchibisov Yes, I tried that, but it messes up the line spacing. While I can get width and height of a paragraph to look the same with those two settings, the fonts don't look correct. I'll try to create a screenshot to show you what I mean

Changing the `x` offset, will not affect line spacing. Make sure you do not modify the `y` value please.

**Comment by binaryplease** [comment]
> 7.5 in alacritty and 10
![image](https://user-images.githubusercontent.com/1719781/73894926-3fb30f00-487e-11ea-9298-87155d1a033c.png)
![image](https://user-images.githubusercontent.com/1719781/73894935-45105980-487e-11ea-9d64-af058fab5592.png)



> 21px termite and alacritty at 17.

![image](https://user-images.githubusercontent.com/1719781/73895070-ad5f3b00-487e-11ea-870c-759804f17612.png)

![image](https://user-images.githubusercontent.com/1719781/73895081-b3edb280-487e-11ea-90bc-c63ef88b3414.png)


>If you want to adjust the height, you can do that with the offset.y. Using font size + x/y offeset, you should be able to get whatever you want.

I'll try to experiment with the offset.y a little more. Have not been able to get it to look correct with various combinations.

**Comment by kchibisov** [comment]
Could you try this thing https://github.com/alacritty/alacritty/pull/2948 ?

**Comment by binaryplease** [comment]
![image](https://user-images.githubusercontent.com/1719781/73895777-09c35a00-4881-11ea-9c24-8ee257f4a8ae.png)

**Comment by binaryplease** [comment]
> Could you try this thing #2948 ? with 7.5pt in alacritty and 10px in termite.

Sorry, but I don't know how to do this. I have not programmed any rust. If rounding is an issue, would it help to try out some bitmap font like terminus?  Those are sharp and would not be rounded maybe? Does alacritty support bitmap fonts?

**Comment by kchibisov** [comment]
You can try bitmap font, however termite doesn't support them. Also you should make sure that no scaling is involved in a terminal to which you're comparing. Alacritty don't have scaling for bitmap fonts yet.

**Comment by kchibisov** [comment]
>One from the official Google Roboto Mono sample page and one of alacritty. I have scaled (keeping the ratio) so that the hight is the same. You can see that the width is different

I don't see any different on image, like at all. Could you compare it to termite?

**Comment by binaryplease** [comment]
What comparison do you need exactly? I don't know what else to provide.

**Comment by kchibisov** [comment]
I mean the same transparency trick you did for us [here](https://github.com/alacritty/alacritty/issues/3293#issuecomment-582680612), but with termite + official picture of roboto mono, so if they matches exactly that will tell us that there's a chance of us doing something a bit wrong.

**Comment by binaryplease** [comment]
Sure, here you go:
![image](https://user-images.githubusercontent.com/1719781/73935941-03b19580-48e2-11ea-99e0-5fcead85bff1.png)
- First is both with half transparency over each other
- Second line official Roboto
- Third line screenshot from termite

You can see the match pretty perfectly. In comparison in https://github.com/alacritty/alacritty/issues/3293#issuecomment-582680612 it looks like a shadow in the far right characters because one of them if wider than the other

**Comment by binaryplease** [comment]
Regarding this: https://github.com/alacritty/alacritty/issues/3293#issuecomment-582671429 
Here is a gif showing what I mean, just in case this is related. I'm pressing CTRL-= (zoom in) multiple times. Some steps increase the size of the glyps only, while other steps increase the glyps *and* the space in between the lines.


![zoom](https://user-images.githubusercontent.com/1719781/73936761-ccdc7f00-48e3-11ea-846a-be5d04e805b4.gif)

**Comment by kchibisov** [comment]
>Edit, Addition: Just between the second and third zoom level in that gif: The width/height-ratio of the glyps in the second and third zoom level is different. I guess one of them must be wrong then

This is related to a font-step we're using(0.5). Also every metric is from FreeType and just passed directly to alacritty, we also don't speculate with anything AFAIK. The information about cell width (glyph advance) is also from it. So, if something is wrong here it's likely related to FreeType glyph loading flags or size passed to FreeType.

I'll take a look on what we can do about the original, however I'd be surprised if we have of by one somewhere tbh. But I don't see any difference on picture you've linked. The only thing that could be related is loading options(subpixel AA, etc), since they could affect glyph shape a bit, etc.

**Comment by binaryplease** [comment]
Okay, thanks for looking into it. I just recorded a better example of the zooming, migth as well upload it. You can see the back-and-forth zooming in and out between two zoom levels. The font gets "higher" but not wider
![zoom2](https://user-images.githubusercontent.com/1719781/73937469-635d7000-48e5-11ea-8a64-abf2dacd9bfa.gif)

**Comment by kchibisov** [comment]
I found out that termite supports settings using `pt` and tested it with `9`, so both terminals were using the same value `9` in a config. I've noticed that it was using cell height `16`, however alacritty was using height `15` . The resulted cells were `7x16` in termite and `7x15` in `alacritty`. I've checked out our metrics math and it was correct. I've also tried `kitty` and it was also using `7x15` cells for the same font and size. The "issue" was completely solve by using `font.offset.y: 1` in `alacritty` config though.

The most important note here, is that font bitmaps **are absolutely** the same, the only difference is cell size, which has nothing to do with bitmap size for char in a font, so termite is just using bigger line height for whatever reason, but the same cell width. Also mapping `pt` to `px` isn't that trivial, and I'd recommend to compare `pt` to `pt` in both terminals. However be awere that we're using different rasterizers, so they could affect metrics, but I'm not sure about this one.

Other `freetype` + `fontconfig` terminals are using exactly the same metrics as `alacritty` for the same `pt` size, so there's nothing we can do. This is not even a rounding issue, since divisions were without fraction part for height/width metrics.

Note about `transparency` pictures:

The result depends on rasterizer, for example subpixel AA, AA, hinting could change the way character looks a bit, so comparing like that isn't fair most, since you're comparing rasterizers.

Also, you're likely using GTK apps and comparing to them, so your point is biased torwards GTK apps and cairo + pango rendering.

P.s.
I've noticed that termite doesn't use my system font loading options, so my font looked pretty ugly in it (I feel like I should setup GTK to make use of them??).
