### ISSUE TITLE
hotkey window feature like iTerm 2?

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [alacritty/alacritty#3313]
Hi, please add a hotkey window feature like iterm2
I can't live without iTerm2 hotkey window now, it's very convenient

**Comment by kchibisov** [comment]
We already had some discussion there #862 , so maybe some suggestions from it maybe worth trying. I have no opinion on this topic, since I don't use macOS, but adding global bindings, to potentially interrupt other apps doesn't sound like a good idea. Though as far as I can see on #862, there are special apps do to that.

**Comment by chrisduerr** [comment]
I don't think it's any of Alacritty's business to listen to global keyboard events to hide and unhide itself.

If you want to show windows on keyboard shortcuts, there should be plenty of keyboard shortcut applications available that allow you to control the default macOS window manager.
