### ISSUE TITLE
Support  `.yaml` extension as well as `.yml` for a config

### ISSUE THREAD

**Issue by cup** [alacritty/alacritty#3316]
Currently Alacritty looks for a file like this:

https://github.com/alacritty/alacritty/blob/5cd13f8c474c71a922e5d8f2b78857badf054f6f/alacritty/src/cli.rs#L26-L31

However the official site recommends `.yaml`:

> Is there an official extension for YAML files?
>
> Please use `.yaml` when possible.

https://yaml.org/faq

**Comment by kchibisov** [comment]
We can't change our extension, it's to late. We can start accepting `.yaml` extension over `yml` though, but we can't remove `yml` extension from search, since it'll break a lot of things.

Also I've seen `yml` most often than `yaml` in practice, but it depends, I guess.

**Comment by chrisduerr** [comment]
I don't think it matters much what is 'officially recommended'. As far as I know, `.yml` is the more widespread used extension and there's no benefit to using `.yaml` over `.yml`. So unless there's a good reason to change it, I don't think we should do anything about this at all. It's not like users might assume it's `.yaml` anyways, since to find out all available paths one would have to read our fallback list, which clearly states that we're loading `.yml` files not `.yaml` files.
