### ISSUE TITLE
Links that overflow the line lose their tails on Windows.

### ISSUE THREAD

**Issue by chris-morgan** [alacritty/alacritty#3361]
933b2e25ff4ecca8e3892c73fa36c35a8f0866b2, Windows 10, 64-bit, ConPTY.

Write a link that exceeds the length of a line.

Alacritty will only recognise the part that appears on the first line as part of the link.

This affects things like pushing to code hosting services and getting a URL to open a pull/merge request, especially if it’s on a long host, repository or branch name.

In practice I would think it almost certain that if the first line goes to the last column, then the next line continues the link, so it’s a more useful semantic to presume it to be so.

**Comment by kchibisov** [comment]
The line should be naturally wrapped and not speculated by application to make such thing work and it's already working in alacritty. Artificially trying to match a URL if there's no line wrap(this is internal thing for alacritty) isn't a good idea and could lead to false positives. For example this is a multiline URL in bash prompt, as you can see it works as expected (same should apply to `cat`, `less` and friends.)

Bash doesn't do anything.

![picture](https://user-images.githubusercontent.com/27620401/74894967-6eaea200-53a1-11ea-8e25-b60a99924704.png)

Fish wraps it on its own, so URL is broken.

![picture](https://user-images.githubusercontent.com/27620401/74895053-b6cdc480-53a1-11ea-860f-5de32d83ddcc.png)

>In practice I would think it almost certain that if the first line goes to the last column, then the next line continues the link, so it’s a more useful semantic to presume it to be so.

This is not true for example it will break my mail client(`mutt`), since your URL could be to the end, and then you have content on side bar, so you'll match content. The only reliable way is that your terminal naturally wrapped line, so you know that this is a whole line.

**Comment by chris-morgan** [comment]
This is not the case for me on Windows. When in zsh I type `echo http://example.com/[lots of data]`, only the first line of the prompt gets linkified, and when I execute it, in the output only the first line of the output gets linkified.

I then wondered whether this was Windows-specific due to ConPTY resolving the wrapping itself and inserting something or other, but the link point adjusts as I resize the window and thereby adjust the wrapping point.

So maybe it’s Windows-specific, but with the issue inside Alacritty specifically?

**Comment by kchibisov** [comment]
zsh also wraps lines by itself sometimes. if you try `cat`  and make a wrapped URL does it work? If `cat` doesn't work then it's ConPty thing, which is wrapping lines by itself.

**Comment by chris-morgan** [comment]
Please reread what I said. Normal command executions (`echo`) aren’t linkifying more than the first line, which absolves zsh, and the text is rewrapping freely on resizing the window, which absolves ConPTY. I see no other candidate for the fault but Alacritty.

**Comment by kchibisov** [comment]
Oh, sorry, ConPty is doing reflow by itself IIRC, we **don't** have special code for Windows to do that at all. The only code we have for Windows is to **pipe** conpty properly, other than that nothing. If normal command aren't linkifying more than the first line it's a Windows bug, because they try to manage as much as they can in their **pipes**, so again, nothing we can do about it. You're free to test our reflowing logic in `fn input` in terminal, but you'll likely see that Windows is splitting lines by itself. There's no way it can work on Linux/macOS, but not on Windows, since our logic is entirely the same for everything, except the **pipes** setup.

**Comment by chris-morgan** [comment]
Ah, I had been presuming that reflow was purely an Alacritty concern.

Could this be reopened as a Windows-specific thing? The next step is probably confirming that ConPTY is at fault, and then opening an issue with Microsoft about that. Then if they say it will never be resolved there, see if a workaround can reasonably be instated here.

**Comment by kchibisov** [comment]
>The next step is probably confirming that ConPTY is at fault, and then opening an issue with Microsoft about that.

They will likely won't do anything, since it's not a bug, it's a "feature" of ConPty. Like all the other things they do

>see if a workaround can reasonably be instated here.

Workaround that could work is match through `\n` and `\r`, which isn't an option at all.

However you can try to contact them and at least ask for an option to disable reflow completely for a client when we setup ConPty interface.

**Comment by kchibisov** [comment]
It seems like ConPty add https://github.com/microsoft/terminal/pull/4415 , I'm not sure that it was released yet, but we'll see if our logic starts working after some period of time.

**Comment by chrisduerr** [comment]
> The next step is probably confirming that ConPTY is at fault

This has already been confirmed.

There is nothing Alacritty can do about this and we shouldn't track issues that are unrelated to Alacritty. There is no change related to this that will ever land in Alacritty. This is purely a Microsoft issue.
