### ISSUE TITLE
Powershell starts in System32 instead of the user directory

### ISSUE THREAD

**Issue by raphtlw** [alacritty/alacritty#3407]
The terminal starts in System32 instead of `%USERPROFILE%`.

### System

OS: Linux/BSD/macOS/Windows
Version: alacritty 0.4.1 (4d9253b)
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: ConPTY

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: Width: 1122, Height: 642
Keyboard and bindings:

**Comment by cfiet** [comment]
Hi @raphtlw 

1. Are you starting Alacritty from Start Menu when this occurs?
2. Does it start in the correct directory when run from `Win + r` prompt?
3. Does it start in the correct directory when you run it from `cmd.exe` from your `%USERPROFILE%`?

**Comment by raphtlw** [comment]
Thanks for replying @cfiet 
1. It occurs anywhere except for when I start it with "open alacritty here"
2. Nope
3. Yes, CMD starts in the correct directory

**Comment by sterlingjensen** [comment]
I've reproduced the behavior.
This is not a bug, inheriting the current directory of the parent process in absence of explicit instruction to do otherwise is the correct behavior. The parent process, `explorer.exe`, has a working directory of `System32`, which `alacritty.exe` inherits before spawning `powershell.exe` - and the pattern repeats. You've got several points at which you can modify this behavior:
* Modify the Alacrity shortcut to use a different "Start in" directory, which `explorer.exe` passes to `alacritty.exe` when spawning the new process.
* Modify your `alacritty.yml` config to explicitly override the current directory passed by the parent process:
https://github.com/alacritty/alacritty/blob/bb0a214a157adc81d1e598602bba7739ecec8672/alacritty.yml#L322-L326

**Comment by raphtlw** [comment]
@sterlingjensen Thanks for the help but after telling alacritty to start in the user directory by specifying it in `alacritty.yml`, it starts up with a strange looking prompt where most of my commands fail to execute due to an error.

```powershell
Microsoft.PowerShell.Core\FileSystem::\\?\C:\Users\raphp
▶
```

**Comment by chrisduerr** [comment]
> Thanks for the help but after telling alacritty to start in the user directory by specifying it in alacritty.yml, it starts up with a strange looking prompt where most of my commands fail to execute due to an error.

That's fixed in the latest master. Should be all good then?

**Comment by sterlingjensen** [comment]
Paths, full and relative, work when set at `alacritty.yml` in the current master. Variables don't get expanded in the config, but that isn't new (I assumed they did, but after looking into the cost of implementation - I'm glad I was wrong).  I tested both master and 4d9253b, and migrating to master solved the UNC problem for both the config file and the `--working-directory` switch.

@raphtlw If you don't want to compile master, the shortcut method I mentioned early still works for both environment variables and full paths.

**Comment by raphtlw** [comment]
Thanks :) This is my favourite terminal emulator 🥇

**Comment by imfulee** [comment]
Hi, my question on this is if there is a way to change the start menu behavior because I have changed the `%APPDATA%\alacritty\alacritty.yml` to 

```yml
working_directory: C:\Users\
```

but when I open it with the taskbar icon or from the start menu, it still uses `C:\Windows\System32` as the working directory. Though with `Win + R` and executing `alacritty.exe` it does seem to have change the behavior, but I'm not sure if that's because I also already changed the default powershell directory to `C:\Users\`.

**Comment by oxmj** [comment]
i edited `Start in:` field to `%USERPROFILE%` in alacritty shortcut located at `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Alacritty`  and it then starts in users home, which seems like sane default for most people, better then `C:\Windows\system32`...
