### ISSUE TITLE
Request: `alacritty -- <command>...` to replace `--command`

### ISSUE THREAD

**Issue by KSXGitHub** [alacritty/alacritty#3414]
I think `--command`/`-e` is unusual when compared to the other flags as it must be the last. This unusual-ness is also inconsistent amongst different terminals.

GNOME Terminal also uses `--` and deprecates `-e` flag.

**Comment by chrisduerr** [comment]
> I think --command/-e is unusual when compared to the other flags as it must be the last.

It doesn't need to be last, it's just easier to say it always must be last. `alacritty --command=true -vvv` will work just fine.

Is there any actual advantage to this suggestion or is this just a change for the sake of changing stuff, because someone else is doing it? As far as I can tell, there's no advantage to this, it would only remove the ability to move this wherever the user wants it.

**Comment by nixpulvis** [comment]
I see absolutely no reason to deprecate the `-e`/`--command` flag, since they are somewhat standard, and useful. However I could see some value in having `--` mark the end of flags/options (as is a standard meaning of `--`), and then accept the positional arguments as commands. Some programs like `xargs` may play nicely with this addition.

That said, I rarely find myself looking for this kind of thing, so I'm not overly motivated to add this flag. @KSXGitHub can you help motivate this feature a bit more?

**Comment by xPMo** [comment]
GNOME Terminal deprecated `-e` because its implementation of `-e` relied on the entire command being in a a single argument to be split, such as `gnome-terminal -e 'tmux attach' --quiet`. Alacritty and other terminals don't have this problem with `-e`.

`xargs` isn't a problem, you can call `xargs alacritty -e` just as easily as `xargs alacritty --` or `xargs alacritty`.

All that said, I like the idea because

1. it would probably simplify option parsing: `--`, `-e`, and `--command` are just end-of-options flags; then collect all args as the command to be run. 

2. Some users are used to gnome-terminal or kitty and may expect this to work. I think it is reasonable to expect `alacritty htop` to run htop in an alacritty window. Currently, any argument produces an error.

**Comment by chrisduerr** [comment]
> it would probably simplify option parsing: --, -e, and --command are just end-of-options flags; then collect all args as the command to be run.

It would actually make it more complicated.

> Some users are used to gnome-terminal or kitty and may expect this to work.

Same goes for `-e`, I'd say that's probably still more common.

> I think it is reasonable to expect alacritty htop to run htop in an alacritty window.

I **really** don't. I'd expect `alacritty htop` to run the htop subcommand of Alacritty, because that's usually how CLIs work.

**Comment by chrisduerr** [comment]
I'm in favor of closing this issue, curious what you think @nixpulvis since you've given @xPMo's comment a thumbs up which I take as a sign of agreement?

**Comment by nixpulvis** [comment]
@chrisduerr we could close this issue if you want. I gave a thumbs up for a thoughtful response to my comment, and a few good points. Though I'm not a fan of everything mentioned (sorry if that was confusing). Specifically, I find other terminal's argument parsing to be a poor guide here, unfortunately.

I stand by my position that the only action we could take here, is to **add** a new `--` flag which marks the end of flags and options, and interpret everything afterwards as a command. If we want to change the title and scope of this issue to track that then so be it, otherwise I don't have a problem wrapping my commands in strings. This issue is one of ergonomics, which I **do** think would be improved by this feature, however is a low priority.

**Comment by xPMo** [comment]
> It would actually make it more complicated.

Oh, right; `clap`. I write too much by-hand.

> Same goes for -e, I'd say that's probably still more common.

It is probably the *most* common.  Both `-e` and `--command` should stay, no question.

> I really don't. I'd expect alacritty htop to run the htop subcommand of Alacritty, because that's usually how CLIs work.

Alacritty has no subcommand (although you could consider which program to execute as a subcommand, which is my logic), and it would seem to be out-of-scope for the project. I'll concede this though; scope can change. For starters, `help` would make sense as a subcommand.

> ergonomics

The ergonomics benefit is marginal, it just takes `alias alacritty='alacritty -e'` to alleviate it.

---

If subcommands are a possibility for the future, then I'll give a hard no to `--`. Maybe, if *anything*, add `-x` as an alternative if users migrate from xfce4-terminal or mate-terminal. (fwiw, `-x` is also supported by gnome-terminal).
