### ISSUE TITLE
Split renderer into seprate crate

### ISSUE THREAD

**Issue by RedHatter** [alacritty/alacritty#3419]
I have been experimenting with alacritty_terminal (just building a gtk frontend for now) and have successfully gotten much of it working. I would like to use the same code as alacritty to render to a gl surface. I see the renderer was originally a part of alacritty_terminal but was moved back to the alacritty crate. If I remember correctly there was discussion of a third crate (alacritty_ui I think?) for the opengl stuff without any dependency on glutin. Is that still the plan?

I'm not too familiar with the internals yet but am willing to give the refactor a shot if it's not too complex.

**Comment by kchibisov** [comment]
> If I remember correctly there was discussion of a third crate (alacritty_ui I think?) for the opengl stuff without any dependency on glutin. Is that still the plan?

There wasn't such a decision and it doesn't make any sense to split `GL` into a separate crate. You can't define a stable interface for `GL` and it won't work well for some cases. Also it was refactored away from `alacritty_terminal` not `moved back` . If your app is just a clone of alacritty, but on GTK then just reuse the entire code right away, but there's no guarantee that we won't break it, since it's end user rendering of alacritty and for alacritty without intention to be reused by others. `alacritty_terminal` on the other hand could be much more stable and used for tmux like applications, since it won't depend on gui libs (libfontconfig, etc, libxcb) soon.

>I'm not too familiar with the internals yet but am willing to give the refactor a shot if it's not too complex.

I would be strongly against such refactor, since it doesn't make any sense to me. Alacritty is a gui app, moving OpenGL rendering out of it doesn't make much sense and could help only "direct clones", but with toolkit `X`(glfw, gtk, qt) to handle window events. If you're just a clone, copy the thing right away, but our GL code could be working bad for you in some cases. Like your font rendering could be different and done with `pango` for example, or you'll use DirectX instead of OpenGL on Windows. Also you could do software rendering instead of GPU one.

I'll wait for @chrisduerr reply here though.

**Comment by RedHatter** [comment]
For reference I found the discussion I remembered [link](https://github.com/alacritty/alacritty/pull/2312#discussion_r275138265). It definitely wasn't as final as I remembered. Sorry for the misunderstanding.

For now I'm simply planning a clone but that's really just for extermination and getting a handle on the library. The app I'm planning will be a terminal emulator but you're probably right, I'll probably need to edit the rendering code at some point.

**Comment by kchibisov** [comment]
>For reference I found the discussion I remembered link. It definitely wasn't as final as I remembered. Sorry for the misunderstanding.

Things changed a lot since then tbh. We have a terminal and gui app around it, which makes much more sense, than having 3 crates for no reason. In theory we can have a crate to create a PTY, but it's also questionable.

**Comment by chrisduerr** [comment]
The goal of the separation was always to make it possible to use the alacritty terminal with a different frontend. Using both Alacritty's renderer and its terminal doesn't make much sense, since you haven't really gained anything at that point.

If you want to write a GTK frontend to the Alacritty terminal backend, you should focus on rewriting everything in the `alacritty` crate. There's still some refactoring going on (see #3417), however that is the best approach to take.

Splitting the PTY into a separate crate in case someone else is interested in using it for their own purposes would make sense, however not for anyone interested in using the `alacritty_terminal` emulation backend.
