### ISSUE TITLE
Alacritty sessions aren't registered as TTYS on OSX Catalina

### ISSUE THREAD

**Issue by HendrikPetertje** [alacritty/alacritty#3420]
When executing the `who` command I normally see the console session (osx debug) and all iterm/terminal sessions on my Macbook. This is however not the case with Alacritty, none of my alacritty sessions (nor tmux sessions that I create within an Alacritty session) are shown in `who`. Is there a reason for alacritty somehow flying under the system's radar?

Who command executed in iterm 
![Screenshot 2020-03-04 at 10 14 43](https://user-images.githubusercontent.com/3583395/75863667-2495d980-5e01-11ea-8c04-187c73bf357a.png)

Who command in alacritty with Iterm no longer running:
![Screenshot 2020-03-04 at 10 16 32](https://user-images.githubusercontent.com/3583395/75863799-57d86880-5e01-11ea-9f1d-142d3db45cc1.png)

### System

OS: macOS
Version: alacritty 0.4.1 (4d9253b)

### Logs

Font/Terminal size:

```
[2020-03-04 10:22] [INFO] Welcome to Alacritty
[2020-03-04 10:22] [INFO] Configuration loaded from "/Users/peter/.config/alacritty/alacritty.yml"
[2020-03-04 10:22] [DEBUG] Estimated DPR: 1
[2020-03-04 10:22] [DEBUG] Estimated Cell Size: 6 x 15
[2020-03-04 10:22] [DEBUG] Estimated Dimensions: Some((1804.0, 1204.0))
[2020-03-04 10:22] [INFO] Device pixel ratio: 1
[2020-03-04 10:22] [INFO] Initializing glyph cache...
[2020-03-04 10:22] [INFO] ... finished initializing glyph cache in 0.030991822s
[2020-03-04 10:22] [INFO] Estimated DPR correctly, skipping resize
[2020-03-04 10:22] [INFO] Cell Size: 6 x 15
[2020-03-04 10:22] [INFO] Padding: 2 x 2
[2020-03-04 10:22] [INFO] Width: 1804, Height: 1204
[2020-03-04 10:22] [INFO] PTY Dimensions: Line(80) x Column(300)

```
Keyboard and bindings: unrelated

**Comment by kchibisov** [comment]
>This is however not the case with Alacritty, none of my alacritty sessions (nor tmux sessions that I create within an Alacritty session) are shown in who. Is there a reason for alacritty somehow flying under the system's radar?

if you read what `who` does with `man who`. it's showing information about users logged in. Logging in multiple times doesn't sound right to me. The thing you see in alacritty is true for most linux terminal btw and for tmux.

**Comment by nixpulvis** [comment]
FWIW, I tried this on El Capitan, and both Terminal.app and Alacritty show both console and tty lines. I'm not sure what changed with Catalina.

**Comment by HendrikPetertje** [comment]
@krlvi, each terminal session would potentially be it's own TTY session (more info here: http://www.linusakesson.net/programming/tty/).

It could be that I've just done something locally that messes this up. I'll try running alacritty on a colleague's computer tomorrow!

**Comment by kchibisov** [comment]
you can type `tty` to get corresponding session, but there's nothing to do with login.

**Comment by chrisduerr** [comment]
Usually we should spawn a login shell, that's certainly not wrong.

If you change your shell to `login -fp $USER` for example, I think that should resolve this issue.

However there's a big problem with the `login` command, it doesn't allow changing the working directory:

https://github.com/gnachman/iTerm2/blob/f6b54d66b5e371b9e69a0881e9608e13e710fda1/sources/shell_launcher.c#L1-L5

There are several hacks to work around this and it seems like Alacritty just picks one which doesn't do everything you want.

**Comment by chrisduerr** [comment]
More info can be found in the old login shell issue: https://github.com/alacritty/alacritty/issues/1071

**Comment by nixpulvis** [comment]
@HendrikPetertje do you have a custom shell entry in your config, or are you just using the default? If my understanding of this issue is correct, our default should work as expected for you.

Perhaps we have an issue with custom shells on macOS?

**Comment by chrisduerr** [comment]
> If my understanding of this issue is correct, our default should work as expected for you.

It shouldn't.

**Comment by nixpulvis** [comment]
@chrisduerr care to elaborate?

The linked issue (and PR) changed the default shell to a bash wrapper that launches a login shell, which is what I understand to be the solution to this issue.

Frankly, replying with just "it shouldn't" is a bit insulting to me.

**Comment by nixpulvis** [comment]
I've tested `Shell::new_with_args("/usr/bin/login", vec!["-fp".into(), "<username>".into()])` and it seemed to fix this issue. Maybe the original hack needs some work? Sorry if I'm missing something, I don't recall the original hacks context.

**Comment by chrisduerr** [comment]
Yes, the thing is that we cannot use the `login` shell since it doesn't allow setting the working directory.

That's why I've mentioned previously that you can just set `login -fp $USER` as your shell in the configuration file if you don't care about that and it'll work just fine.

The linked iTerm code does things slightly differently, but in an even more hacky way than Alacritty. One would have to test iTerm first to see if we could adapt that to work in Alacritty though. But even then, the Rust STD API does not allow for this hackery since it's in no way how things are intended to work, so one would likely have to rely on some lower level unsafe platform APIs and the output of `who` just doesn't matter enough to me to look into that.

If anyone is interested in trying to fix this, a PR would obviously be very welcome and the original PR should basically tell you everything you need to know. But I don't see myself fixing this anytime soon.

**Comment by HendrikPetertje** [comment]
Thanks for all thereplies everyone, I just logged in after my long weekend and noticed all the comments here. 

I’m totally fine with Alacritty not showing up as a TTY if that is expected behavior. if you want to change that as per discussed, then that’s fine by me, but not a life-threatening thing in any way ofc.

To answer the question of start command, yes I have set zsh on mine, so that might have affected things too.

Feel free to close this issue if you want. If others want to continue the discussion, that’s fine too

**Comment by deekue** [comment]
I found this issue while troubleshooting something related.  It seems on Catalina you need to start a shell with `login` or something that already has (eg. Terminal.app).

Not using `login` breaks anything that uses `logname` to detect the current user. 

with no Alacritty config file, starting Alacritty from Spotlight
```
$ who
deekue console  Jun 16 07:49
$ logname
root
$ tty
/dev/ttys003
```
with no Alacritty config file, starting from Terminal.app
```
$ who
deekue console  Jun 16 07:49
deekue ttys004  Jun 18 21:12
$ tty
/dev/ttys004
$ logname
deekue
```

I get different results if I start alacritty from `login` (with no config file)
`login -pf $USER /usr/local/bin/alacritty --config-file /dev/null`
```
$ tty
/dev/ttys004
$ who
deekue console  Jun 16 07:49
deekue ttys003    Jun 18 21:13
$ logname
deekue
```
versus specifying `login` as the shell in the alacritty config,
`alacritty --config-file <(echo "shell: {program: '/usr/bin/login', args: [ '-pf', 'deekue']}"`
```
$ logname
deekue
$ who
deekue console  Jun 16 07:49
deekue ttys004  Jun 18 21:13
$ tty
/dev/ttys004
```

This seems to be affecting other apps/terminals too
- https://github.com/laravel/valet/issues/904
- https://github.com/microsoft/vscode/issues/96463
- https://github.com/vercel/hyper/issues/3762

though not iTerm2 since it [appears to use login](https://github.com/gnachman/iTerm2/blob/3624330bb2ae1a6aa41842b9b4e71ffb4f59945a/sources/shell_launcher.c)

**Comment by chrisnc** [comment]
There's a fix for this in review now for Alacritty's sessions. I had a question about the original issue comment though:

> none of my alacritty sessions (nor tmux sessions that I create within an Alacritty session) are shown in who

Do you see `tmux` sessions show up in `who` when launched from other terminals? I tested this with Terminal.app and iTerm2.app, and I don't see them, so I think `tmux` itself may be affected by the same issue as Alacritty, and would need to use `login` in order for its sessions to be registered in this way. Maybe something has changed since this issue was created though, and `tmux`'s sessions used to show up even when Alacritty's didn't.
