### ISSUE TITLE
macOS GateKeeper

### ISSUE THREAD

**Issue by zllovesuki** [alacritty/alacritty#3448]
It doesn't seem like the precompiled binary is signed with Apple. Is there a plan to have it added to your build process?

For context, this was all it took to have it signed and notarized:
```
make app
cd target/release/osx
codesign --options=runtime --force --verify --verbose --sign "[Use an Developer ID identity]" Alacritty.app
ditto -c -k --keepParent Alacritty.app Alacritty.app.zip
xcrun altool --notarize-app --primary-bundle-id "Alacritty.app.zip" --password "@keychain:[item stored in Keychain with your app-specific password]" --username "[typically your Apple ID]" --file Alacritty.app.zip
# wait about 5 minutes
xcrun stapler staple "Alacritty.app"
```

Reference: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by kchibisov** [comment]
if this thing requires paying apple for developer ID then no.

**Comment by zllovesuki** [comment]
@kchibisov It will require enrollment in the Apple Developer Program (read: $99).

**Comment by kchibisov** [comment]
>it will require enrollment in the Apple Developer Program (read: $99).

yeah, paying apple is not an option for us, sorry.

**Comment by nixpulvis** [comment]
Just to write this down since I tried looking into this just for the hell of it.

1. Even though I have an Apple Developer Account (unpaid for at this point), doesn't mean I have signing certificates. Making `codesign` impossible.
2. Even if I could sign it: step 8 of https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution states that you must "Choose Upload to send your archive to the Apple notary service." which is something I'd **really** like to avoid for any platform.

If this issue is causing you serious problems using software, I recommend you switch operating systems.
