### ISSUE TITLE
Shell Config issue with CMD.exe

### ISSUE THREAD

**Issue by Jangmingjin** [alacritty/alacritty#3485]
I am working on Windows 10 and I need to set default shell as CMD because all git commands are working on CMD
My Config:
```
shell: 
  program: cmd.exe
  args:
    - /s /k pushd %V
```
Result:
```
'\\?\D:\2019_01_01\Dev\DevTools\Alacritty\0.4.2\Alacritty-v0.4.2-rc2-windows-portable'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
The system cannot find the path specified.
```

I am using 0.4.1 (I think this is the latest stable version)

**Comment by chrisduerr** [comment]
I'm pretty sure this has been fixed in the latest version. Would you mind trying the 0.4.2-rc? There should be a portable executable in our releases.

**Comment by Jangmingjin** [comment]
Yeah but when excute .42-rc, it stuck on loading.
I can't run the portable version in windows

**Comment by nixpulvis** [comment]
I'm testing on `Microsoft Windows [Version 10.0.18362.720]` and I can open the latest Alacritty 0.4.2 RC3 without an issue. Also I tried your config, and indeed it doesn't work, because we don't expand `%V` (much like we don't expand other `ENV` variables). This config works as expected for example:

```yaml
shell:
  program: cmd.exe
  args:
    - /s /k pushd C:\
```
