### ISSUE TITLE
Question: Launching application in new alacritty window

### ISSUE THREAD

**Issue by victortrac** [alacritty/alacritty#3529]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux
Version: alacritty 0.4.1
Linux/BSD: i3wm

I just switched from kitty to alacritty and am having an issue reproducing my old vim alias that worked fine in kitty.  

```bash
## That launched a new kitty window with nvim in it, while detaching the process in the invoking shell.
# ~/.bashrc
alias vim='kitty --detach nvim
```

I tried doing this with alacritty, but it doesn't work.

```bash
# This leaves the invoking shell waiting for neovim to exit
alias vim='alacritty --command nvim'

# This tries to run the file passed to neovim as an executable:
alias vim='alacritty --command nvim &'
```

I'd like the shell to just return while spawning a neovim process in a new alacritty window.  How would someone do this in alacritty?

**Comment by cole-h** [comment]
This is because of the `&` -- if you try running `echo hi & bye`, you'll notice it tries to run the command `bye`. Using that alias, `vim asdf ghjk` will open nvim, and then try to run `asdf ghjk` in the current shell.

The way I would do it is to make this a function. I use `fish`, so this will most certainly look different for your shell, but something along these lines:

```fish
function vim
  alacritty --command nvim $argv &
end
```

**Comment by chrisduerr** [comment]
This seems mostly unrelated to Alacritty, since this is just about creating a shell alias that works completely unrelated to terminal at all.

You probably want to completely disconnect the child process, using either nohup or disown.

Then you'll obviously want to pass the parameters of the alias to `nvim`, instead of adding them at the end. If you've got a `&` at the end, that obviously won't work. Probably easiest to make that a function not an alias.

**Comment by victortrac** [comment]
Thanks @cole-h @chrisduerr. Got this to work in bash:
```bash
function vim {
  nohup alacritty --command nvim $@ >/dev/null 2>&1 &
}
```
It outputs this in the invoking shell once nvim exits, which is slightly annoying but I can live with it:
```bash
$
[1]+  Done                    nohup alacritty --command nvim $@ > /dev/null 2>&1
```

**Comment by cole-h** [comment]
You should be able to silence that by wrapping the `nohup` with parens to make it spawn in a subshell, like so:

```bash
function vim {
  (nohup alacritty --command nvim $@ >/dev/null 2>&1 &)
}
```

(At least, that worked on my system.)
