### ISSUE TITLE
tabspaces ignored in config

### ISSUE THREAD

**Issue by Natherul** [alacritty/alacritty#3548]
I know its not technically a bug but a feature request but here I go anyway

### System

OS: Arch Linux
Version: 0.4.2
Linux/BSD: X11

### Logs
[2020-04-02 15:22:33.317304662] [WARN] Config tabspaces has been removed and is now always 8, it can be safely removed from the config

Why was this removed from conf? Removing said option does make it very annoying imho

**Comment by kchibisov** [comment]
>Why was this removed from conf? Removing said option does make it very annoying imho

If you really know what this option does and you're using self compiled custom terminfo file, I feel like you can modify sources, since no other terminal emulator allow that, and no terminfo has it this value to set to a setting other than `8`. This want changed, since users don't understand what this option does to them.
