### ISSUE TITLE
Ignoring the entire RPM distro based Linux community 

### ISSUE THREAD

**Issue by em-winterschon** [alacritty/alacritty#3550]
You're posting windows installers, osx, and ubuntu... but seem to have forgotten that a huge side of the Linux community uses RPM based distros. Building from source or creating an RPM is fine on my own but you're sending a poor message by ignoring a significant amount of potential users this way.

**Comment by kchibisov** [comment]
>You're posting windows installers, osx, and ubuntu... but seem to have forgotten that a huge side of the Linux community uses RPM based distros. Building from source or creating an RPM is fine on my own but you're sending a poor message by ignoring a significant amount of potential users this way.

We have specs and copr files in our repo, we're building Ubuntu on CI only historically IIRC, I'm in favor of not building any distro on CI at all, and just publish sources. I'd recommend you to use copr or ping your disto folks to ship alacritty, like many other distros are doing.

**Comment by nixpulvis** [comment]
I would also like to remove all packaging from this repo personally, but it's not really an option atm AFAIK,

**Comment by chrisduerr** [comment]
I agree with that sentiment. Especially the linux builds have become less and less useful.

While the Windows/macOS platforms have ~1500/2500 downloads, Linux has ~400 even though it should be our largest platform (at least bigger than Windows).

Of those 400 I can only assume that a big part of them downloaded the .deb, just to figure out it doesn't actually work on their system and they have to build from source.

Especially since pop is hosting a PPA for us, I don't really see any reason anymore to offer a .deb which will likely just give users the feeling that Alacritty is broken, rather than being beneficial support for running it on Linux without compiling it yourself.
