### ISSUE TITLE
MacOS new terminal doesn't have shell environment

### ISSUE THREAD

**Issue by nwaywood** [alacritty/alacritty#3560]
If I open a new instance with:

`open -na 'Alacritty.app'`

it works as expected. However if I supply an initial command with the `--command` flag:

`open -na 'Alacritty.app' --args --command nnn`

it launches but doesn't have the shell environment loaded. i.e. My `.zshrc` has not been run/loaded.

### Expected behaviour

Just like when launching alacritty with no initial command, I expect alacritty to load the shell environment before executing the `--command`

### System

OS: macOS
Version: 0.4.2

**Comment by chrisduerr** [comment]
> Just like when launching alacritty with no initial command, I expect alacritty to load the shell environment before executing the --command

If you want to execute a command with a shell, start a shell. Alacritty just uses the command supplied as the shell, this is how it's supposed to work.

**Comment by nwaywood** [comment]
@chrisduerr mmm ok any chance you could please provide me with an example?

Because I have tried many different things to try and get this to work, e.g.
- `exec zsh && nnn`
- `/bin/zsh -c nnn`

and many other variations. I have also tried with other commands aside from `nnn` to see it that was the issue but I have the same problem with any command.

**Comment by kchibisov** [comment]
It depends what do you mean by *shell*` env. I'd assume that env you're trying to execute is a login env, so you should use `-l`, since it's macOS. So you should do something like that.

`zsh --login -c nnn`

**Comment by nwaywood** [comment]
@kchibisov Thanks for the reply.

By "shell env", I mean that I need my `~/.zshrc` file sourced so that the new terminal has my environment variables and the rest of my normal terminal environment (e.g. vim config), sorry I'm not sure what the correct term for that is.

I just tried the following line and it still doesn't work:

`open -na 'Alacritty.app' --args --command zsh --login -c nnn`

Also, I read this in the zsh docs

![image](https://user-images.githubusercontent.com/3773641/78517235-d1e47e80-77ff-11ea-9009-f4cd4733fadc.png)

which says that the `~/.zshrc` file is run for all interactive shells (i.e. not only for login shells).

Which further leads me to believe that this may be an alacritty issue?

**Comment by kchibisov** [comment]
We have nothing to do with your shell, we don't even know what you're running tbh, we just run the thing you asked us to run, how are you testing this? Are you comparing the output of `env` etc? Does macOS has an alternative to linux's `strace`, so we can actually see what you're sourcing, instead of guessing? `-l` or `--login` is required for macOS, since it doesn't have a concept of login shell, so everything should be launched with `--login`, since it's macOS, also take a note, that the thing you're sourcing is `.zprofile`, when running with `--login` IIRC, I'm not sure that it even touched normal configs for interactive shells, but I don't use zsh myself.

**Comment by chrisduerr** [comment]
To start a login shell on macOS, you want to run `login` directly. Passing `--login` as parameter does not work.

**Comment by nwaywood** [comment]
@kchibisov 

> how are you testing this?

I am testing this with keybindings:

```
shift + ctrl + alt - space : open -na 'Alacritty.app' --args --command zsh --login -c nnn
shift + ctrl + alt - return : open -na 'Alacritty.app'
```

nnn uses some environment variables that are set in my `~/.zshrc` to run properly, so when nnn launches if it isn't working properly I know that the environment was not loaded.

> We have nothing to do with your shell

Mmm ok, but `open -na 'Alacritty.app` works, so alacritty must run something by default (something that so longer gets run when I specify a command)?

> Does macOS has an alternative to linux's strace

Not that I am aware of, and a brief google search revealed that a tool that used to work doesn't work on new versions of macOS

@chrisduerr 

> To start a login shell on macOS, you want to run login directly.

I just tried this:

`open -na 'Alacritty.app' --args --command login -f nick && nnn`

and that doesn't work either. However, like I mentioned in my previous comment, I don't think this is a login issue since the `~/.zshrc` file should be run in all interactive shells

**Comment by chrisduerr** [comment]
Which environment variables do you want to be set? Running `open -na Alacritty.app --args -e login -fp $USER env` works just fine for me with all necessary environment variables set.

**Comment by nwaywood** [comment]
@chrisduerr thank for you sharing that example.

That works, but only if you run it from a terminal, since the `-p` flag tells `login` to use the previous environment. If you remove the `-p` flag it fails, even when run from a terminal.

Therefore it doesn't work if you need to run the command from outside of a terminal. In my case, I am trying to run the command via a [hotkey daemon](https://github.com/koekeishiya/skhd) so I am unable to rely on a "previous" environment.

Do you know if it's possible without the `-p` flag?

**Comment by chrisduerr** [comment]
> Therefore it doesn't work if you need to run the command from outside of a terminal.

There's an environment even outside of a terminal.

What happens when you run `login -f $USER zsh -c env`?

**Comment by nwaywood** [comment]
@chrisduerr running `login -f $USER zsh -c env` prints out some core system environment variables, but none of the environment variables that are exported in my`~/.zshrc`. 

```
$ login -f nick zsh -c env | wc -l
11

$ printenv | wc -l
73
```

So the zsh env that is created from that command doesn't seem to be the same environment as the one that is created when using the `-p` flag.

**Comment by chrisduerr** [comment]
Oh, that might depend on if your login shell is zsh or not.

**Comment by nwaywood** [comment]
Can you please elaborate on that? I'm not sure what you mean. I don't see any flags in `man login` that let me specify what my login shell is

**Comment by chrisduerr** [comment]
I don't usually use macOS, which makes it a bit difficult to give you an exact working example, but it boils down to `shell -c` not starting an interactive shell by default, since you've told it to just run a command with no interactivity needed. Without an interactive shell the .bashrc is not sourced.

Depending on your shell, there might be different flags to tell it to still spawn an interactive shell, one such way would be to spawn a login shell, however login shells on macOs are a bit complicated since login works differently. On a normal system just using `alacritty -e shell --login -c env` would work.

Another alternative, what I'd probably recommend testing is to just tell it to start in interactive mode. With your specific issue that would probably suffice. With zsh you can try running `alacritty -e zsh -ic env` to do so.

**Comment by nwaywood** [comment]
@chrisduerr omg yes that one works!!! Thank you so much for you help and patience.

For anyone else who comes across this, this is the command I have in my `.skhdrc` file which works:

`shift + ctrl + alt - space : open -na Alacritty.app --args -e zsh -ic nnn`
