### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by casey** [alacritty/alacritty#357]
Things that need to happen before alacritty can be published to crates.io:

- [ ] publish `font` subcrate to crates.io
- [x] publish `copypasta` subcrate to crates.io
- [x] Get back on main glutin tree

**Comment by jwilm** [comment]
I've reserved the name. There's some work to be done before we can actually publish, though.

**Comment by casey** [comment]
Okay, sweet. What work is left to be done? Is there a tracking issue for that?

**Comment by jwilm** [comment]
I think this is the tracking issue for publishing on crates.io. Basically, each subcrate that we depend on needs to be published (copypasta, font, etc), and we need to get back on the main glutin tree.

**Comment by casey** [comment]
I made a cute todo list. I think `copypasta` and `font` are the only subcrates that aren't on crates.io.

What needs to happen before we can get back on the main glutin tree? Are the patches in your branch things that are likely to be accepted upstream?

**Comment by chrisduerr** [comment]
@jwilm We are on a recent non-git version of glutin now. Is there anything blocking this now?

**Comment by jwilm** [comment]
some transitive dependencies are via git. Check out the font crate.

**Comment by chrisduerr** [comment]
Ah fair enough. I've only looked into the glutin deps.

**Comment by jedahan** [comment]
I don't see any git dependencies in the `font` or `copypasta` crates, are they ready to publish?

**Comment by chrisduerr** [comment]
I believe `winpty-sys` is not on crates.io yet. Maybe @zacps can push it?

**Comment by chrisduerr** [comment]
I think it should be possible to easily change the crates.io repository at a later date should we decide to move it. But since there's no official "Alacritty" organization, but you'd have to rely on jwilm forking it, I think it's probably easier to just keep it with you (at least for now).

There are some disadvantages, to that. But in general I'd say that I wouldn't worry too much about it for now.

**Comment by zacps** [comment]
`winpty-sys` is no longer blocking this.

**Comment by legrostdg** [comment]
This would also help Debian packaging!

**Comment by chrisduerr** [comment]
Might be worth checking out if it's possible to push it now, since there are no git dependencies left. Are you aware of any other issues @jwilm?

**Comment by jwilm** [comment]
@chrisduerr I think we need to cut a new release to capture the winpty-on-crates.io change, but after that, I think we should be good!

**Comment by atouchet** [comment]
Is this ready to go now that 0.2.4 is out?

**Comment by herder** [comment]
Ping on this: is it possible to get this published as a crate now? 

Also: huge thank you for creating my absolute favorite terminal emulator <3

**Comment by im-n1** [comment]
Publishing to crates.io could save Debian user as long as alacritty is not in repo.

**Comment by chrisduerr** [comment]
> Publishing to crates.io could save Debian user as long as alacritty is not in repo.

It wouldn't really change anything. Publishing to crates.io isn't much different than just installing from git.

**Comment by GopherJ** [comment]
Hello everyone, any news about this?

**Comment by chrisduerr** [comment]
It's currently not possible to publish Alacritty to crates.io.

**Comment by ThreeFx** [comment]
Are there concrete blockers? I'm willing to set up the Debian packaging side of the equation, but for that alacritty needs to be published to `crates.io`.

**Comment by chrisduerr** [comment]
Currently we use a non-standard patch version for `servo-freetype-sys`, to achieve compatibility between the different fontconfig crates we use (we can only link to it once).

We'd probably require to work around that first, which might involve a lot of vendoring unfortunately.

I haven't gotten around to that yet, since I'm still missing the `utf8parse` permissions on `crates.io`, which I should get as soon as @jwilm has a bit of spare time to invite me, once all other depedencies are pushed, I can take a look at resolving this last hurdle.

**Comment by hyiltiz** [comment]
This sounds ignorant, but still relevant to this issue: why is it required to be published to `creates.io` before it could be packaged for Debian? I see the Debian wish-list ticket for packaging Alacritty [1], but there was no mention for why this issue was blocking. Now that @chrisduerr stated about 2 months ago that it is not possible to publish to crates.io (yet), maybe we can consider this issue closed, and ask if packaging for Debian is still of interest?

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851639

**Comment by kchibisov** [comment]
The comment isn't accurate anymore, we do have all the perms to crates.io. However it'll indeed require some vendoring + pushing our other crates to crates.io.

Anyway, why we should close this issue? We do want to publish alacritty to `crates.io` in a future. If you want alacritty in debian just go and ping them and explain the situation, IDK.

Anyway, building from sources is the way to go usually. You shouldn't be afraid of doing it.

**Comment by aragilar** [comment]
With #3515 seemingly solving the need to patch `servo-freetype-sys`, and @chrisduerr now having upload rights to `utf8parse`, was there anything still blocking this (especially things non-maintainers can do)?

**Comment by kchibisov** [comment]
We need font crate on crates.io which is blocked by #3127  and we also need #3417 + it'll take us some time to release 0.5.0. Both issues are kind of waiting for review, but we won't be on crates.io before v0.5.0 anyway, so there's no rush here.

**Comment by aragilar** [comment]
Cool, I'll look at ensuring that the dependencies are all included and up to date in Debian then, so 0.5.0 can be packaged when it is released.

**Comment by chrisduerr** [comment]
My plan is to publish on crates.io with 0.5.0 regardless of the status of the PRs linked by @kchibisov.

**Comment by elichai** [comment]
Looking forward to this!
I personally prefer to compile the code myself via cargo and update with `cargo-update` that way I can pass my own compilation flags that I like (LTO, -march=native etc.)

**Comment by chrisduerr** [comment]
You can now install from crates.io using `cargo install alacritty`.
