### ISSUE TITLE
CopyPaste Action

### ISSUE THREAD

**Issue by jmarewski** [alacritty/alacritty#3577]
In the recent Terminal Emulator for Windows10 they implemented copy and paste on right click.
To also get that in Alacritty, I would like an "action" which does "Copy" if there is a selection and "Paste" if there is none.
This seems like a pretty simple implementation. If you point me in the right direction I could do the merge request myself.

**Comment by LovecraftianHorror** [comment]
Can't you just copy and paste with Ctrl+Shift+c and Ctrl+Shift+v already, or is there something extra that I'm missing?

**Comment by chrisduerr** [comment]
That sounds like a UX nightmare. Why would you want one key to do two different things depending on whether selection is active or not? "Because Terminal Emulator for Windows 10 does it" isn't really an argument you'll convince anyone with.

As far as I can tell, this would have similar issues to "smart copy" with ctrl+c/v, so I'd really rather not add this unless there's a very good reason.

**Comment by jmarewski** [comment]
Of course "Because Terminal Emulator for Windows 10 does it" is not an argument. However I think its a nice feature, since you can't paste over a selection anyways. Pressing copy while having nothing selected currently simply does nothing. 

If you don't like it can you at least point me to where I have to look in the code so I can edit and compile for myself? Thanks :)

**Comment by chrisduerr** [comment]
> Pressing copy while having nothing selected currently simply does nothing.

Because it shouldn't. But you can paste just fine while a selection is active.

> If you don't like it, can you at least point me to where I have to look in the code so I can edit and compile for myself?

You'd have to add a keybinding in `alacritty/config/bindings.rs` and then map it to do something is `alacritty/input.rs`. There's plenty of keybindings though, just searching for the existing ones should give you plenty of examples.

**Comment by chrisduerr** [comment]
@kchibisov / @nixpulvis any opinion on this? I haven't really heard any convincing arguments yet.

**Comment by kchibisov** [comment]
We're iterating this feature request in different forms like 3-4 time already. This feature request is identical to smart copy imho. I don't see any reason, why you can't just use `save_to_clipboard` and bind `Pate` on the right click.

**Comment by pmop** [comment]
IMO, Ctrl + Ins / Shift + Ins is quite standard on Windows platform and it works just fine on Alacritty. No need for another copy paste action.

**Comment by kchibisov** [comment]
>IMO, Ctrl + Ins / Shift + Ins is quite standard on Windows platform and it works just fine on Alacritty. No need for another copy paste action.

And you can't define your own binding for Copy/Paste, you can bind Paste to right click, that's not a problem.

**Comment by jmarewski** [comment]
> This feature request is identical to smart copy imho.
Im not talking about switching between interrupt and copy.

> I don't see any reason, why you can't just use `save_to_clipboard` and bind `Pate` on the right click.
This is almost what Im talking about except that I don't want to always copy the selection.

> IMO, Ctrl + Ins / Shift + Ins is quite standard on Windows platform and it works just fine on Alacritty. No need for another copy paste action.
I don't care what windows does at all. I just found that its a handy feature.


Well I there is no real need for that. Its just an 'quality of life' improvement. Copy and Paste works fine as is. You can close the issue if you think this is a bad idea.

**Comment by chrisduerr** [comment]
Closing since there has not been a sufficiently strong argument to convince me this is a feature beneficial to Alacritty.

If someone in the future should have a stronger argument than the following, feel free to comment on this.

> I think its a nice feature, since you can't paste over a selection anyways. Pressing copy while having nothing selected currently simply does nothing.

**Comment by jmarewski** [comment]
How about this: 
Add a selection mode so we can switch keybinding depending on whether there is a selection or not? This would also allow switching between interrupt and copy using the same implementation.

**Comment by loligans** [comment]
I can understand this feature by itself not being valuable @chrisduerr 

In an effort to convince you, here is an idea that would allow this feature to exist and potentially many other features.

For lack of a better name pick 1: **Branch**, **Conditional**, or **Tree** bindings.  
It would function something like this: Some trigger would _activate_ the key/mouse binding like we do today, and perform an action based off some _simple precondition_.

Take this feature request for example:  
If there is a selection in the buffer perform some action. If there is no selection in the buffer, perform a different action. The precondition action would take hire priority if evaluated to _true_.

```yaml
mouse_bindings:
  - { mouse: Right, precondition: Selection, action: Copy }
  - { mouse: Right, action: Paste }
```

Some ideas for preconditions could be:
`Selection`
`Title`
`FontSize`
etc...

**Comment by chrisduerr** [comment]
> For lack of a better name pick 1: Branch, Conditional, or Tree bindings.

We already have modes for keybindings.

> If there is a selection in the buffer perform some action. If there is no selection in the buffer, perform a different action. The precondition action would take higher priority over the default action if evaluated to true.

We have no desire to allow different behavior based on selection state.

**Comment by damcaoson** [comment]
Hi!
I know this issue is quite old and was closed due to inactivity, but I just wanted to share that I also find this behavior (right-click to copy/paste) very convenient. Especially when using the mouse heavily. I can configure "copy on select" but I prefer not to enable it all the time, since sometimes I just want to highlight text without copying it.

I'm not requesting that it be reopened. Just adding my thoughts in case others come across this thread or if it's ever revisited in the future.

My use case: I often browse websites, grab some text, copy it, then switch back to the terminal and right-click to paste (which is convenient since I'm already holding the mouse).
When I need to copy text from the terminal, I simply select it and right-click to copy. Again, no need to touch the keyboard.

Thanks for all the great work on Alacritty!
