### ISSUE TITLE
Title is not updated with dynamic_title enabled

### ISSUE THREAD

**Issue by wpaulino** [alacritty/alacritty#3588]
I would expect Alacritty's window title to show the current running process with `dynamic_title: true`, but it's always static with `Alacritty`.

### System

```
OS: macOS 10.15.4
Version: alacritty 0.4.2 (f68de37)
```

### Relevant config settings

```
window:
  # title: Alacritty
dynamic_title: true
```

**Comment by kchibisov** [comment]
How are you testing this? 

Does this change your title?
```
echo -e "\e]2;New Title\007";sleep 100
```

**Comment by wpaulino** [comment]
That works, I see `New Title` propagated.

> How are you testing this?

I just open applications, e.g., vim, which affect the title of other terminal emulators, but not Alacritty's.

Something else I just noticed now is that within a tmux session, running `echo -e "\e]2;New Title\007";sleep` does not change anything. Not sure if that's expected or not.

**Comment by kchibisov** [comment]
If this escape sequence works, then everything works as expected. It's a job of app running to update title. To make title work in vim use `set title`, to make title work in tmux use `set-option -g set-titles on`. How to configure your shell to set title is up to your shell.

**Comment by kchibisov** [comment]
Also, if you run some arbitrary program in your shell, it's a shell's job to set its title. e.g. if you lauch something like `htop`, your shell, e.g. `bash`, should set title, the options I've recommended for `vim` and `tmux` are making those programs to set titles to something more useful and specific, than what shell set for you.

**Comment by araghunde** [comment]
I've come across a behaviour that I think is related to this issue:

When I have an alacritty instance running and I execute a command (e.g. `htop`), the terminal's title changes accordingly (in this case `WM_NAME(STRING) = "htop"`). But if instead of having alacritty running I execute `alacritty -e htop`, then the window title remains unchanged: `WM_NAME(STRING) = "Alacritty"`.

I don't quite understand this behaviour. Shouldn't the window title change in both cases?
Thanks for your time.

**Comment by kchibisov** [comment]
it's because the title is set by shell most of the time to an executable it's launching, and not by application in your case. If the application is capable to set title on their own it'll work even with `-e` option. If you want to set title for `-e` command use `--title`(in case your app can't do that on its own).

**Comment by araghunde** [comment]
I don't know know where the name of the window is actually being set... The thing is with `urxvt -e htop`, `kitty -e htop` or even `st -e htop` all of them set the title to `htop` (while being launched from the same shell - zsh in this case). Just doing the same thing with `alacritty -e htop` will result in the window name being _stuck_ on `Alacritty`.

I just think it's odd, and I don't know if I fully understand the behaviour :sweat_smile:

**Comment by kchibisov** [comment]
When you do `alacritty -e htop` it's being launched without any shell in between. And we don't set title to the name of executable you're running, since you're fine to set it yourself most of the when doing so or the application can update the title.

If you do `alacritty -e zsh -c htop` it should set the title, I guess.

**Comment by araghunde** [comment]
The `alacritty -e zsh -c htop` thing also results on the title being Alacritty. In fact, the other terminal emulators mentioned above seem to be setting the window title to zsh in this case, as it's the program that's being passed to the emulator, I guess.

**Comment by kchibisov** [comment]
yeah, we're not doing so, and I don't see a reason to do so, since you can set a title yourself when you launch something directly.

**Comment by araghunde** [comment]
I agree that there's no _need_ for doing it this way, but I think it'd just be neat to add an option that achieves this behaviour (from the config file). It would be handy for doing a window manager config that is as emulator-agnostic as it can be :wink: 

Thanks again for your time :)

**Comment by ch1co** [comment]
> I agree that there's no _need_ for doing it this way, but I think it'd just be neat to add an option that achieves this behaviour (from the config file). It would be handy for doing a window manager config that is as emulator-agnostic as it can be 
> 
> Thanks again for your time :)

hey i think i got a solution, I've been trying to start htop on a specific workspace and couldn't get the title because it would not change.
just insert after -t the title you want.
exec                    --no-startup-id i3-msg  'exec alacritty -t htop -e htop'
then :
for_window              [class="Alacritty" title="htop"] move to workspace 2

**Comment by adept587** [comment]
add this line to .zshrc
preexec() { print -Pn "\e]0;$1\a" }

it works on macOS Big Sur 11.5.2

**Comment by nima-dvlp** [comment]
> add this line to .zshrc
> 
> preexec() { print -Pn "\e]0;$1\a" } -- show last command name
> 
> OR:
> 
> preexec() { print -Pn "\e]0;$1%~\a" } -- show last command name + working directory
> 
> it works on macOS Big Sur 11.5.2

Also works on Arch Linux(will work on other distros too)

**Comment by mytagssma** [comment]
make a executable script like this with your terminal and maybe add it to PATH:
```
echo "alacritty -T $1 -e $1 &" >> ~/launcher.sh # -T or --title depending on your terminal
chmod +x launcher.sh  #don't forget to make it executable
```
I use in in fuzzel with: terminal=/home/_user-name_/launcher.sh , here it generally need absolute path
