### ISSUE TITLE
[wayland] Clipboard amnesia with alacritty and geany

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#3592]
Fedora 31 AND Void (musl) [different hardware]
0.4.2
wayland gnome and wayland sway

The problem manifests solely with the geany editor for me but perhaps there are other applications.

To reproduce, have an alacritty terminal open, open the geany editor.
Select some text in geany and Copy, verify that Paste in geany works as intended. It should.
Attempt Paste in alacritty terminal. Nothing is produced.
Attempt Paste in any other application. Should work as intended.

Repeat the attempt in firefox (or some other application), Paste works as intended in alacritty.

Now attempt Copy in alacritty after selecting some text. Paste works in alacritty and firefox.
Attempting Paste in geany produces nothing.

geany seems to be using xwayland but the problem is absent for other xwayland applications.

**In Fedora 31, When using gnome-terminal instead of alacritty, the issue is entirely absent.**

**In Void sway, When using sakura instead of alacritty, the issue is entirely absent.**

On Fedora the alacritty config is entirely default.
On void the alacritty config has been taken from someone's dotfiles and is customized.

**Comment by chrisduerr** [comment]
Sounds like you might be mixing Wayland and XWayland applications?

**Comment by LamaRaz** [comment]
> Sounds like you might be mixing Wayland and XWayland applications?

Yes but that is not supposed to be a problem. And it it isn't for all the other xwayland applications I use. The bug seems to be with the combination of geany and alacritty. Perhaps geany uses some deprecated API or something but alacritty should still be compatible.

Sakura and gnome-terminal are wayland terminals just like alacritty.

**Comment by chrisduerr** [comment]
> Yes but that is not supposed to be a problem.

Since when? Afaik it has always been a problem and has nothing to do with Alacritty itself. We just write to the clipboard of the display server we're currently on, everything else is up to the WM/compositor.

> it it isn't for all the other xwayland applications I use

Alacritty is not an XWayland application.

@kchibisov you probably know more about this, but it sounds like there's not much we could/should do here?

**Comment by LamaRaz** [comment]
I don't know since when but I have no problem copying between any xwayland and wayland windows other than geany and alacritty. And I post this here because geany has no problem with other wayland terminals. Therefore alacritty is an fault here by not playing nice in some way.

> Alacritty is not an XWayland application.

Perhaps there is a misunderstanding?

Because gnome-terminal and sakura are not xwayland applications either but unlike alacritty they have no problem here... As was stated in the original post.

**Comment by kchibisov** [comment]
Could you post `WAYLAND_DEBUG=1 alacritty 2> debug.txt` output during you reproducing the issue?

**Comment by LamaRaz** [comment]
Void musl sway:

https://paste.ubuntu.com/p/BqzSg79bBy/

**Comment by kchibisov** [comment]
thx, seems like it is fixable.

**Comment by Ypnose** [comment]
Hey, same issue here on Sway running on Void. Geany uses GTK3, it is also Wayland native (`Using GTK+ v3.24.14 and GLib v2.64.1 runtime libraries`). In the meantime, `GDK_BACKEND=x11 geany` does the trick.

**Comment by Ypnose** [comment]
With `alacritty 0.5.0` on Void Linux and this [alacritty.yml](https://github.com/Ypnose/dotfiles/blob/master/gui/alacritty.yml), I'm still unable to paste text from `alacritty` to `geany` and vice versa.

**Comment by kchibisov** [comment]
Could you show a `WAYLAND_DEBUG=1 alacritty` log?

**Comment by kchibisov** [comment]
well, paste from geany should work(works for me™), however paste to geany from alacritty doesn't, since it actually uses UTF8_STRING even for paste, so I'll reopen issue to track it.

**Comment by Ypnose** [comment]
Thanks for your help. Here the [log](https://gist.github.com/Ypnose/bb919c5de0a9c2aa7a7b17c8923081b5)

**Comment by LamaRaz** [comment]
I can confirm that copying from geany works when pasting to alacritty.
copying from alacritty does not work when pasting to geany.

**Comment by kchibisov** [comment]
Could someone retest it with master version, I guess it was fixed some time ago.

**Comment by kchibisov** [comment]
I've checked geany one more time and can say the following:

`Ctrl + C/V` always work.
Middle mouse works fine until you select something in geany, and after that geany prevents any interaction with system middle mouse clipboard and starts using its own clipboard, since it doesn't ever call `receive` on primary clipboard, thus geany intended behavior or a bug, nothing alacritty can do about, since geany doesn't even ask for a primary clipboard content in a first place (you can clearly see it with `WAYLAND_DEBUG=1 geany 2>&1 grep -i receive`).
