### ISSUE TITLE
BUILD-ERROR

### ISSUE THREAD

**Issue by DONofDESTROY** [alacritty/alacritty#3617]
hi everyone I have been building alacritty form the github master branch while compiling at this stage

   Compiling alacritty v0.5.0-dev (/home/donofdestroy/Downloads/alacritty-master/alacritty)
warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:85:21
   |
85 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:85:21
   |
85 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

I got this error

what os am i using:
linux(Arch)

**Comment by enizor** [comment]
That's a warning, not an error. Alacritty still builds fine.

`ONCE_INIT` is deprecated since rustc 1.38 but there is no plan to remove it yet so it's "fine".

Its usage come from the `clap` dependency, which [decided](https://github.com/clap-rs/clap/pull/1521) to fix it only on their v3 development branch. We'll have to wait for them to [release](https://github.com/clap-rs/clap/issues/1037) it or for them to [create](https://github.com/clap-rs/clap/issues/1552) a new v2.x version with the fix.
