### ISSUE TITLE
Shift+Insert not working when copying from neovim

### ISSUE THREAD

**Issue by davidmogar** [alacritty/alacritty#3619]
I'm using alacritty 0.4.2-1 on Arch (X11) with mostly the default configuration. The same applies to neovim, in which I'm setting only `clipboard+=unnamedplus`.

My problem here is copying from neovim to alacritty. If I paste to, for example, qutebrowser with `Shift+Insert`, the text from neovim is pasted. When I do the same in an alacritty terminal, nothing is pasted. This is unless I have text copied from qutebrowser. In this case, that text is pasted.

Now, if I use `Ctrl+Shift+V`, the text from neovim gets successfully pasted.

How can I make `Shift+Insert` to behave? That's the shortcut I usually use.

**Comment by chrisduerr** [comment]
[As you can see in our default config](https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L612), <kbd>Shift</kbd>+<kbd>Insert</kbd> is bound to `PasteSelection`. I'd assume that you're probably just copying to the clipboard, not to the primary selection clipboard.

So you've got two options, either you copy to the correct clipboard buffer, or you change the binding to `Paste`, instead of `PasteSelection`.

**Comment by davidmogar** [comment]
Oh, thanks! Makes a lot of sense now.
