### ISSUE TITLE
q: why there is no public member on this github organization

### ISSUE THREAD

**Issue by mobop** [alacritty/alacritty#3625]
why,?

**Comment by kchibisov** [comment]
I guess no one is decided to make their membership public, however I really wonder why are you interested in that, since it shouldn't matter.

**Comment by chrisduerr** [comment]
There's simply no reason to make membership public. It's about the code, not the people behind it.

**Comment by mobop** [comment]
i want to know about the people who make the software that i use. i guess you all want. 
if not you missing one of the key concept of free software

**Comment by mobop** [comment]
the code doesn't code come from the sky. it is written by humans. i want to about them.

**Comment by kchibisov** [comment]
>i want to know about the people who make the software that i use.

Each contributor is making this code, it has nothing to do with members. Just look at all of them [here](https://github.com/alacritty/alacritty/graphs/contributors) or just by cloning repo and looking on authors in `git log`. I don't see how knowing members could help you.

**Comment by mobop** [comment]
so why does rust has more than 100 public members? 

shouldn't they care more about memory safety that making members public

**Comment by mobop** [comment]
individual contributors and the the maintainers aren't same

**Comment by chrisduerr** [comment]
Every user can decide on their own if they want to show up publicly or not. That quite honestly is none of your business but the decision of each member. They will show up in the repositories anyways, but that doesn't make it any less true.

Either the code is good, or it's not. Deciding that is entirely up to you since Alacritty is completely free. If you're looking for anything other than that, you're probably in the wrong place.

**Comment by kchibisov** [comment]
it's just github status, members could be private even in rust-lang/rust, since you can't say for sure, that everyone has public membership. Members are a pure github thing, and it has nothing to do with the ones who can merge code, etc. It doesn't count all the folks with CA to a repo, etc. members could be never contribute to a project, etc.

**Comment by nixpulvis** [comment]
Listen, I'm *slightly* sympathetic to this issue. In theory, a malicious maintainer could more easily slip something into master than a malicious contributor slipping something into a PR, which gets merged. This **is** OSS, so you can always review the `git log` and see what changed, but it's unrealistic to expect all users to scan every line.

That said, exposing ourselves as maintainers of the org shouldn't really give you that much more confidence than just looking at who's merging to master and releasing builds. The fact that GitHub allows private members of orgs means you'll never know for sure who all is in there. There's nothing we can do to change this.

FWIW, I didn't even know this was an option in GitHub until today, and I've updated my status to public for fun.

**Comment by chrisduerr** [comment]
> a malicious maintainer could more easily slip something into master than a malicious contributor slipping something into a PR.

I'd like to point out that neither me nor you can push directly to master and I'm the only one who can change that policy. With me reading every single PR and commit message, I'd say the attack surface of slipping in a commit that is never seen is rather low. The chance of hiding something somewhere is much bigger, which applies both to maintainers and contributors. If you do not trust me, then you're probably out of luck anyways, unless you plan to review the entire codebase yourself.
