### ISSUE TITLE
alacritty not showing correct mouse cursor

### ISSUE THREAD

**Issue by jc9361** [alacritty/alacritty#3637]
OS: Manjaro-i3

I have noticed that alacritty will not show my custom set mouse cusor (breeze light) When hovering over any alacritty window the system default cursor (breeze dark) is show regardless of what cursor theme I have set in lxappearance.

I mentioned this issue on the #alacritty freenode channel and was asked to submit a review on here..... please notify me of any fixes as I would really like to use this terminal with my selected cursor theme.

Thank you.,

For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY/ConPTY (see `alacritty -v` output)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
> regardless of what cursor theme I have set in lxappearance

lxappearance is a tool to set GTK configurations. Alacritty is not a GTK application.

As you can tell from Alacritty not using the default cursor but your system's cursor, it's clearly possible to change the cursor. You just haven't changed it in the right place. If you change it wherever it is set to breeze dark, it'll likely just work.

**Comment by jc9361** [comment]
@chrisduerr That is what I was thinking... I thought maybe I needed to declare it in alacritty.yml.... Could you advise how this can be done in linux so I can get this sorted out?

https://wiki.archlinux.org/index.php/Cursor_themes <--- It looks here as though lxappearance does the same thing as setting it manually... What am I missing?

**Comment by chrisduerr** [comment]
I'd have to look it up myself, it has been a long time since I've changed my cursor theme in Linux on X11. But I'd recommend following that `XDG specification` section in the archwiki.

Especially with DEs involved, there are a ton of different factors at play. You can also try XResources or the environment variable, but your goal should be to figure out where the existing cursor theme is set, so you can change it properly instead of introducing a third setting into your system.
