### ISSUE TITLE
Scrollback using large amounts of RAM (35 bytes per character)

### ISSUE THREAD

**Issue by michaelweiser** [alacritty/alacritty#3650]
I'm observing what appears to be excessive RAM usage with scrollback in alacritty. A new instance starts out like this:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
76209 me         20   0  895648  32844  20904 S   0.0   0.2   0:00.07 alacritty
```
Configuring 10000 lines of scrollback and running `ls -laRt /` it immediately grows to and levels off at:
```
76209 me         20   0  964072  85700  20976 R  59.3   0.5   0:03.56 alacritty
```
That's `85700 - 32844 == 52856 KiB` difference in RSS or 5.28560KiB per line.

Reconfiguring scrollback to 100000 lines and running `ls -laRt /` again makes it grow to and level off at:
```
76209 me         20   0 1426324 555428  20972 S   0.0   3.4   0:13.56 alacritty
```
That's `555428 - 32844 == 522584 KiB` difference in RSS or 5.22584KiB per line.

5KiB per line of 147 characters is around 35 bytes per character which seems excessive.
Is this expected behaviour?
Can it be reduced?

BTW: Reconfiguring scrollback back down to 10000 does not free up that memory even though the scroillback is actually limited to 10000 lines of scrollback but that's just me nitpicking.

### System

OS: Linux
Version: alacritty 0.4.2
Linux/BSD: Wayland, swaywm 1.4

### Logs
```
[2020-04-27 20:13:24.504770256] [INFO] Welcome to Alacritty
[2020-04-27 20:13:24.504817968] [INFO] Configuration loaded from "/home/me/.config/alacritty/alacritty.yml"
[2020-04-27 20:13:24.508213897] [DEBUG] Estimated DPR: 1
[2020-04-27 20:13:24.508235874] [DEBUG] Estimated Cell Size: 13 x 24
[2020-04-27 20:13:24.508241686] [DEBUG] Estimated Dimensions: None
[2020-04-27 20:13:24.519587727] [INFO] Device pixel ratio: 1
[2020-04-27 20:13:24.523836372] [INFO] Initializing glyph cache...
[2020-04-27 20:13:24.531327622] [INFO] ... finished initializing glyph cache in 0.007467607s
[2020-04-27 20:13:24.531345825] [INFO] Cell Size: 13 x 24
[2020-04-27 20:13:24.531352413] [INFO] Padding: 0 x 0
[2020-04-27 20:13:24.531360638] [INFO] Width: 800, Height: 600
[2020-04-27 20:13:24.533183626] [INFO] PTY Dimensions: Line(25) x Column(61)
[2020-04-27 20:13:24.534557021] [INFO] Initialisation complete
[2020-04-27 20:13:24.548094002] [DEBUG] New num_cols is 147 and num_lines is 42
[2020-04-27 20:13:24.549173051] [INFO] Width: 1920, Height: 1021
```

**Comment by kchibisov** [comment]
It seems like about right. We can in theory reduce amount of data per cell by at least 14 bytes, but I'm not sure how to do it even more. Maybe changing the way we store cells could do a better job, also those reduce by 2 bytes is pretty easy from those 14, not sure about 12, since it's the amount we can save on zero width chars, by storing them somewhere else, but it's not that much efficient, since it could require a lot of dynamic allocations. Using less memory for chars itself is pretty touch, since it's unicode, so we can't just use u16 or u8, instead of u32 like we do right now.

**Comment by chrisduerr** [comment]
Currently it's using 4 bytes for the character itself, 4 bytes for foreground, 4 bytes for background, 2 bytes for the flags and 20 bytes for zero width characters. Coming up to 34 bytes in total.

So everything is working as intended. If you have improvements that do not harm efficiency, feel free to submit them. But Alacritty's goal is performance, not saving memory.

> BTW: Reconfiguring scrollback back down to 10000 does not free up that memory even though the scroillback is actually limited to 10000 lines of scrollback but that's just me nitpicking.

If you `reset` it will usually free up some memory, but not all of it since that's how memory allocation works. The freed up memory will be kept around for new allocations.

**Comment by kchibisov** [comment]
I don't agree with close of this issue, it could be reduced without any harm for perf in my opinion and this is definitely something that should be improved. It's working as intended according to some calculations, but we can at least bit pack Rgb struct and store zero width chars somewhere else. So colors `enum Color` could take 3 bytes instead of 4 bytes. Zero width is a different problem, but the 5 chars is pretty arbitrary to me, and knowing how much they consume, I guess we should at least investigate how we can do that more efficiently, since using less memory for cells is also about performance.

**Comment by kchibisov** [comment]
Also, if we manage to lower the amount of memory for Cell down to 16 bytes, it could improve perf on 64-bit arches, since they can pass cell structure on 2 regs as parameter, which is pretty efficient, instead of carrying struct around.

**Comment by chrisduerr** [comment]
> I don't agree with close of this issue, it could be reduced without any harm for perf in my opinion and this is definitely something that should be improved.

The way zero width chars are stored right now was the best way I have found to make them work without completely ruining performance. If you can provide something that works better, feel free to send a PR. But at the moment this is exactly how it is supposed to work and I don't think there's any point in this issue.

> Also, if we manage to lower the amount of memory for Cell down to 16 bytes, it could improve perf on 64-bit arches

Feel free to test performance before and after adding zero width cells. There was no significant performance impact at all back then. So tagging this as `performance` just seems to misleadingly try and inflate its importance.

If you have any concrete suggestions for changes, feel free to open a separate issue. But these 35 bytes per character are exactly how this is supposed to work. It was designed this way, it didn't accidentally fall in place or leak memory unintentionally.

**Comment by michaelweiser** [comment]
Thanks for the explanations. It'll have to be tmux then.

**Comment by nixpulvis** [comment]
Indeed, perhaps a sane way to manage memory on more constrained systems is something like a hybrid of Alacritty's native scrollback and `tmux`.

That said, I'm wondering how bad the performance implications of a compression strategy would really be, if done somewhat intelligently. Something like a new region after a smaller uncompressed scrollback region, which is compressed / encrypted to disk? We've talked about this kind of thing in the past on #774, but it's not a simple fix, and frankly I'm unsure it'll ever be implemented.

**Comment by chrisduerr** [comment]
Kitty does compression of scrollback and I'm not a fan tbh. There are strategies we could use to reduce the memory size of individual cells, but ultimately that's bad for performance (and so is compression). If you're running into memory limits, just reducing the scrollback available is probably your best bet. By default Alacritty has a bigger scrollback than most other terminal emulators anyways.
