### ISSUE TITLE
Add touchscreen support

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3671]
It shouldn't be that hard to use winit's touchscreen events and translate them to our inner `mouse` struct, at least some basic interaction. I'm not sure how to emulate RMB/MiddleClick for mouse mode though.

**Edit:** Apparently for proper touchscreen support it would also be necessary to enable using it with Wayland CSDs.

**Comment by chrisduerr** [comment]
What exactly do you mean by that? What are you trying to support?

Are we talking about touchscreen usage? Or is this a touchpad thing?

**Comment by kchibisov** [comment]
I'm talking about touchscreens.

**Comment by nagisa** [comment]
I suspect to support this well alacritty would need to also support smooth scrolling.

**Comment by chrisduerr** [comment]
While I understand the idea behind that (it would certainly "feel" better), I don't think it's **necessary** for it to work.

We should have a 'distance' from origin and can just verify based on that by how many lines we should offset the viewport. It would be jerky, sure, but it should work and be usable I'd assume. At least more usable than no support at all.

**Comment by calebccff** [comment]
Yes please! Smooth scrolling would be a nice feel good and make some stuff a lot more intuitive.

**Comment by t184256** [comment]
Merging in the observation from #5204.

GNOME 40.
I can select text with touchscreen and stylus, which I find adequate basic functionality. I don't miss scrolling one bit, but CSD is problematic. I can't drag the window by the title with neither my fingers nor my stylus. Titlebar buttons don't react to them either.

**Comment by bytbox** [comment]
It looks like PR #4346 was a bit of a flop. It seems to me that, as Dreomite suggests at the bottom of that thread, a good path forward is a much less complex patch providing only minimal functionality.

For my own use, I desperately want a tap on the touchscreen to be translated to a click. (This way I can switch between vim/tmux windows easily.) A distant second is scrolling. The things that were controversial in the last attempt --- selection, what happens when the finger moves horizontally, what multiple fingers do, what a hold means --- I really don't care about.

So: @chrisduerr, how would you feel, in principle, about a very minimal patch just to get "tap = click" functional? Would such an attempt be welcome, or would you rather have proper touchscreen support in one go? If you're okay with a small change that leaves the hard work undone and the hard decisions unmade, I'll try for it.

**Comment by chrisduerr** [comment]
I think a patch to just add support for clicking on touchscreens should be fairly uncontroversial.

**Comment by Rasie1** [comment]
On i3wm, sadly, alacritty doesn't react to touchscreen at all. Other terminals can select text with fingers. I would find scrolling really useful

**Comment by doctorcolossus** [comment]
Ditto on sway (wayland) - no reaction. I would like to be able to highlight text.

**Comment by alpiua** [comment]
same here in i3wm

**Comment by undg** [comment]
The click path does not work here (i3wm).

I am desperately waiting for scroll support, ideally with 2 fingers. I love to have mimicked phone touchscreen behaviour. I like [termux](https://termux.dev/) implementation on android.

In my workflow, I often use my touch device just to run some diagnostics/tests/logs in watch mode, while working on the main machine. It's a pain to switch to this device when the output is longer than one page.



I see it was added to the milestone, maybe soon it will be a thing 🤞
