### ISSUE TITLE
Configurable padding around titlebar buttons when using `decorations: transparent`?

### ISSUE THREAD

**Issue by jesseleite** [alacritty/alacritty#3676]
When using the mac-only `decorations: transparent` with `padding`, it would be nice to be able to configure padding around the titlebar buttons as well.

Here's Alacritty, compared with other common native mac apps that render padding around their title buttons (iTunes, Spotify, Safari, and Chrome):

![image](https://user-images.githubusercontent.com/5187394/80916139-ea738600-8d24-11ea-9177-a37cc4a891d7.png)

Thoughts?

### System

OS: macOS
Version: alacritty 0.4.2 (f68de37)

**Comment by chrisduerr** [comment]
I'm not sure about your screenshot, there shouldn't be any padding at all.

This is the issue that tracks that: https://github.com/alacritty/alacritty/issues/1671

Is there a fixed size padding at the top for you?

**Comment by jesseleite** [comment]
I think you are misunderstanding :)  I don't mean padding around the terminal; I mean configurable padding around the close/minimize/fullscreen titlebar controls (the red, yellow, and green dots).  See how there's breathing room around those controls in iTunes, Spotify, Safari, and Chrome?

Obviously it should be opt-in, but I find that look pleasing and wonder if it could be configurable.

**Comment by chrisduerr** [comment]
Oh I don't think there's any point in making that configurable, that just seems like more effort than it's worth.

IIRC, there are plenty of applications on macOS that have the buttons closer to the edge than what you've shown in the screenshots.

**Comment by jesseleite** [comment]
@chrisduerr Fair enough 😢  I know there are plenty of other apps without that padding, but there are also plenty of apps with that padding (including apps made by Apple).  Since so much of Alacritty's looks are configurable, I thought this would be a valid feature request.

**Comment by chrisduerr** [comment]
I don't think it would be worth it, especially because macOS is just one platform and this is such a tiny detail. If we'd go into so much detail for every single platform our configuration file would be thousands of lines long.

The real problem here seems to be that macOS can't make up their own mind on where they should be positioned. This is likely done in our winit depedency, but I'd assume moving them would be relatively simple. But there doesn't seem to be an objectively 'right' place. So I agree with their choice to just get it out of the way as much as possible.

**Comment by nixpulvis** [comment]
I'd say it would be nice to add some padding to the top to make the empty space on both the left and top consistent, however this would be best done in winit, and may be somewhat complex, since the position is dependent on if the window is fullscreen or not. For an example implementation see, https://github.com/electron/electron/pull/21781
