### ISSUE TITLE
alacritty from ssh not working?

### ISSUE THREAD

**Issue by MyraBaba** [alacritty/alacritty#3684]
Ubuntu 18.04
latest alacritty

It is working from the installed machine no problem.

when I connect this machine through ssh , its not working gives below error: 

thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /build/alacritty-X6QEnV/alacritty-0.4.1~1578949568~18.04~acf1833/vendor/winit/src/platform_impl/linux/mod.rs:569:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by kchibisov** [comment]
Are you running it from some tmux?

**Comment by kchibisov** [comment]
In general, it's failing because your ssh env is lacking some env variables, presented in normal startup process of your DE/WM/Compositor, however just running it in ssh will likely produce a bad env, so you should likely export it in your session or have valid env in some app like screen/tmux, which should be started from gui. If your goal is X11 forwarding you should enable it on remove server and connect with `ssh -Y` IIRC. However, since alacritty requires OpenGL there could be some implications doing so.

**Comment by MyraBaba** [comment]
Hi,

I added -Y to ssh it's worked through XQuartz now. My client is mac os x.

Best
