### ISSUE TITLE
Add example of how to change the colorscheme on the go

### ISSUE THREAD

**Issue by alessandro-martini** [alacritty/alacritty#3702]
Hey, I would like to add an example on the wiki for how to setup a keybinding that changes the colorscheme on the go, I had to do some digging to find out how to do that and I think it could help others, can I go ahead with it?

**Comment by kchibisov** [comment]
I guess, wiki is open for edits IIRC.

**Comment by chrisduerr** [comment]
I'd like to let you know that I've intentionally removed this from the wiki. I don't think it's a good way to document this, especially not the way it was done.

This is highly dependent on what you actually name your colorschemes, so just adding some random script that changes things isn't really going to work unless the person happens to follow the same assumptions you've made. If someone actually happens to break those assumptions, they might even run the risk of breaking their configuration file by running that script, so I don't think it's a good idea to advertise it.

Spawning `zsh` on keypress to run a `zsh` function instead of just having a script with a proper shebang that can be executed is also something I'd rather not encourage.

I appreciate the contribution, however I think that anyone using Alacritty can be expected to be able to write a script to replace a string in a file. So forcing people to figure it out on their own and actually get familiar with their own setup is the best choice here.
