### ISSUE TITLE
Font size inconsistent across 'retina' and 'normal' displays

### ISSUE THREAD

**Issue by OJFord** [alacritty/alacritty#3732]
I need quite a different font size in my config to get roughly the same size rendered on my 'retina' 2560x1600 Macbook vs. an old 1440x900 monitor on my linux desktop.

I initially thought 'DPI-relative font sizing' would be a feature request, but I noticed in the sample alacritty.yml that it does specify that it's measured in 'points', which as I understand it is supposed to be a physical distance measurement of the final rendering (née printing)?

That doesn't seem to be the case for me. I need `size: 12` on the Macbookand `size: 6` on the 1440x900 for a similarly sized result. (The latter looks awful because of the low DPI, so I actually use `8`, but ideally I'd like one config I'm happy with on both.) 

### System

OS: Arch linux, macOS
Version: 0.4.2
Linux: X11/Wayland, DE or Compositor and WM: X11, compton, i3

#### arch
```
[DEBUG] Estimated DPR: 1.33...
[DEBUG] Estimated Cell Size: 7 x 18
[DEBUG] Estimated Dimensions: None
[INFO] Device pixel ratio: 1.33...
[INFO] Cell Size: 7 x 18
[INFO] Padding: 0 x 0
[INFO] Width: 480, Height: 876
[INFO] PTY Dimensions: Line(33) x Column(114)
```

480x876 is correct - the window was 1440/3 width, and full 900 height less a polybar.

#### macOS
```
[DEBUG] Estimated DPR: 2
[DEBUG] Estimated Cell Size: 12 x 30
[DEBUG] Estimated Dimensions: None
[INFO] Device pixel ratio: 2
[INFO] Cell Size: 12 x 30
[INFO] Padding: 0 x 0
[INFO] Width: 1600, Height: 1200
[INFO] PTY Dimensions: Line(40) x Column(133)
```

I'm not sure if it's relevant, but 1600x1200 was a floating window; when I made it full screen I got:
```
[INFO] Width: 3360, Height: 2100
```

So I'm not sure if perhaps this is something to do with macOS's  'retina'/'subpixel' stuff faking a larger display than the reported `2560x1600`?

That's with the 'More Space' option in System Preferences > Displays > Scaled, which it describes as 'Looks like 1680x1050'.

With instead the 'Default' option ('Looks like 1440x900'):
```
[INFO] Width: 2880, Height: 1800
```

**Comment by chrisduerr** [comment]
Is this an issue on Linux, or on macOS? Because I'm not sure if macOS ever reports anything than whole number DPI factors. Which obviously means that there's a massive 'gap' in between font sizes where you can never have the correct point size. If your DPR would be 1.4 for example and it just reports 1, you'll get a pixel size of 10 instead of the correct 14 with 10 configured.

On Linux that shouldn't be a problem, since everything is reported regardless how inconvenient the factor might be. However, on Linux we're also pretty much the only application that actually scales by DPI by default on X11, so don't expect it to look exactly like every other application because every other application on X11 uses pixel sizes, **NOT** point sizes.

**Comment by OJFord** [comment]
I wasn't sure which was 'wrong', I just suspected macOS because of (knowing very little about it but) knowing it does something weird with scaling on 'retina' branded displays. From what you're saying though, it sounds like it *is* macOS, just not - or at least not directly - for that reason, sounds like my 'DPR: 2' is not right.

So, if I cared enough to base purchasing decisions on it, the only solution (considering the Macbook is employer-provisioned!) would be to choose a monitor with as close-to-integer DPR as possible? Or as close to `2` as possible? Because I'm still not sure I understand why it would be _so_ far off, if it's just that macOS has rounded to the nearest integer.

**Comment by chrisduerr** [comment]
> So, if I cared enough to base purchasing decisions on it, the only solution (considering the Macbook is employer-provisioned!) would be to choose a monitor with as close-to-integer DPR as possible?

As far as I know, yes. This is not only a thing on macOS btw. On Wayland for example (it depends on compositor), the resolution will be downscaled when using a fractional DPR, so you should stick to whole numbers there too. I believe Windows also only allows setting it to whole numbers. So on most platforms you should probably expect to run at a DPR of either `1` or `2`.

Of course that's probably still better than nothing, but I can see how that would be problematic with devices right on the boundary. The closer you get to the boundaries, the less of a difference it will make of course.

That sounds like this is what you're experiencing though, right? If so I'd close this issue, since there's nothing Alacritty can do about displays reporting a DPR that doesn't fit the monitor right.

**Comment by OJFord** [comment]
It certainly sounds like it, and I'd be happy to close if so, I just don't quite understand how it can be as far off as approximately (i.e., it looks) a factor of 2?

If the Macbook really were `2.0`, then we'd expect `size: 12` to appear the same physical size on both, right?

So say it's `.5` out, i.e. the worst case of `[1.5, 2.5)`, would we not expect it to look like `size: 8` or `size: 16` (depending on which side it's out) does on the other? Instead, it seems closest to `size: 6`.

**Comment by chrisduerr** [comment]
You can print the font pixel size by running `alacritty -v` and pressing the shortcut for resetting font size (cmd + 0/ctrl + 0).

That should print the point size * 2 and the DPR, which allows you to calculate the used pixel size simply by dividing the point value by 2 and multiplying it by the DPR.

What it 'looks like' is a different matter of course, that's up to you. Though feel free to take a ruler to your screen to measure how big they actually are.

**Comment by OJFord** [comment]
Thanks.

Linux 1440x900 `size: 8`:
```
Font size changed to Size(16) with DPR of 1.3333333333333333

1em = 8*0.35 = 2.8mm
20 'm's measure ~40mm => 1em ~2mm
```

(Does that mean my compositor is 'rounding' _up_ (ceiling) `1.33` to `2`?)

Macbook `size: 12`:
```
Font size changed to Size(24) with DPR of 2

1em = 12*0.35 = 4.2mm
20 'm's measure ~20mm => 1m ~1mm
```

**Comment by chrisduerr** [comment]
> (Does that mean my compositor is 'rounding' up (ceiling) 1.33 to 2?)

There are various factors that can lead to some rounding problems, which is why it's usually just best to compare between two monitors. Your font in pixels comes out to 10.66666666667 for example, which is probably rounded to 11. So that'll mean it won't match perfectly.

macOs comes out to 12 * 2 = 24 in pixel size. So that'll mean that the display should have double the pixel density or it won't be correct.

Of course all of this also relies on correct measurements and that your monitor on Linux reports the correct dimensions. But it looks like everything's working right.

I wouldn't rely on the point sizes being 100% accurate to what a 'point size' should be when converted to mm, but it should be consistent across displays. As an example my cell size on my two monitors are ~2.1mm and ~2mm for example, so even though the DPI is different with the same font they're fairly close together.

**Comment by OJFord** [comment]
> > (Does that mean my compositor is 'rounding' up (ceiling) 1.33 to 2?)
> 
> Your font in pixels comes out to 10.66666666667 for example, which is probably rounded to 11.

I'm probably misunderstanding, but I was looking at the `Size(16)`, and assuming that that came from `size: 8` * `2 := ceil(DPR 1.33)`, which matches up with the Macbook (`12 * ceil(2) = 24`) - but is that not right, how is the `Size(x)` derived?

> I wouldn't rely on the point sizes being 100% accurate to what a 'point size' should be when converted to mm

I'm honestly not _that_ fussy :slightly_smiling_face: - I'd just like to figure out a way to use one config `size:` and have it look roughly the same (be able to use it without it being irritating) on both devices. As I showed above, currently even at 4pt _lower_ my desktop's monitor displays _double_ the width of the Macbook's built-in display.

I do appreciate your help in understanding the problem; I've also been considering new monitors so I was only half-joking about basing purchasing decisions on it, but of course I don't want to do that and have it still way off, or eventually discover that a different compositor would have sorted it.

I think the next things I'll try will be different compositors, and (an horrific chain of adapters and cables to allow) connecting the Macbook to the 1440x900 monitor.

Thanks again.

**Comment by chrisduerr** [comment]
> I'm probably misunderstanding, but I was looking at the Size(16), and assuming that that came from size: 8 * 2 := ceil(DPR 1.33)

That's incorrect the size is duplicated because we use integers for font size and multiplying it by two allows us to support .5 increments. But that's a bit of an internal oddity.

> I'm honestly not that fussy slightly_smiling_face - I'd just like to figure out a way to use one config size: and have it look roughly the same (be able to use it without it being irritating) on both devices.

Are you talking about achieving the same size across two different operating systems on two different machines? Usually getting DPI somewhat consistently working on one platform can already be troublesome, so I'm not sure how they compare on different platforms.

**Comment by OJFord** [comment]
> Are you talking about achieving the same size across two different operating systems on two different machines? 

Well.. that is what I _hoped_, yes. I thought that sort of consistency would be the point of specifying `size` in points vs. pixels, but it's a lost cause then?

**Comment by chrisduerr** [comment]
> but it's a lost cause then

I've never tried, so I couldn't tell you. The point is mostly consistency on *one* system, which is usually already hard enough with lack of size reporting on X11 and missing support for fractional scaling factors on macOS/Windows.

If you're using two different systems, using two different configs should be trivial though.
