### ISSUE TITLE
`clear` in ssh session to linux server does not clear the screen

### ISSUE THREAD

**Issue by meuter** [alacritty/alacritty#3765]
On Windows 7 (yeah i know... corporate laptop), when using alacritty to ssh into a linux server (running zsh as shell with TERM set to `xterm-256color`), the `clear` command does not erase the screen properly. When invoked, the cursor position is moved to the top left corner as expected, and the prompt is being displayed. But whatever was being displayed before the command was issued (including on the first line where the prompt was redrawn) remains. Pressing enter does scroll normally though.

Note that in (local) PowerShell, the command `cls` works as expected. 

If you need more info let me know. And kudos on a great terminal! 

### System

OS: Windows
Version: alacritty 0.4.2 (f68de37)
Windows:  Using WinPTY backend

### Logs

Font/Terminal size: 

```
[DEBUG] Estimated DPR: 1
[DEBUG] Estimated Cell Size: 9 x 18
[DEBUG] Estimated Dimensions: Some((1090, 544))
[INFO] Device pixel ratio: 1
[INFO] Initializing glyph cache...
[INFO] ... finished initializing glyph cache in 0.016224366s
[INFO] Estimated DPR correctly, skipping resize
[INFO] Cell Size: 9 x 18
[INFO] Padding: 5 x 2
[INFO] Width: 1090, Height: 544
[INFO] PTY Dimensions: Line(30) x Column(120)
[INFO] Using WinPTY backend
[INFO] Initialisation complete
[DEBUG] Term::resize dimensions unchanged
[INFO] Width: 1090, Height: 544
```

**Comment by chrisduerr** [comment]
Just to clarify, you mean that the stuff below the new cursor position remains, correct? Not that there is still shell history present.

I feel like this might just be a bug with the WinPTY backend, I don't see how this could be related to Alacritty really. Chances are the escape sequence to clear the screen just isn't emitted.

Could you record a ref-test and upload it to verify which escape sequences are emitted. You can do that using the following command:

```
alacritty --ref-test
```

This should generate four files: alacritty.recording, config.json, grid.json and size.json. The only one I'm interested in here is the alacritty.recording. It's also probably best to set your scrollback history size to 0 during this test, which should speed things up a bit, but since we're just interested in the recording this isn't mandatory.

**Comment by meuter** [comment]
Sorry for the delay, I did not have much time this week to take care of this. You can find the recording and corresponding screen grab here: https://github.com/meuter/alacritty-issue-3765

Let me know it you need anything else.

**Comment by chrisduerr** [comment]
There is not a single escape to clear the screen emitted, so Alacritty cannot do something it isn't told to do.

This is probably a problem with the WinPTY backend, but you shouldn't be running Windows 7 anyways so things breaking there isn't much of a surprise.
