### ISSUE TITLE
SIGABRT occurs on macOS Catalina 10.15.5 repeatedly

### ISSUE THREAD

**Issue by mrkn** [alacritty/alacritty#3801]
SIGABRT often occurs on macOS Catalina 10.15.5.  I encounter this issue roughly every day.  This issue presumably didn't occur on macOS Mojave 10.14.x.

### System

OS: macOS 10.15.5
Version: alacritty 0.4.3-rc1 (04114e7)

### Logs

I uploaded the crash log on this gist:
https://gist.github.com/mrkn/82e7341472a44589766d26af4d9e809e

**Comment by mrkn** [comment]
I encountered this issue also with alacritty 0.4.2.

**Comment by chrisduerr** [comment]
This looks like a crash in your GPU driver, it occurs in `com.apple.AMDRadeonX4000GLDriver` when we try swapping buffers. So I don't think there's anything we can do here.

Have you tried running a different OpenGL application to see if that's working?

**Comment by chrisduerr** [comment]
It would be good to test how this works with other OpenGL applications and if it can be reproduced before 10.15.5.

Looks like a macOS driver bug, so there's nothing we can do.

**Comment by mrkn** [comment]
@chrisduerr I didn't experience this kind of crashes on Google Chrome and Adobe Lightroom with GPU acceleration.

**Comment by chrisduerr** [comment]
What about pure OpenGL applications though?

**Comment by mrkn** [comment]
I've confirmed that this issue can occur on the other OpenGL application by using [joshb/CocoaOpenGL-Swift](https://github.com/joshb/CocoaOpenGL-Swift).  I encountered SIGABRT at the glFlush call on this application.

Moreover, I found a similar ticket submitted to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1576767
This ticket has a very long thread of comments, so I've not read yet.

**Comment by chrisduerr** [comment]
According to the Mozilla bug report where they went above and beyond to try and work around a bug that was pretty clearly caused/introduced by Apple with no interest from them to help out, it might be related to memory resource limits.

According to one of the users, the `iStat` application can be used to track memory consumption, it's probably worth giving that a shot. If the GPU memory is at critical levels, that probably could cause a crash.

The Mozilla dev driving this issue forward has also reverse engineered one of the most likely causes for these bugs and provided a patch to the driver's binary to work around it here: https://github.com/steven-michaud/PatchBug1576767. It might help, or make things worse, though it's a fairly high effort workaround.

Since this seems to pretty clearly be a macOS bug and Apple does not seem to have much interest in maintaining OpenGL, the best recommendation I can make is to not use macOS to fix this problem. Other than that there doesn't seem to be much we can do here.

**Comment by DemiMarie** [comment]
> Since this seems to pretty clearly be a macOS bug and Apple does not seem to have much interest in maintaining OpenGL, the best recommendation I can make is to not use macOS to fix this problem. Other than that there doesn't seem to be much we can do here.

OpenGL is officially deprecated on macOS, so alacritty would need to use Metal to stay supported.  This could be done via MoltenGL.
