### ISSUE TITLE
Update docs on Windows support

### ISSUE THREAD

**Issue by nu8** [alacritty/alacritty#3803]
I see this:

> For Windows versions older than Windows 10 (October 2018 Update), Alacritty
> requires winpty to emulate UNIX's PTY API. The agent is a single binary
> (winpty-agent.exe) which must be in the same directory as the Alacritty
> executable and is available through the GitHub releases page.

<https://github.com/alacritty/alacritty#other>

however I just had an issue closed because I have one of these Windows. Why are
you distributing `winpty-agent.exe`, if you arent supporting anyone who would
actually need it?

It seems `winpty-agent.exe` needs to stop being distributed, and the Readme
should be updated to reflect that only Windows 10 is supported.

**Comment by chrisduerr** [comment]
WinPTY is still supported, that's why it's even possible to start it. The thing is WinPTY is not maintained anymore and because of that bugs in WinPTY are not getting fixed. There's nothing Alacritty can do about these bugs, you'd have to take this up with Microsoft yourself.

Your bug wasn't closed because you were using WinPTY and we do not support that, your bug was closed because it was a WinPTY bug that will never get fixed.

Windows 8 is also still supported by Microsoft, which is why WinPTY is still supported by Alacritty. There are also still Windows 10 updates that do not ship the ConPTY backend yet. However if you are on Windows 7, you should consider updating since there is no support at all for your platform anymore.
