### ISSUE TITLE
can't click or highlight link when I use fzf preview

### ISSUE THREAD

**Issue by zdmgmail** [alacritty/alacritty#3813]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

Linux ar 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux

### Logs

I use fzf preview  package I should installed , it always have a url

but in alacritty, it can't click and can't select or highlight
in intellij-idea-ultimate-edition 's terminal , it can click

if I copy the url to a file, then cat filename , then in alacritty,  the url can click

alacritty:

![alacritty](https://user-images.githubusercontent.com/50515839/83717648-d2fe2480-a665-11ea-8019-54dc70550e47.png)

idea built in terminal: 

![idea-terminal](https://user-images.githubusercontent.com/50515839/83717656-dbeef600-a665-11ea-80a4-0f5600457739.png)

fzf command:

`pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S`

Is it a bug or I can config something to support it?

**Comment by kchibisov** [comment]
Have you tried mouse over over URL, also try holding shift.

**Comment by zdmgmail** [comment]
> Have you tried mouse over over URL, also try holding shift.

holding shift can work ... but why there need shift but somewhere in alacritty don't need

**Comment by kchibisov** [comment]
because you're in a mouse mode, I guess, so the mouse is captured by application you're using. By default there's no modifier requirement for clicking on URL, unless you're in mouse mode, which requires holding shift. The other thing you're testing is likely don't even implement it. You can notice whether you need shift or not by mouse cursor icon, if it's left pointer -> you need it, if it's `text` - you don't need it.

>And can I highlight it?

You should move over it with required modifier. Recoloring isn't and unlikely be added.
