### ISSUE TITLE
Material Theme, bright black is actually red

### ISSUE THREAD

**Issue by MinePro120** [alacritty/alacritty#3862]
In the wiki, the color #ff262b used for bright black is actually [red](https://duckduckgo.com/?q=%23ff262b&t=lm&ia=answer). Is this intentional?

**Comment by chrisduerr** [comment]
It's probably not! All colorschemes in the wiki are community contributed and only superficially reviewed when I see them pop up.

Want to figure out what it should be and change it? Everyone should be able to do so and it would be much appreciated.

**Comment by MinePro120** [comment]
I did some search before posting, I found the color scheme material-theme uses (it's in their README), but none of those colors are matching with any of the ones in the wiki. I don't know where to look.

**Comment by chrisduerr** [comment]
That's a good point, the bright and normal colors also seem to be the same in some cases which makes little sense.

Feel free to change it completely if you have an idea on how to improve it. Since the original theme is linked it should be possible to just use the colors defined there. It's mostly a question of choosing which colors to use for normal and which for brights.

**Comment by MinePro120** [comment]
Ok, I changed it according to the material-theme repo. Also, I added comments for colors that were not specified from the material-theme. They were set to similar from the theme (i.e pink instead of magenta) or to arbitrary ones.
