### ISSUE TITLE
UI Line Rendering Issue With Ncurses

### ISSUE THREAD

**Issue by Adam-Antios** [alacritty/alacritty#3868]
I am using Alacritty on Ubuntu 20.04. As you can see from the pictures below there is a problem in the rendering of UI lines of Calcurse which is based on ncurses, so I guess this is going to happen to other applications too, at least to those based on ncurses. The first picture is from Alacritty while the second is from Gnome Terminal.

Is this a known issue or it has to do with some kind of configuration I have yet to change in my Alacritty config file? As you see it is kind of a serious issue for people using their terminal for ncurses applications, which are, kind of, a lot.

![Screenshot from 2020-06-18 22-43-01](https://user-images.githubusercontent.com/17729838/85067275-16ee3f00-b1b9-11ea-87e6-dadec41d6f23.png)
![Screenshot from 2020-06-18 22-43-43](https://user-images.githubusercontent.com/17729838/85067279-1786d580-b1b9-11ea-93a8-f1bb88964945.png)

**Comment by chrisduerr** [comment]
Alacritty uses your font to draw these font characters, however gnome-terminal intentionally sidesteps that and ignores your font.

This is intentional and working as expected, it should be fixed in your font or by adjusting the gaps between glyphs in Alacritty. If you run into issues with overlapping box drawing characters looking strange, that is tracked in #118.
