### ISSUE TITLE
nostd port

### ISSUE THREAD

**Issue by sbechet** [alacritty/alacritty#3883]
More than an issue, it is a question. Has anyone ever had the idea of porting from `alacritty` to `nostd`? It would be possible, even fun, to use the [embedded-graphics](https://github.com/jamwaffles/embedded-graphics) project to create a fully autonomous terminal. There are even projects under two euros/dollars for the hard side like [stm32f103-vga-rs](https://github.com/abelykh0/stm32f103-vga-rs).

What do you think ? Is it a good idea?

**Comment by kchibisov** [comment]
There's no value in terminal wtih nostd, since there's no PTY interface, etc, since those are OS provided, so knowing that there's nostd -> no pty -> impossible (maybe you can do something like real terminals were doing).

So the benefit of this issue is closer to 0 percent, since it's faster to write specialized terminal, than port alacritty(you can remove a lot of features, since you don't have anything on that system).

The one thing that could be supported is KMS backend, however not sure that it's useful too...
