### ISSUE TITLE
[Feature Request] Visual Feedback of "Copy on Selection"

### ISSUE THREAD

**Issue by qops1981** [alacritty/alacritty#3886]
It would nice when copying text on selection by mouse; if the window could indicate that a copy action was taken. It could be a window flash, border flash, flash an icon. Doesn't need to be a flash either, but just something to help me know what I did.

Thank you all,
-Bill

**Comment by chrisduerr** [comment]
Why?

**Comment by qops1981** [comment]
To indicate to the user the an action was taken. I can always assume that it has, but it currently feels hollow. Having had the feature on some other terminals, I quite enjoyed having feedback on my actions.

**Comment by chrisduerr** [comment]
This happens every single time the user selects anything on Linux without any application (as far as I know) showing any kind of feedback (just how nobody shows "feedback" on normal copy).

I don't see how this would be something the user needs feedback about?

**Comment by qops1981** [comment]
I believe I described the feature as a "nice" to have, not a "needs" to have. I have started using this Alacritty and I am quite enjoying it. This is something that would make it a little more enjoyable for me, and I think others since I have come across the feature more than once. In the end as you indicate I can certainly live with out it, but I would be remiss if I never mentioned it at all. So there for it is for everyone consideration.

**Comment by chrisduerr** [comment]
@kchibisov / @nixpulvis do you see any reason to add this? I personally do not.

**Comment by nixpulvis** [comment]
> copying text on selection by mouse

Since, when enabled, mouse selections are **always** copied, I do not see why we would indicate anything. How is it possible to select with the mouse and somehow not copy?

Now for the keyboard action, I'm not sure how I feel about this TBH. Part of me thinks it's a bit unnecessary, yet another part of me feels like it serves a real purpose. Simply forgetting to have the correct program focused will cause an intended copy action to fail due to user error, which would be nice to be able to notice.

Furthermore, I know many people who always spam the copy action 3 or more times to be *sure* it in fact copied. I'm not quite sure what misbehaving software trained them this way, but I've seen it myself. Having an indicator would build trust with those users I would think.

So my main question would be, ignoring the possible development hurdles. What would the correct visual indication be? and should this be a default? Personally, I would like the indication to be very subtle (but still noticeable), and enabled by default. I'm imagining something like a flash around or inside of the selection itself. Although, there is in fact some system interaction that happens, and therefor a small time delta between action and copy success. It may be possible that the selection is changed or removed entirely before the copy is complete?

If this feature was implemented for the keyboard actions, I don't see any reason to disallow it from the mouse action as well, however I would not expect it to be enabled by default for the mouse.

**Comment by chrisduerr** [comment]
> Personally, I would like the indication to be very subtle (but still noticeable), and enabled by default. 

There is absolutely no way I'd ever enable something like this by default.

It seems like most of your points are easily resolved by having the WM just indicate window focus. Like a colored border commonly seen in tiling WMs for example. That would be just as visible as a copy/paste action.

> It may be possible that the selection is changed or removed entirely before the copy is complete?

The copy doesn't really matter anyways, since the selection is not buffered. So it all depends on what the application provides as data once queried to paste, not when copying.

All that said, at least to me it seems pretty clear that this does not provide any value. So I'd rather not waste time on that.

**Comment by chrisduerr** [comment]
On a different note though, what would be possible is changing the selection color when the window is not focused. That seems to be a relatively common thing.

**Comment by absorber** [comment]
> It seems like most of your points are easily resolved by having the WM just indicate window focus. Like a colored border commonly seen in tiling WMs for example. That would be just as visible as a copy/paste action.

What about users that have their terminals in full screen and without any window decorations?

I would personally love the terminal emulator to be able to blink (or playback a sound) when copying something.
