### ISSUE TITLE
featreq windows: use OpenConsole.exe next to alacritty.exe if it exists (instead of conhost.exe)

### ISSUE THREAD

**Issue by colemickens** [alacritty/alacritty#3889]
See: https://github.com/alacritty/alacritty/issues/1663#issuecomment-645608542

>conhost is built from the (exact!) same source as OpenConsole; one is just delivered a lot faster since we aren’t stuck behind the multiple-month Windows release cycle ;)

and then

>I replaced conhost.exe as suggested. While 'echo -e "\e[?1000h"' results in garbage characters on mouse inputs, tmux doesn't capture them. Of course I have mouse enabled in tmux and vim (to validate my tmux/vim setup I tried with Terminus and mouse worked as expected).

I can confirm I get mouse working when I replace the system conhost. However, it would be nice to not need to do this, it feels dangerous.

The Windows Terminal folks seem to ship a build of OpenConsole that wt uses instead of ConHost. It would be nice if `alacritty,exe` would use a sibling `OpenConsole.exe` if it exists instead of the system `conhost.exe` for a similar experience for users that want test with newer OpenConsole. I could imagine it being useful for alacritty devs on windows as well.

### System

OS: Windows
Version: `alacritty --version` output
Windows: **ConPTY**

**Comment by colemickens** [comment]
I think this is related: https://github.com/microsoft/terminal/issues/1130

**Comment by chrisduerr** [comment]
I don't see why we would run against a not yet officially released version of the ConPTY? If Microsoft is figuring out themselves that their released software isn't usable, it seems clear to me that it should just be updated more frequently?

**Comment by colemickens** [comment]
It's a request for an optional, user-opt-in feature and I gave an example of how it would be useful immediately to alacritty users. Please let me know if I can clarify further.

**Comment by chrisduerr** [comment]
This seems like an issue that should be fixed on Windows' side, not Alacritty's. Do you have any input on this @davidhewitt?

**Comment by davidhewitt** [comment]
Yes - I think this is potentially interesting if someone wants to work on it, but it might be a low-priority feature. 

Basically instead of using a pseudoconsole handle provided by the system APIs, we can create one that points to `OpenConsole.exe`. 

To achieve this we'd need to replace Windows' pseudoconsole APIs with a Rust equivalent to the implementation of this code: https://github.com/microsoft/terminal/blob/aa1ed0a19c479ce6d7c0087ab4bca95f87e83584/src/winconpty/winconpty.cpp#L54

Doing this would in theory be a nice way to let users with out-of-date Windows editions to get a functional ConPTY. I think that the minimum Windows 10 version would still apply (as they'd still need some pseudconsole support I think, not sure). At least they could manually download a newer `OpenConsole` to work around ConPTY bugs.

**Comment by chrisduerr** [comment]
> To achieve this we'd need to replace Windows' pseudoconsole APIs with a Rust equivalent to the implementation of this code: https://github.com/microsoft/terminal/blob/aa1ed0a19c479ce6d7c0087ab4bca95f87e83584/src/winconpty/winconpty.cpp#L54

That's kinda what I was expecting, which really doesn't seem like it's worth it? Like at that point we're just sidestepping the official Microsoft APIs to do what we're trying to do and then try to roll our own. Not saying that it's not officially supported to do things manually, but it doesn't seem like it's intended?

> Doing this would in theory be a nice way to let users with out-of-date Windows editions to get a functional ConPTY.

I don't think this needs to be a priority at all. If people don't want to update their system and it causes troubles, that's not our problem.

**Comment by chrisduerr** [comment]
@kchibisov / @nixpulvis, what do you think? I'm inclined to close this since it's not something I am interested in maintaining.

**Comment by davidhewitt** [comment]
> I don't think this needs to be a priority at all.

I agree that it's not really something I'm interested in either (but then, my current setup is working fine, I'm not trying to use e.g. mouse). Also Windows synchronises with the Windows Terminal implementation on a rolling basis (I think with each OS biannual update? Not perfectly sure.). So things fixed upstream can be accessed by those that really need them by going to an Insider windows build.

**Comment by nixpulvis** [comment]
If my understanding of this is correct, the Windows Terminal will always stand a chance to be ahead of the current state of what the latest Windows APIs provide because it bundles it's own conhost. So while it may be considered a workaround, https://github.com/alacritty/alacritty/issues/1663#issuecomment-644739799 doesn't seems like something to implement in code, no. I believe our code should use the APIs present on the latest versions of Windows, and make no attempts at patching these things ourselves.

in some ways it's inevitable that the Windows Terminal may see features before other terminals when they are dependent on changes to Windows itself, since the folks at Microsoft are using that terminal to drive the changes.

If I'm missing something, perhaps a summary could be useful. I also do not have strong opinions about this in general, since IMO the windows ecosystem is still a bit messy, and hacky solutions wouldn't surprise or upset me either.

**Comment by colemickens** [comment]
I think others likely have a better understanding than I do, but everyone's comments seems fair/accurate given what I know. I had hoped this would be a fairly small thing to add `if (devMode) { launch OpenConsole.exe } else { launch conhost.exe }` but I realize that's probably ignorant.

Anyway, it sounds like there is some consensus around sticking with stable Win10 conhost api, so I'll close this. Thanks for considering and thanks all for the detailed explanations!

**Comment by fredizzimo** [comment]
I think this has to be done now. I just installed the 20H2 update, and the two main issues I'm having are still not fixed in that. There might be more, but I don't know since I have't really ever used the default conhost, since I always replaced it.
* https://github.com/alacritty/alacritty/issues/1663
* rendering problems with the cursor in the neovim terminal (I could not find an issue for it, either here or in the windows terminal github issue list, but I'm pretty sure there is one somewhere).

Before this I used the workaround reported in https://github.com/alacritty/alacritty/issues/1663, and everything was working fine, except that some windows updates restored the original one and I had to redo it. However, that workaround does no longer work, or at least not as easiliy, because conhost seems to be started with Windows now, and there's no way to kill it in order to be able to replace it. It might be possible to stop some service, but I think the whole process is hacky enough even without doing it.

**Comment by fredizzimo** [comment]
It looks quite straightforward actually, https://github.com/microsoft/terminal/tree/main/src/winconpty compiles to a dll, so it would just be a matter of compiling that, and using that API instead along with the openconsole.exe. I will try it out later today.

**Comment by fredizzimo** [comment]
I have sent a pull request that implements this. You just need to compile the Windows terminal project and copy conpty.dll, and OpenConsole.exe (note OpenConsole.exe is not enough) to the same folder as the alacritty executable.

**Comment by ndavidpsi** [comment]
How do you compile the Windows Terminal from source? It doesn't have any build guide. Also I checked my WindowsTerminal directory, it only contains OpenConsole.exe, no conpty.dll

**Comment by fredizzimo** [comment]
Yes, you will have to build it from source yourself. And there is a short build guide, but it's a little bit hidden inside the long readme. https://github.com/microsoft/terminal#developer-guidance

**Comment by ndavidpsi** [comment]
Doing that rn. 3rd try this time :/ got always some errors
