### ISSUE TITLE
Missing characters in Vim

### ISSUE THREAD

**Issue by zsugabubus** [alacritty/alacritty#3891]
1. `vim --clean '+call setline(1, repeat([">>".repeat("-", 15)], 5))' +redraw`.
2. You should see something like this:
```
>>---------------
  ---------------
           ------
>>---------------
>>---------------
```

brammool:
> This is either a problem with the terminal emulator or with setting the correct termcap/terminfo entries.

(It’s also reproducible with `urxvt`, but no problems with `kitty`.)

### System

OS: Arch Linux
Version: alacritty 0.4.3
Linux/BSD: X11, no compositor

### Logs

```
[DEBUG] [unhandled hook] params=[0], ints: [], ignore: false
[DEBUG] [unhandled put] byte=122
[DEBUG] [unhandled unhook]
[DEBUG] [Unhandled CSI] action='m', args=[0], intermediates=[37]
```

**Comment by chrisduerr** [comment]
Bram told you that it's either a terminal emulator or a terminfo problem. So have you tested if it can be fixed by changing the terminfo?

**Comment by zsugabubus** [comment]
Using `alacritty` with `TERM=kitty` fixes the issue.

**Comment by kchibisov** [comment]
Does `TERM=xterm-256color` fixes issue? Also `TERM=kitty` is not really a kitty terminfo, the terminfi it's using is `TERM=xterm-kitty`.

**Comment by zsugabubus** [comment]
None of them works.

**Comment by kchibisov** [comment]
I don't use vim, but it works fine in neovim and `TERM=alacritty`. I know that vim is tend to do some weird things and is using their own terminfo capabilities instead of well defined one, sometimes even conflicting with them. (undercurl thing is a good example, since they're using some tmux extension for it, instead of default undercurl cap). So, it's really hard to understand who is at fault, even they could say 'not a vim problem'.

**Comment by zsugabubus** [comment]
Maybe I was a bit quick and believed to Bram, but better looking at the `script` output I can see `\e[2;1H(whitespace)\e[3;1H(whitespace)` things. Now I do not really think it’s `alacritty`'s fault. Probably I just let this issue go…
