### ISSUE TITLE
Alacritty --class flag doesn't actually change the instance class

### ISSUE THREAD

**Issue by pradyungn** [alacritty/alacritty#3919]
I use kitty --class floating_term to make it float in bspwm. However when switching to alacritty, alacritty isn't responding to the class flag. While the program runs, the class is still listed as Alacritty. The 'title' flag works, just not the --class flag. Not sure what kind of evidence to send for this, but I monitor the class flags using the rofi window list.

**Comment by chrisduerr** [comment]
Which class do you want to change? Try running it with `--class class1,class2`. Chances are you want to set the general class, not the instance class (which is what is changed by default).

**Comment by pradyungn** [comment]
Oh i didn't understand that part of the help doc :P my bad!

**Comment by RichardBronosky** [comment]
Can you please point me to some information on the meaning of this "class"?

A few details on my exact need. I want to change some configuration options of the current Alacritty instance without changing any of the others. I'm thinking I may be able to do that with `--class` but what I would expect to use is the PID. Any leads would be appreciated.

**Comment by nixpulvis** [comment]
@RichardBronosky if you are looking to change Alacritty configuration options, you should use a seperate config file passed in with the `--config-file` option. Shared configurations can used by this configuration with the `import` key (see the example [`alacritty.yml`](https://github.com/alacritty/alacritty/blob/fc87aaa4b10b9a5949fa2eae9e33ef66949b70d3/alacritty.yml#L3-L12)).

If you are looking to change the way other allications handle alacritty, you can set the class, and have them filter by class. For example, in i3/sway you may set any window with the class "floating" to not be tiled by default.

PID is generally what you want here, since there's no way for you to predict what the PID will be ahead of time, so you'll be stuck trying to guess it somehow.
