### ISSUE TITLE
Alacritty icon concept for macOS Big Sur

### ISSUE THREAD

**Issue by jdsimcoe** [alacritty/alacritty#3926]
This is only a rough concept I put together in Figma, but I wanted to explore what the Alacritty icon would/could look like in the macOS Big Sur container style:

![icon-preview](https://user-images.githubusercontent.com/275617/86828988-c2681200-c048-11ea-80eb-a5b2ed9f43df.png)

Definitely not trying to step on any toes here or take this over, but just wanted to explore and idea and toss it out there for consideration. The other option I explored had the red-to-yellow gradient in a smaller container scaled back behind the terminal view (more like the current icon):

![icon-preview](https://user-images.githubusercontent.com/275617/86829704-9305d500-c049-11ea-8534-991ab09e465b.png)

@jwilm would love any thoughts or feedback if/when you have time.

**Comment by chrisduerr** [comment]
Thanks for sharing your work, but I don't think there's any interest in changing Alacritty's icon just because of some macOS redesign.

**Comment by alexanderniebuhr** [comment]
@jdsimcoe could you supply icon files?
Would love to manually change the icon :)

**Comment by jdsimcoe** [comment]
@chrisduerr I understand that... since macOS is permanently changing its icon container shape I wondered what it would look like to make it feel consistent. I get not wanting to change it around.

@alexanderniebuhr here is a link to the Figma file if you want to play with it: https://www.figma.com/file/gN4EZ0QUHWF9JecskKULEB/Alacritty-Big-Sur-icon/duplicate

Also here is a Dropbox link to the `.icns` icon file: https://www.dropbox.com/s/0i4ez0el7paksg3/Alacritty.icns?dl=0.

**Comment by mambusskruj** [comment]
I like this icon representation for Big Sur. Thank you. 

BTW can't understand what is the problem to put slightly different icon for MacOS while building `.dmg`.

**Comment by kchibisov** [comment]
@jdsimcoe do you have an svg for this icon? We may put it in https://github.com/alacritty/alacritty/tree/master/extra/logo so the users may use it if they want.

**Comment by jdsimcoe** [comment]
Here is the SVG: https://gist.github.com/jdsimcoe/8760878212c4001216a738d2111dcb33. Also here is a link to the icon in Figma if this is helpful for `.icns` export: https://www.figma.com/file/CI8Keod1I0OBlslWjMSiVE/Alacritty-Icon-for-macOS-Big-Sur/duplicate.

**Comment by kchibisov** [comment]
Would you mind opening a PR to add into extra/logo/compat/alacritty-term-bigsur.svg or something like that, I don't see anything against keeping it inside the repo as art, so it won't get lost?

**Comment by jdsimcoe** [comment]
@kchibisov Done! https://github.com/alacritty/alacritty/pull/4435

**Comment by chrisduerr** [comment]
> Would you mind opening a PR to add into extra/logo/compat/alacritty-term-bigsur.svg or something like that, I don't see anything against keeping it inside the repo as art, so it won't get lost?

I do, I don't see any reason why we would add multiple different icon themes to the main Alacritty repository. That just doesn't make much sense to me at all.

There's nothing wrong with providing your own icons, but I have no interest in shipping a collection of different icons tuned for each desktop environment/OS.

**Comment by fatih** [comment]
I understand you don't want to ship different icons. However the current icon on the latest macOS version sticks out and doesn't fit the current set of items. Here is a picture that shows it more clearer:

<img width="341" alt="Screen Shot 2020-11-16 at 21 23 27" src="https://user-images.githubusercontent.com/438920/99349922-fc94bc00-2851-11eb-9f63-9cb9848b0c2e.png">

It's not uniform and doesn't match the OS aesthetic. After upgrading my personal laptop to macOS, I thought someone might fixed it already and opened a Pull request to update the icon. But then I saw the conversation here.

I know it's an hassle to ship bunch of icons and I understand it has nothing to do with Alacritty. But it's an experience and it's right now sticking out from people's screens each time they use Alacritty. Using a terminal is a whole experience and I hope you change your stance and understand why people want to update the icon.

**Comment by jdsimcoe** [comment]
Case in point, Chrome just updated theirs:

https://twitter.com/elvin_not_11/status/1328833704756617217

I think it's worth adapting so that the app icon fits best on each platform.

**Comment by dinhquochan** [comment]
Thanks @jdsimcoe, I really love it.

![image](https://user-images.githubusercontent.com/9979458/99933990-32c0c700-2d8f-11eb-9463-679c03647ea9.png)

**Comment by jdsimcoe** [comment]
thanks, @dinhquochan!

**Comment by juniovitorino** [comment]
> > Would you mind opening a PR to add into extra/logo/compat/alacritty-term-bigsur.svg or something like that, I don't see anything against keeping it inside the repo as art, so it won't get lost?
> 
> I do, I don't see any reason why we would add multiple different icon themes to the main Alacritty repository. That just doesn't make much sense to me at all.
> 
> There's nothing wrong with providing your own icons, but I have no interest in shipping a collection of different icons tuned for each desktop environment/OS.

Damn, this sounds so authoritatively 🤮, the complete opposite to open-source spirit. 
@jdsimcoe beautiful icon, congratulations on the initiative, I also love it. <3

**Comment by jdsimcoe** [comment]
thanks for the kind words @juniovitorino. I really appreciate it.

**Comment by phaazon** [comment]
> > > Would you mind opening a PR to add into extra/logo/compat/alacritty-term-bigsur.svg or something like that, I don't see anything against keeping it inside the repo as art, so it won't get lost?
> > 
> > 
> > I do, I don't see any reason why we would add multiple different icon themes to the main Alacritty repository. That just doesn't make much sense to me at all.
> > There's nothing wrong with providing your own icons, but I have no interest in shipping a collection of different icons tuned for each desktop environment/OS.
> 
> Damn, this sounds so authoritatively vomiting_face, the complete opposite to open-source spirit.
> @jdsimcoe beautiful icon, congratulations on the initiative, I also love it. hearts

Actually, maintainers burn-out because of random requests like that where people wouldn’t understand their feature being out of scope of the project, while it is. So, your “opposite to open-source spirit”, if you mean “let us bomb maintainers with ideas we will refuse to give up on, even if it’s out of scope / the maintainers don’t have time for it” is the “open-source spirit”, I beg to disagree.

I’m surprised **icons** are discussed on the alacritty development repository. You also have to understand that this kind of request doesn’t scale at all. What should the maintainers do if ALL Linux distrubtions / desktop environments / OSes start asking for a different icon? That’s the job of the package manager / distribution.

**Comment by fatih** [comment]
You don't understand that macOS is one of the most popular used operating systems out there. I can bet the total users of macOS extends all the various small linux distros out there. You can't simply compare them. 

I know how hard open source can be, but this is a legit request. Right now, Alacritty is the only application that sticks out because the maintainer doesn't want to bother with it. And eventually he has the say at the end. All we can is, either manually patch Alacritty everytime, or convince him that this is an important detail.

**Comment by phaazon** [comment]
@fatih I don’t really know who packages things. “Normally”, it shouldn’t be the maintainer — in the Linux ecosystem, roles are well defined and it’s typically the packagers (people maintaining .deb, PKGBUILDS, etc. etc.) who would do that. Now maybe that for .dmg, it’s on alacritty’s maintainers side to provide the `.dmg` along with the icon. Is there a document somewhere explaining all this?

Release channels are important and without a document explaining how they are used, we end up to this kind of confusion. I don’t think the initial request of this issue is wrong (I agree it looks better for this particular OS), but I just wanted to point out that it doesn’t scale well if release channels are not correctly understood.

**Comment by aybabtme** [comment]
There's already SVG logos in the repo so it's not like this is introducing something crazy and novel.

**Comment by bouk** [comment]
@chrisduerr i will gladly make a PR that introduces this change, since I was already working on the universal binaries

**Comment by radiosilence** [comment]
@chrisduerr Could you re-open? There is of course a valid desire for people to want their terminal app to look natural on their system of choice.

**Comment by nixpulvis** [comment]
@radiosilence [the SVGs](https://github.com/alacritty/alacritty/issues/3926#issuecomment-728228991) are provided in this issue. I get the feeling we aren't going to update our macOS build any time soon, so changing the icon for yourself would be the best way forward. This shouldn't be hard on macOS IIRC, just replace the icon in the application bundle.

If adding the icon to the source is too heavy handed as @chrisduerr suggests (which I'm tempted to agree with), perhaps someone can update https://github.com/alacritty/alacritty/wiki/Alacritty-Icon with the Big Sur style linked here (with instructions on usage). That should be more than enough for everyone.

**Comment by radiosilence** [comment]
It is quite irritating have to do this every update. Somehow other cross-platform applications manage to bundle platform specific icons. Is `221kB` really a huge amount of bloat?

I wonder if the icon could be patched as part of the homebrew cask install?

**Comment by nixpulvis** [comment]
@radiosilence I'm guessing part of the problem here is that not everyone is running the latest macOS... However, this has been a bad argument in the past since we can't really be expected to maintain the state of Alacritty across all versions of an operating system.

If updating an existing `icns` file is all that's needed, I'd be tempted to agree with this request. However, I suspect we'd also need to store an original somewhere, and this starts to get messier. That said, while it's true macOS has a clear design guideline for this, it does open up other platforms requesting specific things, which we wouldn't be likely to support. So the point made by chris still stands.

I don't see a reason you can't fix this problem for yourself in an automatic fashion with something like a homebrew formula or otherwise though. I know it's not the fix you want, since it's not the default, but perhaps the maintainers of the homebrew package would be interested in adding the patch?

**Comment by radiosilence** [comment]
I mean I think fixing it in homebrew could be one option, but most apps that ship for macOS have solved this by now by updating their macOS icns to be one that fits with the current version, and not sure why it is any more difficult for AlacriTTY.

**Comment by gcg** [comment]
thank you @jdsimcoe 

When I first switched to macos couple of months ago, I found your PR/this issue and downloaded and updated the icon manually. After an update today, the icon reverted back to its original glory and I felt the need to add a comment here to maybe possible nudge @chrisduerr and appeal to them to maybe change their mind about supplying a custom icon for macOS since literally every app is doing so. 

I mean, look how ugly it looks on big sur with the default icon. 

![Screen Shot 2021-05-26 at 4 04 30 PM](https://user-images.githubusercontent.com/811685/119664499-0f5cfe80-be3c-11eb-9898-6994fbc43486.png)

**Comment by danieldiekmeier** [comment]
Hint for people coming from Google (like me): If you want to use the icon design linked at the top of this thread, you can use an app like [Pictogram](https://pictogramapp.com/), that allows you to change dock icons AND retain the changes even between app updates.

**Comment by explogx** [comment]
I feel like the alternative icon should be in the repo, or within a specific branch, for those who run macOS Big Sur and newer, and want to keep the consistency of the UI.

Adding a new icon in the macOS folder already present won't hurt much.

**Comment by ivankovnatsky** [comment]
Open Source is hard. Though there're iTerm and kitty, which are not without problems, but have adapted icons.

**Comment by SeparateRecords** [comment]
First off, I just want to say that I totally get not wanting to "open the floodgates" for aesthetic changes.

It _does_ seem a little strange to not want to change the icon for macOS purely over an ideological issue. An OS that, I'd bet money, makes up the lion's share of Alacritty installs.

Given this issue's long discussion, macOS users _really want_ a better default icon. And [with the PR to homebrew being closed](https://github.com/Homebrew/homebrew-cask/pull/122151#issuecomment-1101391689), it's also pretty clear that (in the Mac ecosystem) it's expected that an app ships with the "canonical" icon. The [majority of Homebrew actions in the last 30 days](https://formulae.brew.sh/analytics/os-version/30d/) (86.96%) were from operating systems where this style of icon is expected.

As was said earlier in this issue, it's also included in [Apple's HIG "platform considerations"](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#macos:~:text=including%20a%20rounded%2Drectangle%20shape%2C%20front%2Dfacing%20perspective%2C%20level%20position%2C%20and%20uniform%20drop%20shadow), which may actually be the weakest argument here 😄

Would this be open for reconsideration now that 2 years have passed and almost every other app, including OSS and Linux-first apps, have moved to using bespoke macOS icons?

**Comment by chrisduerr** [comment]
> Would this be open for reconsideration now that 2 years have passed and almost every other app, including OSS and Linux-first apps, have moved to using bespoke macOS icons?

No.

**Comment by mambusskruj** [comment]
I don't like it BTW. Seems like stubborn and stupid position in a simple community request. The request doesn't even touch product codebase. Open source github project shouldn't be like that.

So yeah, so long meow.

**Comment by phaazon** [comment]
Is there any chance to get it merged by someone else?

**Comment by nixpulvis** [comment]
You can put whatever icons you want in your own builds FWIW.

**Comment by siliconwitch** [comment]
This thread is infuriating 😅

Thankfully, people always find a way: https://github.com/hmarr/dotfiles/blob/main/bin/update-alacritty-icon.sh

**Comment by tea0112** [comment]
I am using Linux, but honestly, this icon is beautiful.

**Comment by epheien** [comment]
Great work! The original icons of macOS are too abrupt.

**Comment by tsndr** [comment]
> Thanks for sharing your work, but I don't think there's any interest in changing Alacritty's icon just because of some macOS redesign.

And that's why I've switched to Kitty!

**Comment by ADemkin** [comment]
Hello. I just switched to Alacritty from iTerm and only thing i dislike is it's icon. I would really appreciate if you change your mind and allow icon update.

**Comment by kchibisov** [comment]
Package manager could change the icon at any time, it's not a part of the binary. That's how linux distros do that.

**Comment by ADemkin** [comment]
@kchibisov As far as i know, homebrew on macOS does not allow that.

**Comment by tbjers** [comment]
@jdsimcoe that is a sweet icon! I am currently on Fedora, but I totally need to change out my MacOS icon for your version.

The sheer fact that I stumbled on this issue via Google four years after its creation should tell you something.

@chrisduerr So, there's already three icons in the `extras/logo` folder, and then another five icons in the `extras/logo/compat` folder. Why can't you add that MacOS icon in that directory? I love Alacritty, and it's one of the best terminal apps out there, but your attitude towards adding a properly styled MacOS icon is confounding.

There are so many hills, and this is the one where you chose to make your stand? Have you looked at how many down-votes your responses have garnered? Replying with "No" without supplying further motivation is pretty weak. Not trying to throw any shade here, I am just seriously confused as to why you feel like adding an OS-specific icon somehow violates the ethos of your work... I mean, dang, bro, you already have a `extra/osx/Alacritty.app/Contents/Resources/alacritty.icns` file.

It's such a minimal lift... And requested by so many people. Don't get me wrong, I wouldn't be caught dead with a Mac in my backpack. Some of the most overpriced junk there ever was, and the users are generally overbearing carebears with too many feelings... But, Chris, this is probably the most stupid "no" I have ever come across in my near-fifty years on this planet.

**Comment by phaazon** [comment]
@tbjers I’m not going to defend the attitude, I agree with you, but you also need to take some hindsight. I think developing a project and releasing it are two different things. You can choose to do both, but it’s fine not to. I think the problem here is that there is no stand. Either Chris should allow release channels contributors to push stuff in `alacritty/alacritty`, or not. I personally think that for small projects, it’s fine to have both in the same repository, but for bigger projects, it’s totally fine for the author to ask other people to bundle it a different way.

Now it also means that Chris doesn’t care about the _image_ (large sense) of Alacritty, if Chris doesn’t want to force people from using it.

And remember that we are not talking about a company here. We are talking about people spending their spare-time to provide others with great software. If they say “No”, I don’t think anyone should blame them for that.

**Comment by tbjers** [comment]
> Either Chris should allow release channels contributors to push stuff in `alacritty/alacritty`, or not. I personally think that for small projects, it’s fine to have both in the same repository, but for bigger projects, it’s totally fine for the author to ask other people to bundle it a different way.

I see the argument being made by you and others that if this icon is allowed to enter the repo, the floodgates will open for all kinds of icons... That line of thinking includes a faulty assumption: that Linux distributions are different operating systems. They are not. They have different **window managers**, sure.

Just because all these Linux distros have different names does not mean we need a different icon for each of them. Besides, all those distros have the ability to replace all icons with styled icons in a sustainable fashion that does not require the user to modify the application files every time a new version of the app is released.

> And remember that we are not talking about a company here. We are talking about people spending their spare-time to provide others with great software. If they say “No”, I don’t think anyone should blame them for that.

No argument here. Alacritty is the best terminal emulator, ever, and I am forever grateful to Chris for spending his time on developing this amazing piece of software. The notion that I am ingrateful just by disagreeing with his opinion about icons is a false dichotomy.

I do not see a donate button on this repo. With one, Chris would be getting a monthly payment from me, and I am sure, many others.

**Comment by kchibisov** [comment]
I wonder whether if the current icon will be a bit _smaller_ will it be fine? Since the only issue I've seen is that it's a bit bigger than others.

**Comment by tbjers** [comment]
> I wonder whether if the current icon will be a bit _smaller_ will it be fine? Since the only issue I've seen is that it's a bit bigger than others.

Or even take the `simple.svg` logo and put it on a white field with rounded corners?

**Comment by kchibisov** [comment]
I was wondering if one can `sed` it during `make app` to *align* a bit, so the icon is the same, just a bit _smaller_.

or icon is already a bit roundish.

**Comment by tbjers** [comment]
I took the liberty of updating the icon by adding a variant without scanlines.
https://www.figma.com/file/ZS3gQ2mMvotsPTurjv4ahk/Alacritty-Mac-OS-icon?type=design&node-id=0%3A1&mode=design&t=7a0Jzp725EpmDZ1R-1

Also working on a script that can be run to automatically generate the icon set in a GitHub Actions flow. Might not be accepted into the repo, but perhaps someone else can take it and do something nifty with it.

**Comment by tdelam** [comment]
> This thread is infuriating 😅
> 
> Thankfully, people always find a way: https://github.com/hmarr/dotfiles/blob/main/bin/update-alacritty-icon.sh

Excellent! thanks. I don't mind alacritty at all but that icon was awful. This looks grrrreat!

**Comment by erlangparasu** [comment]
> @chrisduerr I understand that... since macOS is permanently changing its icon container shape I wondered what it would look like to make it feel consistent. I get not wanting to change it around.
> 
> @alexanderniebuhr here is a link to the Figma file if you want to play with it: https://www.figma.com/file/gN4EZ0QUHWF9JecskKULEB/Alacritty-Big-Sur-icon/duplicate
> 
> Also here is a Dropbox link to the `.icns` icon file: https://www.dropbox.com/s/0i4ez0el7paksg3/Alacritty.icns?dl=0.

Thanks!

**Comment by dabeeeenster** [comment]
I don't understand why there is a position against updating the MacOS icon file that is *already in this repo* with one that actually meets current MacOS HIG? Weird. Thanks for the application - really appreciate it, but I just don't understand why you would be against updating an outdated icon.

**Comment by jdsimcoe** [comment]
@fractalcounty this is _partly_ why I've moved to [Ghostty](https://mitchellh.com/ghostty)

**Comment by fractalcounty** [comment]
> @fractalcounty this is _partly_ why I've moved to [Ghostty](https://mitchellh.com/ghostty)

I'm normally skeptical of anything that has this amount of hype without any form of public release, no less a terminal emulator, but the dev logs were really compelling. I tried to get in on the beta awhile ago but stopped bothering when I realized there's a bajillion other people with the same idea as me in that server

Also, I take back what I said, your icon still looks great and there was obviously more than enough interest in it at the time to warrant at least an attempt to explain why following modern design standards somehow isn't good enough justification to consider it over the obsolete one. I was trying to avoid focusing on the subjective matter of the design itself, but it was an objectively good icon. Most developers I know would jump out of their seats at the first chance to replace their programmer art with something that looks professionally designed. For what it's worth, there's still a lot of people that go through the effort of manually updating the icon after each update and probably will be for as long as alacritty is around

**Comment by kchibisov** [comment]
@jdsimcoe the main issue is the rounding though, since it changes the look and feel of the icon. Yes, macOS really wants things more rounded, and generally the way to solve such things is by having icon theme. But if you just scale the original down (well, because it's svg you have to add empty space, without changing the icon), it could be put in e.g. compat, and should be fine with @chrisduerr , since compat is kept around for the _exact same_ icon, but when DE/etc struggles to e.g. render due to some decisions. Like we have icons in compat because KDE/QT can not render it at all, and for e.g. macOS it would be there just because it can not make it smaller.

**Comment by mustafa89** [comment]
I honestly never even noticed it and just landed on this thread after the founder of Ghostty tweeted it in jest.

Been using Alacritty for many years now, but the maintainer's arrogance has really turned me away from it.

I guess it's time to try Ghostty.

Arrogance should never be rewarded.

**Comment by Exerra** [comment]
I've been meaning to try Alacritty, but the lack of a Big Sur styled icon really threw me off and now reading this thread has fully made me want to never touch this project again.

It's not about the icon itself, but the arrogance and refusal to adapt to OS changes. And now with Tahoe having an even different style Alacritty will stick out even more and look even older.

As a prospective user I am thinking that if even the icon isn't updated to match the new OS, what else isn't? What else do they refuse to update and support that would make my experience on Mac a lot better? The old icon makes it look abandoned since before 2020 - not a great look.

**Comment by acgxv** [comment]
Thanks for the great work. However, it was broken in macOS 26. 

It now has a rounded square shape.

Pretty different to other icons.

<img width="249" alt="Image" src="https://github.com/user-attachments/assets/b2c52579-bc6d-4c90-b1bb-f796419001ad" />

**Comment by nixpulvis** [comment]
Funny, this actually accommodates the original icon.

**Comment by lihsai0** [comment]
@aurexav Try to use the svg icon mentioned in https://github.com/alacritty/alacritty/issues/3926#issuecomment-728228991

**Comment by Owisky** [comment]
this is the best design for alacritty
