### ISSUE TITLE
Backspace and CTRL+L do not work over SSH

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [alacritty/alacritty#3932]
When SSHing into another machine using alacritty, backspace and the `ctrl+l` shortcut no longer work as expected. It seems like moving the cursor position doesn't work?

I've created 2 asciinemas for xfce4-terminal and Alacritty that show backspace and `ctrl+l` usage on a normal shell and over SSH:
- [xfce4-terminal](https://asciinema.org/a/xnUv7D1FeLtC4O5F75Znz5ihx)
- [Alacritty](https://asciinema.org/a/uUiC4JRnBgb1eR7FQnff5Ce37)

### System

OS: Manjaro Xfce
Version: both v0.4.3 and current master (65bff1878ff68698da021b4d5aa00d1cfad41d0a)
Linux/BSD: X11, Xfwm
Using Zsh on both machines, OpenSSH 8.3p1 and 7.9p1.

Not sure if related, but I can also not open tmux over SSH, it gives the error `open terminal failed: missing or unsuitable terminal: alacritty`. It does work locally and with xfce4-terminal.

**Comment by HoLLy-HaCKeR** [comment]
I did some testing and it seems this got introduced in v0.2.1. v0.2.0 did work.

**Comment by chrisduerr** [comment]
> Not sure if related, but I can also not open tmux over SSH, it gives the error open terminal failed: missing or unsuitable terminal: alacritty. It does work locally and with xfce4-terminal.

Please install the terminfo of Alacritty on the remote machine.

**Comment by o0-o** [comment]
Is this the long-term solution for ssh and ssh/tmux functionality? If someone is sshing into dozens of different servers on a daily basis, this makes Alacritty unsuitable (which is a shame because of how great it is otherwise).

**Comment by chrisduerr** [comment]
One can always change the `TERM` or copy it over automatically.

**Comment by o0-o** [comment]
> One can always change the `TERM` or copy it over automatically.

Curious how you would copy it over automatically and if this would solve both ssh and tmux issues. A manual `export TERM` on every ssh session would quickly erase all of the time saved from using a well-optimized terminal emulator.

**Comment by chrisduerr** [comment]
> A manual export TERM on every ssh session would quickly erase all of the time saved from using a well-optimized terminal emulator.

I mean you can always just alias ssh to `TERM=xterm-256color ssh`, which is what I do. Though I cannot recommend it because most people are probably not aware of the issues they might run into. But if you access a lot of systems, especially systems where you do not have control over so just copying files there is not an option, that is your only choice.

I don't have the command around that copies it automatically and then SSHes into the system, but that might be a good option if you regularly ssh into the same systems where you only have user and not admin rights. It should be relatively easy to find online or write yourself though.

**Comment by hsanjuan** [comment]
> Though I cannot recommend it because most people are probably not aware of the issues they might run into

Can you make us aware of issues we might run into? 

I have set:

```
env:
  TERM: xterm-256color
```

which might also not be the right way to tackle this.

**Comment by chrisduerr** [comment]
> Can you make us aware of issues we might run into?

Some features will not work, which does not just include things not working at all, but could also mean that things break in "interesting" ways depending on the terminfo you use.

One example would be control + clicking in an application for example, using `xterm-256color` will break that. The thing is that most users probably won't be able to tell what the reason for an issue is, thus not knowing that they should switch their terminfo to fix it. Which is why you must test with `alacritty` terminfo before reporting bugs.

**Comment by flowthentic** [comment]
I had the same issue with one vps provider, all other ssh sessions work OK.
I set the TERM env for specific host in ~/.ssh/config

```
Host name
    Hostname example.com
    SetEnv TERM=xterm-256color
```
