### ISSUE TITLE
Install instructions in Readme for Mac are incorrect.

### ISSUE THREAD

**Issue by AXington** [alacritty/alacritty#3934]
In the Readme it states:

```Once the cask is installed, it is recommended to setup the manual page, shell completions, and terminfo definitions. These are located inside the installed application's Resources directory: Alacritty.app/Contents/Resources.```

However I don't think they're in there:

> ls /Applications/Alacritty.app/Contents/Resources
> alacritty.icns
>

**Comment by kchibisov** [comment]
If cask is still behind it's not our problem.

**Comment by leosolid** [comment]
The cask is up to date but there is nothing in the folder. Are the instructions outdated?

**Comment by AXington** [comment]
There's nothing in that directory in the main branch of the repo either.
Also kind of really annoyed with the rude dismissal. Very poor form.

**Comment by chrisduerr** [comment]
> The cask is up to date but there is nothing in the folder. Are the instructions outdated?

That's because the changes weren't included in any release yet. The instructions aren't outdated, they're too up to date. If you're looking for instructions related to the latest release, you should check out the tag for the latest release. We always make sure to tag every release partially because of this exact thing. Master branch tracks **development**, not stable.

> Also kind of really annoyed with the rude dismissal. Very poor form.

Instead of getting outraged by a purely factual statement, it seems far more productive to let people spend their time actually working on Alacritty instead of having to respond to pointless support requests. Don't get me wrong, everyone can make the mistake of accidentally reading documentation for master and not the latest release, but responding with accusations against maintainers isn't really the best way to express that you're sorry for causing pointless support overhead.

**Comment by leosolid** [comment]
Thanks for clarifying. I automatically assumed master was the stable branch.
