### ISSUE TITLE
Is it possible to reference environment variables in the YAML configuration?

### ISSUE THREAD

**Issue by synek** [alacritty/alacritty#3943]
Hi folks,

I'm wondering if it's possible to reference an environment variable in my `alacritty.yml` file. Like so:

```
font:
    size: ${FONT_SIZE}
```

**Comment by kchibisov** [comment]
no. And it's not something that we'd like to support.

**Comment by synek** [comment]
Do you have any advice on dynamically setting some configuration options in Alacritty?

Specifically, I have an external monitor which is a lower resolution than my laptop's screen so I would like to set the font size differently when the external monitor is plugged in. Currently I run something like `export FONT_SIZE=12` in my `.xinitrc` to store the desired font size in an environment variable, and I was hoping to use that to configure Alacritty dynamically on X startup.

Any thoughts on how I can achieve something like this? I don't want to manually change my `alacritty.yaml` every time I plug in my external monitor.

**Comment by chrisduerr** [comment]
You could obviously just `sed` the `alacritty.yml` to replace things with the values you're looking for, but what you're talking about sounds a lot like DPI scaling. Alacritty should support DPI scaling by default, assuming you do not set the `WINIT_X11_SCALE_FACTOR=1` variable.

**Comment by synek** [comment]
Thanks @chrisduerr I'll look into that. This is my first time dealing with a mixed DPI set up, so if you have any links available to help guide me I'd appreciate it. Currently working with the Arch Wiki and slowly figuring out DPI scaling in X.

**Comment by chrisduerr** [comment]
Alacritty should automatically scale things, unfortunately GTK has no support for that an QT requires an environment variable.

In theory you could use `WINIT_X11_SCALE_FACTOR` as a variable if you wanted to scale font size based on an environment variable, since that changes the DPI for Alacritty.

**Comment by nixpulvis** [comment]
Follow-up in #4157

**Comment by unphased** [comment]
I'm reviewing this aspect of alacritty config and searching landed me here first. I currently maintain two alacritty configurations, one for linux and one for alacritty. This was already highly untenable, but I kept up with it for probably almost 10 years, because I do have a large discrepancy between necessary key binding overrides on Linux and macOS. At the moment I started regularly using two different linux boxes with different sets of fonts installed, and clearly creating a third config file at this point would be completely absurd.  I also wanted to finally establish a new dimension to terminal customization by assigning a distinct bgcolor to terminal windows based on the specific environment they are running on, in hopes to reduce confusion. I'm just too impatient to carefully scan the hostname in the shell prompt before slapping my enter key in a shell, and I decided I'm going to go for broke on this, so, i'm going beyond merely making the shell prompt different and attempting to go all the way over to controlling terminal window bgcolor. As such, to consistently support bgcolor control even on plain non-tmux'd terminals, I need integration at the terminal emulator level!

As a note to myself and posterity, I will summarize what I learned today regarding alacritty's config management: some welcome improvements compared to back when I started with alacritty a decade ago. Site note: A big thanks! to the project maintainers! for preserving Alacritty's seat on the performance throne!

- Specifying additional alacritty config files is supported via `import` 
- Simple expansion of `~` with `$HOME` seems to be implemented for those imports
- imports are also optional, i.e. missing import config files will not produce an error

This means that even though alacritty config does not enable arbitrary shell env expansion, the main expansion I would want, `~`, should work, and I will be able to break config down into a main file and a few machine specific short import config files, and this will allow for easy machine-specific possibly-git-untracked files. 

That seems to give me everything I want. I came here looking for env var expansion to bring environment specific settings, and I learned alacritty will not have env var expansion, but, it's not a problem because I can do environment specific settings in alacritty config imports instead of using env vars for it. Slightly off the beaten path but it's still a clear path forward.
