### ISSUE TITLE
vi mode

### ISSUE THREAD

**Issue by stokhos** [alacritty/alacritty#3976]
I noticed that alacritty .yml has something about vi mode. But I couldn't find anything about how to turn on vi mode in alacritty. How can I turn it on?

Best Stokhos

**Comment by kchibisov** [comment]
You should use the latest master and the default binding to enter it is `Ctrl + Shift + Space`. You can read all the default bindings it has in a config https://github.com/alacritty/alacritty/blob/e18f5a0a2fbe5b8801dc7d5a402f6a7af1d97d12/alacritty.yml#L598.

**Comment by stokhos** [comment]
Thanks @kchibisov 
Is there a way to open alacritty in vi mode by default?

**Comment by kchibisov** [comment]
That's the mode you trigger on demand to copy stuff, there's no need to start in it, since it's not like vim, you can't move insertion point, nothing special, just select stuff, search, and open urls.

So, there's no way to start in that mode right away, and there's no reason to add an option to start in vi mode, since it doesn't provide any value.

**Comment by j-i-l** [comment]
A note for people who are looking for an alternative to bash's vi-style line editing interface:

Alacritty's vi mode has another purpose entirely, it serves to browse content in the terminal window.

You can use bash's vi mode just like that in alacritty, simply type `set -o vi` (or better add it to your `.bashrc` file).
