### ISSUE TITLE
SearchForward in Vi mode always searches from the top of the buffer

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3985]
In general it should start searching from the start of the viewport, like `SearchForwards` started from normal mode.

**Comment by chrisduerr** [comment]
> In general it should start searching from the start of the viewport

No it shouldn't? The only reason why `SearchForwards` started from normal mode does this is because there's no vi cursor available as origin?

Also your issue title and description are confusing. In the description it sounds like we already search from the top, but your description says that you *want* that?

Either way, this is a feature not a bug, so I don't quite understand what you mean here.

**Comment by kchibisov** [comment]
Hm, I guess you're right and we just follow vim here starting from the top of the buffer, if there's nothing below origin. My point is that normal search starts from the top of the viewport, however if you just enter Vi mode and toggle search right away it'll start from that origin, and so the search will be from the top of the buffer(not viewport).
