### ISSUE TITLE
Latest alacritty broke Neovim's icons

### ISSUE THREAD

**Issue by ms747** [alacritty/alacritty#3988]
### System
OS: Linux ( Linux Mint 19.3 )
Version: 0.4.3
Linux/BSD: i3wm with X11

### Logs
No Crashes

On Alacritty 0.4.3
![Fri Jul 17 12:32:03 IST 2020](https://user-images.githubusercontent.com/20738789/87758637-711b0800-c82a-11ea-9604-8015839cbc71.png)

Works fine on other terminal emulators
![Fri Jul 17 12:35:22 IST 2020](https://user-images.githubusercontent.com/20738789/87758683-8a23b900-c82a-11ea-89b9-ec77de68cb2a.png)

**Comment by kchibisov** [comment]
You have a pixelsize set somewhere for your emoji font, so Fontconfig tells us to use that big size, nothing we can do about it. However the thing you can do is to find who is setting `pixelsize` for `Noto Color Emoji` and prevent it from doing so, since it doesn't make any sense

Look for that in `/etc/fonts/conf.d` or in your fontconfig files.
