### ISSUE TITLE
Sending ANSI Escape Code "clear" does not work 

### ISSUE THREAD

**Issue by jtheoof** [alacritty/alacritty#3997]
I am trying to configure a new keybinding (`Ctrl+k`) to send a clear sequence to alacritty, I have tried:

```
  - { key: K,          mods: Control, chars: "\e[H\e[2J",     mode: ~Alt       }
or
  - { key: K,          mods: Control, chars: "\x1b[2J",       mode: ~Alt       }
```

and a few other variants, but none of them seem to work.

However I simply: `echo '\e[H\e[2J'`, then the terminal is cleared. 

What is even weirder is that the chars seem to be sent to the terminal:

```
> showkey -a

Press any keys - Ctrl-D will terminate this program

^[[H^[[2J 	 27 0033 0x1b
 	 91 0133 0x5b
 	 72 0110 0x48
 	 27 0033 0x1b
 	 91 0133 0x5b
 	 50 0062 0x32
 	 74 0112 0x4a
```

### System

OS: Linux
Version: alacritty 0.4.3
Linux/BSD: Wayland with Sway sway version v1.5-rc2-1d149230 (Jul  5 2020, branch 'master')

### Logs

No Crash
See the `showkey` logs

I have looked at #1047 but none of the suggestions have worked for me (running Arch Linux).

I could use the default `ClearLogNotice` binding (`Ctrl+l`) but it has limitations. For example it doesn't work when piping `tree / | more`, or when logging: `journalctl -b -f`.

My research before posting this:

- [Alacritty Docs](https://github.com/alacritty/alacritty/tree/master/docs)
- [Stack Overflow](https://stackoverflow.com/questions/37774983/clearing-the-screen-by-printing-a-character)
- [vt100](https://invisible-island.net/ncurses/terminfo.src.html#tic-vt100)

**Comment by kchibisov** [comment]
ofc it doesn't work, because you're just doing the same as typing it into the shell, and it's not how it's supposed to do, since you're sending it from alacritty, and trying alacritty to parse, what it send to itself. So, someone else should send those characters, but in general, don't do that, since your pager, etc should handle that.

The default binding works, because it sends a special char, in which it gets a reaction from your shell, and clears the screen. `ClearLogNotice` is a binding to hide message bar, which we just have it on `ctrl + l` for convenience. The actual binding  that triggers clearing is `- { key: L,        mods: Control, chars: "\x0c"                            }`

**Comment by jtheoof** [comment]
Sorry, I misunderstood how the `chars` worked.

Is there any way to have Alacritty clear the terminal, independent of during pipe, or tailing, ... ? (The same way iTerm2 behaves when you hit `Command+k`)

> So, someone else should send those characters, but in general, don't do that, since your pager, etc should handle that.

Could you describe this part a little more? How do I make `more`, `journalctl`, ... handle that?

**Comment by chrisduerr** [comment]
> Is there any way to have Alacritty clear the terminal, independent of during pipe, or tailing, ... ?

I'm not sure what you mean by that, but no, you cannot do anything that ^L can't do.

**Comment by kchibisov** [comment]
IIRC iterm just clears the history on cmd + k, do you want https://github.com/alacritty/alacritty/blob/f0cb1e7cf329f2672fe1335208c9a78562d8ab73/alacritty.yml#L499 ?

**Comment by jtheoof** [comment]
My use case is quite simple:

```
sudo journalctl -b -f
```

A bunch of logs appear. I want to clear the terminal (and the logs displayed) at that point (using `gnome-terminal` I could simply do `Ctrl+k` which I think clears and resets the terminal output and scrollback). 

Is there any way to do that with Alacritty?

**Comment by jtheoof** [comment]
I understand that my original issue was misleading but I still feel like Alacritty is missing a true "Reset and Clear" experience. What do you think @kchibisov @chrisduerr, should I open a separate issue? Am I completely off-track?

**Comment by chrisduerr** [comment]
> Am I completely off-track?

Based on your descriptions, I'm inclined to say you are completely off track. Just throwing away the current visible grid of an application doesn't make much sense to me.

**Comment by kchibisov** [comment]
I guess to understand your issue more we should try it in the terminal you've mentioned, but if you want a `reset`, but via bindnig, it's not a good idea, since you obscure active terminal content.

With `Ctrl + L` you just ask shell to do so, meaning it's aware of what happened. With `ClearHistory` shell and other applications are not aware about history at all, and the history is managed by us, so we can safely delete the history.

IIRC iterm's `Command + K` is just our `ClearHistory`.

Everything else that doesn't manage things alacritty has full control over and other application don't know about, or things like `ctrl + l`, where you send things to shell(though, those things are handled automatically and requires nothing from us, other than supporting proper escapes...)

**Comment by jtheoof** [comment]
You can find below how `gnome-terminal` handles `Ctrl+k` for `Reset and Clear` (this is the same for iTerm)
![wf-recorder-Sun 19 Jul 2020 08:15:14 PM EDT](https://user-images.githubusercontent.com/90020/87888777-c9a1ff00-c9fc-11ea-81cc-50600591f61d.gif)

As you can see it's quite different from `ClearHistory`, it clears the whole terminal no matter the command being run.

**Comment by chrisduerr** [comment]
Yeah I don't see why we would support this.

**Comment by jtheoof** [comment]
Care to elaborate why? I'd understand to be low priority but it's still a major feature from other terminals.

I would see it as a new action: `ResetAndClear` or something like that. Would you be open to a PR at least?

**Comment by chrisduerr** [comment]
> it's still a major feature from other terminals

I don't see how it is a "major feature" given that it has never been brought up before and I didn't even know about it.

> Care to elaborate why?

Sure. Clearing while you're currently in the process of running a command will put you into an invalid state. The application has no clean way to recover from that. This might lead to partial rendering and other ugly side effects. Meanwhile clearing through the application itself or through the shell will always work perfectly, since that's kinda how this whole system was designed.

Based on the name of this feature in the gif you've linked, I'd assume the intention to be error recovery. Using escapes like `echo -e "\e(0"` you can set yourself into modes that not a lot of people know how to escape from and since most of the target audience of gnome probably isn't aware of alternatives, having a GUI for that makes sense.

**Comment by jtheoof** [comment]
> The application has no clean way to recover from that.

If you're doing this inside of `vim` then definitely, the application is in a weird state. `vim` has `Ctrl+l` to refresh its ui but not all applications have that. So I agree with you there.

But the main use case is for log parsing or tails or anything that doesn't care about the current state of its UI. I would assume that it's the responsibility of the user to know what they are doing. Personally, I use this when showing some logs, then clearing the terminal before I do an action that will trigger the logs that I am really interested in.

It's not a killer feature, but definitely something I miss with Alacritty.

If you're open to it, I could rename this issue into something more meaningful and work on this myself, but it sounds like you don't see the value of this at all. 

In any case, I really like this terminal emulator, thanks for maintaining it!

**Comment by markwellis** [comment]
This is something I was looking for too. It may be a strange thing to have, but it is something most other terminal emulators have and is something I have grown used to.

Namely, clearing the output of a long command in the middle of it, so I can keep only the interesting things in my scrollback buffer

**Comment by nixpulvis** [comment]
I do wonder if the default `alacritty.yml` documentation could be a bit more clear.

https://github.com/alacritty/alacritty/blob/ee2c5a6cdd6a07f18b99a50b9d2737bd8ea391c4/alacritty.yml#L481-L486

Unless I'm not labeling things correctly in my head right now, I think it may be enough to change "escape sequences" to "escape codes" here, since I can see how one might think you can directly trigger an ANSI escape sequence from `chars`.

**Comment by jtheoof** [comment]
In case other users are interested in the conversation, I updated the title (I see it's starting to be duplicated, eg: #4199). Hopefully if enough users are interested, it could change the devs' mind.

**Comment by avindra** [comment]
Are we reopening this issue or continuing the discussion elsewhere?

I'll add: using escape sequence hacks like `echo -e "\ec" > /dev/pts/<N>` is _not_ a useable alternative,  because those cannot be used while a command is running.

Compare this to terminal emulators that implement "clearing everything" so to speak... you can use it at any time (if you are running `htop` or `yes`, for example).

**Comment by chrisduerr** [comment]
> I'll add: using escape sequence hacks like echo -e "\ec" > /dev/pts/<N> is not a useable alternative, because those cannot be used while a command is running.

That is incorrect.

**Comment by avindra** [comment]
> That is incorrect.

I'll clarify: you can technically execute the command _somewhere else_ and it will work.

As it stands, I don't see a possibility for using this feature from a single terminal window.

**Comment by avindra** [comment]
Ok I took a crack at information gathering and created a doc with some solutions for external script:

https://github.com/alacritty/alacritty/wiki/Reset-Terminal

**Comment by chrisduerr** [comment]
@avindra I appreciate the effort, but I do not think it is a good idea to document this in the Alacritty wiki. This is not something I'd recommend anyone to do so I do not wish to encourage people to look into it. If someone has the need for it, figuring it out should be trivial.

**Comment by markwellis** [comment]
I still don't get why you're against this. I count 8 people asking for it, and 2 PRs implementing it. It's the reason I stopped using alacritty.

As has been pointed out many times, it's on pretty much every other terminal emulator out there, and it's something you'd have to actively opt into. 🤷‍♂️

**Comment by avindra** [comment]
@chrisduerr  What you might consider destructive to the applications is indeed used by many (for example the `tail -f`-type log users out here) on a routine basis. Further, emulators (in general) _can add_ features that make it possible to go beyond what the original thing was built for.

Alacritty has support for 24-bit colors for example, which might be considered "outlandish" by some. It just isn't totally clear where line(s) are in terms of what is being emulated.

I made that contribution in good faith, so if anyone else wants to see how to configure Alacritty to reset, you can have a look here:

https://gist.github.com/avindra/dd2c6f14ec6e03b05261d370ef60c9d8

**Comment by avindra** [comment]
It _should_ be trivial to send the escape code via `chars:` in the keybinding itself, but that doesn't work. Having to create a shell script means that this is _not_ trivial.

Doing this for rxvt-unicode is as easy as `URxvt.keysym.C-k: command:\033c`. It seems like a bug to me that it doesn't work in alacritty, or maybe it's due to limitations with the current implementation.

**Comment by chrisduerr** [comment]
> It should be trivial to send the escape code via chars: in the keybinding itself, but that doesn't work.

It can't work, you're talking about two different sides of the PTY here. Sending something to the shell by writing from the terminal will not write *to* the terminal. What you want is writing *to* the terminal, not *from* it.

**Comment by avindra** [comment]
> Sending something to the shell by writing from the terminal will not write to the terminal. What you want is writing to the terminal, not from it.

Ok. The clearing code tends to work out of the box in other emulators, so I guess Alacritty is doing something differently. I am not too familiar with the internals of PTY or the original terminal interfaces, so I can't say for sure what is the "correct" behavior here.

In any case, the [workaround](https://gist.github.com/avindra/dd2c6f14ec6e03b05261d370ef60c9d8) is fine for now.

**Comment by alxtz** [comment]
In my opinion, CMD+K to both clear the console and reset scrolling is almost a universal UX now, even in chrome/firefox's browser devtool console they implement this as well.

It's just inconsistent for users on why alacritty behaves like this.

**Comment by chrisduerr** [comment]
A browser console has nothing to do with a terminal.

**Comment by nixpulvis** [comment]
> CMD+K to both clear the console and reset scrolling is almost a universal UX now

As much as I see where you are coming from, this is simply false. No other terminal on my system has this binding by default, and I'm not even sure it's possible to add. @alxtz you have to remember, we're a multi-platform terminal emulator (with a main focus on Linux). While I might personally argue that we should find a way to allow users to create this binding for themselves, I would not necessarily expect it either.

> A browser console has nothing to do with a terminal.

I wouldn't go _quite_ that far. :wink:

**Comment by vmiheer** [comment]
If the command is hung, should the solution be just kill the alacritty and start new process?

**Comment by chrisduerr** [comment]
This issue is completely unrelated to that scenario. But if you execute a command in your shell and it hangs, you should be able to terminate it or put it in the background, worst case kill it.

If your shell is hung up, it's a goner anyways. No matter of resetting will help you with that.

**Comment by vmiheer** [comment]
Here's the scenario: My computer wakes up from sleep and the terminal is not usable because it was used to ssh.
I am not sure what hangs up but with gnome terminal, "reset and clear" fixes this. Now you maybe right maybe I could find out what hung, try to send it SIGKILL signal but it's much simpler to just reset+clear and move on. Same with some rogue terminal app messing up terminal state or human mistake of echoing binary file to terminal.

**Comment by nixpulvis** [comment]
@vmiheer is reset and clear is fixing a hanging process something is very strange with your running programs / shell. I would look at your configuration or environment for the issue in that case.

**Comment by vmiheer** [comment]
I'll try to debug next time this happens.

**Comment by 354651432** [comment]
```
{ key:L,mods: Control|shift, chars:"printf \"\\033c\"\n" }
```
it works on my bash

**Comment by artslob** [comment]
`chars: "printf \"\\033c\"\n"` works only when there is no other input to bash. Also it does not work while some long command is running.

**Comment by darkHat07** [comment]
The native Terminal.app implements the shortcut Cmd+K as something they call "Clear to Start" which does the same thing described by @jtheoof. It doesn't create any complications as far as I know.

**Comment by insilications** [comment]
[Follow this gist](https://gist.github.com/avindra/dd2c6f14ec6e03b05261d370ef60c9d8). If you want to avoid hitting enter, do the following. Setup everything according to the gist, but add a key binding action to the same key that sends a byte sequence to the running application using `chars`. According to the docs: 

`If the same trigger is assigned to multiple actions, all of them are executed in the order they were defined in.`

So:

```
- { key: K,  mods: Ctrl,  command: path/to/reset-alacritty } 
- { key: K,  mods: Ctrl,  chars: "\x0d" } 
```

This will send/press enter right after the reset-alacritty command.

**Comment by mgutz** [comment]
This a quality of life thing. I often look at logs in real time, where hundreds of messages may occur in a second. Without a clear-reset function as implemented in Gnome, iTerm2 and XFCE terminal, it's hard to know which lines are new after I initiated an action on the  app logging to the file.

Most use clear-reset when looking at simple stdio line output, not when using a TUI.

**Comment by kchibisov** [comment]
`ctrl + z` and then `clear`.

**Comment by insilications** [comment]
Following my [reply](https://github.com/alacritty/alacritty/issues/3997#issuecomment-1682070519) on Aug 17,  I've tried using the [Kitty](https://github.com/kovidgoyal/kitty) terminal. It supports ResetAndClear with the configuration `map keys clear_terminal to_cursor active` and is as fast as Alacritty. Give it a try to see if you like it.

**Comment by negativems** [comment]
I am still waiting a support of Alacritty to do this through the config without using an script

**Comment by AXGKl** [comment]
> This a quality of life thing. 

It's not quality of life imho. It's a total **must have** - for anybody who has to debug stuff using application logs, seriously. Especially on big screens ClearHistory totally does not cut it, when the screen is not cleared. 

Thanks god [this](https://gist.github.com/avindra/dd2c6f14ec6e03b05261d370ef60c9d8) guy found a hack to do it, otherwise I would be off to kitty, it's a showstopper.
