### ISSUE TITLE
Alacritty not rendering properly when opened from file manager.

### ISSUE THREAD

**Issue by nemya9066** [alacritty/alacritty#4015]
Hello everyone if I open a file from my file manager(I have it set to use vim) It open in a weird state and I need to restart or resize my wm for it to render properly here is a screenshot
![bad](https://user-images.githubusercontent.com/51141144/88155521-16a1f300-cc00-11ea-987b-d927c6ff49cc.png)
I have tried other terminals to see if they have the same issue and some do some don't gnome-terminal for example do  but st doesn't however I'm pretty happy using alacritty and don't want to switch.
My nvim.desktop file start with this command 'alacritty -e nvim' I tried opening a vim instance this way from my terminal and the same issue occurs.

### System
System: Linux X11, qtile wm, picom

**Comment by chrisduerr** [comment]
Neovim has problems with the window getting resized during its initialization, so it's a bit particular about that. But you can just delay Neovim's startup by a little bit and that should do the job. Something like `alacritty -e sh -c sleep .1; neovim`.

**Comment by nemya9066** [comment]
Yeah this seems to have done it thanks a lot for your help :)

**Comment by Tenyun** [comment]
The command `alacritty -e sh -c sleep .1; nvim` does not work as expected because the command uses a new subshell after the `;` which does not belong to the newly opened alacritty instance. (Not sure if this is really the case)

If you run the command in a terminal neovim will open in the same terminal window where you entered the command. But it should be opened in a new terminal. 

The problem is if you call e.g. `alacritty -e sh -c sleep 0.1; nvim -c VimwikiIndex` from the wm (dwm keyboard-shortcut) nvim will not be opened at all because there is no longer an open alacritty terminal from which to call nvim.

And if you open a terminal application from within newsboat (e.g. `tsp alacritty --title mpsyt -e sh -c sleep .1; mpsyt playurl %u`) you block the newsboat terminal until mpsyt is closed.
