### ISSUE TITLE
can't scroll the screen while copying the contents

### ISSUE THREAD

**Issue by rustiever** [alacritty/alacritty#4028]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: macOS
Version: alacritty 0.4.3 (c723247)

**Comment by chrisduerr** [comment]
Yes you can.

**Comment by kchibisov** [comment]
try latest rc version, since on `0.4.3` there's no autoscroll if that's what you want. If you want to just use mouse wheel, you can do it right now.

**Comment by rustiever** [comment]
when i want to copy the contents in terminal i cant scroll the window through mouse 
for example when i want to copy the long output of cat command i couldn't scroll the window through mouse, if i press arrow key it goes to max extent

**Comment by kchibisov** [comment]
>when i want to copy the contents in terminal i cant scroll the window through mouse
for example when i want to copy the long output of cat command i couldn't scroll the window through mouse, if i press arrow key it goes to max extent

And you were told that it's fixed in latest rc version, so if you move mouse cursor to the top of viewport it'll start auto-scrolling. if it doesn't auto-scroll for view it's some other issue, IIRC if you move mouse outside of the window on macOS it won't do anything now.
