### ISSUE TITLE
Question: How to disable search keybind

### ISSUE THREAD

**Issue by amiralies** [alacritty/alacritty#4090]
is this possible to disable search keybind? I've got `Ctrl+Shift+f` Keybind in vim

**Comment by chrisduerr** [comment]
> I've got Ctrl+Shift+f Keybind in vim

You can't bind to ctrl+shift+f in vim. But the default configuration file documents how bindings can be disabled.

**Comment by amiralies** [comment]
Thank you
```yaml
 65 key_bindings:
 66 ··- { key: F, mods: Control|Shift, action: ReceiveChar }

**Comment by kchibisov** [comment]
@amiralies could you try pressing `ctrl + f` in vim, it should also work, right?

**Comment by amiralies** [comment]
@kchibisov yes, you're right

**Comment by kchibisov** [comment]
yeah, since as we mentioned `ctrl + f`, and `ctrl + shift + f` are the same bindings in terminal. So you don't need to unbind search, just press less keys in vim.

**Comment by filipiz** [comment]
Not a good idea.. ctrl + f in vim = page down.

**Comment by ckcr4lyf** [comment]
In neovim at least, this doesn't work, since it will first detect `Ctrl-F` and apply and shortcut related to that (Default being page down).

Instead you can change alacritty to send the complete modifier:

```
key_bindings:
  - { key: F, mods: Control|Shift, chars: "\x1b[70;5u" }
```

Thanks to https://www.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/
