### ISSUE TITLE
Message bar text unreadable

### ISSUE THREAD

**Issue by zsugabubus** [alacritty/alacritty#4116]
Message bar has harcoded yellow or red background but foreground color is from `colors.primary.background`. It is easy to see that it cannot work both with light or dark themes.

I think either message bar’s background color could be get from `colors.normal.{yellow,red}` or use also hardcoded (black) foreground color for messages.

### System

Version: `alacritty 0.5.0`

**Comment by kchibisov** [comment]
It seems like it got accidentally changed during some refactoring. It always was black on yellow/red.

**Comment by chrisduerr** [comment]
> Message bar has harcoded yellow or red background but foreground color is from colors.primary.background. It is easy to see that it cannot work both with light or dark themes.

I don't see how this is the case. Yellow/Red on your primary background should always be readable. Otherwise how are you going to read yellow/red text if you can't read primary background text on yellow/red background?

This was changed, yes. But I don't think it was by accident. Would you mind sharing a screenshot of how this looks for you?

**Comment by kchibisov** [comment]
I don't really like this change as well tbqh. I'd rather use foreground color in my case, since it's a bit more readable. If anything, I'd use foreground color over red/yellow colors from the config, but that's it.

![picture](https://user-images.githubusercontent.com/27620401/90116669-7a7e8e00-dd5e-11ea-92ee-2f68aa0d30e8.png)

**Comment by chrisduerr** [comment]
I think this should be solved by pulling the yellow/red color from the user's theme, to keep things more consistent.
