### ISSUE TITLE
Alacritty is not reading my config 

### ISSUE THREAD

**Issue by supersonic118** [alacritty/alacritty#4126]
I cannot get alacritty to read the alacritty.yml file no matter where I put it. Ive put it in my home folder and in /.config/alacritty/ I have even tried putting it in just /.config/ but nothing works. Any help would be appreciated.

**Comment by chrisduerr** [comment]
Try running `alacritty -v`. That'll tell you here the configuration file is loaded from and if Alacritty is finding that configuration file.

**Comment by supersonic118** [comment]
It just says alacritty: command not found

**Comment by chrisduerr** [comment]
Are you on macOS? If so you'll have to execute Alacritty with the absolute path. It should be somewhere in /Applications/Alacritty.app/macOS/Contents/Alacritty if I remember correctly.

**Comment by supersonic118** [comment]
I'm on Linux mint .
it says Configuration loaded from "/home/user/.config/alacritty/alacritty.yml".
I've changed the foreground and background colors in the alacritty.yml but there is no change.

**Comment by chrisduerr** [comment]
You're on Linux mint but you don't have Alacritty in your $PATH?

Could you share your configuration file?

**Comment by gvfarns** [comment]
I am seeing the same bug on Fedora 32.

```
~> cat ~/.config/alacritty/alacritty.yml
# Configuration for Alacritty, the GPU enhanced terminal emulator.
padding:
  x: 10
  y: 4

~> alacritty -v
Created log file at "/tmp/Alacritty-2112.log"
[2020-09-15 03:54:58.652051106] [INFO] Welcome to Alacritty
[2020-09-15 03:54:58.652157496] [INFO] Configuration loaded from "/home/gvfarns/.config/alacritty/alacritty.yml"
[2020-09-15 03:54:58.725228997] [INFO] Device pixel ratio: 1
[2020-09-15 03:54:58.730813202] [INFO] Initializing glyph cache...
[2020-09-15 03:54:58.752279655] [INFO] ... finished initializing glyph cache in 0.021426153s
[2020-09-15 03:54:58.752313255] [INFO] Cell Size: 9 x 17
[2020-09-15 03:54:58.752320415] [INFO] Padding: 0 x 0
[2020-09-15 03:54:58.752329695] [INFO] Width: 800, Height: 600
[2020-09-15 03:54:58.765163687] [INFO] PTY dimensions: Line(35) x Column(88)
[2020-09-15 03:54:58.769069520] [INFO] Initialisation complete
[2020-09-15 03:54:58.769554218] [INFO] Width: 800, Height: 600
[2020-09-15 03:55:02.128835512] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-2112.log"
~> alacritty --version
alacritty 0.5.0
```

The issue is not confined to padding (that was just something easy to put there that would show up in the output). No matter what I put in that file, it is ignored despite the fact that alacritty says it is using it for configuration.

**Comment by chrisduerr** [comment]
@gvfarns That's not a correct padding configuration.

**Comment by kchibisov** [comment]
@gvfarns it's
```yaml
window:
  padding:
    x: 10
    y: 4

```

**Comment by gvfarns** [comment]
Thanks kchibisov. Darn user error. I suspect the silent ignoring of misformatted configuration may be at the root of the original submitter's issue as well. Perhaps alacritty should print a warning somewhere when this happens? At the very least, a warning in the `-v` output?

**Comment by kchibisov** [comment]
we have https://github.com/alacritty/alacritty/issues/3467 to track that.

**Comment by chromer030** [comment]
same here on arch linux , "No matter what I put in that file, it is ignored despite the fact that alacritty says it is using it for configuration."

**Comment by chrisduerr** [comment]
This is likely a system configuration issue, since the author has not responded, it makes no sense to keep this issue open any longer.

**Comment by sanjeethBettatti** [comment]
Uncomment both the heading of the section and the specific option.
For example, to set the fontsize
font:
  size: 13
note you have to uncomment both the lines and look for the exact spaces from the beginning
font:                 without any spaces
  size: 13          with two spaces from the beginning.

**Comment by djackreuter** [comment]
It needs to be a dot file.  e.g., `.alacritty.yml` not `alacritty.yml`
That worked for me at least

**Comment by mickmacamhlaoibh** [comment]
I was having the exact same problem. Alacritty was definitely reading my config file ~/.alacritty.yml. I knew that for sure because if I messed up the config file, Alacritty would complain. However, what got me was if I uncommented a line beginning with say decorations, opacity, history, etc. and deleted the spaces so that these settings began at the start of the line, then it wouldn't complain but it would not change the decorations, opacity, etc..  

As @sanjeethBettatti said above, all the settings reside within their own group e.g. decorations and opacity reside within the window group, so you have to uncomment window and then uncomment decorations, opacity, etc. but make sure that window is at the very start of the line and decoration. opacity or any other element within the group is indented i.e. starts two spaces from the start of the line.

There is a tiny bug here in Alacritty in that if I uncomment elements within a group and place them at the start of a line without uncommenting the parent, then it really should complain about it just like it complains about any other error. 
![Snippet of my Alacritty config that works](https://user-images.githubusercontent.com/36901164/195959674-03a86574-0aeb-4470-9120-7268161df282.png)

**Comment by devvrat2311** [comment]
I just installed Alacritty 0.12.2 on Pop_os and i have been at it for the last 2 hours but I cannot get alacritty to recognize my alacritty.toml file. I tried putting the file in all the 4 locations that was mentioned in the config part of the README. Also my $XDG_CONFIG_HOME variable doesn't point to anything, but I read that it isn't much of an issue because then it usually points to .config in home. 
![Screenshot from 2023-09-27 00-43-38](https://github.com/alacritty/alacritty/assets/126454043/57dea3e7-319d-49ec-be32-57071675645a)
I at first i thought that my syntax was wrong but even something like shell="/bin/bash" isnt getting recognized because alacritty can not for the love of god locate the toml file. Please HELP

**Comment by kchibisov** [comment]
>I just installed Alacritty 0.12.2 

https://github.com/alacritty/alacritty/#configuration

first paragraph here.

You should use `yml`.

**Comment by marcelo-franceschini** [comment]
![image](https://github.com/user-attachments/assets/9a4ee7bc-920d-4a1b-b45e-316b67aab40c)

wierd

**Comment by c0ff-prvt** [comment]
Dunno if this helps anyone but for me what got my config loading was following: I installed it from the official page where u download the dmg. After uninstalling I installed alacritty again via `brew install alacritty`, then my config was loaded

**Comment by iobuhov** [comment]
Same issue @devvrat2311, solved by creating `.config/alacritty/alacritty.yml`. Seems 0.12.2 still uses yaml
