### ISSUE TITLE
Wayland CSD color enhancements

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#4162]
Since we added a search bar, which is distinct I was wondering about using its colors to color Wayland's client side decorations. After trying with my personal theme it looked pretty good.

![7JJ](https://user-images.githubusercontent.com/27620401/90986538-5441c500-e58c-11ea-831c-b45963df4da4.png)

With default theme it looked a bit worse, but we may change default search bar colors to something darker, but with a good contrast on our default background. That's how it looks with the current search bar.

![picture](https://user-images.githubusercontent.com/27620401/90986550-7cc9bf00-e58c-11ea-9233-37b0969c4bb4.png)

One concern is that folks may want to have borderless like decorations like we have now(if you forget about ugly separator, which we could get rid of in a future with winit update). Well, for that case we can use our `transparent` and `buttonless` options (yes we can even remove buttons if users don't want them to be there).

If anyone is interested in tuning that Wayland theming is done here https://github.com/alacritty/alacritty/blob/master/alacritty/src/wayland_theme.rs .

**Comment by nixpulvis** [comment]
I feel like it's a bit backwards to set CSDs based on the value of `colors.search.bar`, whereas I could see allowing `colors.search.bar` to somehow indicate using a color from the theme.

I think it would make sense to just add a `wayland` (or something) key to colors, which allows overriding all these values at this point TBH.

**Comment by kchibisov** [comment]
>I feel like it's a bit backwards to set CSDs based on the value of colors.search.bar, whereas I could see allowing colors.search.bar to somehow indicate using a color from the theme.

>I think it would make sense to just add a wayland (or something) key to colors, which allows overriding all these values at this point TBH.

No there's no point doing so knowing that we have 2 more styles to express whatever you want.

If you want header to match background of the terminal you can use transparent style.

It's not backwards, it's actually a part of a theme, and it visually looks much better, and have more potential here.

The point is that when coloring was implemented search bar wasn't even a thing, so that's why we went with background colors, however while actively working on GNOME I felt like it's visually awkward that they match the background by default, knowing that you don't have a visual indicator of movable area.

**Comment by nixpulvis** [comment]
I'm looking at the `WaylandTheme` now, and these are the colors which it sets at the moment:

- `primary_color`
- `secondary_color`
- `(close/maximize/minimize)_button_[icon]_color`

My point is that, if these are to be changed, I feel like they should be named accordingly in the config. Then the question becomes, how do we set the search bar to custom colors, either based on these values, or separately.

Implementing transparent/buttonless decoration modes would be good. And they could use a bit of work on macOS as well, since transparent seems to be broken a bit at the moment.

**Comment by kchibisov** [comment]
>My point is that, if these are to be changed, I feel like they should be named accordingly in the config. Then the question becomes, how do we set the search bar to custom colors, either based on these values, or separately. Or do we need a new color to be added in addition?

I don't understand you here, I'm basically saying use https://github.com/alacritty/alacritty/blob/6cfcd7c25930d0478bc35731543e37a2e0c8f13f/alacritty.yml#L228 instead of foreground/background like it's now.

**Comment by chrisduerr** [comment]
The goal is not to allow optimal configuration for each tiny thing, but to provide a better default fallback for a feature that is only barely supported anyways. CSDs suck and I don't think there's much reason to put in a ton of effort to add dedicated configuration options for users of one of the compositors on one of the display servers on one of the operating systems.

At the same time, we want to support things as much as possible of course. So the goal is to make these colors fall back to a nice color that matches the user's theme, without having to add a new configuration option just for Wayland.

The goal was to use something like background colors, since usually users don't want the maximum contrast between window and decorations, but there's simply no colors that we know with certainty will work other than what we have now. Using the bar colors instead should allow some certainty while still making things blend in a little nicer. That said, since our buttons are colored on hover (iirc) and the search bar never has any color, it might actually be a bit problematic.

**Comment by kchibisov** [comment]
>The goal is not to allow optimal configuration for each tiny thing, but to provide a better default fallback for a feature that is only barely supported anyways. CSDs suck and I don't think there's much reason to put in a ton of effort to add dedicated configuration options for users of one of the compositors on one of the display servers on one of the operating systems.

it's not one component, there're lots of such compositors and it's defined in a spec that we should handle csd. I find them kind of nice for certain cases, where you have nothing in your compositor at all or try to offload as much as you can. For `DE` they don't look that great if you have situation like on GNOME when gtk apps are dominating, but for example in anvil it helps a lot to test things, since you know, you can actually move a window due to them(well anvil handles move, but it's naturally started via Wayland protocol). Though it's a bit offtopic, just the idea isn't that bad in general to have them.

>The goal was to use something like background colors, since usually users don't want the maximum contrast between window and decorations, but there's simply no colors that we know with certainty will work other than what we have now. Using the bar colors instead should allow some certainty while still making things blend in a little nicer. That said, since our buttons are colored on hover (iirc) and the search bar never has any color, it might actually be a bit problematic.

I mean colors on hover are not that bad. And if we explicitly mention that CSD colors on Wayland are using search bar colors it'll be fine, honestly. My only point that when there's no contrast between title bar and window it looks kind of out of place.

The idea of using search bar for such things came not out of nowhere, but from gtk, since in libvte terminals it's a popup, which has very similar colors(or the same most of the time) to title bar and the rest of the gtk theme. So if you treat the search itself as a gui element, it kind of made sense for title bar to match it, and it indeed could look much better(as you can see) compared to just using background color.

**Comment by nixpulvis** [comment]
OK, I understand. It just seems very weird to me to have my CSD primary/secondary colors be changed by the value of `colors.search.bar`. And adding a bunch of wayland specific comments to that configuration seems out of place.
