### ISSUE TITLE
Mouse selection during search not working

### ISSUE THREAD

**Issue by baggiokwok** [alacritty/alacritty#4165]
### System

OS: BSD
Version: alacritty 0.5.0
Linux/BSD: X11 with Awesome WM

### To replicate the problem
During action "SearchForward", try to use mouse to select the strings in the same terminal so that it can be pasted into the search box.
But selection isn't working

**Comment by chrisduerr** [comment]
During search it is intentionally not permitted to start a selection, since the active search text is always selected. If you wish to make a selection, you can first leave the search which should keep your viewport in place. If you just want to copy the match itself, there's no requirement to make a selection at all.

If you require more advanced interaction between match and selection, I recommend using the vi mode instead. That will allow you to make a selection with your keyboard and jump between all visible matches.

**Comment by nixpulvis** [comment]
I'm trying to get a complete picture of how selection and search interact, and I can see how this is potentially confusing.

For example, I enter vi-mode (as I always do to search), I then search for something matching more than one location. I now have _many_ selection-like things, and as stated above, I'm unable to select anything with the mouse. At this point I might understand why, since the search highlights look like selections. However, upon pressing enter I am left with the same search highlights, and suddenly I _am_ able to make selections with the mouse.

I should note here that the behavior of search while not in vi-mode is slightly different. When searching for text with the default <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>f</kbd> only the active search match (reached by pressing enter, for example) is left selected.

I find this interaction strange, and limiting, especially given the fact that it operates in two different ways depending on the type of search you're doing (i.e. vi-mode vs normal mode). Since the search matches themselves are not selections, I wouldn't personally expect them to block creating selections.
