### ISSUE TITLE
`https:` missing in link if url contains query parameters with `=`

### ISSUE THREAD

**Issue by klammbueddel** [alacritty/alacritty#4174]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Windows
Version: `alacritty --version` output: 0.5.0 (a6681e3)
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY/ConPTY (see `alacritty -v` output): ConPTY 

If i echo a link like `echo https://example.com?test=foo` it will not open in the browser if clicked, but in the Windows File Explorer. If double clicked, `//example.com?test=foo` will get selected, but `https` is missing in the selection. That might be the reason why it opens in the Explorer instead of the Browser.

The URL breaks with the `=` char. `https://example.com?test` resolves fine.

**Comment by kchibisov** [comment]
>If i echo a link like echo https://example.com?test=foo it will not open in the browser if clicked, but in the Windows File Explorer. 

We use https://github.com/alacritty/alacritty/blob/ee2c5a6cdd6a07f18b99a50b9d2737bd8ea391c4/alacritty.yml#L416 application on windows to process a url. You can change it to whatever you want, e.g. your browser.

>if double clicked, //example.com?test=foo will get selected, but https is missing in the selection.

That's due to https://github.com/alacritty/alacritty/blob/ee2c5a6cdd6a07f18b99a50b9d2737bd8ea391c4/alacritty.yml#L327 rule. if you remove ':' from that it'll work, or you can click on ':'.

**Comment by klammbueddel** [comment]
Thank you for your help. Both tips did work!
