### ISSUE TITLE
Support Key Binding Actions in Search Mode

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#4176]
The ability to bind actions like `Paste` while using the new search functionality would allow common workflows people expect. This also opens up the doors for more customization, allowing users to stay in search mode while performing other actions.

**Comment by chrisduerr** [comment]
Pasting *to* the search bar is one thing, though I'd be very curious how this should behave in general. If `chars` are sent, are those forwarded to search instead of the terminal? Even if it's escape sequences? Are all actions allowed or do some make no sense (should I be able to clear the history I'm currently searching?).

Also during search the vi mode is likely activated, so how should that work? Are all vi mode bindings automatically going to be active? Then you can't type a lot of characters since they're mapped in vi mode. Are some bindings allowed and others are not? Potentially we'd have to change all bindings and set `ViMode|~Search` for all of them, assuming that `Search` is introduced as mode.

These are some of the problems I can remember why I didn't introduce a `Search` mode in the initial PR for search. However there's a good chance I've forgotten about some significant ones, so it might get a bit complicated wrt the behavior we want to see and the configuration we'd like.

**Comment by seperman** [comment]
Hello, any updates on this? Is it not that you can do `CTRL` +  `R+` in vim to paste in the search bar? That includes pasting special characters too, no?

**Comment by brianjcj** [comment]
vim and tmux all support paste text to search prompt bar, for your reference.

**Comment by brianjcj** [comment]
> vim and tmux all support paste text to search prompt bar, for your reference.

I have created a pull request for this. https://github.com/alacritty/alacritty/pull/4524

**Comment by chrisduerr** [comment]
This has been implemented a while ago.

**Comment by tuanbass** [comment]
> This has been implemented a while ago.

Thanks for the implementation. It's really helpful.
But it's seemed still have a small flaw. 
It works if you go directly to Search mode (Ctrl-Shift-F) from Normal mode. 
But if you go to vi mode first (Ctrl-Shift-Space) then go to Search mode (either use '/' or C-S-F), still cannot paste into search bar. 
Is it intentional to behave like this? 

Thanks,
