### ISSUE TITLE
The contents in less pager not appear from the top of the screen

### ISSUE THREAD

**Issue by yanzhang0219** [alacritty/alacritty#4209]
macOS: 10.15.6
alacritty: the latest mster, 0.6.0-dev (1bf40a8)

When I open less pager via like `git diff`, the contents appear in the middle of the screen, i.e., not from the beginning of the screen. Btw, I have this setting in my zshrc: `export LESS="-R -P ?f%f  .[%lt-%lb]?L/%L. ?pB%pB\% .(press h for help or q for quit)"`

If the terminal is empty, it works normally.
![image](https://user-images.githubusercontent.com/11582667/92357318-80853780-f09c-11ea-98fe-7170ccf6ea15.png)

However, if the terminal window already has something in it, the contents in less pager are shown in the middle.
![image](https://user-images.githubusercontent.com/11582667/92357342-8c70f980-f09c-11ea-8e9a-7c8d2faef4e9.png)

I have tested this in other terminals like iTerm2 and kitty, and both of them do not have this issue. 

Thank you very much.

**Comment by kchibisov** [comment]
it's not a bug, it's a difference in behavior. Some other terminals on Linux also do the same thing as we do, e.g. all libvte based, like gnome-terminal.

It happens because kitty and iterm set cursor position to the first line when you enter alt-screen, but we use the position the cursor was on. Less doesn't set position to a first line as well, so it means that behavior is intended from less.

**Comment by yanzhang0219** [comment]
wow, cool!. Thank you for your answer. It is possible for me to config this behavior, i.e., to config the position of the cursor when entering alt-screen? Thanks.

**Comment by kchibisov** [comment]
Well, you can try to pass `-c` to less. If you don't want tildes in the end try `less -c --tilde`.

**Comment by yanzhang0219** [comment]
Cool! Thanks a lot!
