### ISSUE TITLE
HELP: Alacritty don't use pywal colors at startup

### ISSUE THREAD

**Issue by nlarzon** [alacritty/alacritty#4220]
When alacritty starts it is using "Default" colors I need to run `wal -R` for alacritty to load the pywal colors.

I did a workaround and added `wal -R` in .zshrc but that has the downside of always reloading polybar. 

### System

OS: Linux (Arch)
Version: alacritty 0.5.0
Linux/BSD: X11

**Comment by kchibisov** [comment]
we have nothing to do with pywal in particular. You may want to make pywal to generate an alacritty config for you, which you could include from your main config. Though, it's something only possible on master.

pywal sets colors via escape sequences, which is fragile, so if something resets them at the moment of sourcing your shell configs you're out of luck.

**Comment by tzcrawford** [comment]
I also had this problem transitioning from urxvt to alacritty.

I likewise accomplished this simply by adding the following to `.bashrc`, assuming you don't have a reassignment of `$TERM` somewhere else in your `.bashrc` or `.bash_profile` (you shouldn't). You can also replace `alacritty` with your other terminal emulator of choice and I'm sure it would apply.
```
# Force alacritty to recover color scheme
if command -v wal > /dev/null 2>&1 && [ "$TERM" = "alacritty" ]; then
    # Run 'wal' command with options to recover color scheme, ignore output, and ignore updating other apps
    wal -Rqe
fi
```
This is better than simply adding `wal -R` to your run commands because
1. You only really want this to happen in your terminal emulator on your desktop.
2. `wal -R` is pretty slow and you don't need to run that in every subshell.
3. You don't need to see StdOut, we use the `-q` option.
4. We don't need to cause other parts of our desktop to reload colors again as well (i.e. gtk, xrdb, polybar, i3). This is done with the `-e` flag.
