### ISSUE TITLE
CPU-only build option

### ISSUE THREAD

**Issue by sailfish009** [alacritty/alacritty#4222]
Hi, can i use cpu-only mode? 

when i training model in pytorch/tensorflow, alacritty lagging so much.
since after, i have used terminal which is not using gpu-acceleration.

i like alacritty because which is written in rust, not because of gpu-thing.

### System

OS: Linux (Mx Linux)
Version: doesn't matter
Linux/BSD: X11, tinywm

**Comment by chrisduerr** [comment]
You cannot.

**Comment by sailfish009** [comment]
That's too bad.

**Comment by chrisduerr** [comment]
Your GPU driver on Linux might be able to emulate it, but that's just going to provide terrible performance.

**Comment by nixpulvis** [comment]
> Your GPU driver on Linux might be able to emulate it, but that's just going to provide terrible performance.

To be a bit pedantic, it's not exactly the **GPU** driver as much as the graphics driver at play, since Mesa IIUC will allow a system without a "GPU" to run OpenGL programs. That said, I understand that even some systems with graphics support on the CPU aren't fully supported. This can seems to be a bit of a can of worms, which I'd personally be interested in learning more about TBH.

That said, when trying to use a overloaded system clearly there *may* be some terrible performance. The question is how to best utilize and prioritize resources in that case.

@sailfish009 perhaps something like https://wiki.archlinux.org/index.php/PRIME could allow you to control how your graphics driver selects a device to use.
