### ISSUE TITLE
Option to keep app open after all windows close?

### ISSUE THREAD

**Issue by 12-Seconds** [alacritty/alacritty#4266]
### System

OS: macOS
Version: 0.5.0

I've moved to Alacritty from iTerm2, and one thing I miss is the hotkey window. I've used the [solution](https://github.com/alacritty/alacritty/issues/862#issuecomment-616873890) in issue #862, and it works. However, iTerm2 stays open even when the last window is closed, which I do sometimes to the hotkey window. However, when doing the same to Alacritty, the app closes immediatley. Could an option be added to not close the ap after the last window is closed?

**Comment by chrisduerr** [comment]
There's the `--hold` option for the CLI, but generally I don't see why the terminal should stick around after the shell has been closed.

**Comment by tobx** [comment]
I guess the point here was that the window closes, but the app stays open. This is the default macOS way (compare with the default macOS Terminal or other apps).

I would appreciate an option in the config file for this, because I often have SSH sessions open and switch users within. Then I press <kbd>Control</kbd> + <kbd>D</kbd> a few times to return to my root shell and often I press it too many times. In the macOS Terminal all windows are closed and I can just press <kbd>Command</kbd> + <kbd>N</kbd> to open a new shell. With Alacritty I have to reopen the app first and that means touching the mouse or using Spotlight, but I do not like Spotlight, because it is not reliable.

The `--open` option does not really help since it leaves a useless shell window open and it is generally difficult to configure macOS to open apps with cli parameters.

That being said, it is not really an issue, it would just be a nice to have, but if one day you do not know what to do, maybe this could be implemented :)
