### ISSUE TITLE
url-parsing stops on backslash

### ISSUE THREAD

**Issue by dym-sh** [alacritty/alacritty#4270]
### System

OS: Linux
Version: 0.5
Linux/BSD: X11

### problem
url-parsing stops on backslash
which affects all escaped characters,
but most notably `\?` and `\#`, since they are most often used in urls

mouse-over on url, opens only the underlined text:
![](https://user-images.githubusercontent.com/59403389/94687425-87663980-032c-11eb-913e-d6ad907247ed.png)

**Comment by chrisduerr** [comment]
I mean that's not a valid URL, so that seems correct to me? Or what do you expect to happen here when running into characters that are clearly illegal.

**Comment by dym-sh** [comment]
how are they illegal, if terminal requires you to escape them (and auto-escapes on copy-paste btw) in order to _not_ be treated as bash commands

**Comment by kchibisov** [comment]
They are illegal by a spec, no? Bash just quotes your text, since it have to, but we have no clue that those quotes are intentional or not, since in something like vim those are no presented. We may relax rules to match illegal by spec urls, but only for that character... The thing is that browsers could be confused as well, firefox strips illegal chars, but you can't think about other terminals. Alternatively we can strip illegal things, but I'm not entirely sure about it.

**Comment by dym-sh** [comment]
just assume everything starting with `http` is url until first unescaped seperating character and open url already converted to have all character reverted back to normal

regexp would be `http(s)://[\w(\\.)]+`

**Comment by kchibisov** [comment]
But it's wrong, you're not following url spec, since it's not a url, it's a string you've decided to match.

**Comment by chrisduerr** [comment]
> just assume everything starting with http is url until first unescaped seperating character and open url already converted to have all character reverted back to normal

It's not that simple.

To support this usecase, we'd effectively have to break our URL parser to not only allow illegal characters, but also pretend like they didn't exist to make sure the browser doesn't get them (Firefox does not strip this correctly).

But there's quite a simple solution to this: The only character that cannot be escaped by shell quotes is `!` and that's illegal in URLs. So all you have to do to fix this issue is to quote your URLs and you won't have to escape anything. Fixes the problem and doesn't require breaking anything in Alacritty.
