### ISSUE TITLE
Help message prints strangely on Windows

### ISSUE THREAD

**Issue by maroider** [alacritty/alacritty#4274]
### System

OS: Windows
Version: 0.5.0
Windows: ConPTY

### Description

When I use `alacritty --help` in `pwsh.exe`, or `powershell.exe`, the help message prints itself, but the prompt stays above the help message. This does not occur when using `cmd.exe`.

```shell
>alacritty --help
>alacritty 0.5.0 (a6681e3)
Christian Duerr <contact@christianduerr.com>
Joe Wilm <joe@jwilm.com>
GPU-accelerated terminal emulator

[...]
```

When I start typing after the message has been printed, the cursor jumps up to the second second line (`alacritty 0.5.0 (a6681e3)`) and starts replacing it as I type.

**Comment by bitraid** [comment]
That's because alacritty is build for Windows as a GUI application (instead of Console, to avoid always creating a console window at startup), which means it doesn't attach to the console of the calling program, so alacritty manualy attaches to it:
https://github.com/alacritty/alacritty/blob/f5813899c3212d295358911635109201910b666b/alacritty/src/main.rs#L20-L21
But there are some problems with that approach (redirection also doesn't work), because GUI programs are also forked and return control to the parent console immediately (a console application does not return control until it exits).
A better solution would be to include a console program with the same name and a `.com` extension (which has priority over `.exe`), that runs the `.exe` and does the redirection. I've created such a [program](https://github.com/bitraid/conwrap) a few months ago (compiles with [fasm](https://flatassembler.net/): `fasm conwrap.asm alacritty.com`), but be aware that some antiviruses detect it as trojan.

**Comment by chrisduerr** [comment]
This is really just Windows being a bad operating system for terminal applications. I'd recommend just trying to avoid it whenever possible.

**Comment by bitraid** [comment]
As a workaround, you can pipe to `more` (`alacritty --help | more`).
