### ISSUE TITLE
Dynamic title by default?

### ISSUE THREAD

**Issue by axxx007xxxz** [alacritty/alacritty#4295]
### System
OS: Linux (Fedora 32)
Version: 0.5.0
Linux/BSD: X11, Cinnamon on Muffin (fork of Mutter for Cinnamon)

"dynamic_title" should be enabled by default according to [source](https://github.com/alacritty/alacritty/blob/v0.5.0/alacritty/src/config/window.rs#L60) (I hope I haven't misunderstood) however it isn't.
But for some reasons setting environment variable "TERM" as "xterm-256color" makes it work. Is it an intended behavior?

**Comment by kchibisov** [comment]
Title is set by applications you're running, in your case something sets title when TERM is `xterm-256color`. Alacritty does set dynamic title by default, meaning that it accepts title change from the applications, if dynamic title it set to false it'll never change a title.

So, fix your applications that fail to set title, because TERM name differs from xterm-256color.

**Comment by axxx007xxxz** [comment]
Ok, thanks!

**Comment by 2hk222** [comment]
Hi
