### ISSUE TITLE
Sending Shift+Insert to a window that is not focussed results in the shift being ignored.

### ISSUE THREAD

**Issue by JJK96** [alacritty/alacritty#4303]
Sending Shift+Insert to a window that is not focussed results in the shift being ignored.
Sending it to a focussed window works correctly.

### Steps to reproduce

Start an alacritty window with
```
alacritty -t alacritty_test
```

In another terminal run
```
xdotool search --name alacritty_test key Shift+Insert
```

### Expected behaviour

The clipboard is pasted in the alacritty_test window.

### Actual behaviour

Only insert is registered in the alcritty_test window (tested by typing before other text)

### Other information

Doing 
```
wait 2; xdotool search --name alacritty_test key Shift+Insert
```
And selecting the alacritty_test window before xdotool runs results in a correct paste.

Sending
```
xdotool search --name alacritty_test key Shift+a
```
works correctly when the window is not focussed.

### System

OS: Linux
Version: alacritty 0.5.0 (a6681e3a)
WM: i3

### Logs

http://ix.io/2Aha

**Comment by JJK96** [comment]
According to testing done by @shachaf the `mods` variable in https://github.com/alacritty/alacritty/blob/a754d06b44139b85e8b34a71ece4477cb1caa85e/alacritty/src/input.rs#L934 is `none` in the unfocussed case.

**Comment by kchibisov** [comment]
It's intentional, modifiers on unfocused window are empty.

**Comment by JJK96** [comment]
Is it documented somewhere why this is the case? Security?

**Comment by kchibisov** [comment]
It's an implementation detail of https://github.com/rust-windowing/winit. To provide abstractions on all platforms, since on e.g. Wayland modifiers are always empty for unfocused window.

**Comment by shachaf** [comment]
This argument doesn't make sense to me. If you `alacritty --print-events`, it sees the shift modifier:

    glutin event: WindowEvent { window_id: WindowId(X(WindowId(88080388))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 110, state: Pressed, virtual_keycode: Some(Insert), modifiers: SHIFT }, is_synthetic: false } }

So the modifier is exposed from winit. It's in the X11 KeyPress event itself, regardless.

The argument that this program is portable to other platforms, and therefore needs to take the infimum of the features of all platforms, also doesn't make sense to me. If it was ported to a platform that didn't support a mouse, you would still want mouse support on platforms that do have one, and so on.

**Comment by shachaf** [comment]
In fact, making this work properly is a one-line fix. In `process_key_bindings`, just replace

    let mods = *self.ctx.modifiers();

With

    let mods = input.modifiers;

Which is probably more reasonable anyway (when processing an event, use the modifier state recorded in the event).

**Comment by kchibisov** [comment]
Do you see `ModifiersChanged` event? If not, nothing we can do, since we're only listening to it, the modifiers on keys thing will be removed upstream at some point.

**Comment by shachaf** [comment]
I don't see a ModifiersChanged event, but I do see a shift KeyPress event: `WindowEvent { window_id: WindowId(X(WindowId(92274692))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: (empty) }, is_synthetic: false } }`.

That's enough for most terminal to figure out that the modifier is pressed.

Also, again, removing a feature that's the most accurate way to do something on one platform just because another platform doesn't support it seems silly to me. When compiling for X11, Wayland is irrelevant, abstraction layers that hide useful information are anti-helpful, and it makes sense to use the information X11 actually gives you.

**Comment by nixpulvis** [comment]
The issue as I understand it here is that `winit` would like to advertise a consistent interface, and that forces some of Wayland's behaviors upon us in general. Namely, that it always sends a `ModifiersChanged` event clearing the modifiers on `FocusOut`. I'm personally still not 100% sure why Wayland works the way it does, but given the current state of things, I can't see a good way for `winit` to fix this issue without treating X11 and Wayland differently, which kinda defeats the purpose.

**Comment by shachaf** [comment]
It can fix the issue the way it does right now -- by including modifiers on KeyboardInput events, which could contain the most accurate information it has for a particular event. It already exposes this. I'm not sure what the point of deprecating it is.

It could also fix it by tracking the ModifierState more accurate, since it does get X11 events that indicate the modifier changed, in this case.

Anyway, "our upstream library doesn't support this, so we won't fix it because it's not that important" seems like an understandable response to me (someone who cared might talk with the winit people about it). "not a bug" just seems bizarre. Every other X11 terminal supports this, it's the behavior users expect, and what Wayland does is irrelevant to X11 users.

**Comment by nixpulvis** [comment]
It seems unnecessary to me to store our own copy of `ModifiersState` inside `ActionContext`. Inside `winit`, the modifiers are properly being updated in this case, but since we never receive a `ModifiersChanged` event, we don't update our own version of the modifiers. Why must there be so many versions of this state!?

**Comment by nixpulvis** [comment]
It does in fact seem like a `winit` bug to me, since we get `KeyboardInput` events with changing modifiers without getting the corresponding `ModifiersChanged` event.

I don't really know how to test corresponding functionality on Wayland though TBH.

**Comment by kchibisov** [comment]
Winit has a clear model, when window isn't focused modifiers are empty. It's by winit design. If we want to fix it in winit winit should fake focus or stop following this model.

Winit decided to choose that model because of Wayland in a first place, to build abstraction for each platform. The only bug I can see here according to that model, is that unfocused window gets keyboard input, and winit should suppress it.
