### ISSUE TITLE
Instructions for where to obtain alacritty on Linux

### ISSUE THREAD

**Issue by dancojocaru2000** [alacritty/alacritty#4306]
Since alacritty removed Linux binaries, it should probably still help users by pointing out (in the README.md perhaps) where those binaries can be located and/or instructions on how to install. 

For example, in case of Debian/Ubuntu, a link to a PPA should be included.

**Comment by kchibisov** [comment]
We don't know where those binaries should be located, in general, you should get software from your package manager, and I think that you can use its search capabilities.

There's no such things as Linux binaries, there're plenty of linux distros and every one has its own package format, so it's impossible to provide things for everyone, instead package managers should provide software for you.

**Comment by dancojocaru2000** [comment]
Depending on the Linux distribution, software appears in the official package repositories quite slowly.

Furthermore, in [INSTALL.md](https://github.com/alacritty/alacritty/blob/master/INSTALL.md), instructions are provided in particular for Fedora. Considering that, I don't see why there wouldn't also be - for example - instructions for an Ubuntu PPA.

**Comment by kchibisov** [comment]
Because there's no PPA that we can recommend? idk, gentoo/arch/alpine pushes new versions under 2 days to their repos, and I trust them more tbqh, since they know how to package things correctly.

**Comment by dancojocaru2000** [comment]
Related to the 2nd statement, this is the usual distribution war. Skip a little ahead if you want to ignore my comments on it.

---

For all I know, I always had driver problems when trying non-Debian based distributions, so I'm reluctant to trying them. Furthermore, I am already used to the way Debian does things (like `update-alternatives`, for example), and the effort of reinstalling my OS and learning new things wouldn't really be justified. 

That aside, other distributions have other problems. For example, if you don't update your entire system at once on Arch, stuff breaks very bad very fast.

---

Related to no PPA that can be recommended, that can be understandable and I'm surprised that I haven't though of it, though [on other issues some PPAs have been recommended](https://github.com/alacritty/alacritty/issues/3992#issuecomment-660400014).

In general, I'm confused as to why Alacritty suddenly decided not to provide binaries for Linux, a shift from #80.

**Comment by kchibisov** [comment]
Because we are developers and not package managers, like I don't want to deal with packaging for debian, and I bet @chrisduerr doesn't work that either. I haven't used debian based systems in my entire life for personal machines and never dealt with them for long enough, so I'm not sure why I should.

The only reason why we had them is because travis is using some ubuntu thingy, but one more point is that those binaries weren't working on some debian systems and on some others they were working, because our package had collisions with system packages (ncurses) on some of them, so even in debian only world, it's impossible to provide binaries.

If we want to provide debian binaries we should provide binary for each debian/ubuntu version, to avoid collisions with system packages, and some debian based distros, like pop os having alacritty in their package manager.

You can always package alacritty yourself, I don't see any issue with it, especially when you live on something that tries to stay behind as much as it can like debian.

**Comment by dancojocaru2000** [comment]
Gotcha.

For those concerns, AppImages seem to be the best compromise? It could be the "run on _almost_ any Linux" binary that don't give users the feeling of  
> "Check out our cool software!"
> "Cool indeed! Where's the download button?"
> "There isn't one."

Unless there is something I'm missing, AppImages seem to be the missing "Linux" binary when Windows and macOS ones are provided already.

**Comment by kchibisov** [comment]
>For those concerns, AppImages seem to be the best compromise? It could be the "run on almost any Linux" binary that don't give users the feeling of

We don't like App images, etc, there's no value in such things, packaging things yourself is faster and more secure than using some App Image, especially knowing that you'll do that once and then likely only minor bump things. There're even tools like cargo-deb to help your with packing.

The thing is that App Image and things like flatpack are less secure and reliable than distro provided packages, since those packages are actually reviewed. 

>Windows and macOS ones are provided already.

macOS and Windows expect developers to package things, which we kind of hate. And existing package managers like brew are using just our binaries and not building anything theirself, which I also hate, but you can kind of live with it.

**Comment by dancojocaru2000** [comment]
The point of an AppImage is that it should ideally be built by the developers and distributed, for example, on the releases page on GitHub. Therefore, if an AppImage can't be trusted, the entire software can't.

Packaging things myself if a major hurdle, that is enough to make me not want to put in the effort to use a software. For users other than those who only use GUIs for web browsers and otherwise use the terminal for everything (exaggerated description given to emphasise the point; didn't mean to insult anybody), touching `make` or building a package themselves is enough to negate any benefit of a software. 

Building a package myself would certainly not be faster considering I have no idea how to do that. And the extra research that goes into finding out how is almost never justified.

While you may hate the idea that the developers make binaries, non-enthusiast users hate the idea that they must build the software themselves; it feels like the developers only did half the job, they didn't finish the product.

Ultimately, this ties into the trouble of free software, where developers rightfully do what they want because they're not paid by anybody to do more than that, but at the same time they don't do the inconvenient things that would make things easier for the user. And, when it gets to that, what's the point of the software being free is only the devs will find it convenient?

I know I'm exaggerating here, but in a way this is how things feel. 

Sorry for all of this. GitHub issues are probably not the place for these kind of things.

**Comment by kchibisov** [comment]
>Ultimately, this ties into the trouble of free software, where developers rightfully do what they want because they're not paid by anybody to do more than that, but at the same time they don't do the inconvenient things that would make things easier for the user. And, when it gets to that, what's the point of the software being free is only the devs will find it convenient?

All software I use except firefox doesn't provide linux binaries(yes, those are gui, and they provide only sources), the only thing where I see linux binaries is proprietary software about which I don't personally care, and for which it makes sense, because users can't even built your thing, but we provide instructions on how to build stuff, the code is open, and plenty distros are packing alacritty, even debian based ones, so you can grab the way they built package from them. I really don't see why we should provide binary if no one else except proprietary apps are providing them for linux. (And don't link to some electron things, those are all proprietary to some point, or so cumbersome to built, that no one cares about them).

**Comment by dancojocaru2000** [comment]
Two examples of apps that provide AppImages are Kdenlive and Krita.

**Comment by chrisduerr** [comment]
There is a universal software format that works on basically every machine and this is what Alacritty provides: Source code. Beyond that, complain to your distribution's maintainers, not Alacritty.

**Comment by dancojocaru2000** [comment]
This response feels quite aggressive.

Source code has disadvantages, the two main ones being the need to install build tools (the Rust compiler and others in this case) and no real way to properly manage the installation or easily remove it.

If source code is so great, I don't see why Windows and macOS binaries are provided instead of just instructions for users to install the Rust toolchain and compile themselves.

I would get a "we don't do this because we don't want to, the end". As I said, free software also comes with "devs are free to do what they want".  But if you provide reasons for the "we don't do this", I will try to show why they're not great reasons. If you say that other free Linux apps don't do this, I'll point out that another terminal emulator, many KDE apps, and not only those do.

But providing such a response just feels uncool.

**Comment by chrisduerr** [comment]
> This response feels quite aggressive.

It is. You're pushing issues caused by your distribution being bad directly onto Alacritty increasing maintenance burden with something that will not benefit any Alacritty user.

> If source code is so great, I don't see why Windows and macOS binaries are provided instead of just instructions for users to install the Rust toolchain and compile themselves.

Oh ideally that would be the case. However the maintainers of Windows and macOS are incompetent, just building Alacritty on Windows is a serious undertaking because of their utter lack of developer tooling. Linux has software maintainers that actually do their job, you just need to pick a distro that packages the software you care about. And for everything else building from source is trivial.

> AppImages are not distribution dependent so they would basically have the same status as Windows executables

There is no standard format to distribute binaries on Linux and all formats that try to sell themselves as such are extremely poor. If you have problems with packaging, take it to your distro's packagers.

**Comment by dancojocaru2000** [comment]
> Oh ideally that would be the case

There is a reason why every year will be "the year of the Linux Desktop", while Windows and macOS still maintain marketshare.

In my view, Apple and Microsoft did their job. Apple provides macOS on their computers, Microsoft provides Windows through partners on many computers and provides the installer for others.

In the same view, Manjaro, Ubuntu, Fedora etc are doing their job. They are providing the operating system. From this point, in my view, their job is done.

---

In most industries, the person or company manufacturing something are responsible with either distributing that something or contracting someone to do the distribution for them.

What you are implying is that, after I design a tablecloth, all table manufacturers should come to me and sell my tablecloth for me.

---

Personally, I think that distribution maintainers are doing charity work for app developers by packaging and hosting binaries for them. Since you said that maintaining a deb file is hard, I don't think it's any easier for whoever maintains the Debian or Ubuntu repositories to do that. And you seem to be taking that too much for granted.

It's not nice to bash open source devs for picking and choosing what they work on and what they don't. But somehow it's okay to say a distribution is bad when they don't hurry to do your work and package your app and host it and distribute it? Yet it's not okay to say Alacritty is bad for not doing that work?

---

Google Play asks for payment and asks for developers to submit built binaries to be distributed.  
Microsoft Store asks for payment and asks for developers to submit built binaries to be distributed.  
App Store asks for paym...
PlayStation Store asks fo...
Steam asks...

Debian or Ubuntu or (insert distribution here) don't ask for any payment, they do the work of taking your source code and making sure it works without conflict on the OS, packages it up and hosts it for it to be easily downloaded by users, all for free, and when they don't do this or when they don't do this in "under 2 days" like "gentoo/arch/alpine" they are suddenly at fault and maintainers that don't "actually do their job"?

I'm sorry, but if this were a r/aita situation, yta. You seem to be very ungrateful for the work they do for you and simply expecting them to do it for you.

You are basically like the users that come here and demand you to absolutely work on what they want even if you have no duty to do that for them.

**Comment by chrisduerr** [comment]
> There is a reason why every year will be "the year of the Linux Desktop", while Windows and macOS still maintain marketshare.

I have zero interest in getting more people to use Linux or Alacritty. If you don't like it, don't use it.

> In most industries, the person or company manufacturing something are responsible with either distributing that something or contracting someone to do the distribution for them.

Just like Alacritty distributes the source code, while the people whose job is packaging software can do their job after Alacritty ships the source to them.

> Since you said that maintaining a deb file is hard

It's really not when your job is just to maintain it. It's just a huge waste of resources to set that up for every single application.

> But somehow it's okay to say a distribution is bad when they don't hurry to do your work and package your app and host it and distribute it?

Yes, if someone not doing their job properly causes a constant influx of users on your application, that certainly warrants complaining about them. It's their job and they're not doing it. Alacritty's job ends once the source is provided.

> Debian or Ubuntu or (insert distribution here) don't ask for any payment; they do the work of taking your source code and making sure it works without conflict on the OS, packages it up and hosts your application for it to be easily downloaded by users, all for free, and when they don't do this or when they don't do this in "under 2 days" like "gentoo/arch/alpine" they are suddenly at fault and they are maintainers that don't "actually do their job"?

They reliably fail to do this for several popular applications. This is not only true for Alacritty but a very, very common issue. While other distros that have zero commercial use somehow magically manage to update Alacritty within hours of its update. Clearly one of them has better package maintainers.

> I'm sorry, but if this were a r/aita situation, yta. You seem to be very ungrateful for the work they do for you and simply expecting them to do it for you.

Great, then don't use Alacritty. This is quite literally not our problem to deal with, so please don't report it to Alacritty expecting us to do the work of others.

Nobody is doing work for Alacritty, I am very grateful to the competent package maintainers that ship Alacritty today. If you can't figure it out, you don't deserve my thanks because you literally did not do anything for me. The idea that I would have to be grateful for someone doing absolutely nothing for me is completely bizarre.

> I would get a "we don't do this because we don't want to, the end".

If you don't want an explanation, just move on. Everything we do happens for a reason.

**Comment by dancojocaru2000** [comment]
I think this discussion is concluded.

Summarized, we disagree on what an application developer / maintainer should do. You think their duty ends at providing the source code. I think that source code is not an usable application, but a binary is, therefore providing only the source code is only doing "half" the work.

By extension, we also disagree on what an operating system maintainer should do. You think they should also go to every developer, take their source code, make sure any kind of conflicts are resolved, package the software up and ship it to users. I think that their job is done when the operating system is up and running on an users computer, and they certainly don't have a duty in helping software go from developer to user.

As for Debian/Ubuntu, I was not aware that they are that slow to respond even to popular applications. At that point, it can be considered bad work. But since it's work done for free, _c'est la vie_.

Since we have those fundamentally different points of view, any further discussion is basically politics but related to how to run the development and distribution of software, not how to run a country. And people will never agree on everything.

I hope this is a nice way to end this conversation.

Have a good day!

**Comment by chrisduerr** [comment]
> As for Debian/Ubuntu, I was not aware that they are that slow to respond even to popular applications. At that point, it can be considered bad work. But since it's work done for free, c'est la vie.

Just fyi, especially with things like Ubuntu the funding is probably better than most other distributions out there. The thing is just that their money maker isn't desktop linux, so they have no reason to care about it. But unfortunately most users still rely on a distro built for servers to run their desktops, so it's not much of a surprise that they'll run into problems.

> Have a good day!

You too.

**Comment by dancojocaru2000** [comment]
> But unfortunately most users still rely on a distro built for servers to run their desktops, so it's not much of a surprise that they'll run into problems.

The general consensus is to recommend Ubuntu for new users. Because of that, it is also the system that's most familiar with most people. Most proprietary software is usually provided only as `.deb` (or rarely also `.tar.gz` or `.rpm`) and most users still use proprietary software despite many people in the Linux community disliking that. Since Ubuntu is the most used, it also has the most help resources available when stuff goes wrong. 

There's no real "proof" for this personal experience based claim, but I also had the most straight forward driver experience with Ubuntu. Almost all things work out of the box, generally the only exception being the Nvidia graphics card because proprietary software. With other distributions that I tried, I had issues like Bluetooth, WiFi, etc not working, which, combined with my current experience with Ubuntu, discourage me from trying something else.

While it may be unfortunate that many people use Ubuntu, it's not really surprising.

---

Since Ubuntu is this bad, is there a non rolling release distribution that you could recommend?

**Comment by chrisduerr** [comment]
> Since Ubuntu is this bad, is there a non rolling release distribution that you could recommend?

I do not have enough experience with distros for "normal" people to be able to recommend anything really. There are some distros built on top of Ubuntu that try to provide a more desktop-focused experience (see pop for example, which provides Alacritty in their repos), but generally the prevalence of Ubuntu as the one big user-friendly distro has prevented others from properly filling that space. Things like OpenSUSE generally seem to run a bit of a better ship, but that's obviously not remotely more desktop oriented than Ubuntu.

Unfortunately writing software costs money and you don't really make money with desktop Linux.

**Comment by nixpulvis** [comment]
> In most industries, the person or company manufacturing something are responsible with either distributing that something or contracting someone to do the distribution for them.

That's exactly the conceptual model I suggest you work to shift in your understanding of Open Source Software. We provide the source code, along with an issue tracker and a few other niceties. Users may either build for themselves directly, or rely on a packager for their distribution. Packagers may or may not be tied to the OS, and the OS may or may not help with this process at all (other than to provide the packager's expected interfaces). This allows a better separation of concerns, and reduces the overhead for the source code maintenance, which is fundamentally the most important, and limited resource.

FWIW, I tend to recommend Arch, because it forces you to learn a bit more about the underlying Linux setup. It also currently tends to be very updated. This may not be what everyone wants. Some people just need a working computer ASAP, in which case it's frankly really hard to know exactly what will remain the best advise...

**Comment by dancojocaru2000** [comment]
> FWIW, I tend to recommend Arch, because it forces you to learn a bit more about the underlying Linux setup.

In my opinion, that's not a quality.

Sure, if someone is in university learning details about operating systems, or if they're just interested and they want to tinker around, yeah, it makes sense.

But, in my view, an operating system should work for the user, not against it. When an operating system forces the user to know its internals, it's making the user do extra work that they didn't intend to do, it's working against the user.  
When an operating system is easy to use and convenient and you don't even have to think about how it's doing things, then that operating system is making life easier for the user.

> That's exactly the conceptual model I suggest you work to shift in your understanding of Open Source Software.

In that conceptual model, the people making the original product (in this case, source code) are responsible for ensuring that such product is packaged (in this case, compiled for the right platform while making sure that it works), and then they are also responsible for going to distributors and asking them to distribute the product.

This is the model of the "app stores" from companies nowadays (App Store, Play Store, Steam, etc). They require binaries, and the developer must seek them out and pay them for distribution.

If I go to the beer factory in my town, they give me bottled beer that they would otherwise ship to stores to sell. They don't tell me to bring my own bottles and fill them myself (compile the software from source myself in this case).

**Comment by pvonmoradi** [comment]
@dancojocaru2000 
I think you already know but FWIW, you can use PPA of PopOS! ([https://launchpad.net/~mmstick76/+archive/ubuntu/alacritty](https://launchpad.net/~mmstick76/+archive/ubuntu/alacritty)) to have Alacritty on any xBuntu. Note that their 0.5 version is not actually tracking release v0.5 but I guess they're gonna fix it in the next release.

**Comment by mgutz** [comment]
I'm not understanding. Most other rust utilities provide a pre-compiled binary (not package) in releases. No need for snapd, deb, etc. I can understand the effort required for linux packages but a simple pre-compiled binary?
