### ISSUE TITLE
Feature: easymotion like jumps in vi mode     

### ISSUE THREAD

**Issue by hajdamak** [alacritty/alacritty#4319]
It would be great to have [easymotion](https://github.com/easymotion/vim-easymotion) like functionality in vi mode for quick jumps to place where v selection can start and later on end.

**Comment by chrisduerr** [comment]
While this might be useful to some users, it involves a lot of complexity and is not something that is as commonly used as vi itself. Because of that, I'd like to make it clear that at this point in time I have no interest in adding this by itself.

However, I don't think it should be outright rejected either. An alternative way to open URLs using an easymotion/vimium/tridactyl like mechanism is definitely considered and for that much of the complexity of this issue might already be resolved. Should that make this reasonably simple to get working I would be willing to give it another thought.

So until something like that is in place, I strongly recommend against making contributions towards this issue.

**Comment by chrisduerr** [comment]
PR #4967 pretty much takes this as far as I'm personally willing to take this. Having actual easymotion to jump to individual grid locations independent from hints is not something I'm interested in implementing.

**Comment by hajdamak** [comment]
@chrisduerr  How hints with this new `MoveViModeCursor` action solve problem of jumping to specific place in the screen?  Am I missing something?

**Comment by hajdamak** [comment]
@chrisduerr Is there a way to trigger this hint only in Vi mode using `f` key?

**Comment by chrisduerr** [comment]
Not yet, see #5154.

**Comment by hajdamak** [comment]
@chrisduerr But other than that these hints solve jump problem for me. Thank you for implementation.
