### ISSUE TITLE
Xinerama dont work, bug alacritty.

### ISSUE THREAD

**Issue by Zik42** [alacritty/alacritty#4326]
When I enabled xinerama in my config, alacritty dont start anymore.
I tried these vars, but it does not help, same error output.
WINIT_HIDPI_FACTOR=1 WINIT_X11_SCALE_FACTOR=1 

### System
OS: Linux (Arch)
Version: 0.5.0
Linux/BSD: X11

### Logs
Output of alacritty -vvv
```
Xlib:  extension "RANDR" missing on display ":1".
thread 'main' panicked at '[winit] XRandR extension not available.', /build/.cargo/registry/src/github.com-1ecc6299d
b9ec823/winit-0.22.2/src/platform_impl/linux/x11/monitor.rs:293:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by chrisduerr** [comment]
The randr X extension is required.

**Comment by Zik42** [comment]
@chrisduerr but it is incopatible with xinerama.

**Comment by chrisduerr** [comment]
I'm aware of that, however it is used in one of our dependencies because it has necessary capabilities that are not supported by xinerama.

I'm not fully aware of the complexity of adding special conditional logic to support the dated xinerama setup, but if the following patch works for you I could upstream that:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 0198afd..73f4d4a 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -8,3 +8,6 @@ members = [
 lto = true
 debug = 1
 incremental = false
+
+[patch.crates-io]
+winit = { git = "https://github.com/chrisduerr/winit", branch = "no_randr" }
```

(just apply this patch to the latest master)

**Comment by Zik42** [comment]
@chrisduerr sad...

**Comment by Zik42** [comment]
@chrisduerr Seems I need use another terminal... Sad, I love alacritty.
