### ISSUE TITLE
Randomly jumping cursor from the bottom to the middle of the screen

### ISSUE THREAD

**Issue by b-will-c** [alacritty/alacritty#4351]
The video describes it better than words (wait for around 30 seconds, at the beginning everything's working fine).

[alacritty.zip](https://github.com/alacritty/alacritty/files/5438136/alacritty.zip)

### System

OS: Windows 10
Version: alacritty 0.5.0 (a6681e3)
Windows: ConPTY

### Logs

![image](https://user-images.githubusercontent.com/66522734/97158653-6a355700-1782-11eb-8f7e-766cd89e6810.png)

**Comment by kchibisov** [comment]
Looks like windows conpty bug to me...

**Comment by b-will-c** [comment]
Just changed the ConPTY backend to WinPTY - it doesn't help the case. 

50% of the time cursor is moving fine, 50% of the time - same issues.

Anything else that might be causing the trouble?

**Comment by chrisduerr** [comment]
Can you upload the video to a platform that doesn't require downloading it to look at it?

**Comment by b-will-c** [comment]
Sure - https://vimeo.com/472148912

**Comment by chrisduerr** [comment]
Hah, that's funny. I'd assume you only get that with the `ls` command and only running PowerShell?

I'm pretty sure this is a bug in the `ls` powershell application and how it outputs things. Powershell often seems to have problems with executing things in the foreground.

I'd assume it's impossible for you to reproduce this with a real shell like bash/sh/zsh?

**Comment by chrisduerr** [comment]
Also, just to make things short:

The powershell has `cl` on the prompt and `clear` in the middle of the screen. This is impossible for Alacritty itself to do, which means the duplication of the typed text must come from PowerShell. Thus this is definitely a bug with PowerShell. Since Alacritty just forwards the input without the ability to decide where it goes.

**Comment by b-will-c** [comment]
> I'd assume it's impossible for you to reproduce this with a real shell like bash/sh/zsh?

Nope, same things happen with bash, sh and cmd.

> Thus this is definitely a bug with PowerShell/ConPTY. Since Alacritty just forwards the input without the ability to decide where it goes.

All right, where do I go from here then?

**Comment by b-will-c** [comment]
![image](https://user-images.githubusercontent.com/66522734/97167394-60662080-178f-11eb-896e-7ac98e59960d.png)

It's as if at times it doesn't understand that it's got the whole screen to fill, and not just a portion of it.

**Comment by chrisduerr** [comment]
> Nope, same things happen with bash, sh and cmd.

Huh, now that's surprising. Which version of Windows are you on?

**Comment by b-will-c** [comment]
You were right, after all.

I didn't activate the WinPTY backend properly earlier. Looks like I modified something else in the wrong place. My bad.

All the shells work properly now. However, the settings file mention that ConPTY fixed a lot of bugs and is faster.

Just how many bugs does it fix and what's the speed trade-off, compared to WinPTY?

**Comment by kchibisov** [comment]
>Just how many bugs does it fix and what's the speed trade-off, compared to WinPTY?

WinPty is basically dead, and you should use ConPty, since it's the only one that is being developed right now iirc. And it's something that is used and maintained by windows terminal team. The most important thing wrt ConPty is that it really depends on what windows you're using, and there're ways to provide more up to date binary for ConPty instead of builtin system one.

So if you have an option, try updating windows, since you'll update ConPty as well.

**Comment by b-will-c** [comment]
Awesome, спасибо огромное.
