### ISSUE TITLE
autocompletion 

### ISSUE THREAD

**Issue by GasparVardanyan** [alacritty/alacritty#4360]
It'll be nice to have something like urxvt's autocompletion in alacritty.
https://github.com/Vifon/autocomplete-ALL-the-things

**Comment by nixpulvis** [comment]
I'm generally not a fan of this since I prefer my auto-complete to be based on the shell, or other REPL's rules. If I had to accept or reject this concept at this moment, I'd vote against it personally.

That said, I can see the value of something simple like this, given that it's effectively just a shortcut for a key binding to `chars`. The issue is that we would almost certainly not want to implement any kind of modal selection interface, leaving you with a rule like "always complete the closest matching word". Perhaps repeated calls to `CompleteWord` would somehow cycle through the options, but even this seems more complex than belongs in the terminal, and not a great UX.

Perhaps #1615 would enable an extension to the shell to support this in a more modular way? Or maybe someone has a clever trick already?

**Comment by chrisduerr** [comment]
> I'm generally not a fan of this since I prefer my auto-complete to be based on the shell, or other REPL's rules. If I had to accept or reject this concept at this moment, I'd vote against it personally.

I agree with this sentiment.

If you want nice completions, the best thing is to make them context aware in the application where you're already at. Just completing from a dictionary or based on paths is mostly useless. Paths are already supported almost everywhere and I don't see anyone writing blog posts in their shell prompts.
