### ISSUE TITLE
Konsole like highlighting new lines

### ISSUE THREAD

**Issue by PouriDev** [alacritty/alacritty#4406]
How can I have Konsole like highlighting new line. I mean something like this:

![highlightedlines](https://user-images.githubusercontent.com/61497342/98829010-f798cc80-244d-11eb-8c2b-5c60dd4ea1b8.gif)

And when you type some commands or when you hit enter the are highlightings
Is there a way that I can do it?

**Comment by PouriDev** [comment]
I mean the blue thing right there

**Comment by chrisduerr** [comment]
There is not and I don't see what purpose that would have? Do you expect to see new lines since the last focus?

**Comment by PouriDev** [comment]
Yes I need to check them since last focus, Sometimes I run some command, I will forget them when they are started,
and some commands delete the line that I put the commnad, and this will be
annoying for me.

**Comment by chrisduerr** [comment]
> ome commands delete the line that I put the commnad

Which command does this? That should never happen.

**Comment by kchibisov** [comment]
You can do that with your shell, it shouldn't be done in alacritty in a first place in my opinion. You should just print a line full of `-` before your prompt getting executed. In something like that it could be done in the following way.

```sh
precmd() {
    printf '-%0.s' {1..$COLUMNS}
    printf '\n'
}
```

This is very primitive way to do that and style that, though it'll not reflow things on resize nicely.

looks like that

![picture](https://user-images.githubusercontent.com/27620401/99068389-7ceebf00-25bd-11eb-9d38-c6a14768006f.png)

alacritty can't possible do that since it doesn't know where  your prompts are on screen and whether those are actually prompts (well, maybe with some tricky supervising it can, but it's just a massive hack, and we're not really a superviser in the end).

One more solution is to communicate where prompts are via some escape sequences to mark shell prompts, however there's no standard escape sequence to do that right now (maybe we'll see something like that in a future).

**Comment by chrisduerr** [comment]
@kchibisov Fyi, I think the issue itself talks about the blue bar on the left, not the separators between commands. Though I do still think that this is not something that should be implemented in Alacritty.

**Comment by kchibisov** [comment]
>Fyi, I think the issue itself talks about the blue bar on the left, not the separators between commands. Though I do still think that this is not something that should be implemented in Alacritty.

I think it's scrollbar?

**Comment by chrisduerr** [comment]
No, I believe it's similar to weechat's history separator. Which will show you the last messages since you've read the scrollback. A scrollbar getting bigger after adding messages makes little sense. Though I've never used it either.
