### ISSUE TITLE
Add option to disable text reflow

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4424]
This was requested in https://github.com/alacritty/alacritty/issues/4419.

It might make sense to some users to completely disable text reflow, however #4419 is the first time I've heard a user actually request the ability to change this in the configuration file. I'd be curious if there are other people interested in disabling this.

Fundamentally, the only real issue with it is the integration with shells, however some shells do already have patches available to work around these issues. So it might be questionable whether it makes sense to add a config option to work around an issue that can be completely fixed without losing any functionality.

**Comment by davidnorthetal** [comment]
Thanks for considering this!

I just want to add, that the reflow bug that I mentioned here https://github.com/alacritty/alacritty/issues/4419#issuecomment-727225831 does not seem to be fixed with `alacritty` terminfo support - so the linked issue affects both `git-bash` (no alacritty terminfo) and `msys2` (alacritty terminfo) by-default on windows, which are both widely used

Can you elaborate on what shell patches you were referring to here that would fix this issue? @chrisduerr 

Thanks for your input on this matter.

**Comment by chrisduerr** [comment]
> Can you elaborate on what shell patches you were referring to here that would fix this issue? @chrisduerr 

The issue is that the shell redraws itself during resize because it makes the assumption that the terminal does not do it (or at least not correctly).

This redrawing creates an infinite pool of characters by constantly repopulating the cells that were removed during the reflow, causing the behavior with the duplication you are familiar with.

The "solution" to this and the patch I believe is available for zsh is that the shell trusts the terminal emulator that it is capable of doing it. However this is problematic of course because there's no way to negotiate it.

Generally I haven't looked much into this, since I personally am not really interested in it. But I'm pretty sure that should be an accurate representation of the situation. Since this only affects terminals which are smaller than the prompt, it's possible for many people to just avoid it.

Some terminal emulators also wait for the shell to redraw to try and work around the issue, but there's no fix for it. In practice I was able to reproduce this issue in every terminal I've tested which supports reflow, so the only difference is just how big the problem is.

**Comment by chrisduerr** [comment]
If there is anyone interested in this option, please leave a comment in #4966. I'm not sure how in demand this is and I'd rather not add config options unless people intend to actually use them.

**Comment by chrisduerr** [comment]
Closing since there has been no feedback justifying this addition.

**Comment by AndydeCleyre** [comment]
There is no patch that is being accepted upstream for zsh to be compatible with reflow.

**Comment by chrisduerr** [comment]
I never claimed any patch was accepted.

**Comment by xaverdh** [comment]
So I think the right thing to do is to add a way for applications to disable line wrapping. Xterm uses `CSI ? 7 l` and `CSI ? 7 h` for this (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html).

The reason shells like `fish` do line wrapping themselves is because its hard to keep track of position information otherwise, right?
In a multi line input setting, when the terminal can change the line width any time due to a resize operation, the shell does not know what "go up one line" is supposed to mean.

**Comment by kchibisov** [comment]
Yes, if application could tell us to disable reflow it would help. We do disable reflow for alternate screen apps for example. From what I know there's no **standard** escape sequence used by shells to disable reflow.

**Comment by kchibisov** [comment]
>Well have to start somewhere to create what might become a standard way then? :)

This will end up with every terminal creating their own escape sequence in reality, like we have image protocol for example, I'm pretty sure we have at least 4 different ones. In general communicating with **most** other terminal developers wrt making something standard won't ever work, like every attempt here failed  (we even had terminal-wg by freedesktop at some point which basically died, because nobody wanted to work with each other).

I'd advise to not waste your mental health fighting this in the end whatever the most popular terminal(VTE/xterm) creates will be used by everyone, regardless of how better other options would be.

**Comment by xaverdh** [comment]
ah just saw https://github.com/alacritty/alacritty/pull/5860 and https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md, that could indeed provide a good solution to this issue!

**Comment by xaverdh** [comment]
Not saying this is a good solution by the way, just dumping my thoughts here..
