### ISSUE TITLE
Resize window title on title bar

### ISSUE THREAD

**Issue by sabitm** [alacritty/alacritty#4443]
Hi, is there anything i can do to resize the window title? The title text looks tiny in my laptop and it seems that i can't change it in the config file. here is my setup.

OS: Arch Linux 5.4.77-1-lts
Version: alacritty 0.7.0-dev (18a226fe)
DE: Gnome 3.38.1 with Wayland

Screenshot:
[![tiny-alacritty.png](https://i.postimg.cc/qB9C689D/tiny-alacritty.png)](https://postimg.cc/yWyNwS60)

**Comment by kchibisov** [comment]
I don't think so unless you're fine with patching source code.

Could try something like
```diff
diff --git a/alacritty/src/wayland_theme.rs b/alacritty/src/wayland_theme.rs
index b9c4381..33aa46b 100644
--- a/alacritty/src/wayland_theme.rs
+++ b/alacritty/src/wayland_theme.rs
@@ -67,6 +67,10 @@ impl WaylandTheme for AlacrittyWaylandTheme {
             (_, Button::Close) => self.hovered_close_icon,
         }
     }
+
+    fn font(&self) -> Option<(String, f32)> {
+        Some(("sans-serif".to_owned(), 18.))
+    }
 }

 trait IntoARGBColor {
```

And see how it goes.

**Comment by chrisduerr** [comment]
@kchibisov The size is already scaled by DPI, right?

**Comment by kchibisov** [comment]
I'm not sure if it's, I haven't paid any attention to font in sctk title bar, since it's broken in general, since I was never able to see it.

**Comment by sabitm** [comment]
Whoa, that works. thanks!

[![Screenshot-from-2020-11-19-23-29-18.png](https://i.postimg.cc/Kj5wdBk7/Screenshot-from-2020-11-19-23-29-18.png)](https://postimg.cc/64yMZ7hT)

any possibilities to bring this feature (in configuration)? or is it doesn't make sense to do that? if it's only me that experiencing this problem, feel free to close this issue, cause i'm perfectly fine with above patch. Thanks again!

**Comment by chrisduerr** [comment]
It probably doesn't make a lot of sense. I'm not familiar with a lot of toolkits that allow you to change the window title font size, at least I've never done it. Because of that, I'd assume it shouldn't be necessary.

The only problem there could be is with the font that might be picked, since `sans-serif` can obviously be different on every system.

The main question I have is if the font size is generally a bit small and most people just don't care, or if it's just small for you with your specific font. If it's always a tad small, but most people are just okay with it, we can maybe bump it up a bit. If it's due to differences in font size, that might be a little more complicated.

**Comment by sabitm** [comment]
Yeah, i think of that too. i've never use any tools that allow me to change title size, because window decoration usually handled by OS/DE. And it doesn't seem worth trying and further complicate codebase with this small problem.

For now, maybe it's best to leave it as it is.

**Comment by kchibisov** [comment]
I think we can bump it to something like 17 by default, since 11 is pretty small for the title. I'm not sure why we're using 11 in winit though, we change it there as well at some point, but not sure.

**Comment by sabitm** [comment]
Yeah, 17 definitely helps since 11 looks too small even on my 14" hd laptop. But, i don't know though what possible problem that may occure to other people with their own setup.
