### ISSUE TITLE
Unable to update to alacritty-0.6.0-1 in Fedora 33

### ISSUE THREAD

**Issue by oswcab** [alacritty/alacritty#4518]
OS: Fedora Linux 33
Version: alacritty 0.5.0
Linux/BSD: X11/Gnome

 Package         Architecture             Version           Repository           Size
Upgrading:
 alacritty          x86_64                     0.6.0-1.fc33    copr:copr.fedorainfracloud.org:pschyska:alacritty                                2.0 M

Transaction Summary
Upgrade  1 Package

Total download size: 2.0 M
Is this ok [y/N]: y
Downloading Packages:
alacritty-0.6.0-1.fc33.x86_64.rpm                                                                                                                                                    2.0 MB     00:06
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
**Error: Transaction test error:
  file /usr/share/terminfo/a/alacritty from install of alacritty-0.6.0-1.fc33.x86_64 conflicts with file from package ncurses-base-6.2-3.20200222.fc33.noarch**

**Comment by chrisduerr** [comment]
Please take up maintenance issues with the package maintainers.

**Comment by mikeslattery** [comment]
@chrisduerr, I respectfully disagree that this should have been closed.  The files to create the copr package are maintained here, in the alacritty/alacritty project.

The [copr package](https://copr.fedorainfracloud.org/oprs/pschyska/alacritty/) uses the source from this project to build the rpm (I think).  Changes in this source probably will fix the copr.

I believe the root issue was caused by [adding the terminfo file in ncurses-base](https://bugzilla.redhat.com/show_bug.cgi?id=1849974).   The alacritty copr package should remove the terminfo file.

The fix is:
* Remove (2) references to terminfo in [extra/linux/redhat/alacritty.spec](../blob/master/extra/linux/redhat/alacritty.spec#39)
* Delete [extra/alacritty.info](../blob/master/extra/alacritty.info), the source file for the conflicting terminfo file. 
* Test [.copr/Makefile](../blob/master/.copr/Makefile)

**Comment by pschyska** [comment]
@mikeslattery I think you shouldn't drop extra/alacritty.info . This is probably used by some non-Fedora packages.

**Comment by pschyska** [comment]
I'm making a fix for that today on my personal branch for the time being and will re-trigger the build on copr. I heard alacritty is upstream now and we can drop the copr at some point.

**Comment by pschyska** [comment]
Please re-test with package version 0.6.0-2.

**Comment by oswcab** [comment]
I can confirm it works now with version alacritty-0.6.0-2.fc33.x86_64.

Thanks a lot @pschyska and @mikeslattery
