### ISSUE TITLE
[Feature Request] Stretch window contents to fit (Omit padding)

### ISSUE THREAD

**Issue by toluschr** [alacritty/alacritty#4526]
### System

OS: Linux
Version: `alacritty 0.6.0`
Linux/BSD: X11, picom bspwm

### Idea
Currently, I was able to find a padding option, which leaves this unsightly border at the sides of my terminal.
![image](https://user-images.githubusercontent.com/44272603/101277999-91873700-37b8-11eb-9873-771b0e322930.png)

What I'm proposing is to add an option to stretch the terminal contents to fit the alacritty window.
Since the padding is rather small in comparison to the window size, distortion shouldn't be much of an issue at regular sizes.
![image](https://user-images.githubusercontent.com/44272603/101278014-a8c62480-37b8-11eb-891a-35aea19ca8fb.png)

**Comment by chrisduerr** [comment]
If you don't want a padding, don't add one. If you're talking about the padding that is created due to the cell sizes not matching the window's size correctly, then use something like `dynamic_padding`.

Trying to stretch out content that isn't meant to be stretched out and keeping track of doing this correctly is just unreliable and hacky. I have no interest in supporting that.

**Comment by toluschr** [comment]
Alternatively, duplicate the background color?
