### ISSUE TITLE
FR: Code Sign macOS app

### ISSUE THREAD

**Issue by apizz** [alacritty/alacritty#4529]
For integrating into automatic download & distributions are  mechanisms (like https://github.com/autopkg/autopkg), it's helpful to be able to verify the app's code signature to ensure it hasn't been tampered with.  An Apple Dev code signature isn't necessary for our purposes, just looking for something that can checked against.

### System

OS: macOS
Version: 0.6.0
Linux/BSD: N/A
Windows: N/A

### Logs

N/A

**Comment by chrisduerr** [comment]
All our releases are signed, what's the point of signing the application bundle? Seems like something you should be able to do yourself if you're redistributing Alacritty. At least that's what all linux distributions do.

**Comment by apizz** [comment]
From Apple dev docs:

> Code signing is a macOS security technology that you use to certify that an app was created by you. Once an app is signed, the system can detect any change to the app—whether the change is introduced accidentally or by malicious code.

While I can download the DMG with the app bundle inside, without code signature I have no way of verifying that the app hasn't been tampered with.  This has become common practice and an easy way for users & admins to verify the authenticity of downloaded software.

**Comment by chrisduerr** [comment]
> While I can download the DMG with the app bundle inside, without code signature I have no way of verifying that the app hasn't been tampered with.

The code, which is the thing Alacritty developers actually provide, should always be signed at the very minimum on release. Is that not sufficient?

If you're talking about a third party platform for redistribution, they should recompile from source anyways instead of relying on Alacritty's CI to build the packages.

**Comment by m4c0** [comment]
I presume apizz is talking about Apple's code signing. In Apple's world, *binary* code needs to be signed (executables, dynamic libraries, etc). That is an expected practice for OSX/iOS users. Amongst other things, unsigned applications shows a warning - which is a sign of distrust for users - and it's unsafe for them as well, since unsigned binaries can't be checked for tampering by the operating system.

**Comment by chrisduerr** [comment]
I'm aware and everyone is free to sign their own builds of Alacritty. That shouldn't be any issue.

**Comment by nixpulvis** [comment]
I'm not really sure why this issue is still open to be honest, but before I close it I'll just add this.

We provide both: the source code and CI generated builds for the major platforms. All of the infrastructure to do this is here in this repository, so if your builds need additional features (like `codesign` support) please feel free to implement that for yourself. We don't want to bother with managing a public/private key and distributing it among ourselves and users accordingly just to sign binaries which are automatically generated by our CI. It's unclear exactly what security that would actually add to me, and it's not an insignificant overhead for us.
