### ISSUE TITLE
Remove `terminfo` dependency

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4597]
Currently terminfo is used only to check if the Alacritty terminfo is
installed, so the fallback `xterm-256color` can be used if it is not.

However the terminfo crate does a few things and comes with some
unnecessary dependencies for Alacritty's usecase, like `phf`.

Since Alacritty's usage is so basic, it should be trivial to move this
terminfo functionality into Alacritty instead, reducing the dependency
on these external projects.

**Comment by brightly-salty** [comment]
I'd be willing to attempt to implement this and submit a PR if it would be accepted.

**Comment by brightly-salty** [comment]
So, after investigating, it looks like there might be a problem or two.

1. `terminfo`'s implementation of `Database::from_name` depends on dirs (which I would replace with dirs-next because dirs is unmaintained)
2. `terminfo`'s implementation of `Database::from_name` depends on `terminfo::parser::compiled`, which is a nom parser for databases.

(1) can be solved by introducing a new dependency for alacritty_terminal if that is all right. (2) can be solved by assuming the database is parsable (not checking like terminfo does) or by simply keeping terminfo as a dependency.

**Comment by chrisduerr** [comment]
> which I would replace with dirs-next because dirs is unmaintained

Dirs being unmaintained is not a problem. We use dirs already and I suggest we keep using it.

> terminfo's implementation of Database::from_name depends on terminfo::parser::compiled, which is a nom parser for databases.

That is not a problem. We don't need to parse the terminfo file. All we need to check is if the file exists in terminfo's paths or not.
