### ISSUE TITLE
Unable to use XDG Base Directory on macOS.

### ISSUE THREAD

**Issue by ress997** [alacritty/alacritty#4618]
When a user configures the XDG Base Directory on macOS, configuration files such as `$XDG_CONFIG_HOME/alacritty/alacritty.yml` and `$XDG_CONFIG_HOME/alacritty.yml` are not loaded.

Why can't I use `$XDG_CONFIG_HOME` on macOS?

**Comment by ress997** [comment]
README.md says to use the XDG Base Directory.
- https://github.com/alacritty/alacritty#configuration

However, in the source code, macOS appears to be disabled.
- https://github.com/alacritty/alacritty/blob/master/alacritty/src/cli.rs#L14-L19

**Comment by chrisduerr** [comment]
Where do you set your `XDG_CONFIG_HOME` on macOS?

**Comment by ress997** [comment]
For example, the Rust library may be set to `~/Library/Application Support`.
- https://lib.rs/keywords/xdg

Other Go language libraries also use `~/Library/Application Support`.
- https://github.com/OpenPeeDeeP/xdg

However, there are some libraries that use `~/Library/Preferences` as `$XDG_CONFIG_HOME`.
- https://github.com/adrg/xdg

I also think that `~/Library/Preferences` is the correct configuration file.
(However, in `~/Library/Preferences`, only `.plist` file used in macOS exists, and honestly, I'm not sure if it's correct here...)

**Comment by chrisduerr** [comment]
I didn't ask you what, or why you set it. I asked **where** you set it.

**Comment by ress997** [comment]
Oops, sorry.

I'm setting environment variables in `~/.zshenv`.

**Comment by chrisduerr** [comment]
And where is that file sourced? Because macOS doesn't usually have the concept of login shells, so what actually starts your login shell is Alacritty.

As you might be able to figure out, setting your `XDG_CONFIG_HOME` in your shell is pretty useless, when trying to get Alacritty (which launches *before* the shell) to use that directory.

A simple test would be to launch Alacritty from Alacritty. Does that find the configuration file correctly? Usually you should be able to access the executable directly in the `Contents` of the `Alacritty.app` bundle.

**Comment by ress997** [comment]
> A simple test would be to launch Alacritty from Alacritty.

I tried it and it loaded the config file and booted me up!

> Because macOS doesn't usually have the concept of login shells

Since I was able to configure the login shell settings on macOS, I assumed that the login shell settings were the same as those on Linux.

**Comment by ress997** [comment]
I couldn't do it by setting it in `/etc/zshenv`.

@chrisduerr  I'm much more familiar with macOS now, and thanks for showing me something I didn't know.
