### ISSUE TITLE
Default Directory

### ISSUE THREAD

**Issue by Milo123459** [alacritty/alacritty#4655]
I have a question, is there a way to set a default directory when opening? On windows it keeps opening to The system32 directory which is annoying. Any ideas?

**Comment by chrisduerr** [comment]
Yes, there's the `working_directory` in the configuration file and the `--working-directory` command line argument.

**Comment by eggbean** [comment]
For anyone finding this through search, this is easiest and allows adding more lines for further wsl arguments:

```
shell:
  program: "C:\\Windows\\System32\\wsl.exe"
  args:
    - --cd ~
```

**Comment by KishoreKaushal** [comment]
The easiest way is to set the `Start In` property to your desired directory which in my case is my windows user home path: `%USERPROFILE%`.

![image](https://user-images.githubusercontent.com/21371609/159108017-01cdebe7-1ac4-44ef-9a16-a01d4a391581.png)

**Comment by yutanguyen25** [comment]
> The easiest way is to set the `Start In` property to your desired directory which in my case is my windows user home path: `%USERPROFILE%`.
> 
> ![image](https://user-images.githubusercontent.com/21371609/159108017-01cdebe7-1ac4-44ef-9a16-a01d4a391581.png)

It works for me. Thank you for that.

**Comment by ashish0kumar** [comment]
> For anyone finding this through search, this is easiest and allows adding more lines for further wsl arguments:
> 
> ```
> shell:
>   program: "C:\\Windows\\System32\\wsl.exe"
>   args:
>     - --cd ~
> ```

Thank you for sharing this! Just a quick note for anyone who might be looking at this in the future: YAML is now deprecated for Alacritty configurations, and TOML is recommended instead. Here’s how to set the shell program and arguments in TOML:
```
[shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["--cd", "~"]
```

**Comment by ghost** [comment]
> Thank you for sharing this! Just a quick note for anyone who might be looking at this in the future: YAML is now deprecated for 
> Alacritty configurations, and TOML is recommended instead. Here’s how to set the shell program and arguments in TOML:
> 
> ```
> [shell]
> program = "C:\\Windows\\System32\\wsl.exe"
> args = ["--cd", "~"]```

Thank you for sharing this! Another quick note for anyone who might be looking at this in the future: `[shell]` is now deprecated.
Use `terminal.shell` instead:

```toml
[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["--cd", "~"]
```

**Comment by brunomdsmartins** [comment]
Is there a way to set multiple starting working directories, as a fall-off kind of thing?

I agknowledge this seems not very intuitive, but I use alacritty on Linux for personal and Windows for work computer, and I do not use WSL on Windows, so having something like:

```toml
working_directory = [ "C:\\Users\\MyUser\\Projects", "~/Projects" ]
```

To store it in a single `.toml` file **like it already exists in the `import` field** for theming, e.g.:

```toml
import = [
  "C:\\Users\\MyUser\\AppData\\Roaming\\dotfiles\\alacritty\\themes\\catppuccin-latte.toml",
  "~/.config/dotfiles/alacritty/themes/catppuccin-latte.toml"
]
```

**Comment by chrisduerr** [comment]
> Is there a way to set multiple starting working directories, as a fall-off kind of thing?

There is not and that's not something I'm interested in adding.

You can use imports for this though, those aren't just for theming.

**Comment by nixpulvis** [comment]
> I agknowledge this seems not very intuitive, but I use alacritty on Linux for personal and Windows for work computer, and I do not use WSL on Windows, so having something like:

One solution, which chris could have been eluding too, is to just use an import for each platform specific config. I believe that no warnings will be issued for missing config files, so that could work for you, though frankly, it seems like something I could imagine being considered an issue. Otherwise, I'm not actually sure how to best handle this without having some branched logic or generator outside of alacritty for platform specific configs.

The way I've done this in the past is have a dotfile installer script which can detect what platform I'm on and move a specific config to a common filepath for the generate config to import, e.g. `platform.toml`.

**Comment by chrisduerr** [comment]
> I believe that no warnings will be issued for missing config files, so that could work for you, though frankly, it seems like something I could imagine being considered an issue.

This is exactly the way it is designed to work, so it most certainly is not an issue.

**Comment by brunomdsmartins** [comment]
Just to close this, the current approach, and what you are suggesting, is for me to have:

```bash
~/.config/dotfiles/alacritty$ tree
.
├── alacritty.toml
├── working_dir_linux.toml
└── working_dir_win.toml
```

And each one of those files to be just one line with:

```toml
# working_dir_win.toml
working_directory = "C:\\Users\\MyUser\\Projects"
```

And:

```toml
# working_dir_linux.toml
working_directory = "~/Project"
```

And on `alacritty.toml`

```toml
import = [
  "C:\\Users\\MyUser\\AppData\\Roaming\\dotfiles\\alacritty\\working_dir_win.toml",
  "~/.config/dotfiles/alacritty/working_dir_linux.toml"
]
```

Because this is the only way for the program not to error / warning out?

**NOTE**: This does not work. The program errors out anyway, not because the file path for `working_dir_win.toml` not exit, but because I can not overwrite the `working_directory` field. What would be the solution then?

**Comment by chrisduerr** [comment]
> This does not work. The program errors out anyway, not because the file path for working_dir_win.toml not exit, but because I can not overwrite the working_directory field. What would be the solution then?

Because you got it backwards. The main file is loaded *last*, not *first*. Just don't define a working directory in the main file and this works just fine.

**Comment by brunomdsmartins** [comment]
The problem was not that. I had not defined `working_directory` in my main toml.

Alacritty can't seem to solve `~/Projects` for Linux and instead only works with `/home/bruno/Projects` for the `working_directory` toml field.

Would this need a PR to parse `~` or you think it is fine? Because `import` resolves `~` just fine.

My first issue is solved now tho, thank you. Just import two files with the `working_directory` field and it will at least work on Linux. Will try for Windows on Monday, but should be fine.

**Comment by chrisduerr** [comment]
> Would this need a PR to parse ~ or you think it is fine? Because import resolves ~ just fine.

Hm, good question. I think that generally that should be a pretty simple problem to solve. We should just have a function or type to handle this automatically, so for things that are **guaranteed** to be paths, we should probably treat them all the same.

**Comment by anasouardini** [comment]
I see a solution for Windows, what about Linux?
under which section do I add `working_directory`?
```yaml
general:
  working_directory: ~
```
does not change anything, It still open with the path I `cd`ed into from TTY.

- alacritty version: `0.15.1`
