### ISSUE TITLE
Notarize macOS Binaries

### ISSUE THREAD

**Issue by dcow** [alacritty/alacritty#4673]
Look, I'm no Apple apologist. I have publicly and vocally opposed Apple's rigid stance towards control of their platform time and again. And I always encourage people to put their time, money, and effort behind more open systems if the limitations they face are imposing. However, while I mostly avoid Apple (and Google, for that matter) in my personal life, there are professional scenarios here and there that require me to develop on and operate within the Apple ecosystem.  

If this project is ideologically opposed to Apple's ecosystem and the maintainers have "no interest" in supporting it: https://github.com/alacritty/alacritty/issues/1896#issuecomment-524436732, https://github.com/alacritty/alacritty/issues/1896#issuecomment-690677828, and https://github.com/alacritty/alacritty/issues/3448#issuecomment-598333977, then I don't think it's fair to list macOS as a supported platform.

Am I disappointed that the maintainers are not interested in supporting macOS? A little. It feels like others are being denied the opportunity to use a nice terminal emulator for largely personal reasons. But I'm mostly just interested accurately capturing reality. The reality is that when you attempt to run Alacritty on macOS, the system prompts you to move the software to the trash because its integrity cannot be verified by the platform. The release provided by this project _does not function_ within Apple's ecosystem.

There is a channel available for projects to receive a free developer program membership. It does not take more than a day total to sit down, apply for a tax-id, and then fill out the fee waiver application. The path exists to support macOS without paying Apple a cent. But the maintainers here have indicated they are not interested in taking it. It doesn't feel so much like macOS users who "made the mistake to purchase a macOS device" are facing a limitation of Apple's platform, but rather are caught amidst an ideological dispute between the maintainers of this project and Apple Inc.

Like it or not, supporting macOS entails signing or notarizing release binaries.

I came here to install Alacritty on macOS so I can have a consistent terminal emulator across the various platforms because the README says you support macOS. I would really like to avoid the conclusion, "use a different terminal emulator on macOS because Alacritty's maintainers don't like Apple and consider usage of hardware that runs macOS a mistake".

I'm willing to lend my time to help get this resolved if the effort required to setup a non-profit and apply for a tax-id and submit the fee waiver application is truly the only barrier.

**Comment by chrisduerr** [comment]
> There is a channel available for projects to receive a free developer program membership.

There is not. 

> Like it or not, supporting macOS entails signing or notarizing release binaries.

There's nothing stopping you from running Alacritty on a macOS machine you have control over.

> I'm willing to lend my time to help get this resolved if the effort required to setup a non-profit

There's not the slightest chance that Alacritty would succeed in setting up a non-profit organization. That process is **very** complicated and requires a lot of upkeep even if Alacritty would somehow be able to magically achieve it.

**Comment by dcow** [comment]
> There is not.

The process is pretty clear: https://developer.apple.com/support/membership-fee-waiver/.

> There's nothing stopping you from running Alacritty on a macOS machine you have control over.

Gatekeeper will not allow the application to be launched because it has not been notarized. Right clicking the application and selecting open no longer whitelists the app in the latest version of macOS.

<img width="372" alt="Screen Shot 2021-01-07 at 11 58 08 PM" src="https://user-images.githubusercontent.com/547926/103984371-3b553d00-5144-11eb-9463-6a09f5d69346.png">

If there's a way to do this, can you share?

> There's not the slightest chance that Alacritty would succeed in setting up a non-profit organization. That process is very complicated and requires a lot of upkeep even if Alacritty would somehow be able to magically achieve it.

It's not actually. You file a document with your secretary of state and pay a small fee for the filing. The fee does not go to Apple. Then you file a document with the IRS to receive the tax-id number. Finally you file another document with the IRS to designate your corporation as 503(c) a non-profit. You can pay a registered agent to do this for you for a few hundred bucks and they have all the templates setup and often turn things around within hours (for the initial state filing, at least, IRS stage usually takes a few days). The only hurdle would be that you need more than one member on the board.

**Comment by chrisduerr** [comment]
> Right clicking the application and selecting open no longer whitelists the app in the latest version of macOS.

It works just fine for me on the latest macOS version.

> It's not actually. You file a document with your secretary of state and pay a small fee for the filing. The fee does not go to Apple. Then you file a document with the IRS to receive the tax-id number. Finally you file another document with the IRS to designate your corporation as 503(c) a non-profit. You can pay a registered agent to do this for you for a few hundred bucks and they have all the templates setup and often turn things around within hours (for the initial state filing, at least, IRS stage usually takes a few days). The only hurdle would be that you need more than one member on the board.

You're aware that not everyone is from the US, right? Difficult concept to grasp, I know.

**Comment by dcow** [comment]
> It works just fine for me on the latest macOS version.

Probably because it's already whitelisted or you've disabled gatekeeper previously. I have tried it twice today on a fresh install to no avail.

> You're aware that not everyone is from the US, right? Difficult concept to grasp, I know.

There are contributors here in the US as is one of the two Alacritty gh-org members, I checked. Don't patronize me.

Anyway it doesn't matter. Apple allows you to provide a DUNS number. dnb (the organization that provides the number) is a global business registry. All you have to do to get one is upload two legal documents with you business's name and they'll send you one for free. I don't know what country you are in, but you simply register as a business and submit two legal docs. Going that route is potentially even easier than a US 503(c) with a tax-id.

I offered to help since I _am_ in the US, have easy access to incorporation services, and because I've done this before. But you're just being dismissive and condescending so I don't really know how else I can help, and I can't say I'm super interested in engaging with this project anymore at that. Thought it would be fun to switch to a rust-based terminal emulator as my daily since I'm working on a few rust projects now and I've used Alacritty on Linux here and there but I don't really see the point in expending the effort just to be received this way.

**Comment by chrisduerr** [comment]
> There are contributors here in the US as is one of the two Alacritty gh-org members, I checked. Don't patronize me.

No member of the Alacritty organization other than me is currently active.

> I don't know what country you are in, but you simply register as a business and submit two legal docs.

Sure, will you be paying the money required to do that? It's only around 25,000 initial capital required. You can hit up your lawyers to set that all up, so I don't have to waste my development time doing so. Let me know once you're done.

**Comment by dcow** [comment]
> Sure, will you be paying the money required to do that? It's only around 25,000 initial capital required. You can hit up your lawyers to set that all up, so I don't have to waste my development time doing so. Let me know once you're done.

Looks like the initial capital requirement is only 10.000 rubles to form a closed JSC in Russia. That's 137 USD. There are "legal service providers" that offer incorporation services for a flat rate, not exorbitant personalized lawyer fees, and take care of all the paperwork. Or, one could just pay Apple $99 and forget about it. I guess the point is you seem to consider it a waste of development time if you expend effort properly distributing macOS release packages which makes it hard to feel like any such support from my end along those lines would be appreciated and utilized at the moment.

But for the record yes, I was considering donating up to about 300 USD plus my time for non-profit incorporation services.

> No member of the Alacritty organization other than me is currently active.

I mean this is news to me and is a _real_ problem with going the business route. I thought this was a healthy/bigger project with a group of active contributors that might benefit from having a backing foundation. If it's not then I agree setting up a non-profit just to avoid a single contributor paying Apple Inc. 99 USD is rather silly. It would make more sense for me to just fork the thing and release notarized macOS binaries, for example.

If things change with the health of the project then we can discuss a backing foundation and developer program membership fee waiver assuming the existing contributors remain or future contributors would be ideologically opposed to funding Apple Inc but collectively still wish to ship a cross-platform application to achieve the marketing goals of the project. In the mean time you might just recommend that macOS users build from source since everyone is allowed to distribute locally to their own machine with a free developer account.

**Comment by chrisduerr** [comment]
> assuming the existing contributors remain or future contributors would be ideologically opposed to funding Apple Inc

Just to be absolutely clear here: Even if there was someone willing to donate 99/year to get Alacritty notarized, I would refuse it simply because the entire notarization and apple developer account thing is a scam. If at some point supporting a platform costs me significant money and time besides just writing the code for it, the solution for me would be to simply drop that platform rather than invest that time and money. If a company does not want open source applications on their platform, that's on them.

**Comment by msanders** [comment]
I agree with @dcow that the response to this issue has been disappointing and unnecessarily hostile to macOS users. Would also be willing to contribute to setting up an org as a solution to the opposition in paying the developer fee. In the meantime one of the following can be used as a temporary hack to allow opening the app:

```
brew install --cask alacritty --no-quarantine
```

or

```
xattr -rd com.apple.quarantine /Applications/Alacritty.app
```

or

```
spctl --add /Applications/Alacritty.app
```

**Comment by dcow** [comment]
> the solution for me would be to simply drop that platform rather than invest that time and money. If a company does not want open source applications on their platform, that's on them.

This is my whole point, drop support for macOS if Apple rubs you the wrong way! Don’t grief macOS users by claiming to support a platform you don't actually support. Stick it to *Apple*, not their users. 

And then a community of macOS users can work on maintaining a port if so desired and it’s not your concern anymore.

**Comment by nixpulvis** [comment]
OK, I've tried to sum up my feelings on this subject and it turned into a whole essay. Feel free to read [the whole thing](https://nixpulvis.com/ramblings/2021-02-02-signing-and-notarizing), but I suspect you (@dcow and @msanders) already know most of this. I'll copy the final section here, since it's the most relevant to the discussion on this issue.

-----

**Distribution support is not the same as the software support itself.**

Just as some software may not be included in a package manager of specific flavors of Linux, some software may or may not be packaged with signatures and/or notarizations. In both cases, the underlying software can still be fully compatible with the platform, even being tested effectively (developers generally compile from source themselves). Both package manager submission and package security features are separate from the development of the application itself. In many cases, the packager is even a separate person from the development team.

It may be fair to say that both software support and distribution support fall into the category of "fitting in with the ecosystem". For some software, this fitting in is crucial, while for others it may matter less. A lot of great software aims to be platform agnostic, which can already be a challenge to achieve for the application, let alone the distribution.

For Alacritty, perhaps the most widely used cross platform terminal emulator, being platform agnostic is very important to us. With that in mind, it should be understandable why we are resistant to adding too many features to our codebase which only work for specific platforms, and why we generally avoid dealing with distribution issues at all.

At the very least, distribution support implies software support. Which means, if you're going to start somewhere, you had better get the software itself working. Distributing broken software would be useless. It also should help you understand that some software may still work, even if installing it may be a bit different than you expect.

Of course in the case of Alacritty, **it is open source**, so there's never anything stopping you from pulling down a version and building it yourself. This is how I install it, and is probably the best way to do things in general. If build times are a concern of yours, then there may be hoops to jump through (like passing the `--no-quarantine` flag), but that's not stopping you from using the software either.

**Comment by nixpulvis** [comment]
So fun fact. I just had a friend test out downloading one of our releases with `curl` (or `wget`), and the quarantine flag wasn't set. It would seem applications like Firefox and Homebrew are setting these things themselves to play along with macOS.

Since the goal is to run a terminal emulator, it seems reasonable to recommend downloading the application from the terminal (probably Terminal.app) in this case too! We're no stranger to these tools.

Anyway, hope that gives you a more ergonomic installation workflow.

**Comment by dcow** [comment]
@nixpulvis thanks for the thoughtful reply. It's worlds different from the vibe one gets when spelunking the issue tracker. And I'd say that's exactly the core of the problem here. We don't disagree, distribution is a different effort from development. However, multiple people have offered to help with the macOS _distribution_ side of things and been met with callous replies to the tune of "piss off macOS idiots we're never going to bend to Apple's will your offer is declined and unappreciated". The response has not been *"hey thanks, we're swamped with development but we'd love some help figuring out macOS distribution can you propose a solution",* or even *"hey, we're focusing on locking down core functionality first and then there will come a time to worry more broadly about distribution, but not right now",* both absolutely reasonable and probably acceptable for most macOS users. So it's no wonder that people get the feeling macOS is not truly supported when contributors are berating community members for using it.

Anyway, I'm happy to hit reset on the whole issue of tone (I think the message is clear) if your example represents a change in attitude surrounding working with community members who are trying to make it easier to run this software on the systems it supports. You're also right, it's not hard to build from source or install using `curl` or remove the quarantine attribute (I'm no stranger to doing all these things, albeit newly back on macOS, so the reflex had languished). Overall I simply think people want to help close the gaps so that Alacritty feels like a first class macOS experience.

**Comment by chrisduerr** [comment]
You **cannot** help with notarization, that's against the whole principle of notarization. Anyone interested in helping is just a third party that cannot be trusted. You're just making the situation worse.

Everyone is free to redistribute Alacritty and notarize it themselves. If brew wants to do that, I'd encourage that. If someone wants to coordinate with brew to do that, it's up to brew to verify the trustworthiness of that individual. But nobody in here suggesting to assist is in any position to help with distributing an officially notarized version of the application.

**Comment by dcow** [comment]
> Anyone interested in helping is just a third party that cannot be trusted. You're just making the situation worse.

What is open-source software, if not a collaboration between a bunch of parties towards a shared goal?

> If brew wants to do that, I'd encourage that. If someone wants to coordinate with brew to do that, it's up to brew to verify the trustworthiness of that individual.

`brew` doesn't notarize, it would be up to the package maintainers to do so. `brew` provides flags to remove the quarantine attribute on casks, apparently.

> But nobody in here suggesting to assist is in any position to help with distributing an officially notarized version of the application.

I don't see how that's accurate. Whatever or whomever builds the project releases simply needs to submit the binary for notarization during each release build. This is a single command on a macOS box. You can rent a cloud mac mini for like $0.10/hr. And people have offered to cover the developer membership, help setup the infrastructure, etc. Or, they could just do it themselves and pass the notarized binary back to you and you can verify the signatures have not changed pre/post notarization (minimal work on your part) as can anybody who would trust you to publish a release SHA even if they don't have a clue who owns the developer account that ultimately requested notarization. You're acting like we don't have software solutions to verify binary integrity when multiple parties are involved. And hey if we're working together as part of the community here, the idea is the community sees this and trusts _us_ (not just you) as wardens of the release (so it's ultimately a non-issue who holds the developer account membership as long as the community trusts, well, the community).

Finally, you're kinda missing the big point on notarizing which is that _Apple_ is attesting to the integrity of the binary (not the "untrusted" third party) and they are "sealing" (signing) it so that a user explicitly doesn't need to fully trust random people on the internet and so that tampering of the application on the filesystem is not possible. The notary system Apple has devised inarguably operates to combat the proliferation of malicious software on their platform by making it very hard to effectively spam low quality software or repack applications. It doesn't matter if you or I ultimately notarize a binary anyway provided what most people are looking for in notarization is the tamper-proof and static analysis seal by Apple.

You're making this harder than it needs to be for idealogical reasons. You don't _want_ to see the value in Apple's platform, and so it will remain impossible to have a productive discussion on this front so long as you remain stalwart. My evidence that this can work is all the other open source projects that manage to ship notarized releases on macOS.

**Comment by nixpulvis** [comment]
Let's talk briefly about Trust.

If you trust Alacritty on faith (without vetting the code) then you are implicitly trusting the developers. Notarization requires a build which we provide to be signed off by Apple. However, none of the existing developers want to deal with this notarizing stuff. So what do you do?

With typical features in the open source world, the developers review and essentially accept patches as thier own. Gradually growing the community while building trust.

Here however, you are proposing (for only the low monthly payment of ~$8.25) an essentially random packager should be trusted with everything we submit to Apple/Microsoft. These are the same builds people are trusting on faith from above. So now they are trusting the developers + a new packager, and perhaps hoping that Apple will magically catch any malfeasance they might try. Doesn't something sound fishy about that?

Meanwhile, no value is added from our perspective through all this. We aren't in the business of making malware. We expect people to understand what their terminal is doing, and probably be able to dig around in the source if they are curious. We welcome that, since the more people in the code the more likely actual progress will be made on the project. It seems highly unlikely that Apple's review process would be anything but a nuisance for us. And paying for a certificate is just pay to play for developers. Yes it limits the damage malware developers can inflict, but it also ties our hands. If we are truly expected to do this there needs to be a better solution. Luckily it remains possible, and frankly quite easy, to accept our build for yourself by flipping the quarantine flag manually. If you are scared away by the warning, or angry at the additional flag you need to pass or command you need to run, that's really your problem not ours.

Maybe one day there will be a better solution for notarizing open source applications. I know we are not the only ones who are not satisfied with the status quo.

I've given this a decent bit of my time today, and I cannot promise I'll respond much more unless there's something new to discuss. I fear we may just be going in circles around each other at this point.

**Comment by nixpulvis** [comment]
Actually, I'll say one more thing.

If someone wants to work together with the brew folks to make a build that they use to provide the cask, I see no issue with that from our end. I think that's what chris was referring to in his comment.

As long as people are getting the releases in a timely fashion, I'm happy.

**Comment by nixpulvis** [comment]
Attempting to fix messaging in #4758.

**Comment by msanders** [comment]
> So fun fact. I just had a friend test out downloading one of our releases with `curl` (or `wget`), and the quarantine flag wasn't set.

This is news to me, when first reading I assumed it was from the `spctl developer-mode enable-terminal` setting but looks like that's not the case. It seems to happen from any terminal emulator too, including Alacritty when it's unsigned which is surprising.

> It would seem applications like Firefox and Homebrew are setting these things themselves to play along with macOS.

Firefox is signed, and by default Homebrew preserves quarantine attributes for applications.

```
$ brew ls --versions --cask firefox
firefox 85.0
$ spctl -a /Applications/Firefox.app 2>/dev/null && echo signed
signed
$ xattr /Applications/Firefox.app
com.apple.FinderInfo
com.apple.quarantine
$ codesign -dv --verbose=4 /Applications/Firefox.app
Executable=/Applications/Firefox.app/Contents/MacOS/firefox
Identifier=org.mozilla.firefox
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=863 flags=0x10000(runtime) hashes=18+5 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=720896
Hash type=sha256 size=32
CandidateCDHash sha256=d1c9a300bcd4c0ce89a1dab8bf788b5eb153bd4b
CandidateCDHashFull sha256=d1c9a300bcd4c0ce89a1dab8bf788b5eb153bd4b1672304fe06b4393600fa30a
Hash choices=sha256
CMSDigest=d1c9a300bcd4c0ce89a1dab8bf788b5eb153bd4b1672304fe06b4393600fa30a
CMSDigestType=2
Page size=4096
CDHash=d1c9a300bcd4c0ce89a1dab8bf788b5eb153bd4b
Signature size=8939
Authority=Developer ID Application: Mozilla Corporation (43AQ936H96)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jan 18, 2021 at 09:14:39
Info.plist entries=25
TeamIdentifier=43AQ936H96
Runtime Version=11.0.0
Sealed Resources version=2 rules=13 files=82
Internal requirements count=1 size=188
```

They specifically worked around the above behavior with curl to mitigate issues being reported with malware. See https://github.com/Homebrew/homebrew-cask/pull/22383, https://github.com/Homebrew/homebrew-cask/issues/22388, https://github.com/Homebrew/brew/pull/4656, and a write-up on their stance [here](https://github.com/Homebrew/homebrew-cask/blob/15846c21d279d2cc5fee56b4114479a29bc28c16/doc/faq/apps_with_malware.md).

One option might be convincing the Homebrew devs to allow including the `no-quarantine` option with cask formulas, although that may be a tough case to make since I'm not sure how many applications need it that wouldn't be better addressed by signing. Currently on my computer there are only two apps that ship unsigned releases: Alacritty and Chromium.

As it is the `brew install --cask --no-quarantine` command isn't a great solution since it breaks upgrades and can't be included in a `Brewfile`. Since Homebrew already checks SHAs after downloading I agree there isn't much of a security benefit in Alacritty's case from notarizing when used with that installation method. Not sure how common that is for Alacritty though, seems like it would be more frequent for users to download the disk image from their browser.

**Comment by nixpulvis** [comment]
> spctl developer-mode enable-terminal

_Wow, this is a new one for me. I have no idea what this is supposed to do exactly but holy shit I don't like the sounds of `enable-terminal`..._

Anyway, I looked into how `brew cask` works, and indeed, they simply set the `kLSQuarantineTypeWebDownload` for cask downloads by default themselves.

https://github.com/Homebrew/brew/blob/f33dc70e856540ba300400e3ceb34ac84e49ee2b/Library/Homebrew/cask/utils/quarantine.swift#L19-L32

I would therefor assume, any application which can download a binary (or create one) can bypass all of this nonsense with ease. And, any binary that *is* quarantined, was downloaded with a compliant downloader (for better or worse).

> As it is the `brew install --cask --no-quarantine` command isn't a great solution since it breaks upgrades and can't be included in a Brewfile.

Sounds like a brew issue.

> One option might be convincing the Homebrew devs to allow including the `no-quarantine` option with cask formulas, although that may be a tough case to make since I'm not sure how many applications need it that wouldn't be better addressed by signing.

This option could improve our use case, since indeed you wouldn't need to know to type `---no-quarantine` in order to install. However I suspect in order to implement this brew would probably want to offer their own warning. Maybe, that helps the situation, maybe not... this issue seems endless. What's next, issues titled "homebrew thinks Alacritty is malware"?

My advise is still to download the source and run `make app` yourself. But if you must use the packages, it's still just the way things are going to be on macOS now, you need to run `brew` with the `--no-quarantine` flag.

**Comment by msanders** [comment]
> Wow, this is a new one for me. I have no idea what this is supposed to do exactly but holy shit I don't like the sounds of enable-terminal...

The full name of the setting is "Allow the apps below to run software locally that does not meet the system's security policy", with Terminal.app included as an option under System Preferences > Security & Privacy > Privacy. Presumably it's for command line utilities downloaded by a browser. I don't have it enabled personally.

> Sounds like a brew issue.

It is to an extent, although they're coming from a place of dealing with actual malware rather than ideological concerns. Maybe we can convince them to at least address these two issues if they can't fix it in the formula itself.

> What's next, issues titled "homebrew thinks Alacritty is malware"?

macOS already displays this for all users in its system alert shown in the first screenshot in this thread. Even if Homebrew works around it it's likely to be the most common experience with new users assuming they're downloading directly from GitHub using a browser.

> Meanwhile, no value is added from our perspective through all this. We aren't in the business of making malware. 

Most malware on macOS are trojan horses from altered software, typically virus scanners or system cleanup tools. See [here](https://resources.malwarebytes.com/files/2020/02/2020_State-of-Malware-Report.pdf) for a 2019 report. The main value for Alacritty would be improving onboarding experience since it's rare and ill-advised for users to have these checks turned off.

**Comment by matekelemen** [comment]
### If you're just here to get alacritty working on MacOS

**Just [build from source](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#macos)**; it's not much more difficult than installing it from `brew` or downloading it through your browser, and you won't have to dirty your security settings.
- `brew install rust`
- `git clone https://github.com/alacritty/alacritty.git` (I recommend checking out the latest release branch)
- `cd alacritty && make app`
- `cp -r target/release/osx/Alacritty.app /Applications/`

Works without a hitch, at least on my machine™.

### My 2 cents on the whole fiasco

Alacritty runs just fine on MacOS, so why shouldn't it say so? It's truly nuts to expect people working on a pet project to to either spend a significant amount of money or do a mountain of paperwork, just to save typing a few extra characters during the installation/update process on a specific platform. Sure, the developers' response could've been less impulsive, but they do have a point.

**Comment by dcow** [comment]
You can "have a point" without actively being hostile to macOS users when they offer their time/help to get things working better, or accept the PR to update the docs with one sentence that points macOS users in the right direction when installing the official release build instead of closing it out of spite. There is no excuse for the hostile behavior which has continued even after the maintainers said they'd like to reset and start over on the tone.

Also consider this: of all the other applications people running macOS use and love on a daily basis, Alacritty  is the *only one* that claims macOS support but that doesn't have a notarized official release and requires users to jump through additional hoops to run. So while "just build from source" is a workaround, it's far from achieving the happy flow thats 100% possible without inordinate time and effort if only the maintainer was open to working with macOS users who have tried to step up and help get the issue solved in the past.

If I'm going to be installing a project from source it's a different vibe for me. It puts me more in the mindset that this is a project I can hack on. And if that's the case then it better have a community that will will at least treat users with respect instead of insulting them because of the OS they're using. Sadly, I've moved on to `kitty`: https://sw.kovidgoyal.net/kitty/

<sub>Also if you're seriously using Rust then please use `rustup`, not `brew`, to install the rust toolchain (:</sub>

**Comment by msanders** [comment]
Homebrew has now added an option for Brewfiles:

```ruby
cask "alacritty", args: { no_quarantine: true }
```

I've since moved on as well and currently use the stock Terminal app for improved Little Snitch compatibility, which was nontrivial to workaround (when using tmux all processes are treated as distinct leading to extraneous alerts, and [reptyr](https://github.com/nelhage/reptyr) which might fix it is currently incompatible with macOS, but according to the devs Little Snitch may still have issues with Alacritty even with that addressed due to it not being signed).

**Comment by kchibisov** [comment]
> There is no excuse for the hostile behavior which has continued even after the maintainers said they'd like to reset and start over on the tone

Yet, I'm the only person who actually fixes bugs on macOS even though I don't use macOS and some things I patch inside the kvm or on some old hardware which apple refuse to provide support for anymore. The amount of patches from macOS users was always close to no
existence. No-one actually cares about their stuff being solved on macOS from the users.

>Also consider this: of all the other applications people running macOS use and love on a daily basis, Alacritty is the only one that claims macOS support but that doesn't have a notarized official release and requires users to jump through additional hoops to run

Do you understand that maintainers don't **owe** you anything and that asking us to pay `99$` to Apple **a year** is just wrong? We write software not to get recognition, earn respect, or anything like that. We right it because we just want to have something good for ourselves which is public so others can use. We don't want to sell anything or *rule the world*, we write software we use daily ourselves.

We do self sign, we accept patches (unless it's something like 'change icon because macOS changed its design', so every app in existence should change their design), but in the end of the day, see who fixes most stuff in alacritty on macOS, a person with a macOS hardware from a decade ago (me).

>Also if you're seriously using Rust then please use rustup, not brew, to install the rust toolchain (:

This is so wrong, use whatever you want to install rust. I always used the package manager for that, because it's manageable that way, but brew is not a package manager, so I understand. Better than running `curl | sh` and what rust-lang suggests though.

**Comment by matekelemen** [comment]
> You can "have a point" without actively being hostile to macOS users

We agree on that.

> of all the other applications people running macOS use and love on a daily basis, Alacritty is the only one that claims macOS support but that doesn't have a notarized official release

I'd be amazed and disappointed if that were true: amazed at just how much power Apple has over the open source sector, and disappointed by the servileness of developers. 

> If I'm going to be installing a project from source it's a different vibe for me. It puts me more in the mindset that this is a project I can hack on.

The Apple ecosystem lacks a concept like the AUR that would allow users to install unvetted software at their own risk. Building from source is just a less convenient way of doing just that, nothing more, nothing less. That said, no-one is preventing you from hacking on the source or forking the project if you don't share the maintainers' views.

> Also if you're seriously using Rust then please use rustup, not brew, to install the rust toolchain (:

Thanks for the tip! I'm not planning to seriously use Rust though.

**Comment by msanders** [comment]
> Yet, I'm the only person who actually fixes bugs on macOS even though I don't use macOS and some things I patch inside the kvm or on some old hardware which apple refuse to provide support for anymore. The amount of patches from macOS users was always close to no
existence. No-one actually cares about their stuff being solved on macOS from the users.

It's hard not to read this as, "The hostile behavior is justified, because we no longer get many contributors for this platform." Personally I was initially very interested in contributing but felt deterred after seeing these exchanges.

> Do you understand that maintainers don't owe you anything and that asking us to pay 99$ to Apple a year is just wrong?

A maintainer above explicitly said cost was not the issue after people on this thread offered to help pay for the fee or setup an organization to avoid it. It's been three years since this issue was created an there's not even installation instructions on how to workaround notarization.

**Comment by kchibisov** [comment]
>It's hard not to read this as, "The hostile behavior is justified, because we no longer get many contributors for this platform." Personally I was initially very interested in contributing but felt deterred after seeing these exchanges.

it's a statement of fact as of today. I never discouraged anyone to send patches and finished contributors work myself over the years lots of times.

>A maintainer above explicitly said cost was not the issue after people on this thread offered to help pay for the fee or setup an organization to avoid it. It's been nearly three years since this issue was created and there's not even installation instructions on how to workaround notarization.

Well, each maintainer is free to do what they want. @chrisduerr has principles and I'm banned from paying apple and I don't feel like I should try my way to avoid ban. So...

**Comment by dcow** [comment]
You can have principles and also not shit on people trying to contribute to your project who have slightly different ones. You can say I don't do macOS stuff but I'll work with you if you want to help improve things for macOS users. Chris did the opposite: "fuck you this project doesn't care about macOS". 

And the reason I'm recommending not using `brew` to install rust is because thats not what beginners should do. If you're hung up on piping a script to bash you're straight up stuck in security theatre land acting like piping to bash is different than downloading a script and running it. Seriously think about it...

**Comment by kchibisov** [comment]
>You can have principles and also not shit on people trying to contribute to your project who have slightly different ones. You can say I don't do macOS stuff but I'll work with you if you want to help improve things for macOS users

If you can point to the PR for macOS where I 'shit on people' I'd like to at least see that, because I don't remember anything like that. Unless you're talking about the icon which
is a 'nonsense' and we even suggested how to solve it.

>And the reason I'm recommending not using brew to install rust is because thats not what beginners should do. If you're hung up on piping a script to bash you're straight up stuck in security theatre land acting like piping to bash is different than downloading a script and running it. Seriously think about it...

folks not using rust should install rust from the package manager, since the installation is far more secure that way. But that's another topic. rust != rustup, you can surely install just a rust compiler + cargo without any tool to manage its toolchain downloads. Also, rustup is not a script it's an rust binary, the package manager could at least verify signatures when downloading stuff.

**Comment by chrisduerr** [comment]
> Chris did the opposite: "fuck you this project doesn't care about macOS".

Made it so clear and somehow you still didn't get the message. If you don't like it, just move on. And rather than being a macOS terminal, I'd rather categorize Alacritty as a Linux terminal that works on macOS, that's what I've used it as in the past considering all the "macOS first" terminals suck.

**Comment by dcow** [comment]
Nobody is asking this project to be Apple first. Where did you get that idea? Some stupid assumption in your warped mind about the intentions of macOS users no doubt.

We did move on.

**Comment by nixpulvis** [comment]
The dream I always had was that in building a good terminal for Linux, which is often much less prescriptive of it's applications (though not always, looking at you Gnome), it would provide a solid base for supporting other platforms like macOS and Windows. In fact, one of the things I like most about Alacritty is that it's able to run on both my Mac and my Windows machines, even if these aren't my primary computers.

If you search through the massive list of issues in this repo, you'll find that many macOS spesific issues have been resolved, as well as many which have been closed ass "wont fix" because they would involve too much platform specific attention. I think this is a very sane approach to a cross-platform terminal emulator. If you read through the code and look for `cfg` compiler switches for the various platforms, you may become a bit more sympathetic to the maintenance burden that is imposed upon the developers.

Long ago I tried to settle some of the sentiment here by writing up post about what notarization is, and why we don't bother with packaging in general. @dcow, you seemed happy enough with my writing, but seem caught up on "sentiment".

At this point, I suggest anyone reading this should realize that sentiment is bad because the topic has been closed for well over 2 years and the developers are sick of arguing about it.

Still nothing is stopping anyone from running the applications if they want. We should be more focused on actually building features and fixing bugs.

Friends, I'm sorry for continuing this thread, but I just felt compelled to reply.

**Comment by unphased** [comment]
Hi guys, i see a lot of advice saying to `make app`, supposedly that works around, but I built from source with cargo and trying to open the .app results in this every time: 

<img width="364" alt="image" src="https://github.com/user-attachments/assets/9e2b1456-7cd4-4f67-a45f-f0b4b71512a3">

I have also run `spctl --add /Applications/Alacritty.app` and `xattr -rd com.apple.quarantine /Applications/Alacritty.app` as well as right click -> open, to no avail. On Sonoma.

**Comment by savoygrizzly** [comment]
The easiest fix would be to add a donation button to the repo, and Mac users can pay like half a buck or a buck to pay for the membership (which is not really that expensive when you look at the price of a coffee these days).

I don't really support apple's way of doing business for apps like this since I am sure more than many a dev working there uses Alacritty.

**Comment by SteveClement** [comment]
In 2025 on 15.3.1 (24D70) you can go into your "Privacy & Security"[keepScrolling] settings and just open it anyway.

**Comment by Valve** [comment]
I'm sorry for not  having read the entire thread, but man, this hostility to Mac users was disappointing.

**Comment by nixpulvis** [comment]
It's really Apple's hostility towards developers for this thread, which has incidentally and along with other things bred an unfortunate attitude towards macOS here.

**Comment by dcow** [comment]
MacOS users have showed up offering to *cover the cost of notarizing this project’s release* and even *do it in a way that doesn’t give money to Apple*.  I’m so sorry that effort has “bred an unfortunate attitude towards macOS here”. If this project had an emotionally mature and responsible maintainer this thread would have been locked years ago.

**Comment by nixpulvis** [comment]
Why does the thread need to be locked? You and I are free to unsubscribe if we wish. Nobody is harming anyone else here as far as I can tell. We just have different opinions of what's agreeable for a software project to do to distribute software.

**Comment by dcow** [comment]
Stop sea-lioning.
