### ISSUE TITLE
Command line --option issue or feature request

### ISSUE THREAD

**Issue by dork3nergy** [alacritty/alacritty#4701]
Not sure if this is a bug or not if you do :

`alacritty --option colors=*some-scheme`

it does not override the colors: *some-scheme" in the config file.

This is also true for a --option import=whatever.yml

It seems like top level config items cannot be modified from the command line.  Would be nice if they were.

Cheers.

### System

OS: Linux
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: ArcoLinux

Error : Invalid CLI config option: "colors=*gruvbox"

**Comment by chrisduerr** [comment]
You can only modify individual items. It sounds like you're talking about modifying the yaml anchor inside the file? That obviously won't work, since these configuration options are separate and have nothing to do with the file itself. You cannot link to something that doesn't exist.

If you want to modify the entire `colors` section, you'll have to change the entire `colors` section.
