### ISSUE TITLE
MacOS - Allow opening `*.command` files with alacritty?

### ISSUE THREAD

**Issue by tom-sherman** [alacritty/alacritty#4722]
Right now macOS doesn't let me select alacritty to register against this file type 

![image](https://user-images.githubusercontent.com/9257001/105159277-cc45f400-5b06-11eb-9498-d115641dadc5.png)

### System

OS: macOS
Version: 0.7.1

**Comment by chrisduerr** [comment]
What exactly is a command file supposed to do and why would Alacritty have anything to do with what it's allowed to open?

**Comment by tom-sherman** [comment]
@chrisduerr I believe it's essentially a macOS alias of `.sh`. The core problem here is that you can't register any files to open with alacritty on an ad-hoc basis or by default. I assume there's some macOS configuration that needs to be packaged with the app to allow this, I'm no mac dev though so not 100% sure.

**Comment by chrisduerr** [comment]
What would you expect to happen when you open a `.sh` file with Alacritty? That doesn't make much sense to me.

**Comment by jansol** [comment]
Opening a .command or .sh or such file in the native Terminal.all and iTerm.app is basically equivalent to `alacritty -e $filename`

**Comment by chrisduerr** [comment]
Why would you do that when what you pass is not a shell?

**Comment by ulisesvina** [comment]
> Why would you do that when what you pass is not a shell?

He just said what he's passing is a shell script. `.command` (files with that extension) are a macOS alias for `.sh` in Linux or `.bat` in Windows, for instance. I think the expected behavior is to pull up Alacritty on double click or right click -> open and execute the script automatically.

**Comment by chrisduerr** [comment]
Well that makes no sense.

**Comment by tom-sherman** [comment]
It makes no sense and yet both the built in mac terminal app and iTerm2 behave this way, okay then...

**Comment by nixpulvis** [comment]
I'm not sure I'd say it makes no sense, since the behavior is somewhat clear. However, it should be noted that there are two very different ways for a terminal to act upon receiving a file path.

1. Effectively just pass the path to the `-e`, `--command` argument, which would require the file to be an executable
2. Write the contents of the file to STDIN, thus depending on the default shell of the terminal

I know that on Windows you can double click `.bat` files and get into a console. That said, I just tested this on macOS with a `.sh` file and it didn't work at all. A `.command` file (as requested in the issue title) did work only after marking the file as an executable, which leads me to believe that macOS's Terminal.app is doing option 1. This is a relief, because option 2 honestly feels weird to me.

As for if I think it's worth implementing this. I'm very indifferent. As a Linux user who operates mostly from the command line, I don't personally have a use case, and furthermore would find it generally better to launch applications using the shell. I can see how some users are accustomed to opening applications through desktop environment as well though.

**Comment by chrisduerr** [comment]
A shell script doesn't need a terminal to be executed. The only reason why you would want that is if the script was a shell itself and I doubt anyone is doing that.

**Comment by nixpulvis** [comment]
> The only reason why you would want that is if the script was a shell itself and I doubt anyone is doing that.

Not all commands must be "shells", in fact Windows attaches a lot of things to a console. You may call this a bug more than a feature, and I would be hard pressed to really argue, but it's true. Generally speaking though, I can see the value in launching terminal applications directly, even bypassing a shell.

**Comment by jonahclarsen** [comment]
Just wanted to add my two cents. Alacritty would have been perfect for my use case were it able to open shell scripts like native MacOS Terminal, iTerm2, and Hyper when called like `open -a Alacritty "/path/to/script.sh".`

I like its customizability and speed, but unfortunately this was essential to me. I'll spare you the details of my situation, but basically I needed to launch a python process as sudo from another program *via a shell script* (since it has to run sudo, and running it sudo directly without first calling a non-sudo shell script has MacOS would interrupt the user, which is not acceptable in my case, while with visudo I can make the first script run sudo with no interruptions), and have it output to a console.

Hopefully this is a feature you'll consider adding in the future (at least for .sh files).

**Comment by kchibisov** [comment]
>Edit: I was able to get around this by running open -a "/path/to/Alacritty.app" --args -e "/path/to/script.sh". I still see no reason why it shouldn't behave like native MacOS Terminal, iTerm2, and Hyper and just do that by default when trying to open a .sh or .command file with it.

alacritty has extensive CLI, you can run `./alacritty msg` or `./alacritty config` to use `IPC` communications, the subcommand name could have a collision with your script and it's not future compatible if we try to extend CLI interface. Using `-e` is essential to have clear intention on what user wants to do. Also mostly all terminal emulators on other platforms use `-e` or `--command` option, it's just macOS terminals defined such behavior.

**Comment by kchibisov** [comment]
>Edit 3: Again found a workaround, by duplicating Alacritty.app and running the second command pointed at the new .app. Again this shouldn't be necessary as the typical behaviour of other terminal emulators are to open a new window and run the new script.

That's just home macOS behaves when you do `open`, if you want a new window. Maybe there's a way to somehow get the intention from macOS on what it wants to do, but you're on your own here. If you want a new window from existing alacritty instance you can do `alacritty msg create-window -e YOUR_COMMAND`.

**Comment by jonahclarsen** [comment]
@kchibisov Thank you for that! That was very helpful - looks like Alacritty actually does work for my needs.

I am having trouble finding documentation on the CLI arguments (-e, -T, etc.), and there are a few more I want (specifically ones to set the window size, but maybe others too). Do you know where I could find a list of all available CLI arguments?

**Comment by kchibisov** [comment]
`alacritty --help`.

**Comment by MrGru** [comment]
<img width="408" alt="image" src="https://github.com/alacritty/alacritty/assets/3302193/8e60e6c3-9fbf-4f50-bc52-bba74b32887c">
The document “launchPackager.command” could not be opened. Alacritty cannot open files in the “Terminal shell script” format.
