### ISSUE TITLE
Missing Wayland Input Redraws

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#4736]
I just updated to `alacritty 0.8.0-dev (530de000)`, and while using Wayland I now experience an issue where Alacritty seems to be missing redraw requests. Input will be received correctly, but the display isn't updated until another input is received. This causes the display to lag behind my typing (for example) by exactly one keystroke.

**Comment by nixpulvis** [comment]
This issue seems to be caused by the latest commit (530de000).

**Comment by chrisduerr** [comment]
> This issue seems to be caused by the latest commit (530de00).

That doesn't surprise me, I expected there to be a few bugs with how big this change was. The terminal damage tracking code has been removed so all the damage tracking is now done through `Wakeup` events and externally in the UI. I'd assume that's probably the most likely candidate for this regression.

**Comment by chrisduerr** [comment]
Can you maybe check where it is getting stuck at? I'd assume the `draw` function is never executed and it will return `false` on the dirtiness check?

**Comment by virus-found** [comment]
Hi, I'm experiencing this as well. And would like to provide an information to help to resolve the issue.

> Can you maybe check where it is getting stuck at? I'd assume the draw function is never executed and it will return false on the dirtiness check?

Though, I have no idea how to check this.

**Comment by j0ni** [comment]
I hesitate to comment here, because a couple of things in my situation are very different.

I saw and see this input lag (exactly one keystroke) too, but I see it running Alacritty on X11 and not Wayland - everything is good on Wayland - and I also saw it several days ago, so before this commit mentioned by @nixpulvis.

Some additional info for my case - when the terminal is tiny (20 columns, 10 lines) it is completely fine. It starts happening when the window is larger, typically 50+ columns.

I only see this happening on one particular machine - a brand new Dell XPS 13 (9310) - which has a lot of teething problems anyway, such as poorly supported networking, power management, and what seems like instability with the i915 drivers, though where exactly in the stack that is I don't know. I mention this because there may be several disparate causes in my case.

Anyways, if you have a recipe I can use for tracking down where this happens, I would love to provide a trace.

**Comment by chrisduerr** [comment]
> Edit to add - I'm using Alacritty 0.7.1 on Arch Linux.

This is exclusively about the latest commit on master.

**Comment by nixpulvis** [comment]
@chrisduerr OK, my preliminary investigation led me to the the order in which `draw` and the `Receiver` end of the `event_loop::Notifier` are being called. On X11 everything looks normal:

```
received_char
write_to_pty
drain_recv_channel Msg::Input
draw
```
However on Wayland, the call to `draw` comes in before the `Msg::Input` is received.

```
received_char
write_to_pty
draw
drain_recv_channel Msg::Input
```

I can recall the details of how the notifier is scheduled at the moment, but I can try and continue looking into this if you'd like me to.

**Comment by chrisduerr** [comment]
> I can't recall the details of how the notifier is scheduled at the moment, but I can try and continue looking into this if you'd like me to.

I'd love that if you've got the time to do so. Of course I'm open for questions if you have any.

~~Generally they `Input` itself shouldn't matter, since of course all input goes through the PTY before mutating the grid state.~~

~~So for input to be relevant, there should be a `Wakeup` after it has been processed. It might be necessary to put debug statements on the wakeup send and receive end to see if the wakeup coming after the PTY update might just be dropped.~~

Oh, I think I just realized the bug. We need to move the `dirty` flag from being active within just one event loop iteration to just be available for the entire execution by storing it on the `Processor`.

See this part of the code: https://github.com/alacritty/alacritty/blob/master/alacritty/src/event.rs#L1095-L1099

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/pull/4741 should fix this, testing would be appreciated.

**Comment by mckellygit** [comment]
@chrisduerr, hi
I tested this commit and it is MUCH better now, feels like the issue is fixed.
thx again for awesome alacritty,
-m

**Comment by shoober420** [comment]
This is fixed for me too.
