### ISSUE TITLE
Macro support

### ISSUE THREAD

**Issue by dmoa** [alacritty/alacritty#4749]
There doesn't seem to be an option to create a macro in Alacritty.
E.g. F4 puts "build.bat\n" into the terminal.

I know this is a minor thing, but I think it could be very useful.

**Comment by nixpulvis** [comment]
@dmoa this should be what you are looking for:

```yaml
  - { key: F4, chars: "build.bat\n" }
```

**Comment by dmoa** [comment]
Oh thank you!
My apologies.

**Comment by dmoa** [comment]
@nixpulvis  \n Doesn't seem to work though, is there an alternate?

**Comment by nixpulvis** [comment]
I tested it on Linux, perhaps you are on Windows. Does `"\r\n"` work for you?

**Comment by dmoa** [comment]
\r\n works for me, thank you.
Any reason why \r is required?

**Comment by nixpulvis** [comment]
Wikipedia has a pretty good rundown on the situation [here](https://en.m.wikipedia.org/wiki/Newline). But basically, in the old days things were modeled after typewriters. `\n` was akin to activating the roller to advance the line (aka. newline), while `\r` was used return the carriage back to it's starting position on a line (aka carriage return). Since these are two different mechanical actions they are two separate control characters.

These days, we don't generally use typewriters so many systems have taken to interpreting `\n` as a newline which also resets the column. Windows however, is somewhat weird in this respect.
