### ISSUE TITLE
I Confirmed Installation Process Works for RHEL 8

### ISSUE THREAD

**Issue by TheCedarPrince** [alacritty/alacritty#4757]
I followed your build instructions and can confirm everything works for RHEL 8. Would you like a PR to update the docs to say that your build process holds true for RHEL 8?

**Comment by nixpulvis** [comment]
I'm not sure I understand what would be the contents of this PR. We already have https://github.com/alacritty/alacritty/blob/master/INSTALL.md#centosrhel-7, which mentions RHEL 7, would we just need to update that to say 8 now?

**Comment by TheCedarPrince** [comment]
Precisely @nixpulvis - the same set of instructions also works for RHEL 8 so it would be a super small docs PR.

**Comment by nixpulvis** [comment]
It's probably easier for you to just open the PR and let us review it there then, since it's impossible to know if we want to update the docs or not without knowing what the proposed change is. Seems like we might just need to bump a single number? or add a "/8" to a line in INSTALL.md, but I'm not sure what else you have in mind.

**Comment by TheCedarPrince** [comment]
That is exactly what I have in mind @nixpulvis - I'll go ahead and open a new PR either today or tomorrow.

**Comment by chrisduerr** [comment]
RHEL 7+ is probably the easiest solution. I don't want another PR once RHEL 9 comes along. :)
