### ISSUE TITLE
[macOS] alacritty window doesn't move once decorations:none is set

### ISSUE THREAD

**Issue by sonntaghimself** [alacritty/alacritty#4825]
Once I set decorations to none, I'm unable to move the window in any way.
I'm used to using magnet, to manage my windows, but I'm unable to move the alacritty window in any way.
Does anyone have a solution?

### System

OS: macOS 11.2.1
Version: alacritty 0.7.2

**Comment by chrisduerr** [comment]
You should be able to move Alacritty windows even without decorations? It works just fine for me. You should be able to do so by grabbing on to the top edge of the window.

**Comment by rbong** [comment]
Same issue on Windows 10 (10.0.18363 Build 18363) with Alacritty 0.7.2:

Cannot change window with keybindings (WIN+up/down/left/right), cannot change window via the bottom bar (context menu has most options greyed out, "move" option is available but doesn't work), cannot click on the border to change size.

I don't know if this is possible to fix but it would be great if it is. Also let me know if I should post a new issue - I know window management is probably different on Windows/Mac but I didn't want to post a duplicate in case it's related.

**Comment by ngerritsen** [comment]
I have a a similar issue (I'm on macOS Big Sur). When I set decorations to none, I can **resize** the window by grabbing the edges but not **move** it in any way. This makes it so that when you switch screens you basically have to restart Alacritty. 

Another notable thing is that the window manager app I use (Moom) is also not able to control the Alacritty window, but Amethyst (a tiling window manager for macOS) IS able to manipulate the Alacritty window.

I hope this information helps, it would be very nice if this would be possible tofix, I really love Alacritty so far!

**Comment by BingchenLi** [comment]
It works for me by doing:
1. Moving the cursor to the top edge of the alacritty window
2. When the cursor turns into double-arrow, then click and hold. Now you can drag the window.
Get the solution here https://apple.stackexchange.com/questions/261785/how-to-drag-window-from-anywhere-on-the-window-without-using-the-title-bar 
macOS: Catalina 10.15.7
alacritty 0.8.0

**Comment by imcodingideas** [comment]
macOS: Big Sur 11.4
Magnet: 2.6.9
Alacritty: 0.9.0

When I have **decorations:none** set I cannot use the windows hot keys to move around the window. I use Magnet on Mac. When I set it back to full it works like normal.

Regarding @BingchenLi's suggestion. It doesn't work in this scenario because both me and @sonntaghimself use Magnet to move the window. Not dragging the window.

**Comment by rbong** [comment]
The given solution also does not work on Windows

**Comment by applericky** [comment]
To provide an update. Magnet has issues with certain applications when adjusting the window. On the FAQ page of their website it says certain apps will not work. I can confirm that window management works with Hammerspoon and Rectangle. Both are free on Mac.

**Comment by ckgresla** [comment]
Setting `decorations` to `buttonless` solved the issue for me -- able to resize windows with Magnet and move the window with the mouse on MacOS Monterey 12.3.1

**Comment by kc0btp** [comment]
I'm on macOS Tahoe. When I set the decorations to buttonless, it was hit-or-miss trying to move the window by grabbing the top portion of the window. Even if I successfully managed to move the window, it would also select text in the window, and frequently do so while scrolling back a bunch in the buffer.

I learned today, after using Macs for over thirty years, that you can hold ctrl+cmd then click **anywhere** in a window, which "lifts" the window and lets you move it around easily with the mouse. It works perfectly with Alacritty and pretty much every other app I've tried.
