### ISSUE TITLE
"Plugin framework?" or... making Alacritty user-extensible.

### ISSUE THREAD

**Issue by Sleepful** [alacritty/alacritty#4844]
I know Alacritty aims to be minimal and stay out of the way of features, but some people like those features and having the option to add them as "plugins" or anything similar is very neat and huge driver of open source projects.
Is extensibility part of Alacritty? If not, are there plans to make it so?

Extensibility through programming is the best customization any application can reach and the reason Free Software makes it through the decades.

**Comment by Sleepful** [comment]
It would also qualm people like [this](https://github.com/alacritty/alacritty/issues/1309).

**Comment by Sleepful** [comment]
I just noticed that the thread I linked seems to be a "yes" to my question, because of this comment https://github.com/alacritty/alacritty/issues/1309#issuecomment-388952254.

I'm curious if there's any progress on it, or if it's even a goal still.

**Comment by nixpulvis** [comment]
@Sleepful if you look at the way we've designed our code you may find a sizable portion of it is in `alacritty_terminal` which is not concerned with things like the window at all. In many ways this already realizes your ideals of Free Software (not to mention our [vte](https://github.com/alacritty/vte) crate).

If you want tabs, you could do what I do and rely on your window manager. If you're stuck on macOS there's #1544.

**Comment by nixpulvis** [comment]
Since there's no specific extensibility being requested here that's not already handled by other issues, I'm going to close this issue.

**Comment by Sleepful** [comment]
@nixpulvis
From https://github.com/alacritty/alacritty/issues/1544:
> Tabs just aren't something that should be supported in a terminal emulator. It's just a waste of effort since it's very complex and completely unrelated to the issues a terminal emulator actually needs to solve

But what if I *do* want to implement tabs *inside* the terminal? 
What if I want to implement my own "[leader key](https://stackoverflow.com/questions/1764263/what-is-the-leader-in-a-vimrc-file)" for terminal keybindings? 
What if I want to add new fields for the configuration file that aren't currently part of Alacritty?
What if I want to add animations to the terminal?

**Comment by nixpulvis** [comment]
What is stopping you?

**Comment by Sleepful** [comment]
> What is stopping you?

Missing some sort of "plugin api". Forking the project and having to keep-up with up-stream is not my favorite way of extending software. And making PRs to this repo with said ideas doesn't seem feasible either because it goes against the project's minimalist design goal.

**Comment by nixpulvis** [comment]
@Sleepful

- But what if I do want to implement tabs inside the terminal?
Tabs are really not the concern of the terminal emulator, and there are already open issue about how to handle this.

- What if I want to add new fields for the configuration file that aren't currently part of Alacritty?
Technically, today you can add whatever fields you want to the config, they just wont do anything.

- What if I want to add animations to the terminal?
What does this even mean? Are you going to build VLC inside the terminal? Why?

- What if I want a hotkey that cycles through different color themes?
This is perfectly possible today.

- What if I want to implement my own "leader key" for terminal keybindings?
I actually think that out keybindings are the first place that could benifit from a slightly more powerful configuration language. It might allow for something like this, and it could make the complexities of existing and future features easier to configure. However, it's no small task even changing this, since we don't want someone changing their config with a `loop {}` and complaining that their terminal is frozen.

**Comment by Sleepful** [comment]
@nixpulvis Here is what you are saying: 

> "We don't really care how you would like to extend our project, unless it aligns with the way that *we* want to extend it"

I don't care that you don't want trailing animations for your cursor, I really don't expect you to. Why are you trying to tell me whether my ideas are good ideas or bad ideas? That's not the point. The question was whether you care to develop/support a "plugins" API at all; which doesn't require an answer anymore.

**Comment by Sleepful** [comment]
I don't want a "workaround for tabs", I want to modify the behavior. Look at emacs as an example of what I mean.
