### ISSUE TITLE
Resizing width sometimes deletes lines

### ISSUE THREAD

**Issue by st3iny** [alacritty/alacritty#4948]
Scrolling and then growing/shrinking the window multiple times in succession will sometimes delete one or more lines from the buffer. This seems to be somewhat random and I couldn't reproduce it every time.

Here is an example where multiple lines vanish:

https://user-images.githubusercontent.com/1479486/113577001-d913b780-9620-11eb-8560-23ccaa0abcd0.mp4

### System

OS: Linux
Version: master cbcc12944006603131119b73c2ad72ebccf4562d
Linux/BSD: Wayland, GNOME

**Comment by st3iny** [comment]
@chrisduerr As discussed in https://github.com/alacritty/alacritty/issues/4944. Most of the time just one line gets deleted below the viewport.

**Comment by chrisduerr** [comment]
How far back can you reproduce this issue? I'd assume this is due to your multi-line prompt and always has been a problem. Which would mean there's no solution to this.

**Comment by st3iny** [comment]
Yes, you are right. I can reproduce this on my installed version aswell: `alacritty 0.7.2 (5ac8060b)`. Why is there no solution?

**Comment by chrisduerr** [comment]
> Why is there no solution?

Because Alacritty is both resizing the content of your prompt and your shell is redrawing the prompt on its own based on the assumption that the terminal did not resize the prompt.

All shells I'm aware of basically operate on the assumption that the terminal just truncates on resize. I've seen some patches floating around which fix this, but generally the problem is that the shell and the terminal have no way to synchronize this, so neither knows what the other one does.

Some terminals have a slight delay before resizing the content, giving the shell a short time to do its own magic first. But I haven't seen a single terminal with resize out there where you couldn't force this issue to happen. As long as you don't shrink your terminal below your prompt width, it shouldn't matter though. But especially with prompts floating at the right, that becomes problematic.

**Comment by st3iny** [comment]
TIL. Thanks for your detailed answer.
