### ISSUE TITLE
Unbind all default keybindings

### ISSUE THREAD

**Issue by klorax** [alacritty/alacritty#4970]
Hi,
how do I unbind/remove all default (non character insertion) key bindings / keyboard shortcuts?

As it is now, it is time consuming, trying to make sure every key is unbound in the right mode while not overwriting my own bindings at the same time. It would be slightly better if I could mark all keys for `ReceiveChar` action and then proceed to setup my own bindings, but that does not work, of course.

Is there any particular reason why the default bindings are [hard coded](https://github.com/alacritty/alacritty/blob/96fc9ecc9a62c8a766da745d05fbe60e6c2e1efe/alacritty/src/config/bindings.rs#L349) and not provided in an optional default config? If not, then please consider this a **feature request**.

Thanks!

**Comment by chrisduerr** [comment]
For most bindings the defaults should be irrelevant. Why exactly are you trying to unmap all bindings? If you want to overwrite an existing binding, you don't need to unmap the original first.

**Comment by klorax** [comment]
In my use case, I am rebinding most (~ 90%+) keys and the way to do it currently is quite prone to bugs, e.g.:
I mapped `Paste` to `Alt + V` and the different `Selections` to another key, and to not have any `Selections` left on `V` I mapped the different `modifiers` on it to `ReceiveKey` ... for some reason `Paste` did not work --- of course I had accidentally also mapped the `Alt` modifier to `ReceiveKey` (so it did that after `Paste`).

The thing is, it is just too much to keep track of reliably if you want to change most keys. I understand if this is something you are not interested in implementing, just thought I would ask: _if there could be a faster more reliable way to do it, or better yet, make the defaults optional._

**Comment by chrisduerr** [comment]
I'm not sure why this would make you remap 90%+ bindings, but I don't see much of a problem doing so. All you have to do is just copy the example config and change the action of the bindings.

**Comment by klorax** [comment]
I respect the wontfix, but I am not sure I follow you?

> I'm not sure why this would make you remap 90%+ bindings

I gave you an example of why it is difficult to do so, not the reason why.

The reason is that I use something similar to (in Emacs and everywhere else possible): [Vem](https://www.vem-editor.org/) or [Ergovim](https://www.hxa.name/articles/content/ergovim-key-mappings_hxa7241_2010.html).

Other reasons include: using different keyboard layouts or if some of the defaults would change (the user config then needs to be updated). But, I really do not see why any of this should matter.

> All you have to do is just copy the example config and change the action of the bindings.

Of course, this is what I have currently done, but like I said, it is easy to make mistakes. Also, I do not see the benefit of them being hard coded (except the fact that they already are and it takes work to change that, which I respect as a valid argument).

**Comment by unphased** [comment]
I need to prevent linux's alacritty default behvior of ctrl+= and ctrl+- from changing the font size, because i use ctrl+- without prefix to issue a tmux horizontal split! 

The thing that is really awkward here is that i would need to customize a bind in the config to set it to what the terminal emulator would emit anyway, which is something I now have to look up!

**Comment by unphased** [comment]
@kchibisov true but it doesn't work properly with <kbd>Ctrl</kbd>+<kbd>-<kbd>. I'll grant you it probably works as intended for most combos. I believe control minus is special because of the old ascii conventions and how only control underscore is a valid output and most terms i think make control minus do the same as control shift minus (e.g. control underscore). 

I am back on macos but i checked my commit and i left Control Equals set to ReceiveChar but I dont use that for anything so I can't confirm it works perfectly either.

**Comment by kchibisov** [comment]
yeah, because `Control` is not affecting the value of the `+` and `-` usually, you can see from `alacritty --print-events | grep text_with_all`, it'll show the strings you get originally from the windowing system (on linux, from libxkbcommon).

So if you don't see what you want, you should redefine to what you want, probably one of the reasons a lot of terminals bind ctrl+- is because the don't do anything useful by default.
