### ISSUE TITLE
Alacritty dies when run from cmd.exe and then closing the cmd.exe window

### ISSUE THREAD

**Issue by fefe17** [alacritty/alacritty#5013]
I tried the 0.7.2 release and a binary I just cross compiled myself from Linux, same behavior.

If I start alacritty from explorer, no such problem.
If I start it from a command line window and then close that window, Alacritty ends too.

I have never seen this kind of behavior with any Windows GUI program before. Very strange.

**Comment by chrisduerr** [comment]
Sounds like I'd expect it to behave.

**Comment by bitraid** [comment]
That happens because it attaches to the console of the calling program, so it can be able as a GUI program to print to the calling console (although this is a little ugly, because the control has returned to the calling program).
If you don't want this to happen, remove these lines:
https://github.com/alacritty/alacritty/blob/11cbc439c8785ed937125e0ba2a60ef470564a5e/alacritty/src/main.rs#L70-L73

**Comment by fefe17** [comment]
May I ask why this is done in the first place?
Alacritty does not actually write anything to the calling console as far as I can tell. If there is an error in the config file, it will display it in its own window in a bar at the bottom.

Also, can you please turn this into an option that I can turn off?

I'm frankly baffled you'd expect this behavior. If I run firefox from cmd, or gvim, or literally anything other than alacritty, and then close the cmd window, that thing keeps running. What kind of convention of programs intentionally killing themselves off am I missing?

**Comment by bitraid** [comment]
Alacritty *does* write to the console with `--version`, `--help`, `--print-events`, and when it fails to start. The program doesn't "kill itself" - Windows does because the attached console has terminated. You can blame Microsoft for that, and the different way that programs behave when built for the CUI (character user interface) or GUI (graphical user interface) subsystem.

**Comment by fefe17** [comment]
OK, compromise:

When done with --version and --help and not running under --print-events, detach from the console again by calling FreeConsole()?

https://docs.microsoft.com/en-us/windows/console/freeconsole

**Comment by hissssst** [comment]
@fefe17 I am experiencing the same issue. Do you have a workaround?
By the way, why is this issue closed?

**Comment by hagaigold** [comment]
+1
any workaround around it?

**Comment by kchibisov** [comment]
Maybe `start alacritty.exe` will work, but I'm not on windows to try that.

**Comment by hagaigold** [comment]
> Maybe `start alacritty.exe` will work, but I'm not on windows to try that.

`cmd /c start alacritty.exe` seems to work.  
But I can't understand why just `start` wasn't enough for that.

**Comment by kchibisov** [comment]
maybe because the console is still attached.

It's the same on linux, we have `disown` for that things.

**Comment by hagaigold** [comment]
this what baffled me:
if just `start` keep it attached to the called console, why tunnel it thru `cmd /c` detached it?

`start alacritty.exe` - stay attached
`cmd /c alacritty.exe` - stay attached
`cmd /c start alacritty.exe` - **detached** from the called console

**Comment by bitraid** [comment]
> this what baffled me: if just `start` keep it attached to the called console, why tunnel it thru `cmd /c` detached it?
> 
> `start alacritty.exe` - stay attached `cmd /c alacritty.exe` - stay attached `cmd /c start alacritty.exe` - **detached** from the called console

Because with `start` cmd doesn't wait for alacritty, and with `/c` it exits before alacritty can attach to parent console (its parent is the second instance of cmd).

if you run for example (`^` is important):
`cmd /c start alacritty ^& pause`
You will notice that alacritty attaches to the console, and terminates when the console is closed.

Another way to test this, is by adding the `--help` argument to alacritty, and notice when you get output to the console and when not.

Also, this happens when you start alacritty from any terminal. For example, if you run alacritty and start from it another instance, closing the first instance will also terminate the second.

**Comment by kchibisov** [comment]
That's pretty much how it's supposed to work, no? We have the same on linux and it was like that since for ever.

**Comment by hagaigold** [comment]
> Also, this happens when you start alacritty from any terminal. For example, if you run alacritty and start from it another instance, closing the first instance will also terminate the second.

true, but not with `createNewWindow`..
