### ISSUE TITLE
Remove whitespace

### ISSUE THREAD

**Issue by palsivertsen** [alacritty/alacritty#5014]
Is there any way to remove whitespace characters from the terminal. Copying from the terminal is annoying since long lines are split by new line chars. There's also padding at the end of every line, making it difficult to determine where a line actually ends:
![image](https://user-images.githubusercontent.com/11890143/116222736-23371700-a74f-11eb-98f0-1985f6d21c05.png)

Demo:
![Peek - alacritty whitespace](https://user-images.githubusercontent.com/11890143/116223210-980a5100-a74f-11eb-8443-2691ff588c15.gif)

**Comment by nixpulvis** [comment]
Related to https://github.com/alacritty/alacritty/issues/4812#issuecomment-789163793.

I also think there might be some possible improvement to the UX in this area.

It's kind of tough for me though, because on one hand, I think empty cells shouldn't act like something wrote a `0x20` to them. But, on the other hand, the terminal is a grid. I like how line selections span the full width (though perhaps that's just something I've gotten used to), and block selections are also more clearly highlighted as a rectangle.

**Comment by nixpulvis** [comment]
I'll also add, unless I'm missing something, it's impossible to select the last cell without also selecting a newline character.

**Comment by chrisduerr** [comment]
As stated in previous issues, this is not something I'm interested in changing at the moment.
