### ISSUE TITLE
- import: does not support environmental variables/relative paths

### ISSUE THREAD

**Issue by salopst** [alacritty/alacritty#5017]
### System

CPU: Dual Core Intel Core i5-6300U (-MT MCP-) speed/min/max: 629/400/3000 MHz
Kernel: 5.11.0-7612-generic x86_64 Up: 5d 22h 38m Mem: 9966.1/23773.2 MiB (41.9%)
Storage: 447.13 GiB (191.6% used) Procs: 399 Shell: Zsh inxi: 3.1.07

### Logs
No such file or directory (os error 2)

### Problem

at the head of $XDG_CONFIG_HOME/alacritty/alacritty.yaml I am trying to call in `colors.yml` ...

```
import:
  # - "$XDG_CONFIG_HOME/alacritty/colors.yml"   # no work
  # - "$HOME/.config/alacritty/colors.yml"   # no work
  # - ~/alacritty/colors.yml"    # no work
  - /home/salopst/.config/alacritty/colors.yml    # works
```

It would appear that only the absolute path works.

**Comment by nixpulvis** [comment]
@salopst first of all, you must make sure you have a recent enough version of Alacritty.

Second, you are missing a component of the path starting with `~`. It **should** match the following line (since `~` just expands to `$HOME` or `/home/slopst` in your case). You also seem to have some quoting issues... Anyway, try this out.

```
  - ~/.config/alacritty/colors.yml
```

As for environment variables and relative paths in general, see #4157 for previous discussion.
