### ISSUE TITLE
Alacritty freeze

### ISSUE THREAD

**Issue by hissssst** [alacritty/alacritty#5174]
### Summary

This happens rarely, about 2 or 3 times in a day. This happens only with alacritty
Terminal is not responding to any keyboard events, resizing and closing

### System

OS: Linux
Version: `alacritty 0.8.0 (a1b13e68)`
Linux/BSD: wayland, sway

> Is there any other information I can collect for this issue and how can I do this?

https://user-images.githubusercontent.com/37012324/119395136-9f773880-bcc2-11eb-829d-e9b425814ba8.mp4

**Comment by hissssst** [comment]
I will try to switch to current master for a few days and see if this issue can be reproduced

**Comment by chrisduerr** [comment]
So on resize the terminal stops responding to key/mouse events and further resizing?

**Comment by hissssst** [comment]
@chrisduerr , no, it stops responding on everything

I've just found out that this happens when I immediately press `Ctrl+Shift+V` (which is bound to `Paste`) after starting the terminal

**Comment by chrisduerr** [comment]
Does this only happen immediately after startup? How "immediate" are we talking?

**Comment by hissssst** [comment]
I've reproduced it on master right now
`3e867a056018c507d79396cb5c5b4b8309c609c2`

> Does this only happen immediately after startup?
Yes

> How "immediate" are we talking?
I don't know how to answer this. I am just pushing `Win+Enter` and immediately `Ctrl+Shift+V` without leaving the keyboard
This happens when shell is not initialized, so it is about 100ms

**Comment by chrisduerr** [comment]
Can you get me a backtrace of where Alacritty is stuck using `gdb`?

**Comment by gaving** [comment]
I've noticed this on Windows but finding it hard to reproduce, will check out the logs if it happens again and hope there's something in there!

**Comment by cdecompilador** [comment]
Its happening also to me, pretty annoying but hopefully 1-2 time per day

**Comment by guildem** [comment]
I have it on an updated archlinux host, I open alacritty, CTRL+SHIFT+V, and nothing is responding, I can't close it without killall.

Started with 'alacritty -v', nothing happens when I press the keys.

**Comment by ArmandXiao** [comment]
Yeah, this problem is pretty annoying... It happens on Windows 11 also. Usually when you open the terminal up to an hour. Then it may happen to me.

**Comment by Jiruu246** [comment]
This also happens to me. After I try to run multiple instances of Alacritty on Awesome wm, nearly half of them freeze immediately. it happens frequently and is extremely annoying

**Comment by chrisduerr** [comment]
@Jiruu246 Are you also on Wayland? Unfortunately I'm not able to reproduce this on any system.

**Comment by Jiruu246** [comment]
> @Jiruu246 Are you also on Wayland? Unfortunately I'm not able to reproduce this on any system.
I do some debugging and found that ibus is the reason why Alacritty freeze. 
Remove these lines from my .bashrc solves the problem

`export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx`

**Comment by chrisduerr** [comment]
That would be very interesting. Can someone else confirm this is related to IME?

**Comment by hissssst** [comment]
@chrisduerr , I don't use IME. This bug still occurs, from time to time
Awesome WM is not Wayland

**Comment by dhedlund** [comment]
This has also been happening to me for months on Linux, maybe a couple years.  It used to occur once a week or so, but has increased in recent weeks and got as bad as multiple times per hour; I had to temporarily switch from alacritty to kitty for day-to-day use, which has been stable.

My original assumption was that it had something to do with the OpenGL rendering because I would see the same random window freezing in some electron apps such as slack if I had multiple electron apps open with alacritty.  Things seemed to have gotten a lot worse around the time that Firefox switched to EGL about a month ago; I might have had hardware rendering disabled in Firefox before when it was using GLX, but I'm not certain.  I believe wayland also uses EGL, which leads me to the suspicion that it has something to do with EGL.  Keystrokes are not registered and no long messages are recorded after the freeze.

My setup is xmonad with a dozen workspaces across two monitors.  At any one time I'm running about 15-20 alacritty windows and am constantly switching between workspaces.  Freezing tends to occur when switch between workspaces, especially ones that have either Firefox or electron apps open.  If I have three alacritty windows open on a workspace, there's a good chance that when one terminal on the screen freezes, that 2-3 of them will.  Most of the time it's just the terminal windows on that screen that freeze, but freezing does come in clusters where it will become contagious; more terminals will usually freeze after switching between workspaces a few more times if I leave the frozen windows open, but this might be coincidence.  The frozen alacritty windows will not repaint, so if I switch to another workspace and back, whatever was on that other workspace will show where the frozen alacritty windows are.  Nothing I do such as resize or move them to another workspace will ever cause them to repaint again; they will continue to show whatever was at those coordinates previously.

I'm not sure it's hardware related, at least not with a specific GPU.  My desktop has a Radeon 5700 XT GPU with FreeSync enabled, using the amdgpu kernel driver.  A laptop that I use much less frequently has an Intel integrated GPU.  I've seen it occur before on both when hooked up to my external gaming monitor.  I made a number of hardware and firmware changes a couple weeks ago to diagnose a separate driver crash that occurred once every couple of days or so from GPU memory corruption.  I originally thought he crashes were related to a hardware fault in the video card, but turned out to be due to GPU-monitor synchronization (maybe due to FreeSync?).  All I know is that upgrading the monitor firmware seems to have somehow fixed that issue.  That got me wondering about whether this could also be an related to FreeSync, maybe a combination of the two.  The Intel GPU also supports adaptive sync.  I never thought to disable FreeSync on the monitor to see if it would fix alacritty until recently, after temporarily switching away from alacritty.

When looking into this a couple weeks ago, I tried running alacritty with logging turned way up and stdout/stderr of all terminals redirected to a file.  There was nothing out of the ordinary, the logs just suddenly stop.  While writing this message, I switched back to alacritty to see if I could reproduce the issue since it had been happening so frequently, but no crashes in the last couple hours.  I'll report back if I can reproduce the issue.  I'll try to get a stacktrace of each thread and check if attaching strace to the frozen process will emit any syscalls when the terminal is manipulated after the freeze.  Anything else I can do to help with debugging this?

**Comment by chrisduerr** [comment]
There is https://github.com/alacritty/alacritty/issues/824 which seems to only happen on X11 systems, so I'd redirect any X11 users to that issue.

But it sounds like with Wayland the only way this happens is with IME?

**Comment by gilbsgilbs** [comment]
I am using X11 and I am also affected by the very same symptoms. I don't think my issue is related to #824 as a keypress is not enough to redraw. Even WM events seem ignored by Alacritty and I need to trigger a signal (sigterm at least) from another terminal session to actually close the frozen window. I have a few other relevant details to add:

- If I have multiple Alacritty processes running, they are all freezing at the same time. I can start new Alacritty processes and they are not frozen, but already frozen ones remain frozen until killed. Could some Wayland user confirm (or deny) that it's the same symptoms for them?
- I've been able to get a gdb backtrace from a frozen Alacritty process: [bt.log](https://github.com/alacritty/alacritty/files/7775248/bt.log) [bt-full.log](https://github.com/alacritty/alacritty/files/7775249/bt-full.log). (built against 3af1940192245f96f0b7c8e2d2d5c4a5d8eb98a1) I hope this is exploitable.
- I feel that programs with "curses-like behavior" (sorry if there's a more appropriate term for that) are more susceptible to produce freezes: less, git log, paginated gdb logs, interactive progress bars… But that could be biased.
- I've been using Alacritty for months without any issue and the random freezes started to affect me just a few days ago. Something may have changed in my configuration, but I haven't been able to figure out what yet. I'm still investigating.
- I'm using X11, i3wm and Compton. Yeah, only legacy stuff, sorry about that. I hope that's still the same issue affecting you, folks from the future using Wayland. I'll probably try to stop my compositor in the next few days and see if it may be a cause to the problem. By the way, I use Arch.

Let me know if and how I can provide more helpful information. Thanks to all the contributors and maintainers doing an astounding work on this project.

**Comment by kchibisov** [comment]
The original issue is a duplicate of #2453
