### ISSUE TITLE
Word boundary not supported in hint regex?

### ISSUE THREAD

**Issue by guiniol** [alacritty/alacritty#5198]
Is it expected that the word boundary token `\b` is not supported in hint regexes?
AFAICT, the library does support it, but I could not get it to match.

My use case is matching links without the scheme in front.

### System

OS: Linux
Version: 0.9.0-dev (3e867a05)
Linux/BSD: X11, i3wm

**Comment by chrisduerr** [comment]
You have to use `\\` for the regex escapes, since we're talking about a string in yaml which itself uses `\"` as an escape.

If you use `\\b` like that, you should get the error that word boundary assertions are not supported, which comes straight from the regex-automata library.

So it would have to be fixed upstream, which you can maybe create an issue for. But I'm not personally invested in implementing that, I'm fine without support for it.

**Comment by guiniol** [comment]
Thanks for the precision.
I did find that the regex-automata says it support the same syntax as the regex crate which does support word boundaries, but you are right about getting an error message about it being unsupported when trying it out. So I'll see with the regex-automata crate, but I expect it is not a quick fix.

In any case, thanks for the super quick support, and for alacritty!

**Comment by guiniol** [comment]
Ah, found it in the regex-automata crate's README:
> This crate does not support zero-width assertions such as `^`, `$`, `\b` or `\B`.
