### ISSUE TITLE
Make mouse right click move nearest selection point instead of always moving the second point

### ISSUE THREAD

**Issue by tchici** [alacritty/alacritty#5252]
Currently (alacritty 0.8.0), using the right click on the mouse to adjust the selection always moves the second point of the selection. I think it would be more useful if it moved the nearest point of selection instead (like in xterm or vim with mouse enabled). This would allow adjusting where the selection starts from.

It's kind of difficult to explain, so I will provide an example and hopefully it will make it clearer. So, I want to select from one point back in the buffer to another point at the bottom. What I would do is left click on the start, then scroll down to the end and right click. Then, I notice the beginning selection was not quite right (e.g. missed a character). Using alacritty, I would have to repeat the entire process (since adjusting the initial selection position is not possible), but in xterm, e.g., I would be able to right click near the start of the selection, and it would know that I want to adjust where the start of the selection is. Of course, if I right click closer to the end of the selection, it would adjust the end position. Enabling mouse on vim has similar behavior to xterm as well (trying it for yourself might be better than trying to understand this).

**Comment by chrisduerr** [comment]
This was considered during the initial implementation and we've explicitly decided against this for the sake of predictability.

**Comment by tchici** [comment]
Maybe it should be a bindable action? The action would be something like "MoveInitialSelectionPoint," and it would always move the initial point.

**Comment by anarcat** [comment]
coming from rxvt, xterm, foot, and numerous other terminal emulators, i find that behavior baffling, and its explanation even more so:

> This was considered during the initial implementation and we've explicitly decided against this for the sake of predictability.

right-click selection extension is a strange user interface, when coming from classic (say GTK/Qt/Windows/Mac) user interfaces, where right-click typically pops a contextual menu instead of messing with the selection.

But it's a well established tradition that terminal emulators do this, and i use this all the time. Except I've been using this for decade precisely in the way you seem to describe as "unpredictable". I find the right-click behavior in alacritty to be at best inconvenient and at worst completely unpredictable. Perhaps it's me that's used to the old model, but i don't find this new approach either useful or more intuitive at all.

What i find useful with the right/left approach is that you can repeatedly refine the selection, character by character, unless you get it exactly right. This is much easier to do with a right click, as you can immediately see the effect of the selection. Now in alacritty, you have to immediately pick the right character and aim precisely well to start your selection, you can't fix it after you're start, which i find slows me down and adds cognitive load.

I urge you to reconsider, and at least make this configurable!

I'll also note that this is a similar breakage of POLA (Principle Of Least Astonishment) than the double-click selection in https://github.com/alacritty/alacritty/issues/4237.
