### ISSUE TITLE
Slow SGR parsing performance under heavy load

### ISSUE THREAD

**Issue by skyline75489** [alacritty/alacritty#5278]
### System

OS: Windows 10
Version:  0.8.0

### Description

This is a sister issue of #5266.

By using this benchmark software https://github.com/cmuratori/termbench/releases/tag/V1, on Linux I found that  rendering non-colored text is about 70x faster than rendering colored-text (release build, version 0.8.0 from PopOS repo)

Note that the benchmark currently can't run fully on Windows because of #5266. Still I am able to use VS to gather the performance trace of alacritty and this is what I got:

![image](https://user-images.githubusercontent.com/4710575/123376719-89a8ac00-d5bd-11eb-997f-9ff7ed75877e.png)

This shows that the CPU usage of VT parsing is a little higher than expected.

Note that this trace is gathered using Debug build, because with Release build some of the stack is not available. Based on my result on Linux mentioned above, I think it's safe to say that VT parsing still drags the rendering behind when the load is heavy.

**Comment by chrisduerr** [comment]
Running a trace on a debug build is completely useless. Chances are the issue of #5266 is because Windows' ConPTY is atrociously slow.

Depending on what escapes you use, it's no surprise that colored text is slower than non-colored, since the payload is obviously much bigger. So unless you have any concrete examples of troublesome escapes or evidence that other terminal emulators show a significantly lower load here I see no reason to action.

Our own benchmarks are run regularly and automatically and there's no evidence of any issues here.

**Comment by skyline75489** [comment]
@chrisduerr Thanks for the response. I'm rather new to Rust and didn't realize the debug build is not worth running benchmark on.

>on Linux I found that rendering non-colored text is about 70x faster than rendering colored-text

By saying "it's no surprise that colored text is slower than non-colored, since the payload is obviously much bigger", are you suggesting the 70x difference is within reasonable range?

**Comment by chrisduerr** [comment]
> By saying "it's no surprise that colored text is slower than non-colored, since the payload is obviously much bigger", are you suggesting the 70x difference is within reasonable range?

It depends on what you're doing. I haven't looked at the benchmarks you're running but I'm aware that with my own benchmarks there's nothing out of the ordinary. Have you tested other terminal emulators on Linux?

**Comment by skyline75489** [comment]
Yes. I also tested tilix, and it also shows about 40x - 50x difference. The benchmark basically produces a entire of changing SGR sequences like `\x1b[38;2;12;34;56;m` and  `\x1b[48;2;12;34;56;m` .

**Comment by chrisduerr** [comment]
And I'd assume you ran the benchmarks in release mode?

Looking at the character count alone with your escapes the parsing will take ~17x times that of plain text, just because the SGR codes you're using are so massive. Together with your tilix tests I don't see any particular reason for concern unless you have actually identified a concrete problem.

**Comment by skyline75489** [comment]
Thanks very much for the response @chrisduerr. I'll close the issue for now and reopen it when I find something concrete that can work on.
