### ISSUE TITLE
[Feature Proposal] Support display of relative numbers and navigation in `vi` mode

### ISSUE THREAD

**Issue by dofinn** [alacritty/alacritty#5292]
First of all thanks for making an awesome terminal emulator. This thing rocks!

In vi, you can `set relativenumber` which is extremely useful for navigating code from your current context. The requirements for this request would be:

* ability to configure relative number in config
* relativenumber is only present when entering `vi` mode
* bonus: ability to navigate with vim keys with relative numbers. 

  * Eg: `5k` would move 5 lines up from current cursor position. 
  * Eg: `22gg` would move cursor to line 22 on screen (22 would be relative to cursor position)

Would be interested to know your thoughts on a proposal like this.

**Comment by chrisduerr** [comment]
Even though I do use relative line numbers myself in vim, I think this goes beyond what is reasonable to implement in Alacritty for vi mode. Having to create a separate UI element to try and show them is just overly complicated and not worth the effort, especially since it would either overlay the existing text and hide content or move content around and potentially mess everything up.

**Comment by dofinn** [comment]
Fair enough @chrisduerr . Thanks for the response.
