### ISSUE TITLE
Scrolling in terminal scrolls Vi mode when display_offset != 0

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#5339]
To reproduce output something to generate scrollback and then do the following
```
sleep 5; ls -lah # Could use something else instead of ls to generate output
Enter Vi mode and move into scrollback buffer 
```

When output from `ls` or `cat ` appear the cursor will scroll for the amount of lines output, however it should stay still.

**Comment by chrisduerr** [comment]
Hm, I feel like that might actually be a tough one. Since the vi cursor position is absolute from the bottom of the grid, we'd have to determine the display offset at scroll time which seems awfully inefficient.

**Comment by kchibisov** [comment]
I feel like it was working the way I described before. At least in December.

**Comment by chrisduerr** [comment]
Before the grid indexing rework the vi mode cursor was viewport based, rather than using a global index. So that's why it worked before without any further trouble. Of course changing back to a viewport based indexing would be an option for the vi mode cursor.

This issue also allows the vi mode cursor to leave the viewport, which is problematic.
