### ISSUE TITLE
Tmux scrollback doesn't work

### ISSUE THREAD

**Issue by A1ex-N** [alacritty/alacritty#5374]
### System
OS: Windows (Using WSL)
Version: alacritty 0.8.0 (a1b13e6)

While using tmux in any terminal other than alacritty, i can scroll back through the history using the mouse scroll wheel. In alacritty, this feature does not work. I have no idea why

**Comment by chrisduerr** [comment]
Because Windows probably.

**Comment by A1ex-N** [comment]
> 
> 
> Because Windows probably.

Well that's a pretty piss poor excuse. Windows terminal, the WSL terminal, powershell terminal, they all work just fine. So instead of addressing the issue that alacritty has, you just say "because windows probably"

**Comment by dusanbrankov** [comment]
I'm running Linux Mint 21.2 and had the same problem. I was able to fix it by adding the following line to `.tmux.conf` and restarting the terminal:

```
set -ga terminal-overrides ',*256color*:smcup@:rmcup@'.
```

This will disable faux scrolling, which is enabled by default. I didn't have to change anything in my Alacritty configuration, but I thought I'd share this solution anyway, since this issue ranks high in search results.

Source: https://terkwood.farm/tech/tmux_alacritty_scroll.html
