### ISSUE TITLE
Add option for foreground opacity or option to apply background opacity to foreground of just powerline glyphs

### ISSUE THREAD

**Issue by reportaman** [alacritty/alacritty#5445]
``window.opacity`` coupled with ``transparent_background_colors: true`` works well for most cases except places like powerline where an illusion of shape/fake shape is created by matching the background color of some text with foreground of adjacent powerline glyph.

Here's an example:
![126858273-32b505ff-9e4a-44a4-948b-382d1e9ba5c7](https://user-images.githubusercontent.com/71736629/130546987-60be83cf-ecee-49c1-822e-8c23f86e8e10.png)

Here if the transparency of foreground of powerline glyph were the same as the transparency of background, the powerline shape would appear uniform. If its easier, perhaps there can be an option to apply transparency to all foreground colors with an option like: ``transparent_foreground_colors: true``. Or maybe just a ``transparent_powerline_glyphs: true``. Both the options will support in upholding the illusion of a uniform block/shape.

**Comment by chrisduerr** [comment]
If you want **everything** to be slightly transparent, you can use your compositor to do so. But I seriously doubt there's much of a point in doing so.

**Comment by jansol** [comment]
In the case of making **everything** transparent doing it in the compositor makes sense. But this issue is specifically about powerline glyphs which I'd argue are generally used as background elements although they use the foreground color due to technical limitations. #5795 special cases them to not use an actual font for drawing so I don't think it would be too far-fetched to also make their foreground color transparent when background transparency is enabled.
