### ISSUE TITLE
Neovim cursor change

### ISSUE THREAD

**Issue by x7429** [alacritty/alacritty#5450]
![screen](https://user-images.githubusercontent.com/62779661/130645954-b1446e3e-8c56-4ed6-9697-94a4c75fd384.png)
Alacritty refuses to keep the cursor shape (Underline) when exiting nvim.
This does not happen in vim.

**Comment by chrisduerr** [comment]
Because neovim requests a cursor shape change and doesn't reset it when leaving neovim. This is to be expected.

**Comment by McAuleyPenney** [comment]
For those who run across this in the future, there is a thread about this here: https://github.com/neovim/neovim/issues/6005
I chose to go with an adapted version of an autocommand mentioned in that thread. Below is the Lua version.

```lua
cmd
[[
    augroup change_cursor
        au!
        au ExitPre * :set guicursor=a:ver90
    augroup END
]] 
```

**Comment by 4volodin** [comment]
but the same after leaving LF (file manager)
It's stange the alacritty doesn't keep a cursor shape

**Comment by chrisduerr** [comment]
It has nothing to do with Alacritty. Alacritty just does what applications request.

**Comment by mrp4sten** [comment]
Ok but usgin Neovim with lua config, how can aI resolved this bug?

**Comment by mcauley-penney** [comment]
> Ok but usgin Neovim with lua config, how can aI resolved this bug?

1. This isn't a bug
2. This isn't related to Alacritty, so it doesn't belong here
3. I already posted about this [here](https://github.com/alacritty/alacritty/issues/5450#issuecomment-929797364), which I just updated to use the Neovim API.

**Comment by XavierFigari** [comment]
Hi there, if you come accross this problem, here's a summary of what was said above. This solution works fine for me.

Put this in your Neovim config (~/.config/nvim/nvim.lua) : 
``` lua
vim.api.nvim_create_autocmd("ExitPre", {
	group = vim.api.nvim_create_augroup("Exit", { clear = true }),
	command = "set guicursor=a:ver90",
	desc = "Set cursor back to beam when leaving Neovim."
}) 
```
Replace `ver90` above with whatever you like : 
```
	hor{N}	horizontal bar, {N} percent of the character height
	ver{N}	vertical bar, {N} percent of the character width
	block	block cursor, fills the whole character
```
(see https://neovim.io/doc/user/options.html#'guicursor')

In the end, when you exit Neovim (or vim), this will overwrite any setting you may have in ~/.config/alacritty/alacritty.toml , like : 
``` toml
[cursor]
style = { shape = "Beam" , blinking = "Off" }
```

But when you start Alacritty, and until you run and exit Neovim, it's important to leave it here. Make sure that the Alacritty setting here matches the Neovim setting. Since Alacritty does not seem to have as many options to set the cursor shape/blinking/color as Neovim, start by setting the cursor in Alacritty config, then set the equivalent in Neovim, according to the documentation above.

**Comment by chrisduerr** [comment]
> Replace ver90 above with whatever you like

Note that the 90 here is completely useless. It's always equivalent to 100.

**Comment by XavierFigari** [comment]
Is it specific to Alacritty, or do you know other terminals where the percentage value is taken into account ?

**Comment by chrisduerr** [comment]
> Do you know other terminals where the percentage value is taken into account?

I'd imagine the option exists for GUI frontends. I'm not familiar with any escape that would allow you to set cursor percentage.

**Comment by przepompownia** [comment]
Is it possible to query Alacritty about the current cursor shape before start (for example) Nvim (in a form reusable at its exit, e.g.`ver100`)?
