### ISSUE TITLE
Ubuntu doesn't detect Alacritty as a default terminal emulator

### ISSUE THREAD

**Issue by palolo330** [alacritty/alacritty#5591]
When finishing installing it i try to configure it as a default terminal emulator, but it doesn't appear, there's just the gnome-terminal. Also the tutorial i'm watching can open alacritty using the command ctrl + alt + t but in my case it only opens the gnome-terminal

**Comment by chrisduerr** [comment]
I'm not sure why you're "watching a tutorial" for installing a terminal emulator, but everything required for Alacritty is documented in the repository, including the desktop file setup and setting the default terminal emulator.

If you have any more problems beyond that, I recommend looking at documentation for your specific distro/DE, since it has nothing to do with Alacritty at that point.
