### ISSUE TITLE
pasting from clipboard into vim doesn't work properly

### ISSUE THREAD

**Issue by Cryp70m4n** [alacritty/alacritty#5636]
You can find my alacritty config on my github github.com/cryp70m4n/breaking_bad_rice
When I try to paste into VIM from clipboard it adds additional spaces to every new line if there was tabs in clipboard.

Tried using different terminal such as kitty and st and didn't had such a issue, I hope you will fix it soon.

**Comment by chrisduerr** [comment]
> You can find my alacritty config on my github github.com/cryp70m4n/breaking_bad_rice

Please try it **without** any config.

>  When I try to paste into VIM from clipboard it adds additional spaces to every new line if there was tabs in clipboard.

Could you be a little more specific? This sounds like paste/noposte mode.

**Comment by Cryp70m4n** [comment]
I tried removing config same thing happens, the wierd thing is it happens only when file has exstention which is valid, such as main.c, main.py, main.php,... it could be that alacritty doesn't work properly with some of my vim plugins but I tried using kitty with same plugins and pasting into main.c everything works perfectly fine with kitty while alacritty adds spaces/tabs for no reason.

**Comment by chrisduerr** [comment]
Yeah, this very much sounds like a lack of understanding vim to me. This certainly isn't an issue anyone else has ever reported before and Alacritty is almost exclusively written in vim.

**Comment by rahilarious** [comment]
@chrisduerr I have same problem happening on alacritty and st. On kitty and terminator it's working fine.

**Comment by zbyju** [comment]
I have literally the same problem. I use WSL2 and I whenever I try to paste from my Windows environment (e.g. try to copy from a browser and then paste) to Neovim it would paste it with additional lines (all lines would get an additional newline - could there be something wrong with CRLF?) and there would also be some additional lines at the end.

**Comment by hardyoyo** [comment]
Same problem here. It feels like a garbled connection to the clipboard... most of the text comes through, parts of the first line end up at the bottom of the pasted text block, sometimes randomly upcased. Cannot reproduce in Gnome terminal, so not a Vim thing.

You should probably re-open this.

**Comment by hardyoyo** [comment]
I believe I have found the root cause of this issue, and a better solution. It seems that Alacritty sets the environment variable TERM=Alacritty. That non-standard value for TERM seems to cause Vim to lose its mind, at least on Linux, and pasting to Vim gets really garbled. A nice workaround is to set TERM to something more common, I use TERM=xterm because that gets me higher contrast colors in terminal applications. I humbly suggest that Alacritty not set the TERM variable. Setting TERM=xterm resolves this issue for me. I will make a PR to remove setting the TERM environment variable.

**Comment by rigzba21** [comment]
I've been running into this same issue for a little while now (random missing characters from the beginning of pasted text).  I just tried out @hardyoyo's recommendation of setting `TERM` to `TERM=xterm-256color` instead of `TERM=alacritty`, and can confirm that I'm not experiencing the weird paste behavior.

My steps (on Ubuntu/PoPOS 22.04):
1. in a browser, copy some text with `CTRL+c` 
2. Open Alacritty and `export TERM=xterm-256color`
3. In Alacritty, open a file with `vim`
4. enter `vim` Insert mode and paste with `CTRL+SHIFT+v`

If I set the environment variable back to  `TERM=alacritty`  and try to paste in vim with `CTRL+SHIFT+v` I do get the weird paste behavior.

**Comment by kchibisov** [comment]
>That non-standard value for TERM seems to cause Vim to lose its mind

alacritty is not xterm, each terminal has their own terminfo entry. alacritty TERM is even a part of ncurses.

if `TERM` breaks something it's a vim issue, not alacritty one.

**Comment by hardyoyo** [comment]
Well, at least we have a documented workaround, and I can again paste in Vim. :-)
