### ISSUE TITLE
Environment variable support in configuration file

### ISSUE THREAD

**Issue by nodomw** [alacritty/alacritty#5673]
It would benefit a lot of people who use cloud services to store their configurations to use between more than 1 computer.

Aside from that, my problem is not with the storing of files. It's with trying to set the working directory to %USERPROFILE% (I know that YAML doesn't support values starting with % I just put it there for the sake of it.) or any other folder assigned with a variable.

using alacritty 0.9.0 (fed349a)
Windows 10 Pro 21H1

**Comment by chrisduerr** [comment]
Not going to happen.

**Comment by davidandreoletti** [comment]
@chrisduerr Would you mind sharing your rationale for not resolving $HOME or its Windows equivalent ?

I believe you have a good reason yet I don't see it.

**Comment by chrisduerr** [comment]
Determining where you should and shouldn't do it is almost impossible. We have a lot of strings so where exactly should we draw the line? NONE of our strings are actually invoked through a shell so we would need to expand things ourselves.

And which environment variables should get expanded exactly? Where are these environment variables inherited from? Systems like macOS likely don't have anything set where Alacritty gets launched from. How does this work when launched through IPC, do we take the parent process' env or the IPC's env? Do we share the entire env through IPC just to pull some variables out? Do the environment variables defined in Alacritty itself get considered for all of these strings? Then this post also talks about Windows environment variables, so do we support both Windows and Linux syntax? What about a Linux user who doesn't know anything about Windows env vars, why does he now have to escape things? How exactly are we going to escape things if people want the literals?

There's literally a billion implementation questions, which not only makes implementation difficult, but also makes it impossible for a user to intuitively figure out which options we picked for each of these choices. At the end of the day it's too complicated for anyone to use and just causes bug reports because things get incorrectly recognized as environment variables.

**Comment by davidandreoletti** [comment]
> And which environment variables should get expanded exactly?

@chrisduerr The scope is narrow: allow ONE variable to get resolved as:
- macOS: /Users/<my_user>
- linux: /home/<my_user>
- windows: _some windows user home path :-) _

For linux/macOS and any POSIX compatible OS:
- `$HOME` is the standard way to get the home dir path and is a [mandatory env variable](https://unix.stackexchange.com/a/123859/45954) for **logged in** users.
-- the **Alacritty GUI runs with my logged in user permission** (macOS > Activity > select the Alacritty process > user is my logged in user)
- In rust, [`home_dir`](https://doc.rust-lang.org/std/env/fn.home_dir.html) is deprecated. A replacement might be [`get_my_homedir`](https://docs.rs/homedir/latest/homedir/unix/fn.get_my_home.html).


For Windows,
- Others will chime in and provide the details.

> How exactly are we going to escape things if people want the literals?

For linux/macOS:
```
command = { program = "bash", args = [ "$HOME/code/project/.bin/opener" ] }
```

String replace `$HOME` with whatever `get_my_homedir` returns.

It will be important to document only this "env var: HOME" (or its windows equivalent) gets resolved dynamically.

> At the end of the day it's too complicated for anyone to use and just causes bug reports because things get incorrectly recognized as environment variables.

Not allowing users to specify a user local path for a binary file is - very confusing - in a user configuration file.

If $HOME (or its windows equivalent) is too complicated/platform specific:
- create one "ALACRITTY_USER_HOME" and doc where it resolves to per platform.
- have people use this variable/token in their path. Eg:

```
command = { program = "bash", args = [ "ALACRITTY_USER_HOME/code/project/.bin/opener" ] }
```
