### ISSUE TITLE
bindings: Selected mode

### ISSUE THREAD

**Issue by csimpi** [alacritty/alacritty#5763]
I would like to add a feature request. 

For the key bindings, there should be a `selected` mode which would work only when something is selected in the terminal.
Why is this would be important? 
Because it would be fun to know and react differently when I selected something on the terminal and handle the keyboard events that way.

**A real-life problem:**
It's very frustrating to use `CTRL+SHIFT+C` for copying instead of `CTRL+C`. 
On the other hand, we need `CTRL+C` to send `break` when something is running and we want to cancel.

**Solution:**
When something is selected on the terminal and push `CTRL+C` => Copy to the clipboard
When nothing is selected on the terminal and push `CTRL+C` => Send break message and cancel running

The only Terminal emulator I know that handles this perfectly is the PHPStorm's Terminal. I am looking for the same behavior.

If this can't work ANY other custom workaround is good for me, I just want to solve this really bad, that's why I installed Alactritty in the first place it seemed very customizable, but I don't find the solution for this problem.

**Comment by chrisduerr** [comment]
>  When something is selected on the terminal and push CTRL+C => Copy to the clipboard
>  When nothing is selected on the terminal and push CTRL+C => Send break message and cancel running

I have no intention of supporting this behavior, as stated in numerous other issues.

**Comment by csimpi** [comment]
@chrisduerr 
1. Please don't be rude, we are here to support your package
2. I asked for a workaround if you are not willing to support this
3. If many others asked for this as you mentioned why are you refusing to add this? This feels like you resist for no reason. This would mean a lot for the community. We don't ask for a permanent change, we ask for a setting, nothing else.

Please think again and let me know if I can help/solve this without your "intention".

**Comment by chrisduerr** [comment]
> Please don't be rude, we are here to support your package

Lol.

**Comment by csimpi** [comment]
@chrisduerr Nevermind I have no intention of using your software anymore when we have the same + much more: [Kitty](https://sw.kovidgoyal.net/kitty/overview/#configuring-kitty) <3 

It has a `copy_or_interrupt` action so I could solve what I wanted in 5 minutes. 
Your hype won't last forever...

**Comment by nixpulvis** [comment]
> I have no intention of supporting this behavior, as stated in numerous other issues.

@csimpi this is not an example of rude developer behavior. It's simply a terse description of the state of the developers opinions.

-----

I'm also frustrated by the state of control-c and have tried to think through some solutions. But as Chris mentioned, there are a bunch of issues already on this topic, and not even mentioning them is a bad sign here. Do your homework before coming to the developers asking for your idea to be implemented. I know it's a deep well of commentary, but that's why we need developers to exhibit restraint at times.

I think this issue (https://github.com/alacritty/alacritty/issues/1919) has some thoughts and references to other related issues if you were interested in reading the history here. But I wouldn't expect the default behavior of the terminal to be changing in this respect necessarily.

**Comment by csimpi** [comment]
@nixpulvis His tone was super rude. 

> I have no intention of supporting this behavior, as stated in numerous other issues.

Also, this wasn't even the question. But again as I said, I just use Kitty instead.
