### ISSUE TITLE
[Feature request]: action for changing between windows

### ISSUE THREAD

**Issue by Andras-Csanyi** [alacritty/alacritty#5786]
Hi All,

I'd like to setup key bindings for changing between windows/instances created by `CreateNewWindow` action. I haven't found any action doing this, so I assume it doesn't exist yet.

Key binding I need:
  - next window/instance: Cmd+RightArrow
  - previous window/instance: Cmd+LeftArrow

Thanks,
Andras

**Comment by chrisduerr** [comment]
Seems like something more window-management focused? Why would you expect Alacritty to do this?

**Comment by Andras-Csanyi** [comment]
Possibly I misunderstood something, or I use the wrong terminology. Or the terminology is right, just Mac does something Mac-ish thing.

Let me explain. On Mac the `CreateNewWindow` creates a tab - see the screenshot below -, and what I want is being able to switch between these tabs. In iTerm CMD-LeftArrow and CMD-RightArrow provides this. I don't know what `CreateNewWindow` does on Linux and/or Windows.

I hope it is clearer what I wanted to say.
<img width="1774" alt="Screenshot 2022-01-18 at 19 40 37" src="https://user-images.githubusercontent.com/5106373/149999498-03c1d48e-2434-4770-8bed-a16ba9d963c9.png">

**Comment by chrisduerr** [comment]
These tabs have nothing to do with Alacritty and are likely created by your system automatically. In facto on my mac `CreateNewWindow` will create a new window instead.

If there's some property one has to set or something like that to make this work, I'm open for PRs. But generally that's window management and system-level configuration thus shouldn't have anything to do with Alacritty.

**Comment by imomaliev** [comment]
Hi! Is there a way to switch to window using numbers? For example CMD+1 to first one, CMD+2 to second one etc.

**Comment by Andras-Csanyi** [comment]
> These tabs have nothing to do with Alacritty and are likely created by your system automatically. In facto on my mac `CreateNewWindow` will create a new window instead.

Whether the new window will be an actual new window or a tab is controlled by MacOS (System Preferences -> General -> Prefer Tabs).

> If there's some property one has to set or something like that to make this work, I'm open for PRs. But generally that's window management and system-level configuration thus shouldn't have anything to do with Alacritty.

I'm not aware of anything like this. MacOS is very clunky in window management for me.

**Comment by sshock** [comment]
Luckily the Cmd+Shift+[ and Cmd+Shift+] do work (see https://github.com/alacritty/alacritty/issues/1544#issuecomment-1052960158).  These shortcuts must be built into macOS.

Unfortunately, Cmd+1, Cmd+2, etc. aren't supported automatically, yet somehow the Terminal app is able to do it.  I would love to find out how it does that, then we could add, e.g., `SelectTab1`, `SelectTab2`, etc. actions that we could then hook up key bindings to.

On a related note, I would love to know if it is possible for alacritty to create a new window that is forced to not be grouped with the tabs; then we could add a, e.g., `CreateNewWindowNeverAsTab` action.  Then we could map Cmd+N to that one and Cmd+T to `CreateNewWindow` for a perfect setup.

**Comment by imomaliev** [comment]
If I am not mistaken, iTerm has this functionality. Here is repo https://gitlab.com/gnachman/iterm2. But I don't know where to look in source code.

**Comment by sshock** [comment]
@chrisduerr can we re-open this feature request?  It doesn't seem wrong to me at all that alacritty, which knows about all the windows it created, should not support the ability to show/focus a particular window.

winit does have a [focus_window](https://docs.rs/winit/0.26.1/winit/window/struct.Window.html#method.focus_window) method.  Although not supported on all platforms, it looks like it is supported on Windows, macOS, and Linux X11.

I would like to support the following actions:
* FocusFirstWindow
* FocusSecondWindow
* ...
* FocusNinthWindow
* FocusLastWindow
* FocusPrevWindow
* FocusNextWindow

Alacritty knows about all the windows it created (see Processor windows in alacritty/src/event.rs).  It seems like not a huge stretch to be able to show/focus one of them. The only tricky part may be that since `windows` is a HashMap, maybe alacritty doesn't currently know the order the windows were created/added, but it could keep track of that.

**Comment by chrisduerr** [comment]
Why should Alacritty have to bother with this at all though? Surely macOS has a way to switch through tabs in their own window manager? There's no way to just focus the first/second/whatever window when we don't even know the order of the windows.

**Comment by sshock** [comment]
Unfortunately, as far as I can tell macOS only has one way to cycle through separate windows (cmd+backtick) and one way to cycle through tabbed windows (cmd+shift+`[` and cmd+shift+`]`).

The problem is, what if you want to use different keys for this, like Ctrl+Tab and Ctrl+Shift+Tab?

The other problem is, macOS has no built-in way to switch to window/tab N.

I already mentioned that alacritty would need to be updated to keep track of the order of the windows.  Would it be a huge lift to have a Vec of WindowId next to the HashMap that gets updated (insert and delete) in the same places the HashMap is updated?

**Comment by chrisduerr** [comment]
> The problem is, what if you want to use different keys for this, like Ctrl+Tab and Ctrl+Shift+Tab?

So raise that issue with Apple?

> The other problem is, macOS has no built-in way to switch to window/tab N.

Apple is the only one who knows. We don't even know if the user uses tabs or not.

**Comment by sshock** [comment]
> > The problem is, what if you want to use different keys for this, like Ctrl+Tab and Ctrl+Shift+Tab?
> 
> So raise that issue with Apple?

It's weird because, somehow the Terminal app supports all of these, but I'm not sure how because only the first one works from alacritty (and presumably other apps):
1. Cmd+Shift+`[` and Cmd+Shift+`]`
2. Cmd+Shift+Left_Arrow and Cmd+Shift+Right_Arrow
3. Ctrl+Tab and Ctrl+Shift+Tab
4. Cmd+1, Cmd+2, Cmd+3, ...

> > The other problem is, macOS has no built-in way to switch to window/tab N.
> 
> Apple is the only one who knows. We don't even know if the user uses tabs or not.

Well, I was thinking that being able to switch quickly to between windows might be useful even when they aren't tabbed.

I think your best argument for why alacritty can't / shouldn't try to handle this is that when windows are tabbed, the user can drag the tabs around, changing the order, and alacritty will have no idea about that, so then the key bindings won't work as expected.

Now I'm even more curious how the Terminal app is able to do things, because not only does it support so many more key bindings, but it also gets the order right even when the tabs have been moved around.  Maybe it uses some secret macOS API calls that we don't know about yet...

**Comment by chrisduerr** [comment]
> I think your best argument though for why alacritty can't / shouldn't try to handle this is that when windows are tabbed, the user can drag the tabs around, changing the order, and alacritty will have no idea about that, so then the key bindings won't work as expected.

Correct, the only way for us to handle things like that would be for macOS to expose this information. Which it probably does. But at that point I feel like macOS should just support the binding itself.
