### ISSUE TITLE
Window decorations are less good-looking since 0.10 on Gnome-wayland session

### ISSUE THREAD

**Issue by Porkepix** [alacritty/alacritty#5829]
### System
ArchLinux with latest stable versions of Alacritty, Gnome and Wayland.

See the screenshots below about how different does look Alacritty with 0.9 version and 0.10 on Gnome-wayland.
As it happened in the past, it's likely I'll get answered it's Gnome's fault for badly implementing some protocols and the like, but just in case, I think it's worth signaling here.
I guess this also might be related to https://github.com/alacritty/alacritty/blob/master/CHANGELOG.md#removed

Screenshots:

0.9:![Screenshot from 2022-01-29 12-54-37](https://user-images.githubusercontent.com/709500/151664025-d75e8630-45a2-43a8-a879-aa0715a45dc7.png)
0.10:![Screenshot from 2022-01-29 12-54-13](https://user-images.githubusercontent.com/709500/151664028-6feddf48-1bb4-4be0-9b4d-bb3e050fe3bb.png)

**Comment by kchibisov** [comment]
>As it happened in the past, it's likely I'll get answered it's Gnome's fault for badly implementing some protocols and the like, but just in case, I think it's worth signaling here.

Upstream decided to stop maintaining fancy drawing client side decorations, since it pulled extra font rendering and stuff. So they went with something that can provide usable bare bones decorations. The thing is that gnome is making clients draw client side decorations, unlike mostly all other compositors. GNOME has it's rights and vision for it, but maintaining them isn't something that is easy on maintenance , since it's not something that is used by the majority.

Maybe someday GNOME will change their stand or there will be an easier way to integrate client side decoration drawing for us, but I don't fill like it. Using libdecor isn't an option, since it's basically pulling cairo and doing similar things that we did in the past...
