### ISSUE TITLE
Possible to configure modifier that escapes from mouse_mode?

### ISSUE THREAD

**Issue by jez** [alacritty/alacritty#5919]
If I'm not mistaken, these lines make it so that mouse-capturing mode can only be bypassed by holding down <kbd>Shift</kbd>:

https://github.com/alacritty/alacritty/blob/8ea6c3bc523f5024271d8a58f689a3a91b8f6fca/alacritty/src/input.rs#L869-L872

In other terminal emulators I'm used to, the keybinding for that is <kbd>Option</kbd>. I'd love for the modifier used here to be configurable.

Is that the sort of change that you're interested in being configurable? If so, I'd be happy to throw together a pull request for it, unless you think there's some hidden complexity that would make the change particularly hard (any implementation tips or pointers appreciated).

Thanks for building Alacritty btw; I've been splitting my time between macOS and Linux these days and it's really nice to have such a nice cross-platform terminal emulator.

**Comment by chrisduerr** [comment]
> Is that the sort of change that you're interested in being configurable?

Nope, definitely not interested in making this configurable. There's too much logic sitting on all the different modifiers when it comes to mouse interaction, so remapping them doesn't really make sense because ensuring everything still works is far more effort than just getting used to the existing behavior.
