### ISSUE TITLE
Would you consider also referring to Zellij as a terminal multiplexer?

### ISSUE THREAD

**Issue by imsnif** [alacritty/alacritty#5989]
Hi Alacritty,

I'm one of the [Zellij](https://github.com/zellij-org/zellij) maintainers. In your [README faq](https://github.com/alacritty/alacritty/blob/master/README.md#faq), you recommend tmux as a terminal multiplexer. One of the goals of Zellij is to make terminal multiplexers friendly and accessible. I think a lot of the intended audience of this question would benefit from knowing about us.

Would be cool if you'd consider linking to us as well.

Either way, thank you for all your hard work!

**Comment by chrisduerr** [comment]
> I wonder if we should link to anyone at all direclty, could link to https://en.wikipedia.org/wiki/Terminal_multiplexer or something like that.

I'd rather remove the mention of `tmux` than adding other terminal multiplexers to the list. While I'm sure the link to `tmux` was well-intended to help people with their search, it also drives them into one specific direction rather than encouraging to explore the options.

If I would write this section today, I wouldn't put any link at all. I don't see any specific reason to change this, but if either of you have strong opinions about changing it to a more generic resource just open a PR. Adding Zellij as this issue suggests is certainly not an option.
