### ISSUE TITLE
Reload mouse cursor theme dynamically

### ISSUE THREAD

**Issue by Hubro** [alacritty/alacritty#5990]
As part of my dark/light color scheme switching scripts (using [darkman](https://gitlab.com/WhyNotHugo/darkman)) I change my mouse cursor theme between Adwaita and Breeze_Snow, so that my mouse cursor keeps high contrast and stays easy to see.

I do this by changing the cursor theme using `gsettings`, by updating the GTK config ($HOME/.config/gtk-3.0/settings.ini) and by changing the icon theme in `$HOME/.icons/default/index.theme`.

I'm not sure which of these places Alacritty gets the cursor from, but it works. When I open a new Alacritty window, the correct mouse cursor theme is being used. However, Alacritty windows that are *already open* don't update the mouse cursor theme when I change it. This stands in the way of being able to change themes at runtime.

https://user-images.githubusercontent.com/597206/162183316-96a0a37e-61e8-4534-9962-245b5b090c77.mp4

How can I resolve this? How does Alacritty figure out which mouse cursor theme to use? Could Alacritty be written to watch the setting and act when it changes? Or is this an upstream issue?

**Comment by Hubro** [comment]
It seems to me like the mouse cursor theme is handled by glutin:

https://github.com/alacritty/alacritty/blob/master/alacritty/src/display/window.rs#L42

However, that's about as far as I got... I'm not sure if the GitHub search feature is just complete shit? Or am I looking in the wrong place?

https://github.com/rust-windowing/glutin/search?q=CursorIcon

![image](https://user-images.githubusercontent.com/597206/162185611-4520aad1-3994-4ed3-aeea-b474d8bd21b7.png)

**Comment by kchibisov** [comment]
@Hubro you're looking in the wrong place.

Are you on Wayland?

**Comment by Hubro** [comment]
> Are you on Wayland?

Yes, I'm using Sway.

Seems that CursorIcon was just re-exported from winit. Digging into winit, it seems it's getting themed cursors from sctk, i.e. "Smithay's Client ToolKit". The relevant function seems to be `theme_pointer_with_impl`:

https://github.com/Smithay/client-toolkit/blob/0701edd05835fd0803c725088fb5bb1c17e5022b/src/seat/pointer/theme.rs#L95

So my current guess, without knowing almost anything about Rust or Wayland, is that automatic reloading of the cursor theme config should be handled by `client-toolkit`. What do you think?

**Comment by kchibisov** [comment]
The problem is that it should inotify watch random system files if you want automatic reload. While you'll solve it for alacritty, you won't solve for anything else, not using e.g. dbus.

Ideally there should be wayland protocol for cursor settings in clients, however we rely on environment variables.

If anything I'd rely on some protocol than inotify here, since inotify approach is complicated and not worth it, since cursor theme isn't that something is changed often in reality ( I use the same adwaita cursor for both light and dark variants, since the cursor has slight white border).

**Comment by Hubro** [comment]
> since cursor theme isn't that something is changed often in reality

I don't agree at all with this. It's obviously true now, because it *can't* change without restarting every application. I really love the Breeze_Snow cursor theme, because it's stylish and very easy to see on dark backgrounds:

![image](https://user-images.githubusercontent.com/597206/162196093-35f7bed1-2ed4-4f52-8c49-dee2fa1446b4.png)

However, when I switch a light theme, I often have difficulties finding my cursor, and I often have to move the cursor to a corner to locate it. (Though to be fair I have a very big monitor.) So I want to switch back to the default Adwaita cursor in this case.

Any application that uses GTK, which includes Waybar and all my web browsers, already pick up the cursor icon change instantly.

**Comment by kchibisov** [comment]
Yeah, and then you pick some non-gtk application and it doesn't work anymore. There should be generic solution for that on Wayland. It'll work in your use cases, but not in mine, since I don't really use gtk apps.

Also, your background drawer, like swaybg won't update cursor, since it's also stuck with old theme iirc. Unless you force reload sway leading to restart of swaybg.

**Comment by chrisduerr** [comment]
> If anything I'd rely on some protocol than inotify here, since inotify approach is complicated and not worth it, since cursor theme isn't that something is changed often in reality.

I have to agree with this. Chances are GTK just automatically gets changes through dbus, but that's not a system you want to hook up to usually. So the only alternative is reading some system config files and I really wouldn't expect every application to have inotify running on a billion different system configs that *may* reload for some users at some point.

Since most cursors are also designed to work on both light and dark backgrounds, I would expect the number of users that frequently change their cursor theme to be **very** low.
