### ISSUE TITLE
Multiline prompt redraw 

### ISSUE THREAD

**Issue by zbirenbaum** [alacritty/alacritty#6011]
A while ago, kitty released a patch fixing the mess caused by resizing with a multiline prompt with reflow on. This is how they describe it in the change logs: 
>Glitch free window resizing even with complex prompts. Achieved by erasing the prompt on resize and allowing the shell to redraw it cleanly.

Is this something that could be reasonably integrated in Alacritty?  I think it would be much easier to implement this in the core terminal emulator code than try write a script to handle all the moving parts.

Edit: to be a bit more descriptive, the same has been implemented in iterm and tmux in zsh4humans. It seems that it makes use of OSC 133, but I couldn't find any info one whether or not alacritty supports that escape code.

**Comment by chrisduerr** [comment]
> Is this something that could be reasonably integrated in Alacritty?

No, because it only works if the shell redraws its prompt which is not guaranteed on resize. There's nothing that says behavior like that is to be expected from a terminal, so it's mostly just asking for trouble.

Beyond that as you've mentioned it likely relies on proprietary escape sequences that aren't natively supported by any shell, so that just makes things even worse.
