### ISSUE TITLE
Key release event in keymap

### ISSUE THREAD

**Issue by andr-savel** [alacritty/alacritty#6042]
Hello,

First of all thank you for the amazing terminal emulator!

As far as I know, alacritty has no ability to map key-release event.

For example I can create key-press map for F11
```
key_bindings:
    - {key: F11,       action: ToggleFullscreen            }
```
However I cannot create key-release map for F11 (please correct me if I wrong).

Is it possible to implement such feature?

**Comment by chrisduerr** [comment]
Why do you want this?

**Comment by andr-savel** [comment]
When I start neovim from alacritty and open several files, then I can switch between nvim file buffers via fzf window.
Fzf window appears and I can choose particular buffer via Ctrl+PageUp presses. Then I can switch to specified buffer only via Enter press. However it is better to switch to buffer via Ctrl release.

If alacritty can handle Ctrl release, then I can send specific key sequence (for example via xdotool) to neovim and neovim can switch to specified buffer.

**Comment by chrisduerr** [comment]
> If alacritty can handle Ctrl release, then I can send specific key sequence (for example via xdotool) to neovim and neovim can switch to specified buffer.

Excuse me but what? That sounds like a gigantic mess.

Patching Alacritty to enable using a massive hack that involves xdotool seems like a very roundabout way of solving this. Especially because your issue seems to be with neovim/fzf, not with Alacritty?

So unless you have other potential usecases in mind, I don't think this is good enough.

**Comment by andr-savel** [comment]
Ok, I will think about other ways.
