### ISSUE TITLE
Support 'resize -s <nr> <nc>'.

### ISSUE THREAD

**Issue by tevaughan** [alacritty/alacritty#6059]
When I try using the resize-command (which is packaged along with xterm in Debian), it does not successfully resize inside alacritty.  For example
```
$ resize -s 40 100
resize: unknown character 0xd, exiting
```
That doesn't happen, for example, in xterm, which just resizes to the specified size.

I looked through the example yaml-config and didn't see any option to enable dynamic resize.
I did some searching through tickets and didn't see a feature-request for this.

So I'm wondering if this might show up in an upcoming version.

**Comment by chrisduerr** [comment]
> So I'm wondering if this might show up in an upcoming version.

No, I have no intention of supporting this.

**Comment by tevaughan** [comment]
Is there a FAQ where you might mention this?
(So that one who might want it needn't have to search through tickets to find this.)

**Comment by chrisduerr** [comment]
It's too obscure of a feature to put it in an FAQ tbh. Given that you're the only person to ever ask about that, it would be more of an AQ.

We do have documentation on our supported escape sequences though, but that would assume that the user has at least a basic understanding of how the resize operation might work to figure out if it is supported or not.

**Comment by tevaughan** [comment]
Fair enough!  A once-asked question!

I am curious about whether you might accept contributed work toward this or whether you are simply opposed because it would go against a principle in your design.

Also, I'm wondering if you might recommend an easy solution that doesn't rely on an escape-sequence.

I am asking only because I like alacritty otherwise, but this feature is one that I have grown to depend on.  Maybe I could modify my shell-functions to modify the window-size by going through the window-manager or something, but often I just want to resize the terminal when I'm at the command-line, and I don't want to pick up my hand from the keyboard to fiddle with the mouse. Maybe if I switched to a better window-manager.... But I'm often in MS Windows and running a shell under WSL.

**Comment by chrisduerr** [comment]
> I am curious about whether you might accept contributed work toward this or whether you are simply opposed because it would go against a principle in your design.

I'm opposed to adding these features to Alacritty. While I'm not 100% familiar with the `resize` command itself, I assume it uses XTerm's resize escape sequence, which most modern terminal emulators do not adopt because terminal clients resizing the terminal window is just a bad idea and there's no great way to confirm this resize request was actually prompted by the user.

> Also, I'm wondering if you might recommend an easy solution that doesn't rely on an escape-sequence.

I'd say a good window manager should allow some amount of scripting to extend its functionality. I know the ones I use do at least. With that kind of stuff you should be able to just instruct your window manager to do the resizing, which is the appropriate way of doing it.

> often I just want to resize the terminal when I'm at the command-line, and I don't want to pick up my hand from the keyboard to fiddle with the mouse

Honestly this just sounds like something you should be able to bind in your window manager. Like a binding to grow/shrink width/height of any window certainly isn't uncommon functionality for a window manager. Unfortunately if your window manager doesn't give a fuck about being usable without a mouse, Alacritty isn't really the correct place to fix that for you.

**Comment by zen2** [comment]
I was looking for the same feature and find this issue.

These is from `man resize`:
- `resize -s rows columns` use Sun console escape sequences
- `resize rows columns` use VT100-style xterm  escape  codes
