### ISSUE TITLE
Erase in Line ANSI code (\e[K) deletes the character that precedes it

### ISSUE THREAD

**Issue by jonathanpoelen** [alacritty/alacritty#6159]
When a line is full and EL is used after the last character of a line, it is deleted.

The following command `s=$(echo {1..100}); echo ${s:0:$(($COLUMNS-2))}a$'+\e[Kb'` normally displays a `+` at the end of the first line. Except that here, `\e[K` which removes the characters from the cursor position at the end of the line actually removes the `+` character.

From wikpedia (https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences)

Code | Abbr | Name | Effect
-- | -- | -- | --
CSI n K | EL | Erase in Line | Erases part of the line.<br>**If n is 0 (or missing), clear from cursor to the end of the line**.<br>If n is 1, clear from cursor to beginning of the line.<br>If n is 2, clear entire line.  Cursor position does not change

To tell the truth, I don't know who is at fault, the behavior differs between terminals:

- xterm, urxvt-unicode, alacritty, default terminal on WSL and Mac: `+` is removed
- konsole, pantheon-term: `+` is visible

### System

OS: Manjaro Linux
Version: alacritty 0.10.1 ()
Linux/BSD: X11 / i3

### Logs

```console
$ alacritty -vv
[0.000006604s] [INFO ] [alacritty] Welcome to Alacritty
[0.000032873s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000043868s] [INFO ] [alacritty] Running on X11
[0.001007959s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/jonathan/.config/alacritty/alacritty.yml"
[0.011114444s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.013632921s] [DEBUG] [alacritty] Estimated DPR: 1
[0.013644582s] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 724, height: 412 })
[0.013653733s] [DEBUG] [alacritty] Estimated cell size: 9 x 17
[0.055238663s] [INFO ] [alacritty] Device pixel ratio: 1
[0.060883228s] [INFO ] [alacritty] Initializing glyph cache...
[0.062635990s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.065278962s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.067899470s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.070583416s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.082055954s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.021151761s
[0.082078992s] [INFO ] [alacritty] Estimated DPR correctly, skipping resize
[0.082141694s] [INFO ] [alacritty] Cell size: 9 x 17
[0.082149532s] [INFO ] [alacritty] Padding: 2 x 2
[0.082169881s] [INFO ] [alacritty] Width: 724, Height: 412
[0.088027508s] [INFO ] [alacritty] PTY dimensions: 24 x 80
[0.090589056s] [INFO ] [alacritty] Initialisation complete
[0.093047710s] [DEBUG] [alacritty_terminal] New num_cols is 106 and num_lines is 12
[0.093131748s] [INFO ] [alacritty] Padding: 2 x 2
[0.093160257s] [INFO ] [alacritty] Width: 963, Height: 212
[1.245937538s] [INFO ] [alacritty] Goodbye
```

**Comment by chrisduerr** [comment]
Does this actually affect you in any way? Considering that XTerm and URxvt behave the same way as Alacritty here, I'd consider Alacritty's behavior reasonably, if not recommended.

**Comment by jonathanpoelen** [comment]
I have had several cases of character disappearance related to this. The latest one is this one: (the `+` that is missing)

![2022-06-27-034332_1163x209_scrot](https://user-images.githubusercontent.com/1436727/175846607-fa70220e-bee9-41e9-b759-1ae5d2a254eb.png)

There are much more annoying cases that falsifies the output.

I was going to report the bug to urxvt, but the mailing-list made me cold, so I started here :)

**Comment by chrisduerr** [comment]
> I was going to report the bug to urxvt, but the mailing-list made me cold, so I started here :)

Fair enough. I'm not opposed to changing this behavior, though I'm not sure how trivial the implementation is going to be.

**Comment by j4james** [comment]
FYI, if you care about the DEC standards, erasing the `+` is technically the correct behavior. Per DEC STD 070, when a character is output on the last column of the page, it doesn't increment the column number - it just sets the "last column flag" (this is documented on page 5-141). Thus if you execute an `EL` at that point, it would have to erase that character.

If you want to see how it worked on the original DEC terminals, you can test several of the VT10x variants and the VT240 on MAME. Although make sure you set autowrap mode first, because some terminals will have that off by default.

The position of the `b` character is more complicated though. Per DEC STD 070, the `EL` operation is meant to reset the "last column flag" (see pages D-13 and 14). So when you execute another character after that, it should still be output in the last column. The VT10x devices were not fully compliant with those rules, though, so they would output the `b` at the start of the next line.

**Comment by jonathanpoelen** [comment]
I didn't know, but is this behavior consistent? Currently, many programs that add color use `x1b[K` because it has a significant effect on the background color:

- without it, tabs have no background color
- without it, it is not possible to put a background on a whole line without knowing the size of the terminal (which is not always possible)

![2022-06-28-035835_418x112_scrot](https://user-images.githubusercontent.com/1436727/176072547-d513536f-c831-466e-9083-cbeee9ec28b5.png)

In my previous post I gave an example with `gcc`, but it happens with `grep` too.

Reading https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90411 which contains several links, I just learned that gnome-terminal has specifically changed its behavior for grep. I think this is a very good thing and some deviations from the standard are beneficial.

**Comment by chrisduerr** [comment]
> FYI, if you care about the DEC standards, erasing the + is technically the correct behavior. Per DEC STD 070, when a character is output on the last column of the page, it doesn't increment the column number - it just sets the "last column flag" (this is documented on page 5-141). Thus if you execute an EL at that point, it would have to erase that character.

Yes, this has been my understanding too. Which is likely why XTerm does this.

> In my previous post I gave an example with gcc, but it happens with grep too.

Now that you mention it, I swear there was a `grep` issue opened before. IIRC grep even has an option for this?
Turns out I opened it: https://github.com/alacritty/alacritty/issues/5397

My last comment there seems to boil down to the same reasoning as this issue: The current implementation right now seems technically correct and is likely the simpler implementation. I don't think it would be worth it to introduce significant code changes into Alacritty to work around an application bug like this, but I'd at least like to take a look when I've got some time.

**Comment by chrisduerr** [comment]
Okay, something I found interesting while testing and wanted to leave here just to remember it: What is interesting is not only the behavior of `\e[0K`, but also the behavior of `\e[1K` and `\e[2K`. Generally I was curious if terminals that ignored the clear right would clear the newline flag and I got some curious results.

Kitty has the most sensible behavior I think. `\e[0K` is ignored after the last column, `\e[1K` and `\e[2K` just clear the first line completely and still put the `b` in the second line.

VTE seems kinda broken to me. `\e[0K` is also ignored after the last column, but `\e[1K` clears the newline flag putting the `b` in the last column of the first line while `\e[2K` doesn't and puts the `b` in the next line. If anything `\e[2K` should clear the flag, not `\e[1K`.
