### ISSUE TITLE
Resizing the window slowly causes some smearing

### ISSUE THREAD

**Issue by mikayla-maki** [alacritty/alacritty#6176]
When resizing the Alacritty window slowly, it causes this strange smearing effect. May be related to https://github.com/alacritty/alacritty/issues/1668. 

https://user-images.githubusercontent.com/2280405/176935558-ffe4d6a0-3287-4f1f-b298-a1285431b9dd.mov

### System

OS: macOS (ARM)
Version: 0.10.1 (1)
Linux/BSD: N/A

### Logs

N/A

**Comment by mikayla-maki** [comment]
Note that slow resizing -> fast resizing after the bug is triggered, there is more interesting smearing:

<img width="1123" alt="Screen Shot 2022-07-01 at 09 41 21" src="https://user-images.githubusercontent.com/2280405/176936057-c024ca48-f7ae-4da8-98af-d999f377c3c1.png">
 
And also, fast resizing does not cause any issues at all. 

Also, with further messing around, I'm pretty sure https://github.com/alacritty/alacritty/issues/1668 is closely related, as only duplicated lines are affected by this smearing.

**Comment by kchibisov** [comment]
That's expected because your shell decides to redraw while we're still resizing. For example if you run `sleep 100` and try to repro you won't be able to do so.

Every terminal which does reflow is affected by it(unless they do some heuristics, but those are heuristics), so nothing can be done about it.

**Comment by mikayla-maki** [comment]
Ahh, thank you for the explanation @kchibisov!
