### ISSUE TITLE
Rendering issue with irust

### ISSUE THREAD

**Issue by darg2012** [alacritty/alacritty#6225]
### System

OS: Windows
Version: alacritty 0.10.1 (2844606)

### Logs
N/A

I starter playing with [irust](https://github.com/sigmaSd/IRust) and noticed that there was a rendering issue as when typing as shown in the pics. The issue is not present in other terminals (i.e. cmd, pwsh, vscode). 

![alacritty_irust_issue](https://user-images.githubusercontent.com/60045376/180820430-7d6aff41-7b9c-419d-800f-0a8cd1a3a602.png)

All the lines should be like this (ignoring the different theme):

![alacritty_irust_issue2](https://user-images.githubusercontent.com/60045376/180821103-e3598d79-3ad2-48fd-a2e9-c7f2e685bbd8.png)

**Comment by chrisduerr** [comment]
The escape sequences without introducer here clearly indicate that they're either not emitted correctly, or something in-between Alacritty and the application (ConPTY) is swallowing them.

Since `CSI H` is extremely common, I'd suspect it's an issue with `irust`, but either way unrelated to Alacritty.
