### ISSUE TITLE
Add optiom to replace alacritty to handle cmd/bat files by default

### ISSUE THREAD

**Issue by ibay770** [alacritty/alacritty#6267]
The default app dialogue on Windows isn't cutting it so I was wondering if an option for alacrity to handle the bat/cmd batch files could be made by default, on a double click instead of just a right click.

**Comment by chrisduerr** [comment]
I don't know how this works in Windows. Can't you just set the default application yourself?

**Comment by ibay770** [comment]
I would, if the Microsoft programs set to do just that actually worked. I'll keep researching though and if I find a solution I'll post it here.

**Comment by j4james** [comment]
My understanding is that this functionality is still being developed. For now I think it's only possible with the preview version of Windows Terminal, because they're still working out the details of the handoff protocol. But eventually you should be able to select any third-party terminal as your default, assuming it has been registered correctly. It's also worth mentioning that this will probably only be supported on Windows 11.

**Comment by ibay770** [comment]
Ok so while I found a way to set the associations with [this](https://support.4it.com.au/article/how-to-change-file-associations-from-the-command-prompt/) nothing happens as @j4james mentioned, because of missing functionality. if I find a working method, I will try and update this.
