### ISSUE TITLE
Configuration not taking effect except for size

### ISSUE THREAD

**Issue by TimePrinciple** [alacritty/alacritty#6290]
The requirements says the OpenGL ES 2.0 is needed.
How can I check for if there is an existing OpenGL ES in my linux system, and how to install one if not?
Will the absence of OpenGL ES leads to this problem?
### System
OS: Ubuntu 22.04

**Comment by chrisduerr** [comment]
Have you tried running Alacritty? Does it work? What is up with this title?

**Comment by TimePrinciple** [comment]
> Have you tried running Alacritty? Does it work? What is up with this title?

Tried but the configuration is not working, only the modification of size in `alacritty.yml` takes effect.
I'm wondering is there any way to verify that whether my system has the required openGL ES? Or how can I install one.

**Comment by chrisduerr** [comment]
How would OpenGL version have anything to do with configuration not taking effect?

If your problem is that you struggle with the configuration, then the issue most likely is just that your indentation is off. Yaml is very picky about whitespace. If you need concrete help I'd need your configuration file, but just look at the yaml spec and that should make things rather simple.
