### ISSUE TITLE
signed release tarballs

### ISSUE THREAD

**Issue by moralground** [alacritty/alacritty#6307]
Hi. Would it be possible to publish gpg-signed release tarballs with a detached signature for the official releases? It's good to see the tags being signed, but this would make downstream packaging a bit more easy.

**Comment by chrisduerr** [comment]
What distribution channel would you expect for this and how does it help distribution (I'd also be curious which package ecosystem specifically)?

I'd imagine your goal is to just pull from the GitHub release artifacts directly to obtain the signed source code, rather than having to go to the corresponding tag? Since you explicitly mention detached signatures, would you just want an `alacritty.tar.gz.sig` added to the relase artifacts basically?

This would be a manual process, which I don't have *too* much of a problem with though it's certainly extra effort. Though I'm not actually sure I'd recommend it over the signed tag, since the signed tag is guaranteed to have been created by a contributor. The signed tarball however is created automatically by GitHub, thus they could be messing with it unless it is explicitly verified that it matches the tag every time (and I don't think it's realistic to do that for every release).

I don't think this matters too much, considering you're getting the tag from GitHub too and they could also mess with that anyway. But I at least wanted to point out that it's a bit icky to me to sign stuff that hasn't been explicitly verified.

**Comment by moralground** [comment]
Thanks for your quick reply! To get right to the point:

>  Since you explicitly mention detached signatures, would you just want an `alacritty.tar.gz.sig` added to the relase artifacts basically?

Yes, that would be perfect.

> What distribution channel would you expect for this and how does it help distribution (I'd also be curious which package ecosystem specifically)?

Normally you would publish the key fingerprint somewhere (README or wiki or whatever works) and upload the public key to one of the PGP key servers. Then those who package the software for Debian, Fedora, etc could verify the tarball against that signature before building their binary packages. 

> The signed tarball however is created automatically by GitHub, thus they could be messing with it unless it is explicitly verified that it matches the tag every time (and I don't think it's realistic to do that for every release).

It would be signed by a private key that only the developer holds, not Github. The Github key signing is basically worthless from a trust perspective.

> I don't think this matters too much, considering you're getting the tag from GitHub too and they could also mess with that anyway.

Having a signed release file would more or less bypass the need to trust Github in any capacity.

**Comment by chrisduerr** [comment]
> Having a signed release file would more or less bypass the need to trust Github in any capacity.

This is inaccurate. You're making the assumption that the developer goes and verifies the tarball before signing it. I don't think this is something we can ever guarantee and I wouldn't want to guarantee it either. That just seems like a lot of unnecessary manual labour to deal with what realistically is likely a flaw in the packaging process.

You've also avoided my question on which package manager specifically this would benefit. Could you please document this here? I wouldn't want to go through the process of manually adding a signature to every single release without anyone ever using it. Especially considering existing packagers like Archlinux don't seem to have any problem with pulling from tags rather than releases.

**Comment by moralground** [comment]
> > Having a signed release file would more or less bypass the need to trust Github in any capacity.
> 
> This is inaccurate. You're making the assumption that the developer goes and verifies the tarball before signing it. I don't think this is something we can ever guarantee and I wouldn't want to guarantee it either. That just seems like a lot of unnecessary manual labour to deal with what realistically is likely a flaw in the packaging process.

Not sure I follow your logic here. You have a local copy of the repo you work on, then push the changes to Github. The tarball to be signed would more likely be created from your local (trusted) copy, not what's on Github. Pulling the sources back down from Github and then signing them would indeed be mostly useless.

> You've also avoided my question on which package manager specifically this would benefit. Could you please document this here?

I didn't answer because I didn't quite understand. You're talking about package managers (software) while I'm talking about package maintainers (people). In Debian, for example, a developer will download the source of a program, verify its signature locally, and then upload the sources to their repo. Arch is unique in its ability to verify sources directly from the Makefile equivalent. Everyone else has to do this process manually.

> I wouldn't want to go through the process of manually adding a signature to every single release without anyone ever using it.

I think most packagers for various OSes would appreciate and use it.

**Comment by chrisduerr** [comment]
> Not sure I follow your logic here. You have a local copy of the repo you work on, then push the changes to Github. The tarball to be signed would more likely be created from your local (trusted) copy, not what's on Github. Pulling the sources back down from Github and then signing them would indeed be mostly useless.

So you want separately distributed source tarballs then? The tarballs uploaded in the GitHub releases are automatically generated by GitHub. These are not uploaded by users.

> I didn't answer because I didn't quite understand. You're talking about package managers (software) while I'm talking about package maintainers (people). In Debian, for example, a developer will download the source of a program, verify its signature locally, and then upload the sources to their repo.

So how exactly does signed tarballs simplify the process? Downloading artifacts is more difficult than just cloning the repository, right? I'd expect maintainers to prefer just a simple `clone` over having to go and manually pull the artifacts.

> I think most packagers for various OSes would appreciate and use it.

This just seems too vague for me. "I think most could probably maybe use it" doesn't really sound like a convincing statement that someone is actually going to benefit from it. Alacritty is already packaged in a bunch of distros and while I'm always trying to actively support packagers, none of them has ever voiced their interest in this.

To me this workflow seems very heavily built around GitHub as a platform, which seems strange since a maintainer would likely have to deal with many different platforms anyway. So I wouldn't want to create additional manual labour for me, just to support a usecase that maintainers aren't going to benefit from anyway, since their workflow is built around simple `git` tooling rather than GitHub's release artifacts.

**Comment by chrisduerr** [comment]
It seems like you've opened the same issue in Tmux (https://github.com/tmux/tmux/issues/3322), also not providing any details on why specifically this would be required for packaging there.

If someone is interested in packaging Alacritty and would actually benefit from this, I'm happy to work with them. But I don't plan to make any changes based on suspicions what package maintainers *might* need.

**Comment by VlkrS** [comment]
@chrisduerr I'm not a downstream packager of alacritty, but for maintaining / updating the port for OpenBSD, it would be handy to have a source tarball as part of the release artifacts. The autogenerated tarballs from github are not always stable but change sizes and checksums without changing their content.

**Comment by kchibisov** [comment]
But it's a packaging issue if you look at it and it's a matter of how you compute the hashes. For example nix computes hash of files inside the tarball instead, so it's stable across the git changes.

I know that source forges try to keep source tarballs stable.

**Comment by VlkrS** [comment]
> But it's a packaging issue if you look at it and it's a matter of how you compute the hashes. For example nix computes hash of files inside the tarball instead, so it's stable across the git changes.
> I know that source forges try to keep source tarballs stable.

I was referring to @chrisduerr 's remark "If someone is interested in packaging Alacritty and would actually benefit from this, I'm happy to work with them." - and while I'm not the maintainer for the OpenBSD package specifically, I know that for OpenBSD ports it's beneficial to have stable source tarballs. I assume that the same goes for other OSes.

Right now when I try to retrieve alacritty's tarball via the v0.12.1 tag, github responds with 

```Error retrieving https://github.com/alacritty/alacritty/archive/v0.12.1/alacritty-0.12.1.tar.gz: 300 Multiple Choices```

In other instances, autogenerated source tarballs change because they've been regenerated etc.

Are there workarounds and can we work with the way things are? Sure. Would it be beneficial to have a released source tarball? Definitely.
