### ISSUE TITLE
Artifacts in the corners of the titlebar on maximized window

### ISSUE THREAD

**Issue by rumpelsepp** [alacritty/alacritty#6338]
On alacritty master there is a new cool title bar. At least on gnome the title bar is rendered with rounded corners. This causes unpleasant artifacts when the window is maximized, since the background is visible (blue on my screenshot below).

![Screenshot from 2022-09-15 08-27-40](https://user-images.githubusercontent.com/1961699/190330301-b8c2f8b1-50ee-4fc6-9ba7-c37958145eb0.png)

I would suggest disabling rounded corners on Linux as it was the case with the old titlebar.

### System

OS: Linux
Version: `alacritty --version`: `alacritty 0.12.0-dev (bf3e8822)`
Linux/BSD: Linux, Gnome, Wayland

**Comment by chrisduerr** [comment]
Complain to gnome, round corners are a terrible idea.

**Comment by rumpelsepp** [comment]
May I ask you to give more context here, since I have no idea about the technical problem here? I thought alacritty is drawing the title bar because of Client Side Decorations. Isn't this the case with alacritty's new title bar? No windows on my Gnome Desktop have rounded corners when the window is maximized.

**Comment by chrisduerr** [comment]
Gnome forces client-side decorations, this means your desktop will always look like shit because there's zero consistency unless you give in and port everything to gnome's "officially blessed" GTK toolkit (with the correct version that is currently hip).

The upstream windowing library decided that rounded corners would be a good idea, because that's what everyone seems to be doing these days. I don't think they provide an API to configure this and I have zero interest in fighting that battle myself. If you wish for this to change, ask in https://github.com/PolyMeilex/sctk-adwaita.

**Comment by rumpelsepp** [comment]
Thanks for the pointer. I understand your feelings, I don't like this direction as well.
