### ISSUE TITLE
Feature request. MacOS multiple windows group in one Dock icon

### ISSUE THREAD

**Issue by buahaha** [alacritty/alacritty#6346]
# Feature request for _MacOS_ version of `Alacritty`

Currently when opening many windows, Alacritty terminal creates for each one more icon. Even when `Keep in Dock` is set to true, **only the selected window is moved to Dock**.

I ask to group all the windows in one icon in Dock to do not overly expand space when running multiple windows simultaneously.

Kind regards,
Szymon

**Comment by chrisduerr** [comment]
Already supported. See the `CreateNewWindow` action and IPC messages in the CLI.

**Comment by b4sen** [comment]
I added this to the key_bindings:
`  - { key: N,     mods: Command,  action: CreateNewWindow }`

**Comment by aspauldingcode** [comment]
ok but how do I do this without using alacritty to do so?
like, instead of a binding, I want to have it by default launch a new window using the same icon.

with skhd on macos. 
I can use the osascript, or open commands all I want but if alacritty's default behavior is just to create a new icon in the dock instead of grouping as a subinstance of the original than that's not on me. 
You guys gotta solve that.
There should be an option to keep new windows under one icon in macOS dock.
