### ISSUE TITLE
Add support for the kitty keyboard protocol

### ISSUE THREAD

**Issue by Munksgaard** [alacritty/alacritty#6378]
I'm developing a terminal application using [crossterm](https://github.com/crossterm-rs/crossterm), and I would like to use the number keys as modifiers instead of ctrl and alt. That can be done through the use of [`PushKeyboardEnhancementFlags`](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html), whereupon my program will receive [`Release`](https://docs.rs/crossterm/latest/crossterm/event/enum.KeyEventKind.html#variant.Release) and [`Repeat`](https://docs.rs/crossterm/latest/crossterm/event/enum.KeyEventKind.html#variant.Repeat) events in addition to just [`Press`](https://docs.rs/crossterm/latest/crossterm/event/enum.KeyEventKind.html#variant.Press). However, it seems like that functionality is dependent on the terminal implementing the [kitty keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/), which alacritty doesn't.

Are there any plans for implementing such a feature, or is there a better way to achieve the same goal (arbitrary keys as modifiers) in alacritty?

**Comment by chrisduerr** [comment]
I'm not sure Kitty's protocol is actually strictly superior. The support of the super modifier for example is something I consider a rather bad idea.

But ultimately this should be a pretty easy patch to submit, there just hasn't been anyone interested in doing so. I know I personally don't really care about it.

I thought we already had an issue open for `CSI u`, obviously we'd implement only one of the two. But since I can't find it I'm going to leave this open.

**Comment by Munksgaard** [comment]
Perhaps https://github.com/alacritty/alacritty/issues/5850 is the one you're thinking of?

**Comment by chrisduerr** [comment]
No? OSC 133 is something *completely* unrelated to this. I was specifically thinking of leonerd's `CSI u`.

**Comment by Munksgaard** [comment]
Ah, my ignorance is showing. Thanks for clearing that up for me.

**Comment by j4james** [comment]
> I thought we already had an issue open for `CSI u`, obviously we'd implement only one of the two.

@chrisduerr Were you perhaps thinking of #3101?

**Comment by chrisduerr** [comment]
No, I'm thinking of `CSI u`. I know that has been discussed numerous times in the past and I thought that included GitHub issues. But sometimes I get confused between GitHub and IRC.

**Comment by j4james** [comment]
My understanding is that `CSI u` is just a variant of the `modifyOtherKeys` protocol which is controlled in XTerm by the `formatOtherKeys` resource (documented [here](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:formatOtherKeys)).

For more details on how it works, and the origin of the `CSI u` protocol, there is a separate page of documentation [here](https://invisible-island.net/xterm/modified-keys.html).

**Comment by pataquets** [comment]
I fully share @chrisduerr's reluctancy to *fully* implement Kitty's protocol. Implementing and maintaining such a protocol is quite a burden going on, which seems not trivially justifiable (at least without getting deeper in what benefits it brings). Also, I'm not sure about if such a protocol is a product of a small group and how much peer-review has undergone. from a cursory research, I've seen it had problems in the past (as stated in the first words of kitty#3248). Also, Kitty has [gone its own path for graphics instead of using libsixel](https://news.ycombinator.com/item?id=28758979). By no means I'm an expert on the subject and I can't judge myself which path is superior, but on the surface, it looks like Kitty prefers a more bold approach to implementing features, but some stability and agreement would be a requirement for fully embracing any protocol. Again, not advocating for either path, since I'm not an expert, just pointing out.

Having said that, as a safe middle ground, I would be in favour of implementing `CSI u`, as it looks like some (more or less common) terminal standard extension and would not prevent future Kitty protocol implementation, as it's already in it (correct me if I'm wrong). It's also a supported solution for widely used software such as [NeoVIM](https://alpha2phi.medium.com/neovim-101-terminal-and-shell-5be83b9f2b88) and [Emacs](https://gist.github.com/gnachman/b4fb1e643e7e82a546bc9f86f30360e4).
*Disclaimer*: I'm just looking for Super (ie. Win) key to reach my Emacs to be able to use as another modifier.

So here it is my +1/2 on the feature request. If it'll help managing issues to @chrisduerr, I will open a separate issue to focus on `CSI u` (or whatever approach he feels best) as it would solve some of the use cases requested, even with requested issues: #1861, #4451, #4938. Even a PR existed in the past: #5358.
(Note: I've also found #3101, but I can't figure out how it fits in the picture).

**Comment by airtonix** [comment]
not being able to bind `Ctrl + Shift + some letter` to a separate thing to `Ctrl + some letter` is going to be the main motivator for majority of people.

**Comment by utkarshgupta137** [comment]
@chrisduerr @kchibisov What is the status of this issue? Have you guys decided which protocol should be added? If so, are either of you interested in implementing it? If not, would you be interested in a PR? I can't promise anything as I've very little knowledge of terminals, but I would love to see support for `CSI u` in Alacritty.

**Comment by kchibisov** [comment]
@utkarshgupta137 we're interested in supporting one of the protocols.

It would be nice to know what is actually used across the editors and implement one of them. The implementation is sort of simple, given that you have to translate the chars according to some scheme.

I'd suggest to:

1. Look at what is used and report here (how the use of each protocol is detected should be also reported here). I'd check at least `neovim`, `vim`, `helix`, and some libraries(rust or not, doesn't matter).
2. ping me here or on libera.chat(preferred) **before you start writing the actual impl**, so we can cooperate, because I'll break all keyboard input in alacritty soon™, so you write your changes against actual code. (I'll open a draft PR regardless). Also, the solution must not be based on key bindings, it should simply translate on the fly.

**Comment by utkarshgupta137** [comment]
> @utkarshgupta137 we're interested in supporting one of the protocols.
> 
> It would be nice to know what is actually used across the editors and implement one of them. The implementation is sort of simple, given that you have to translate the chars according to some scheme.
> 
> I'd suggest to:
> 
>     1. Look at what is used and report here (how the use of each protocol is detected should be also reported here). I'd check at least `neovim`, `vim`, `helix`, and some libraries(rust or not, doesn't matter).
> 
>     2. ping me here or on libera.chat(preferred) **before you start writing the actual impl**, so we can cooperate, because I'll break all keyboard input in alacritty soon™, so you write your changes against actual code. (I'll open a draft PR regardless). Also, the solution must not be based on key bindings, it should simply translate on the fly.

1. The Kitty protocol [page](https://sw.kovidgoyal.net/kitty/keyboard-protocol) mentions quite a few terminals/editors/libraries which now support the Kitty protocol. I found one inaccuracy though, NeoVim only has partial support as of now: https://github.com/neovim/neovim/issues/14400. Both `vim` & `helix` claim full support. In addition, all the applications which support the Kitty protocol, also support `CSI u`.
2. Alright I'll wait for your PR. Don't expect anything soon from me as I'm a complete terminal internals noob, but I'm handy with Rust.

**Comment by utkarshgupta137** [comment]
If I'm not wrong, Kitty still supports the `CSI u` mode for compatibility & then the applications that support the Kitty protocol can send escape sequences to check & enable the enhancements progressively.
So I guess the first step would be to support `CSI u` anyway? So maybe we can start there? I guess that there might be a bunch of applications out there which support `CSI u`, but not the Kitty protocol.
After that, I think the first enhancement of the Kitty protocol, `Disambiguate escape codes` is the most important & desirable enhancement for most users, so we can add that & then work on the remaining ones one by one?

**Comment by kchibisov** [comment]
Yeah, starting with just `CSI u` sounds good to me. Do they simply assume `CSI u` or do some sort of detection whether it's supported?

**Comment by utkarshgupta137** [comment]
> Yeah, starting with just `CSI u` sounds good to me. Do they simply assume `CSI u` or do some sort of detection whether it's supported?

No, I think applications have to enable it explicitly, so `CSI u` is enabled whenever the application requests it. It is enabled as it normally would regardless of the Kitty protocol.

**Comment by kchibisov** [comment]
@utkarshgupta137 this is the branch I was talking about https://github.com/alacritty/alacritty/pull/6958 . Basically you need to do is to:

1. add detection to https://github.com/alacritty/vte/blob/master/src/ansi.rs according to how the protocol defines it. From what I see it's a bit over engineered and involves requests stack handling and such. For that would suggest to look at `TITLE_STACK`(you'd have to have 2 stacks...). The device report things are `identify_terminal/device_status` or similar, can't say which thing exactly. The end result would be to expose some flag according to the protocol on how the keys should be reported.
2. Use the flag from 1. and do what the extension wants you in https://github.com/kchibisov/alacritty/blob/1d08a4c6aab94d2da9c4917117ae4754a068ca1c/alacritty/src/input.rs#L969 (you don't need other functions). Everything you need is contained inside this function, if you'll feel like missing something let me know.

If you want more live hand holding just hit me on `#alacritty` on libera.chat.

**Comment by utkarshgupta137** [comment]
> @utkarshgupta137 this is the branch I was talking about #6958 . Basically you need to do is to:
> 
>     1. add detection to https://github.com/alacritty/vte/blob/master/src/ansi.rs according to how the protocol defines it. From what I see it's a bit over engineered and involves requests stack handling and such. For that would suggest to look at `TITLE_STACK`(you'd have to have 2 stacks...). The device report things are `identify_terminal/device_status` or similar, can't say which thing exactly. The end result would be to expose some flag according to the protocol on how the keys should be reported.

It looks like `CSI u` detection [is not a thing outside of the Kitty Protocol](https://github.com/neovim/neovim/pull/18181#discussion_r856952625). So only programs that implement the Kitty Protocol will try to detect and/or enable it.
But there may be programs out there that could interpret `CSI u` without implementing it. So should Alacritty report keys such as `Ctrl+j` using `CSI u` even if the support isn't enabled as per the Kitty Protocol? It will lead to inputs such as `Ctrl+j` to stop working in applications that don't support `CSI u`, but any well-behaved application should already not use that keybinding.

**Comment by kchibisov** [comment]
Changing the established like `C-j` is not a good idea.

**Comment by utkarshgupta137** [comment]
But `C-j` is unusable anyway because it represents the enter key. If we don't change the existing keys, `CSI u` will only work for apps that support the Kitty protocol, which isn't many. I don't think Zellij has any support for the Kitty protocol, but it works with manual `CSI u` style mappings.

**Comment by kchibisov** [comment]
No, the `Enter` is `\r`, but `C-j` is `\n`. You can check that with `showkey -a` and `\r` is what os sends most of the time, you don't have `\n`.

**Comment by utkarshgupta137** [comment]
> No, the `Enter` is `\r`, but `C-j` is `\n`. You can check that with `showkey -a` and `\r` is what os sends most of the time, you don't have `\n`.

On macOS, I get `C-j` with showkey, but the point still stands if we talk about any other key.

**Comment by kchibisov** [comment]
macOS doesn't have `showkey` to begin with, but you likely managed to obtain it somehow.

I'm just saying none of the terminals supporting keyboard protocol, even kitty, alter the default behavior.

**Comment by kchibisov** [comment]
The mentioned before keyboard rework was merged, now it should be pretty trivial to implement this. It's more about reading the spec and mapping `String` to what it should be by the specification.

**Comment by kchibisov** [comment]
If someone could test https://github.com/alacritty/alacritty/pull/7125 it'll be very nice.

**Comment by aburlak** [comment]
Tried this patch (rev. 89e5477) for a couple of days - and hit some bugs:

1. `<DELETE>` key is reported as `<BACKSPACE>`, in both normal and CSI-u mode
2. In CSI-u mode, Ctrl+Space and Ctrl-Backspace send nothing at all (not even the usual ^@ and ^H).
3. Ditto for Ctrl+Tab and Ctrl+Return.

Tested with Sway 1.8.1 + NVim 0.9.2 + Linux 6.5.5, default ('us') XKB layout.

Patched my copy as follows - with the patch, NVim correctly reports `<Del>` `<C-Space>` `<C-BS>` `<C-Tab>` `<C-CR>` keys.

```
diff --git a/alacritty/src/input.rs b/alacritty/src/input.rs
index 67ac1680..96d304cf 100644
--- a/alacritty/src/input.rs
+++ b/alacritty/src/input.rs
@@ -1077,6 +1077,7 @@ impl<T: EventListener, A: ActionContext<T>> Processor<T, A> {
         //    modifiers and the location of the key is not on the numpad, and it's not an `Esc`.
         let normal_write = !mode.contains(TermMode::KEYBOARD_REPORT_ALL_KEYS_AS_ESC)
             && !text.is_empty()
+            && key.logical_key != Key::Delete
             && (!mode.contains(TermMode::KEYBOARD_DISAMBIGUATE_ESC_CODES)
                 || (mode.contains(TermMode::KEYBOARD_DISAMBIGUATE_ESC_CODES)
                     && (mods.is_empty() || mods == ModifiersState::SHIFT)
@@ -1395,6 +1396,7 @@ fn build_keyboard_esc_sequence(key: KeyEvent, mods: ModifiersState, mode: TermMo
         Key::AudioVolumeUp => ("57439".into(), 'u'),
         Key::AudioVolumeMute => ("57440".into(), 'u'),
         Key::Escape if named_csi_u => ("27".into(), 'u'),
+        Key::Space if named_csi_u => ("32".into(), 'u'),
         // Keys which are reported only when all key must be reported
         Key::CapsLock if encode_all => ("57358".into(), 'u'),
         Key::NumLock if encode_all => ("57360".into(), 'u'),
@@ -1413,9 +1415,9 @@ fn build_keyboard_esc_sequence(key: KeyEvent, mods: ModifiersState, mode: TermMo
         Key::Hyper if key.location == KeyLocation::Right && encode_all => ("57451".into(), 'u'),
         Key::Meta if key.location == KeyLocation::Right && encode_all => ("57452".into(), 'u'),

-        Key::Enter if encode_all => ("13".into(), 'u'),
-        Key::Tab if encode_all => ("9".into(), 'u'),
-        Key::Backspace if encode_all => ("127".into(), 'u'),
+        Key::Enter if named_csi_u => ("13".into(), 'u'),
+        Key::Tab if named_csi_u => ("9".into(), 'u'),
+        Key::Backspace if named_csi_u => ("127".into(), 'u'),
         // When the character key ended up being a text, like when compose was done.
         Key::Character(c) if encode_all && c.chars().count() > 1 => ("0".into(), 'u'),
         Key::Character(c) => {
```

**Comment by kchibisov** [comment]
>Patched my copy as follows - with the patch, NVim correctly reports <Del> <C-Space> <C-BS> <C-Tab> <C-CR> keys.

Thanks, though, the patch is not correct.

**Comment by aburlak** [comment]
Also, I noticed that Numpad8 (Up) key moves the cursor to the left (if NumLock is off).
Looks like a winit bug (only on Linux):
```
alacritty --print-events | grep Numpad8
[0.643400971s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94157725689536)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Numpad8, logical_key: ArrowLeft, text: None, location: Numpad, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: ArrowLeft, text_with_all_modifiers: None } }, is_synthetic: false } }
[0.731366568s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94157725689536)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Numpad8, logical_key: ArrowLeft, text: None, location: Numpad, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: ArrowLeft, text_with_all_modifiers: None } }, is_synthetic: false } }
```

Reporting it here, because v0.12.3 isn't affected.
On the current 'master', the keypad without NumLock doesn't work at all - since db903503df024a3f5066937fbe0272be88226738.
With this patch - it works, except for the Numpad8 / Up key.
