### ISSUE TITLE
Same name for tags and branches

### ISSUE THREAD

**Issue by jpalus** [alacritty/alacritty#6406]
When packaging software from GitHub distributions often use source URL in the form of `https://github.com/owner/project/archive/<version>/<project>-<version>.tar.gz` unless official source releases are provided. These URLs are not working for `alacritty` though since same name is used for ie tag `v0.11.0` and branch `v0.11.0` resulting in following file being downloaded when attempting to fetch from https://github.com/alacritty/alacritty/archive/v0.11.0/alacritty-0.11.0.tar.gz:
```
the given path has multiple possibilities: #<Git::Ref:0x00007f5df9c23e00>, #<Git::Ref:0x00007f5df9c42ff8>% 
```
Would you please consider giving unique names to refs since it's somewhat confusing on it's own or perhaps provide source archives?

**Comment by kchibisov** [comment]
If you want tags then ask for tags like most distros do.

https://github.com/alacritty/alacritty/archive/refs/tags/v0.11.0.tar.gz

**Comment by jpalus** [comment]
I guess I'll have to make exception for `alacritty` just like everyone else. Most other github projects in major distributions fair with the other url scheme like for ie `neovim`.

Fedora:
https://github.com/neovim/neovim/archive/v%{version}/%{name}-%{version}.tar.gz

Gentoo:
https://github.com/neovim/neovim/archive/v${PV}.tar.gz

Arch:
https://github.com/neovim/neovim/archive/v${pkgver}/${pkgname}-${pkgver}.tar.gz

Thanks anyway.

**Comment by kchibisov** [comment]
Maybe @chrisduerr would be fine to adjust branching here to something like `v0.11.x` in the future, but it's not like you don't have an option.

But in my opinion it's not really forward compatibly if you're not asking explicitly for tags, since the project could change scheme, so you should be aware of that as well. With tags it's more clear.

Wrt sources they're uploaded on github release page.

And if you click the link you'd get to  https://github.com/alacritty/alacritty/archive/refs/tags/v0.11.0.tar.gz

**Comment by jpalus** [comment]
Yes I do realize my options, I just merely asked if you could consider adjusting naming scheme so distributions can keep consistent source URL scheme for GitHub projects including `alacritty`. You're of course free to reject the request and distributions will cope with it.

**Comment by chrisduerr** [comment]
I don't see a reason to change anything here. This is *exactly* what `/tags` is for. I'd say distros not explicitly asking for tags is a bad idea anyway.
