### ISSUE TITLE
Use a variable as shell program

### ISSUE THREAD

**Issue by GNOMES** [alacritty/alacritty#6497]
To make it so my terminal can be used on multiple machines I am trying to not hardcode my login shell, but want to ensure I am using a login shell.

```
I am trying to use:
    shell:
        program: "$SHELL"
        args:
            - --login
```
            
This is resulting in Alacritty crashing. 

alacritty -vvv output:
`    Error: Failed to spawn command '$SHELL': No such file or directory (os error 2)`

I attempted to use `$SHELL` (no quotes), `${SHELL} `(curly brace in both quotes/no quotes).

As Alacritty was resolving this with single qoutes, I also attempted to use \"$SHELL\", but this also failed.

**Comment by kchibisov** [comment]
Also, why do you pass `--login` for Linux stuff? You generally don't have to run shell as login on it... The config will be inherited anyway from the system startup, no?

**Comment by Cokile** [comment]
I have a similar scenario, I'm using alacritty with fish and tmux in Mac:
```yml
shell:
  program: /usr/local/bin/fish
  args:
    - -l
    - -c
    - 'tmux attach || tmux -2'
```

This works well until I got a M1 device. The problem is that the Homebrew install path changed to `/opt/homebrew` in M1 device but I want the same config can be reused on both Intel and M1 devices.

fish is my login shell and I have tried to use `$SHELL` or remove `shell.program` but neither of them works.

Is it possible or is there any workaround to let me just keep one "alacritty.yml" in my "dotfiles"?

**Comment by chrisduerr** [comment]
@Cokile You don't need to specify the full path if your shell is in your $PATH properly.

**Comment by Cokile** [comment]
@chrisduerr  Which shell's $PATH would alacritty use if it's launched directly from GUI?

Am I in a dead-lock situation: I need to start fish(the default shell) to setup $PATH but fish needs $PATH to start

**Comment by chrisduerr** [comment]
@Cokile Environment variables are inherited when new applications are spawned. So on Linux that means either your login shell or your login manager defines the `$PATH` globally available to applications.

I'd imagine macOS has some way to configure this, I know Windows does. But you're on your own there.
