### ISSUE TITLE
Feature suggestion/Bug fix: Use libdecor for CSDs on Wayland

### ISSUE THREAD

**Issue by orowith2os** [alacritty/alacritty#6506]
### System

OS: Linux
Version: any
Linux: Wayland

### Description

Currently, Alacritty draws its own CSDs for GNOME, as it's the only Wayland compositor that doesn't implement SSDs (for technical reasons, and CSDs are required by the Wayland spec anyways). This can cause it to look out of place on GNOME and other compositors that don't implement CSDs.

the library libdecor (link unavailable as the GNOME servers are down atm) can help to draw CSDs for applications not using a GUI toolkit, and that don't want to pull in an entire toolkit just for CSDs. It also recently got a GTK plugin, so now applications using it look "right" on GNOME Wayland.

There has yet to be a release including this feature, but it might be wise to start looking into it to help fix the user experience of Alacritty in (hopefully) all Wayland environments, regardless of whether or not they implement SSDs.

**Comment by orowith2os** [comment]
Found some Rust bindings, maybe unmaintained? <https://github.com/cmeissl/libdecor-rs>

**Comment by kchibisov** [comment]
libdecor doesn't provide GNOME looking decorations as well, so it's irrelevant. Is GTK using libdecor? I doubt it, so it's all irrelevant anyway. libdecor is to help drawing CSD not to make CSD look like they should look on GNOME.

**Comment by kchibisov** [comment]
Seems like you've mentioned GTK plugin, but what I can say that it doesn't matter anyway, since it's not even remotely rust friendly, so that's why you don't see bindings for it. No way to safely use it in projects from what I'm aware. If you want something like that in alacritty see `smithay` issue, once it get's resolved it'll work here automatically.

**Comment by orowith2os** [comment]
Coming back to this, I think there was some confusion.

Libdecor has a GTK plugin in -git, using it is done the same as using libdecor was before. The GTK plugin is used automatically, nothing else needs to be done for the apps using libdecor.

Even if libdecor isn't meant to make CSDs look native, that doesn't stop it from trying to achieve that goal, and it's a useful one, especially since apps like Blender are using it now.

Is using *libdecor* not Rust-friendly, or GTK?

**Comment by kchibisov** [comment]
Using libdecor is not rust friendly.

https://gitlab.gnome.org/jadahl/libdecor/-/issues/30

**Comment by kchibisov** [comment]
Just to ensure, since I randomly came back to that.

Do you really not like the current CSD decorations, they don't look that bad and not that off on GNOME, ofc we don't read your GTK theme settings, but it's not like they're bad.

![picture](https://user-images.githubusercontent.com/27620401/223556973-bb495a6f-3deb-4749-badc-e37596b84daf.png)

**Comment by orowith2os** [comment]
To put it simply, they look *very* out of place, I'd rather have decorations embedded inside of an app that aren't similar to GTK. The positioning of the icons feels off, the coloring is.... Weird, and they look worse than the default Cairo decorations libadwaita gives.

Mimicking libadwaita doesn't feel like the right move here. What I would suggest is add a few features, like tabs, and self-draw the decorations there so they integrate well with the app.

**Comment by kchibisov** [comment]
>To put it simply, they look very out of place, I'd rather have decorations embedded inside of an app that aren't similar to GTK. The positioning of the icons feels off, the coloring is.... Weird, sizing is off, and they look worse than the default Cairo decorations libdecor gives.

Yeah, every app should have the same title bar, that's way gnome is a no go basically.

>Mimicking libadwaita doesn't feel like the right move here. What I would suggest is add a few features, like tabs, and self-draw the decorations there so they integrate well with the app.

No, but you're free to submit your window frames to winit, right now it has 2 variants. This option is default in winit, because it's preferred by the majority of gnome users on winit.
You can even submit a real GTK based theme the way libdecor has, just no-one cares about such thing (and it's likely won't be enabled by default at all).

**Comment by orowith2os** [comment]
> Yeah, every app should have the same title bar, that's way gnome is a no go basically.

No, I'm saying that the title bar should be application-specific and integrated with the app. Normal title bars are space inefficient because all they're used for is an application name and three buttons.
