### ISSUE TITLE
Synchronized Output via SM/RM ?2026

### ISSUE THREAD

**Issue by christianparpart** [alacritty/alacritty#6507]
I'm kindly asking you to expose synchronized output feature via SM/RM ?2026. We've been talking about it 2 years ago and I drafted a spec and adoption tracking document over here: https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036

I now came across that again and wanted to see if anything has changed since then. So I realized that Alacritty did not adopt to that just yet.
So I want to kindly ask you now.

What do you guys think?

**Comment by kchibisov** [comment]
Yeah, we use original DCS IIRC. Though @chrisduerr has more info wrt that, since he added it.

**Comment by chrisduerr** [comment]
What's the argument over what Alacritty supports already? Just adding more stuff for the hell of it doesn't seem productive.

**Comment by christianparpart** [comment]
Good morning. Without going into the political discussions from the past, my whole idea here is to streamline the idea here. Such that apps don't need to care about more but one subtle way for doing things. I hope that argument can be understood.

**Comment by chrisduerr** [comment]
Well any terminal out there is capable of implementing the original DCS, so that should really take care of streamlining things.

If an application developer desperately wants it they can send a patch to implement it themselves. But from what I've seen nobody cares about the escape anyway.

**Comment by kchibisov** [comment]
I think the main motivation is that everyone is moving to mode instead of DCS, so we can support the mode and drop the DCS?

I don't see a reason to support DCS if most use the new mode escape sequence.

I don't really like the DCS escape sequence so removing it entirely and using the mode thing sounds like the plan.

**Comment by chrisduerr** [comment]
Which application actually relies on it being one way or another though? I'm not aware of any application that would actually need this escape actually making use of any of the variations.

**Comment by christianparpart** [comment]
I know of notcurses making use of it. And I was just about to submit a patch to vim/neovim. Zellij is about to implement it.

Some side needs to start, if we all wait for it to happen on the other side first, we are not moving at all.

Mind, my idea here is to bring the terminals at least on the protocol level closer together. Some cooperation and willingness for that to happen as a shared goal in the open source community is really appreciated but if course not required. We are all humans.

Enjoy the weekend,
Christian Parpart.

**Comment by chrisduerr** [comment]
Alacritty made the first move, implementing support for it a while back. At this point applications don't have an excuse anymore.

If people actually adopt the alternative escape sequence than it's trivial to change Alacritty to support it. But I don't think Alacritty is in a position where its lack of support prevents applications from making use of it.

**Comment by christianparpart** [comment]
But it WILL diverge the protocol and make it more hindering for the application developers as there is always those left out with the special case to be handled.

That is the broader picture I think it's worth to avoid. Especially since it is easy to avoid on our end

**Comment by kchibisov** [comment]
Be aware that `awhile` was even before you've drafted spec I think. It was done during terminal-wg era discussing original DCS from iterm.

I do agree that we should use whatever everyone decided to use even though we have a situation where we had working solution done in multiple terminals and then folks decided to use modes and strange feature detection for that.

The reason we have feature detection is because we have mods for that, but that's something I do understand(not a fan of given that with DCS we used terminfo cap).

I'm more inclined to have mode only because major applications target the mode variant and not the DCS one.

Also, is tmux using the new mode now? It's also a terminal emulator and I think they used DCS as well initially, since the mode variant wasn't even there(same about when alacritty added the mode).

I'd at least figure out what tmux is using since lots of folks are running their stuff inside of the tmux and given that it's a yet another terminal emulator you rely on it using the same escape sequence as your outer terminal for that. From now I feel like it's still DCS.

**Comment by christianparpart** [comment]
Oh yeah, I know I'm not the first to start this. when I joined this discussion, it was however stale, and (after reading through it) I was simply agreeing with the iTerm author that mode based is better than DCS based. The fact that you can use `DECRQM` to do feature-detection was my idea, which seems to be a strong argument for it mode based rather than DCS.
When sticking to DCS that would only be unreliably possible via terminfo entry.

Speaking of which, tmux doesn't seem to use either, it however reads out the "Sync" entry from terminfo. I am not sure however who else is doing that nor providing it (probably Alacritty?).
I agree with you here, too, @kchibisov, that supporting both would be less ideal (I think: hurting in fact): Just go with what we seemed to have a consensus with over a year ago and stick with it. I'm personally simply the one trying to push forward here (so nothing personal, I apologize if it looks like such). I also do not want that ticket to end up being the place to discuss deep cross-terminal organizational issues we have.

What I'm currently doing (apart from this ticket here), is trying to update the above linked document with the current state, see if anything has changed, and what could be added or should be improved.

**Comment by chrisduerr** [comment]
> Speaking of which, tmux doesn't seem to use either, it however reads out the "Sync" entry from terminfo. I am not sure however who else is doing that nor providing it (probably Alacritty?).

Alacritty implemented it after tmux already had all the implementation details down. Thus we added the `Sync` terminfo after it was already somewhat established by tmux. Though (unsurprisingly) Thomas Dickey declined adding the `Sync` capability to `ncurses` due to its terminal-wg affilitaion.
