### ISSUE TITLE
failed to build from source on ubuntu 22.04.1

### ISSUE THREAD

**Issue by 0ussamaBernou** [alacritty/alacritty#6646]
i followed the documentation to build from source but it keeps failing with this error!

### System

OS: Linux ubuntu 22.04.1
Version: building from source
Linux/BSD: x11

### Logs

Crashes: STDERR
```rust
 --- stderr
  thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit status: 1
  error: could not find system library 'fontconfig' required by the 'servo-fontconfig-sys' crate

  --- stderr
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  ', /home/oussama/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by Abhijrathod** [comment]
It seems that you are encountering an issue with building Servo (a web browser engine) from source on Ubuntu 22.04.1. The error message "thread 'main' panicked at '"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1" did not exit successfully" is indicating that the build process is failing because it cannot find the "fontconfig" library, which is required by the "servo-fontconfig-sys" crate.

It looks like the problem is related to the pkg-config package, which is used to locate the "fontconfig" library on your system. The error message "Package fontconfig was not found in the pkg-config search path" suggests that the pkg-config package is not able to find the "fontconfig.pc" file, which is needed to identify the location of the library.

To fix this issue, you can try the following steps:

Install the fontconfig library:
Copy code
sudo apt-get install libfontconfig1-dev
Check if the fontconfig.pc file is present in your system
Copy code
find /usr -name fontconfig.pc
If the fontconfig.pc file is not present, you can try installing the pkg-config package
Copy code
sudo apt-get install pkg-config
Set the PKG_CONFIG_PATH environment variable to the directory containing the fontconfig.pc file:
Copy code
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig/
Re-run the build command
These steps should help you to resolve the issue and build Servo from source on Ubuntu 22.04.1.

Note: It's always a good idea to check the Servo's documentation and the issues section of the Servo's Github repository, as this problem might have been already reported and a solution might exist.

**Comment by chrisduerr** [comment]
See INSTALL.md.
