### ISSUE TITLE
Add support to highlight lines scrolling into view

### ISSUE THREAD

**Issue by pickfire** [alacritty/alacritty#6679]
Konsole have support to highlight lines scrolling into view so users know what lines are new. In preferences > scrolling > highlight the lines scrolling into view.

![Screenshot_20230206_153947](https://user-images.githubusercontent.com/4687791/216912737-83c04457-f0ba-4d35-8d06-95385c5327b9.png)

Notice the blue lines on the left on the window, if there are multiple lines at different times, the blue lines may be different in color, from light to dark.

**Comment by chrisduerr** [comment]
Why do you want this?

**Comment by pickfire** [comment]
Because the terminal is too fast and I would like to know what are the new lines being rendered without having to trace manually with my eyes, so far I think only konsole does this and when I first noticed this unique feature I find it quite interesting.

**Comment by kchibisov** [comment]
But how would you determine if something was seen or not? By whether this content was ever rendered, by focus? I'm not sure if this is any useful tbf, you usually look for specific lines in the input, so you can just live search for them...

**Comment by pickfire** [comment]
Yeah, can live search, but if it's log output and it keep streaming in, usually on those terminals without this feature I have to enter a few newlines manually using space, but with this feature don't really have to.

**Comment by chrisduerr** [comment]
Yeah I don't see how this would be useful at all. Sure you could track being read by input or focus but at that point you're basically just tracking output since the last command which is better solved by other features.

To me this feature doesn't exist anywhere but in Konsole because it's just not a good feature. There probably might be a simple-enough unoffensive implementation that could get included if enough people are interested, but it's certainly not something I'm personally interested in adding.
