### ISSUE TITLE
Alacritty stops outputting after special escape sequence

### ISSUE THREAD

**Issue by m0ppers** [alacritty/alacritty#6714]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: Wayland,sway

First of all: This report might as well be bogus but I am not sure as I am not really into all these terminal standards.

I have a program that is using a binary third party library. this library outputs broken byte sequences on the terminal (no idea why they thought that might make sense). After one of these byte sequences alacritty stops outputting. when the program exits everything works again. So far my workaround was to use `termite` when I start this program as this doesn't have the problem. Today I failed once again to recall that I need to switch to termite when I execute that program, lost all log output but this time I got annoyed and tried to find what was going on :joy: 

I can now reproduce it very simply:

Open alacritty (bash if that matters):

```
[mop@ludwig-otto ~]$ printf "\x1b\x94\x5f\naaa\n"
[mop@ludwig-otto ~]$
```

alacritty does not seem to recover from that. any output after the escape sequence is lost. I would hope that `aaa` is printed. I am not sure what makes this escape sequence so special. maybe this is expected behavior. As I said: `termite` does what I expect. `kitty` for example has the same problem like `alacritty`.

**Comment by chrisduerr** [comment]
Cannot reproduce this. Are you running any multiplexer like tmux?

**Comment by m0ppers** [comment]
no multiplexer. I just installed alacritty on my mac and there it hangs completely when I execute the printf stuff 😱

**Comment by chrisduerr** [comment]
Oh are you complaining that the `printf` command isn't outputting anything? It sounded like your terminal emulator was freezing up completely, unable to render any more output.

**Comment by h-leth** [comment]
Tested on my system. Alacritty doesn't freeze but it's not printing the `aaa`s. It's printed when I run the command in iTerm

**Comment by kovidgoyal** [comment]
That's invalid UTF-8. alacritty and kitty both ignore the invalid byte which here is \x94. After ignoring it whats left is the start of an escape code \x1b_ (the PM escape code). This escape code must be terminated by \x1b\\ which is missing in your printf. I presume the other terminal emulators you tested abort processing of the escape code instead of discarding \x94. Or they abort PM escape codes on conditions other than just \x1b\\ and \a, such as when they contain non-printable bytes or control codes.

And on a general note, you should *never* output unsanitized bytes directly into a tty. If you have some program doing this, pipe its output through cat -v

**Comment by chrisduerr** [comment]
There's generally a couple scenarios where Alacritty behaves a bit differently than other terminal emulators (xterm/vte/urxvt) when it comes to parsing unicode byte sequences. Kitty generally seems to behave the same way as we do, which gives me some confidence, but there are a couple issues in the VTE repo I wanted to look into.

But yeah, considering that this doesn't break the terminal or anything obviously buggy like that, I'll consider it working as intended for now. You mostly just got lucky that the emitted bytes didn't break other terminal emulators since there's a bunch of escapes that would leave the terminal in a seemingly inoperable way in a fully intended fashion (like `\x1b(0`).
