### ISSUE TITLE
Fonts not loading correctly

### ISSUE THREAD

**Issue by Azkaas** [alacritty/alacritty#6724]
So for some reason my fonts arent loading correctly in alacritty.

Many fonts will act weird like this:
![image](https://user-images.githubusercontent.com/112915552/220080575-ba6fb00a-2918-4e42-925d-7b9079a5057c.png)

The font i want to have kinda works, but its still a bit buggy:
![image](https://user-images.githubusercontent.com/112915552/220080696-1054d50a-90b9-46c3-9fb8-bf9ad16bb974.png)
![image](https://user-images.githubusercontent.com/112915552/220080732-fc0ebf39-699a-4737-b13b-a2c380cc9dab.png)

There are a few small bugs like this with this font as well. The fonts Im trying are installed, and they work with other programs.

![image](https://user-images.githubusercontent.com/112915552/220080950-d38c71e2-9c5b-42db-bb4e-d23d6a2b2b80.png)
Also worth mentioning is that the font size needs to be 7 in alacritty to show a somewhat normal font size which i also find weird

**Comment by kchibisov** [comment]
It seems like everything working as it should. The font is `DPI` scaled automatically in alacritty(I'd assume you're on X11 or something) and the font is in `pt` not in `px`.

When font is not looking as expected, like on the first picture, you're likely miss spelled it. See `fc-list | grep -i YOUR_FONT_NAME`(if you're on free platforms) to get the idea how to spell it.

As for the rounded character, it's likely the issue because the character is coming from some other font and not align correctly, some terminals draw built-in version of it(not from your font), while alacritty don't(at least for now).
