### ISSUE TITLE
"謹" character appears as double width

### ISSUE THREAD

**Issue by unphased** [alacritty/alacritty#6750]
This character (which appears normally here as a CJK glyph, a hint to me as to why alacritty might render it double-width) is used in Nerd Fonts as a `</>` code symbol (usually used to indicate an XML file or something). 

I'm curious to know if there's a simple setting I can use or something to force alacritty to never make any character glyph consume two spaces. As you can imagine this throws TUI rendering seriously out of whack. 

Issue is replicated in iTerm2 as well (though with slightly different behavior where the rendering changes depending on cursor position. to be clear alacritty does not have THAT behavior), so given that I don't know how fonts actually work at all, this might be a problem with the nerd font patching process and the root of the issue belongs with the font itself. 

Still, I'd like to know if it's possible to more forcibly render all glyphs monospaced.

**Comment by chrisduerr** [comment]
There is no setting to make CJK characters single-width. Everything is working as intended here, I would suggest fixing your broken font.

**Comment by Finii** [comment]
> I would suggest fixing your broken font.

Which means: Have a font with the correct CJK glyph on the CJK codepoint.
That is why Nerd Fonts will stop patching symbols into CJK codepoints starting with `v3.0.0`.

And already now you can move, because the current Nerd Fonts fonts have already moved (copied) the affected symbols to correct codepoints and having them in the wrong-CJK-codepoints in parallel is just to give people time to convert their symbol settings.

A list old-to-new codepoints is [here](https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287) (open 'details').

**Comment by unphased** [comment]
@Finii appreciate the added detail 👍
