### ISSUE TITLE
Alacritty Prompt & Colors not displaying correctly.

### ISSUE THREAD

**Issue by mghalix** [alacritty/alacritty#6830]
#### Description
I have been using [**Kitty**](https://github.com/kovidgoyal/kitty) for a while now, I decided I want to give **Alacritty** a shot and I LOVED it!
I can feel how faster it is compared to Kitty, the only thing is I cannot seem to use my favorite font as I do in Kitty
without having a weird-looking edge of [Starship Prompt](https://github.com/starship/starship) and the color intensity difference is clear between the two terminals.

#### Screenshot
# <pre>           ↙ <img src="https://raw.githubusercontent.com/alacritty/alacritty/master/extra/logo/compat/alacritty-term%2Bscanlines.png" alt="Alacritty Terminal Logo"  width="25px" height="25px"  /> Alacritty          <img src="https://sw.kovidgoyal.net/kitty/_static/kitty.svg" alt="Kitty Terminal Logo"  width="25px" height="25px"  /> Kitty ↘ </pre>
![Alacritty vs Kitty](https://user-images.githubusercontent.com/74559094/229316362-dc2422d9-151d-485f-9520-1d503bf2bd5a.png)

### What I have tried
- Setting `use_thin_strokes: false` then the log prompted an error that this key is deprecated and is now mapped to AppleFontSmoothing. So I set  `AppleFontSmoothing: true`  but unfortunately still looks the same.
- Setting `env: TERM: xterm-256color`.
- Setting `draw_bold_text_with_bright_colors: true`.

### PS
I made sure I am using the exact **_same font family_** in **both terminals** and the **_same color scheme_**.
### System

OS: Linux
Distro: Ubuntu Lunar Lobster (development branch)
Release: 23.04
DE/WM: i3wm
**Version: alacritty 0.12.0**

**Comment by chrisduerr** [comment]
We make zero guarantees about exactly matching the colors of other applications.

**Comment by svanharmelen** [comment]
This is very likely due to a change made in the last release. It's a shame @chrisduerr is as stubborn as he is (no offense 😉) as it's super easy to allow people to keep using the old behavior but somehow he (or they, maybe better to refer to the maintainers in general) doesn't want to give people that choice.

After a few days of trying to get used to the new washed out colors I ended up compiling Alacritty myself to enable the old behavior. Sounds ridiculous, but I guess there is no other way. Yeah maybe sticking with Kitty as they do offer this choice to their users....
