### ISSUE TITLE
Alacritty --hold -e command  - hold for a specific amount of seconds - countdown and stop

### ISSUE THREAD

**Issue by arcolinuxz** [alacritty/alacritty#6895]
Alacritty --hold -e command  - hold for a specific amount of seconds - countdown and stop

No bug report.

Is this already possible?
Can this be added if not available?

**Comment by kchibisov** [comment]
What would be the use case for such thing which couldn't be covered with the shell?

You can clearly do what you want with `--hold` with just e.g. alacritty -e bash -c "script; sleep 100; exit". Which will run your script, sleep for 100 seconds afterwards, and exit.

**Comment by Name-Identity** [comment]
A use case for this would be as follows:

alacritty --hold -o font.normal.style=bold -o "colors.primary.background='#000000'" -o "colors.primary.foreground='#ff00ff'" -o colors.cursor.text=CellBackground -o colors.cursor.cursor=CellBackground -o window.position.x=700 -o window.position.y=300 -o font.size=12 -o window.dimensions.lines=13 -o window.dimensions.columns=31 -o window.decorations=none -o window.padding.x=20 -e protonvpn-cli c -r -p tcp

After spending an unacceptably long time figuring out how to translate configuration settings as listed in the manual into there "-e" switch equivalents I now have a working command to connect to my vpn via a keyboard shortcut. 
Although i was aware everything i was doing was probably easily achievable by a more experienced person via scripting, I choose this skill set to develop first. 

The only things i am missing that would make this command perfect is the ability to have it automatically disappear after a suitable period of time, instead of the "alt+f4" key combination which is not terribly troublesome.

Having perhaps pushed the -e switch to its intended limits (is stacking -e switch`s possible? i cant seem to make it work.)
I appreciate the head start you have given me on transitioning these commands to a script.

**Comment by chrisduerr** [comment]
This is trivially resolved with a bit of shell scripting similar to @kchibisov's suggestion.
