### ISSUE TITLE
Feature Request: adding an option to hide the hyperlink URI preview 

### ISSUE THREAD

**Issue by peterwu** [alacritty/alacritty#6950]
I use my own status bar built on terminal emulator. It uses OSC 8 to show a list of hyperlinks that will show the desired workspace when clicked. Since it is a status bar, it has only 1 line.

The issue is that when the mouse hovers on an OSC 8 hyperlink, alacritty displays the preview of the URL at the bottom, which happens to be on the only line the status bar has. This causes the preview to overlay the text underneath.

Is it possible to add an option to disable the preview or hide the footer bar ? Thanks.

**Comment by kchibisov** [comment]
But it shouldn't obscure anything? The preview won't be shown on the line with normal cursor and mouse pointer, so it shouldn't change anything from the usability point of view or the ability to click the content.

**Comment by peterwu** [comment]
The status bar hides the cursor, by using `tput civis`, to simulate the experience of a true bar.

**Comment by kchibisov** [comment]
I'd just not show the preview when you don't have enough space, the preview should move, but if we don't have enough space it'll obscure the line.

**Comment by peterwu** [comment]
I am not sure how to hide the preview and hence I opened this issue. :-)

Do you have any suggestion? Thanks.

**Comment by kchibisov** [comment]
To fix it in code?

**Comment by peterwu** [comment]
> To fix it in code?

If you could add something in alacritty's code to show/hide the preview, that would be great.

**Comment by peterwu** [comment]
> I've already said that I'd likely not show preview for single line terminal.

I'm sorry I don't think I am following you on this. 

Did you mean to say:  this function is in alacritty already? or, you wanted to say : you are not going to write code to hide the preview in a single line terminal? Honestly, I'm confused by your reply.

Would you please clarify a little bit? Thank you.

**Comment by kchibisov** [comment]
I mean that we need to change logic to not show preview when you have a single line terminal. Right now we force preview to overlap when there's no sufficient space.

**Comment by peterwu** [comment]
> I mean that we need to change logic to not show preview when you have a single line terminal. Right now we force preview to overlap when there's no sufficient space.

Got it. Thank you!

**Comment by chrisduerr** [comment]
> I've already said that I'd likely not show preview for single line terminal.

I strongly disagree with this. The code is behaving as intended and it works just fine.

The issue here is that you're not actually using a terminal emulator, which is what Alacritty's purpose is.

If you're able to use Alacritty for anything that it's not intended for, that's good for you. But if that stops working at any point because of changes made to Alacritty for the purpose of terminal emulation, that's 100% on you. This thing you're using Alacritty for is **not supported**.

If you want to fork Alacritty and tweak it to make it work for your bar, that's perfectly fine. I'm happy to help out if you're looking for some advice on where to get started. But upstreaming that is not an option unless it benefits Alacritty's actual purpose.

**Comment by kchibisov** [comment]
>I strongly disagree with this. The code is behaving as intended and it works just fine.

it's not, because it doesn't show preview for 2 lines already. I just never tested one line. The motivation is that you simply can't click, so that's why we have it that way.

**Comment by chrisduerr** [comment]
> The motivation is that you simply can't click, so that's why we have it that way.

Yes but in the example the cursor isn't actually obstructed. You're perfectly capable of clicking.

The only reason to ever remove it is if you cannot put it in a place where it wouldn't obstruct the cursor.

**Comment by kchibisov** [comment]
Well, the preview should show only when you have a cursor over it or mouse cursor, and we don't place the preview on the line with the mouse pointer and terminal/vi cursor. I just feel like there's a bug due to ` * 2` mul, which I don't really understand in the preview logic.

I'd at least test myself, because as I've initially seen this, the preview obscured the button.

**Comment by kchibisov** [comment]
So the obscuring is intentional given that you can still click and it shouldn't raise any issues with the bar on its own.

In general though, if you want a bar and you write an application for that already, use mouse mode, you won't have preview inside of it unless you hold a shift and you'll get mouse clicks directly, so you won't rely on external terminal having OSC 8 support.
