### ISSUE TITLE
Bring back self-documenting config file

### ISSUE THREAD

**Issue by pinko-fowle** [alacritty/alacritty#7026]
[`alacritty.yml` was recently deleted]( https://github.com/alacritty/alacritty/commit/bd4906722a1a026b01f06c94c33b13ff63a7e044#diff-f5b5672ff049d966893431bfa5fee85f289d8388da5a25a203f4fbcd1a05dda2), during the move to toml. This file was an excellent resource for users, to quickly understand the default configuration & to quickly make modifications.

It would be excellent to have a similar file in toml format available, that self-documents all the config options. Without this, configuring Alacritty is a daunting task. I'm unsure what users can do to understand/learn the default configuration, with where we are now.

**Comment by kchibisov** [comment]
man pages are expected to be used with the new config file, much better because you can do `man 5 alacritty` and read about all the options and it'll get updated for you, instead of going into github page and comparing the configs.

It's also always for your version, because it's shipped by your system/package.

**Comment by pinko-fowle** [comment]
This feels like a bad tradeoff to me. I still have to go craft a config file from scratch to use `man 5 alacritty`. Where-as before I had a great fully self-documented complete inventory of all config options that I could quickly tweak. We've gone from useful structured information that can be directly used to indirect reference material that has to be marshaled into something useful.

Ideally, to me, there'd be an `alacritty --print-default-config` that would print a complete reference file, for the current version. And that would be automatically checked in & updated. And a `alacritty --print-config` that would print the current complete config. Creating better ergonomics around handling config would be a huge improvement, but I also appreciate that this is asking for a lot of support/development.

**Comment by kchibisov** [comment]
You take options you want to change and then use just them? Why would you need a config file with all possible options, such configs are never synced in the first place. man pages are standard source of documentation, they provide color/style coding and simpler to use.

Besides it's a lot of work to handle incorrect users configurations, or configurations from the development branch, because they've used the self documenting config for master, now they don't have config at all, so no issue, there'll be man pages and alacritty.org with the man page for stable releases. So configs are synced and only stable documentation is present to the end users.

**Comment by chrisduerr** [comment]
> Where-as before I had a great fully self-documented complete inventory of all config options that I could quickly tweak.

This only ever helped people the first time they would configure Alacritty and has caused **numerous** issues with people that copied config files decades ago and never updated them.

> a complete reference file, for the current version

Again, this will just cause pain and suffering on version updates. We do **not** want people to have all available config options in their configuration files. That's just not a good idea.

Also the "default config"/"current config" is just empty in a lot of cases. So that doesn't really help.
