### ISSUE TITLE
Why is so hard to make alacritty load bashrc and profile at the same time? Why isn't that the default behavior?

### ISSUE THREAD

**Issue by sgon00** [alacritty/alacritty#7150]
### System

OS: Linux (debian)
Version: `alacritty 0.11.0`
Linux/BSD: X11, KDE

### Problem

With the default config, alacritty can load `~/.bashrc`, but it can NOT load `~/.profile`.

So to make it load `~/.profile`, I googled the problem and added the following to the config file `~/.alacritty.yml`:

```yml
shell:
  program: /bin/bash
  args:
    - --login
```

After the above config, alacritty can load `~/.profile`, but it won't load `~/.bashrc`

So how to make alacritty do what it should do like all other terminals?

Thanks a lot.

**Comment by kchibisov** [comment]
We don't load any files other than alacritty config. It's all up to your shell. If you want to load your `.bashrc` on login just source it from `.profile`.

**Comment by sgon00** [comment]
@kchibisov I can not source it from `.profile` because that will make the file loaded twice in other terminals. Can you please provide a proper alacritty way to load both files at the same time like what other terminals do? I don't think this issue should be closed until there is an alacritty way to load both `.bashrc` and `.profile`. Thanks.

**Comment by kchibisov** [comment]
those files belong to bash, bash does the sourcing, if other terminals try to be smart and source arbitrary env, it's up to them, we don't do that.

Do they source `.profile` when `zsh` is used or fish? That would be just nonsense.

**Comment by sgon00** [comment]
@kchibisov thanks for the reply. Sorry for the harsh words earlier. Please understand that I spent a day and couldn't make alacritty do a very simple terminal function and collapsed. I won't bother you and report any issues here if I can find an answer by search. I don't want to talk about the concept and the background technology of other terminals. You are a terminal expert, I am just a normal user. I don't have to be an expert to use a terminal. All I want to do is to load `.bashrc` and `.profile` in alacritty, that's all. If I follow your advice to source `.bashrc` from `.profile`, other terminals will load `.bashrc` twice, that's not what I want. `alacritty` is not the only terminal I am using. So how to load them properly in alacritty? As a normal user, I think this is just a normal request and a normal linux terminal feature. Thanks a lot.

**Comment by kchibisov** [comment]
Source on condition? There's `ALACRITTY_WINDOW_ID` variable you can check.

But usually, the way it works that you login with your login shell and it sources the `.profile` env. Then upon launching regular applications the stuff from login is being inherited, the `.bashrc` is being loaded, because you're running interactive shell (bash -i).


`.profile` is usually meant to set on login (that's why `bash -l` sources it, and why it doesn't source `.bashrc`), also, sourcing twice shouldn't matter, because `.profile` usually sets the `env` with `export FOO`, unless you do something complex in `.profile` which sort of assumes that interactive shell.

This all, again, has very little to do with terminals, it's just shell stuff. I'm surprised that you have this issue at all on Linux, because you surely login somehow, unless your login shell is not bash and it doesn't source the profile.


In the following case, it'll do what you want automatically.

1. You login on `tty`, your login shell is used, and `.profile` is being sourced.
2. Then you run your kwin/compositor and run alacritty in it. The interactive `bash` is used and `.bashrc` is being loaded.
3. So in the end both files are sourced.

Maybe kde is not trying to source it, that would be expected, since some gui login stuff doesn't source anything.

>So how to load them properly in alacritty? As a normal user, I think this is just a normal request and a normal linux terminal feature. Thanks a lot.

alacritty is not a bash interpreter, sourcing profile the way you describe is completely arbitrary https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bash-Startup-Files 
Usually login stuff is inherited from the actual login into the system.

**Comment by sgon00** [comment]
> I'm surprised that you have this issue at all on Linux, because you surely login somehow

@kchibisov I don't restart my PCs and laptops. For example, I haven't restarted (re-login) the laptop I am currently using for more than a year. Normally, when I need to carry it around, I just suspend the system to ram. Other terminal will re-source `.profile` everytime I launch them. `alacritty` doesn't do that without `--login` args in config file.
Anyway, yeah, I can source on condition, that's just a workaround I thought about it. If there is no easy way to achieve that, I will source on condition. 
Thank you very much for the detail explanation, help and time.

**Comment by kchibisov** [comment]
if you don't `relogin` why do you even put settings in a file meant for `login` in the first place? It all sounds like you want to put things into `.bashrc`.

**Comment by sgon00** [comment]
I don't relogin locally. But I do ssh in from remote. And I want to run some scripts and setup some env on both current running DE and remote ssh login in. Anyway, I will rethink and modify both `.bashrc` and `.profile` then if I want to make both reload in `alacritty`.

**Comment by sgon00** [comment]
PS: there is one more reason I forgot to mention in last comment. Some scripts take a long time to run. If I put them in `.profile`, it will just load once and all tabs in the same session will not load it again. If I put it in `.bashrc`, it will load it again and again in every tab, that's kinda too much to wait for a tab to open.
