### ISSUE TITLE
Problem with Japanese keyboard.

### ISSUE THREAD

**Issue by arafune** [alacritty/alacritty#7167]
### System

OS: macOS
Version: alacritty 0.13.0-dev (6143b3f4)

In the previous version, which uses yml file for  configuration, following works.  (I'm Japaneses and I use Japanese keyboard.)

{ key: Yen, mods: Alt, chars: "\\" }
{ key: Backslash, mods: Control, chars: "\x1c" } 

However, after update, it doesn't work even if converted toml file. Could you let me know how can I fix it?

**Comment by kchibisov** [comment]
What do you get when you press a key with `alacritty --print-events | grep KeyEvent`?

**Comment by kchibisov** [comment]
@arafune hm, yeah. You have to use `"¥"` directly now in the bindings. I guess I simply forgot to add compat layer for that, because upstream changed.

It's unclear why macOS tells us the keys that way and why we get `|` for `ctrl`, but I think we have issue like that already wrt `ctrl` doing something weird with some special keys...

**Comment by kchibisov** [comment]
@chrisduerr  Do we want to have backward compat bindings for stuff like that? We already have some, but I feel like I forgot about special chars...

**Comment by chrisduerr** [comment]
Can we do this generically?

**Comment by kchibisov** [comment]
The old enum in winit was exhaustive, we've done some events, but it seems like I've missed a few ones, since I thought that we had `Yen` for example...

it's a matter of adding more stuff to the list, I'm just not sure what they have as a character variant...

**Comment by chrisduerr** [comment]
Would probably depend on the number of new stuff. But probably makes sense.
