### ISSUE TITLE
kernel rejected pushbuf: invalid argument

### ISSUE THREAD

**Issue by Robin-Sch** [alacritty/alacritty#7222]
### System

OS: Arch Linux
Version: 0.12.2
X11 with bspwm

### Logs
nouveau: kernel rejected pushbuf: invalid argument

Whenever I uninstall `xf86-video-intel`, alacritty launches fine and works correctly. However, with it installed it doesn't launch and gives the error above.
I have 2 GPU's in my laptop, an intel iGPU and a nvidia dGPU. Issue is probably related to this, not sure tho.

**Comment by kchibisov** [comment]
Well, don't use `xf86-video-intel` (use modesetting driver) and your issue has nothing to do with alacritty since your drivers fail.

**Comment by Robin-Sch** [comment]
Well, I kinda need it to control brightness etc. Also, every other program works except alacritty. So this is an issue with alacritty then isn't it?

**Comment by kchibisov** [comment]
I mean, we use OpenGL API, your issue is with the video driver.

And you can control the brightness just fine without `xf86-video-intel` (unless you use some i2c?, but on Wayland you don't use any of that for example and you can control the brightness just fine).

There're tools like `light` and other brightness related stuff, it's all in `sysfs`, which xorg driver has nothing to do with.

**Comment by kchibisov** [comment]
Ah, light is not maintained anymore, but there should be other tools to actually write to `sysfs` which you can use without a need of `xf86-video-intel`, which is only for old hardware.
