### ISSUE TITLE
Launch New Window Upon Clicking Dock Icon or Spotlight Enter in MacOS

### ISSUE THREAD

**Issue by denppa** [alacritty/alacritty#7230]
Is it possible to configure alacritty to launch a new window upon clicking the dock icon or pressing enter after searching for alacritty in spotlight? Thanks!

Note: Installed via brew, v0.12.

**Comment by kchibisov** [comment]
I'm not sure why it wouldn't be, but I don't know much about such things in macOS.

In short, you can open a new window via the alacritty's IPC (`alacritty msg create-window`). Maybe macOS allows to configure something like that?

**Comment by chrisduerr** [comment]
What's the current behavior?

**Comment by denppa** [comment]
> What's the current behavior?

It brings me to the opened alacritty window. If that can't be helped, adding a menu item in the docker like browsers have to open a new window is also nice.

**Comment by chrisduerr** [comment]
Pretty sure we currently just rely on whatever's the default. I'm not sure having these configurable in Alacritty's config makes any sense, considering that macOS already has more OS-specific options than I'd like.

Can this not be configured globally? It sounds like the job of the DE.

**Comment by denppa** [comment]
For mac it seems to be an application specific thing, not related to the launcher.

**Comment by nixpulvis** [comment]
I'm unaware of any applications on macOS which open a new window when you click on an open window's icon. They often have a "New Window" right-click option however. But we don't have these setup for macOS or other platforms as far as I know.

[`applicationDockMenu(_:) `](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428564-applicationdockmenu?changes=_4)

I'm not I know _exactly_ how simply clicking on the dock (or spotlight search and command-tab) item works, but I believe it targets the last instance of the application on the current space. I'm unaware of any way to change this, unfortunately. See [this SO thread](https://superuser.com/questions/665004/how-do-you-prevent-the-dock-from-switching-monitors-in-macos-monterey).

This is actually one of the reasons why Alacritty having the ability to spawn new instances of itself (in addition to new windows within each instance) is useful. Ideally there would be a way to differentiate the icons when there are many running instances, but it still allows you to switch to exactly the one you want instead of just the one window that macOS selects.

Sorry if this doesn't make perfect sense. It's a bit confusing.

**Comment by chrisduerr** [comment]
I've tried hooking up an extra "new window" option to the menu when implementing this feature and decided it's not worth the hassle. A PR that doesn't introduce a bunch of ugly code to Alacritty might be accepted, but it's not something I'm planning to implement myself (though there might still be an issue open from back then?).

**Comment by nighthawk469** [comment]
@chrisduerr to be clear do you mean a PR for the implementation of a right click on Dock icon, "New Window", may be accepted?

I personally would love this right click functionality, which i use often for Chrome or Terminal.app.

**Comment by kchibisov** [comment]
>@chrisduerr to be clear do you mean a PR for the implementation of a right click on Dock icon, "New Window", may be accepted?

Yes.
