### ISSUE TITLE
Termkit Claims to be much faster

### ISSUE THREAD

**Issue by TheBlueMatt** [alacritty/alacritty#7237]
Probably not the most useful issue, but the README does suggest opening an issue if there's evidence alacritty isn't the fastest.

 https://fosstodon.org/@hergertme/111110865983787267

**Comment by chrisduerr** [comment]
> If you want to write a faster terminal emulator, I'm happy to take money in exchange for this esoteric knowledge.

Sounds like a scam.

What looks like their "benchmark" is certainly complete nonsense.

I appreciate the issue, but this is clearly just someone who isn't experienced in what they do.

**Comment by TheAlgorythm** [comment]
>> If you want to write a faster terminal emulator, I'm happy to take money in exchange for this esoteric knowledge.
>
> Sounds like a scam.

Sounds like he is joking about the usefulness of his knowledge.

> I appreciate the issue, but this is clearly just someone who isn't experienced in what they do.

The [Phoronix article](https://www.phoronix.com/news/Linux-Terminals-Could-Be-Faster) reads differently. E.g.:
> He [Prominent GNOME developer Christian Hergert] added part of the reason he was able to make it so far was due to his knowledge from writing a large part of the GTK renderer code and the profiler to guide how to spend the time optimizing the code.

**Comment by kchibisov** [comment]
>Sounds like he is joking about the usefulness of his knowledge.

It's not like they are joking, or they don't have knowledge. They haven't released the sources or tell anything about the benchmark. I could also change alacritty to run a particular benchmark faster than any other terminal and just post the end screenshot, but what's the point if no-one can validate the results? 

It could be faster than alacritty, cool, but how would I know that myself until I can actually run the thing? VTE isn't faster in the end though on the benchmark they showed on the picture.

And for example, they don't mean that their renderer is faster than alacritty renderer, because alacritty renderer is running on the separate thread and capped to frame rate, they need to patch the source to even measure it. But the point with renderer is that it should just be `fast enough`.

I also have no idea whether the terminal they used can parse escape sequences correctly, since more sophisticated payloads could just break the spec.

**Comment by TheAlgorythm** [comment]
I totally agree that `time` on `cat` (or whatever he uses) on a large file isn't a large benchmark suite. But I don't see any reason to attack him for a lack of knowledge.

>  But the point with renderer is that it should just be `fast enough`.

This is exactly what I thought he was joking about.

**Comment by kchibisov** [comment]
@TheAlgorythm I don't think there was an attack on anyone, it was just claimed that "they don't know what to do" when it comes to **benchmarking**, since I could tune alacritty to run way faster and account for a specific `cat` behavior, yet real applications don't render like that, and it's harder to optimize for them, as in they constantly change the position they write text into.

The `scam` also referred to the way results were presented, because I can scam like that as well by modding alacritty to run faster, but may be not correctly. Without a code you can't validate anything. When we asked for the source code of the terminal they run, they [refused](https://fosstodon.org/@hergertme/111115149505986350) to provide it.

Don't get me wrong, we get something like that from time to time, and I'm not sure how to reply to such messages anymore. The person wasn't attacked in my opinion, the way the decided to present all of that was attack, since they shared that to public, showed off that they're better than others, and refused to communicate unless you pay them money to do so.

**Comment by chrisduerr** [comment]
> The Phoronix article reads differently.

Phoronix is literally just blog-spam about any Linux-adjacent topic without any sort of in-depth understanding.

The original code talks about how to tweak things to make interaction with Pango more efficient for example, which is related to the Tweet author's GTK experience, but that is a completely self-inflicted problem by using GTK to begin with. No other terminal emulator (unless it's written in GTK), even has to struggle in this area to begin with.

> But I don't see any reason to attack him for a lack of knowledge.

Nobody got attacked, it's just a matter of fact considering the screenshot they posted. Nobody who actually knows anything about terminals would claim this as a big "gotcha" screenshot without adding several paragraphs of explanation.
