### ISSUE TITLE
Regex `;*|rust` doesn't match anything in `rustfmt` string

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#7276]
The bug is present on master and on v0.12.3. It's enough to search for the following regex.

The `;+|rust` works just fine.

**Comment by chrisduerr** [comment]
This is likely due to the leftmost search for the pattern causing `;*` to match empty strings and ending in a dead state thereafter.

I'm not sure if this can be solved without switching to a backtracking regex parser, but since users can relatively easily work around this, I don't think it's a big issue.
