### ISSUE TITLE
Accept environment variables for shell.program value

### ISSUE THREAD

**Issue by pentago** [alacritty/alacritty#7304]
For example, to make it easy to use different binaries depending on the architecture/OS, allow user to configure `shell.program` with environment variables, like this:

```
shell:
  program: $SOME_VAR/bin/binary
```

At a bare minimum (or also), accept relative path such as `~/.dir/bin/binary`

**Comment by kchibisov** [comment]
Use `SHELL` var if you really want to do it that way for other cases you can set shell as your default shell, or symlink the app.

**Comment by pentago** [comment]
how would that look in my example?

**Comment by kchibisov** [comment]
set `SHELL` before running alacritty. But there's no need to support complex configurations and env expansions.

`SHELL=sh alacritty`

**Comment by pentago** [comment]
The whole reason for asking all this is because I develop a shell and need to be able to use different binary depending on the architecture of the computer I use, and I'm using multiple different architectures at work, home and during the field work, it may be any architecture and operating systems combination really.

Using variables in `shell.program` would make this a ton easier.
For example, even if I used `sh` or `bash`, their binary paths might be different across operating systems and architectures.

A way to dynamically pick a program to run as shell would be amazing, I'm just not sure if there's a way to do this with non-CLI started Alacritty instance.

**Comment by kchibisov** [comment]
You don't need a full path, it should just be in your path or you should set a shell for your user with `chsh`. As I said, what you want is usually done via aliasing/setting as default, etc.

**Comment by kchibisov** [comment]
You can set shell to

```
shell: "my_shell"
```

if "my_shell" is in your `PATH` before running alacritty.

**Comment by pentago** [comment]
1. Does that mean I should remove `program`, because Alacritty reports YAML config error (_block mapping_).
2. How about shell args in this case?

**Comment by kchibisov** [comment]
it's a shorthand syntax. you use either `shell: <binary>` or
```
shell:
    program: <binary>
```

**Comment by pentago** [comment]
No, this isn't working for some reason.

Does alacritty support running a shell script stored in a relative path like `~/.bin/scripts/commands.sh` somehow via program or args?

**Comment by kchibisov** [comment]
I'm pretty sure it's not in your `PATH` before running alacritty. In general, if you always store your script in the same place, just use it with absolute path. This is all just macOS issues, because macOS doesn't run login shell and you have to do all of that yourself.

I'm not sure how you even wanted to solve this originally with `env` variable, because it won't be set when you run `alacritty` anyway, you can only set it in alacritty's `env` section, but that means that you still have the same issue you had before.

Just do a symlink which is present in the macOS's default `PATH` or use `import` and bring the shell settings from it.

**Comment by nixpulvis** [comment]
Duplicate of #6497, full discussion is here: #4157.
