### ISSUE TITLE
kitty keys: updated spec with regards to modifier-only presses

### ISSUE THREAD

**Issue by mitchellh** [alacritty/alacritty#7435]
Issue: https://github.com/kovidgoyal/kitty/issues/6913

I've attached a screenshot of the new spec behavior and this matches Kitty as of b2587c1. This screenshot is of my terminal but this matches Kitty, I just had this on my clipboard at the time of making this issue.

Key press events below:

1. Enter release (ignore)
2. Left control down
3. Right control down
4. Right control up
5. Left control up

![image](https://github.com/alacritty/alacritty/assets/1299/8b2652b5-3d4f-4dcc-ab44-685ad66c924a)

**Comment by mitchellh** [comment]
Screenshot of Alacritty as of 0fd04c37

![CleanShot 2023-12-13 at 22 15 10@2x](https://github.com/alacritty/alacritty/assets/1299/f7cc1faa-f7b3-426e-85f3-d94c3eb268a2)

**Comment by kchibisov** [comment]
Alacritty behaves as OS expects it to behave, the behavior you show on macOS is the same for us on Linux, since modifiers are delivered after the key resulted in change.

I don't like the way kitty changed the spec if I read it correctly. The modifiers are expected to be sent after keys and it's **impossible** to do otherwise cross platform without lingering events, since pressing `ctrl` doesn't actually mean that you've pressed control, unless you track modifiers yourself with the actual key presses which is obviously wrong, since it doesn't work with latched, sticky mods.

For example wayland spec mandates the modifier update after the key introduced the event, so alacritty behavior matches it, since we just forward the events.

**Comment by mitchellh** [comment]
You're entitled to do whatever you want, it's your terminal, but I feel like you should take this up with Kovid. 

One of the benefits of a protocol in my opinion is that it's meant to behave equally on all platforms, even the broken parts (i.e. sticky keys potentially). By not matching behavior, I feel you're just making it harder for terminal application developers to adopt these protocols with confidence. I'm unsure if its fair to claim Alacritty implements the Kitty keyboard protocol if it only implements the parts of the spec it agrees with...

On a separate point, I'm not sure exactly what you're claiming is impossible. I may be misunderstanding, but I've implemented the spec as currently written without an issue on macOS (I dropped a code sample in the Kitty issue with the event to listen to), X, and Wayland, so its definitely possible. You may be correct that its going against how the OS _wants_ things to happen or how certain windowing protocols specify their own events, but it is _possible_ to match the behavior of Kitty (like I said, even in cases it may be broken).

In any case, I understand some of your concerns, I have my own feelings about certain parts of the Kitty protocol. And like I said, I absolutely respect that it's your terminal, your choice, I'm just sharing my opinions. I also apologize for the noise because I wasn't aware of this stance for the project prior to opening the issue, I just saw news recently that Alacritty implemented the protocol and thought it may be of interest.

**Comment by kovidgoyal** [comment]
Yeah if you disagree with the spec now is the time to argue about it before the update is released. And note this is not a change in behavior in the spec, the previous behavior was unspecified it is now specified. If you prefer some other rule for the value of the modifier bits when reporting modifier key events, feel free to ask and provide some reasons to justify your choice. I dont have strong opinions on this, other than that the protocol *must* define the behavior and do so in a platform independent manner as terminal programs cannot know what platform their input events are coming from.

If you do wish to propose a different rule, feel free to comment on the issue in the kitty repo.

**Comment by kchibisov** [comment]
>One of the benefits of a protocol in my opinion is that it's meant to behave equally on all platforms, even the broken parts (i.e. sticky keys potentially). By not matching behavior, I feel you're just making it harder for terminal application developers to adopt these protocols with confidence. I'm unsure if its fair to claim Alacritty implements the Kitty keyboard protocol if it only implements the parts of the spec it agrees with...

Pushing changes to a widespread protocol without research in how it's done or even giving a grace period for developers implementing it to chime in is what just unprofessional. If the protocol is going to change that way, I'd rather revert its implementation.

>On a separate point, I'm not sure exactly what you're claiming is impossible. I may be misunderstanding, but I've implemented the spec as currently written without an issue on macOS (I dropped a code sample in the Kitty issue with the event to listen to), X, and Wayland, so its definitely possible.

Are you aware that Wayland mandates that modifier change is **after** the key event? The same as flags separate on macOS. The reason is to press `Shift + Shift`(double shift) which is now impossible withe the change. And no, checking left/right shift is not how it should be done, since shift keysym doesn't always mean a modifier change in shift. modifiers are a separate event on most OSes.

>I also apologize for the noise because I wasn't aware of this stance for the project prior to opening the issue, I just saw news recently that Alacritty implemented the protocol and thought it may be of interest.

This has little to do with alacritty itself, pushing breaking doc change to the protocol without even trying to ask other terminal devs whether it makes sense or how it's usually done is just straight unprofessional.

Kitty even lists apps supporting the protocol, clearly, it's not that hard to ping people and ask them.

**Comment by kovidgoyal** [comment]
On Wed, Dec 13, 2023 at 11:16:47PM -0800, Kirill Chibisov wrote:
> >One of the benefits of a protocol in my opinion is that it's meant to behave equally on all platforms, even the broken parts (i.e. sticky keys potentially). By not matching behavior, I feel you're just making it harder for terminal application developers to adopt these protocols with confidence. I'm unsure if its fair to claim Alacritty implements the Kitty keyboard protocol if it only implements the parts of the spec it agrees with...
> 
> Pushing changes to a widespread protocol without research in how it's done or even giving a grace period for developers implementing it to chime in is what just unprofessional. If the protocol is going to change that way, I'd rather revert its implementation.

Please do revert it, I would much rather not have to deal with the likes
of you.

**Comment by chrisduerr** [comment]
> Please do revert it

I never liked it to begin with, so I wouldn't mind this at all.
