### ISSUE TITLE
why alacritty can't dispaly ⚠️ as emoji

### ISSUE THREAD

**Issue by i18n-now** [alacritty/alacritty#7635]
## System

OS: macOS
Version: 0.13.0

I want display ⚠️ as 
<img width="547" alt="image" src="https://github.com/alacritty/alacritty/assets/145643935/6e3b0f5a-2abd-425f-ac66-1f1bc1cb5584">

but is display as this

<img width="469" alt="image" src="https://github.com/alacritty/alacritty/assets/145643935/2dd96dc5-7a83-41ed-866f-f198017cddf9">
<img width="561" alt="image" src="https://github.com/alacritty/alacritty/assets/145643935/1b483734-d028-419f-bb91-4bacb1027d96">

my config is 
```
live_config_reload = true
# tabspaces = 2
[colors.bright]
black = "0x808080"
blue = "0x0099ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xaa99cc"
red = "0xff0000"
white = "0xFFFFFF"
yellow = "0xfeff00"
[colors.cursor]
cursor = "0x99ff99"
text = "0xF81CE5"
[colors.normal]
black = "0x000000"
blue = "0x66ddff"
cyan = "0x006666"
green = "0x33ff00"
magenta = "0x9966aa"
red = "0xee0000"
white = "0xd0d0d0"
yellow = "0xfeff00"
[colors.primary]
background = "0x000000"
foreground = "0xffffff"
[env]
TERM = "xterm-256color"
[font]
size = 16
[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"
[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"
[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
[hints.enabled.mouse]
enabled = true
mods = "Control"
[hints.enabled.binding]
key = "U"
mods = "Control|Shift"
[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"
[selection]
save_to_clipboard = true
[window]
startup_mode = "Fullscreen"
```

**Comment by kchibisov** [comment]
It depends on the font you use, some may provide monochrome variant for this symbol. Mine font stack doesn't, so I have it rendered as emoji. I think nerd fonts do have it as emoji, since this glyph has monochrome and colored variants, and colored is full width and monochrome is half width.

In the current state of things you'd need to use a font that doesn't have this character in monochrome variant (I think all nerd fonts have it).

**Comment by i18n-now** [comment]
Is there a way to set it so that color fonts are displayed instead of monochrome fonts?

**Comment by AnhQuanTrl** [comment]
@i18n-now I got the same problem and honestly it seems like an uphill battle.
The reason why all the emoji show up properly in webpage is because the fonts we use in web page (Noto Sans for my case) has limited set of monochromes so the fallback emoji will show up most of the time.
In contrast, nerd fonts have monochrome for almost every emoji and so those get prioritised.
This is a problem for some cases, but for other cases it is perfectly fine. For example, in your vim editor screenshot, the monochrome look fine to me whereas warning emoji would look out of place.
So I guess we have to pick your poison :)

**Comment by AnhQuanTrl** [comment]
Hey @i18n-now so it turns out the issue is not because of NerdFont. In my local system (I use arch) the font that render the weird warning icon is actually Noto Sans Symbol 2 !!. I need to prioritized the emoji font over this symbol font for it to work. Here is my font config (at `~/.config/fontconfig/fonts.conf`) 
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <alias binding="strong">
    <family>monospace</family>
    <prefer>
      <family>FiraCode Nerd Font</family>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <match target="scan">
    <test name="family">
      <string>Noto Color Emoji</string>
    </test>
    <edit name="charset" mode="assign">
      <minus>
        <name>charset</name>
        <charset>
          <range>
            <int>0x0020</int>
            <int>0x2714</int>
          </range>
        </charset>
      </minus>
    </edit>
  </match>
</fontconfig>
```
The `minus` section is to remove the checkmark icon from my Noto Emoji font which I think is really ugly compared to the one from Symbol. 
`font-config` is a mess :)

**Comment by i18n-now** [comment]
> Hey @i18n-now so it turns out the issue is not because of NerdFont. In my local system (I use arch) the font that render the weird warning icon is actually Noto Sans Symbol 2 !!. I need to prioritized the emoji font over this symbol font for it to work. Here is my font config (at `~/.config/fontconfig/fonts.conf`)嘿，事实证明问题不是因为 NerdFont 造成的。在我的本地系统（我使用 arch）中，呈现奇怪警告图标的字体实际上是 Noto Sans Symbol 2 !!。我需要优先考虑表情符号字体而不是符号字体才能正常工作。这是我的字体配置（位于 `~/.config/fontconfig/fonts.conf` ）
> 
> ```
> <?xml version="1.0"?>
> <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
> <fontconfig>
>   <alias binding="strong">
>     <family>monospace</family>
>     <prefer>
>       <family>FiraCode Nerd Font</family>
>       <family>Noto Color Emoji</family>
>     </prefer>
>   </alias>
>   <match target="scan">
>     <test name="family">
>       <string>Noto Color Emoji</string>
>     </test>
>     <edit name="charset" mode="assign">
>       <minus>
>         <name>charset</name>
>         <charset>
>           <int>0x2714</int>
>         </charset>
>       </minus>
>     </edit>
>   </match>
> </fontconfig>
> ```
> 
> The `minus` section is to remove the checkmark icon from my Noto Emoji font which I think is really ugly compared to the one from Symbol. `minus` 部分是从我的 Noto Emoji 字体中删除复选标记图标，我认为与 Symbol 中的字体相比真的很难看。 `font-config` is a mess :) `font-config` 一团糟:)

i use macos , seems there is no ~/.config/fontconfig/fonts.conf

**Comment by AnhQuanTrl** [comment]
I don't know about MacOS, but I guess it should also have the same fallback system. A bit of Google Search guide me to this page: https://gitlab.com/zerustech/font-fallbacks-tutorial . Something to do with `Plist`.
Hopefully it can help you.

**Comment by janpfeifer** [comment]
Odd ... I still see this issue with alacritty 0.15.1 on X11 (my desktop). But in Wayland (my laptop), it seems to use the correct colored emojy.

What could be causing the difference ?
