### ISSUE TITLE
more idiomatic drag and drop file path

### ISSUE THREAD

**Issue by b01o** [alacritty/alacritty#7636]
### System

OS: WSL2 (Ubuntu), Windows 11
Version: alacritty 0.13.1 (fe2a3c5)

When we drag and drop a file onto alacritty, the path is using conventional windows path. 
![image](https://github.com/alacritty/alacritty/assets/16791440/d8354265-0e89-4676-87b8-e0fb76ebd0a3)

In windows, this seems ok. However when using alacritty with WSL, such path does not make sense.
![image](https://github.com/alacritty/alacritty/assets/16791440/0ac39f99-47ff-4929-9f5d-cb5c4e68dcc3)

Since files in host system(Windows) all have a unique path in the Linux subsystem, It would be great if the dropping file path can be converted automatically, eg.:
`C:\Users\expin\Documents\example.txt`  => `/mnt/c/Users/expin/Documents/example.txt`

Is there any way I can achieve this?

**Comment by kchibisov** [comment]
In general, we can't translate the path, since we don't know what target we're pasting to, however you can probably do that yourself in at least shell by hooking the bracketed paste logic (you can do that in zsh I think, like bracketed-paste-magic plugins, and run arbitrary logic on pastes). 

>C:\Users\expin\Documents\example.txt => /mnt/c/Users/expin/Documents/example.txt

This can't me done, since it's implementation detail of wsl, and other similar software could do different things, so no, translating like that is impossible to do correctly for all users out of the box.
