### ISSUE TITLE
Narrow windows push links to multiple lines, breaks link

### ISSUE THREAD

**Issue by wassupluke** [alacritty/alacritty#7640]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

Found a bug where viewing a manpage in a narrow Alacritty window sometimes prints links across multiple lines (hyphenated). When clicking the link, the site it takes you to ends at the hyphen. For example, when I open the manpage for libinput, the link to their latest documentation at the bottom splits to multiple lines and obviously gives me a 404 error when trying to open "https://wayland.freedesktop.org/libin-" (missing next line, "put/doc/latest"). Would expect Alacritty to recognize the link is split to multiple lines and concatenate them appropriately. Or maybe it's a manpage issue?

### System

OS: Arch Linux x86_64 6.7.0-arch3-1
Version: alacritty 0.13.1 (fe2a3c56)
Linux/BSD: Wayland with sway

**Comment by kchibisov** [comment]
We just render the content. `man` should either do natural wrap(just push text and terminal will wrap on its own, less can do that just fine) or it can use the hyperlink escape sequence to highlight the links. alacritty can't do anything about, because we're not aware of the layout of the program you're running to account for bars, splits, panes, etc, and the way it wraps things.

I'd suggest to probably try to push hyperlinks support to man if it's not done yet(it's supported in e.g. gcc/systemd/senpai/aerc (it has the same issue with very long links)).
