### ISSUE TITLE
Feature request: Blur Radius

### ISSUE THREAD

**Issue by Jihillestad** [alacritty/alacritty#7682]
I really enjoy that blur is implemented. It could even improve with adjustable Blur Radius,

**Comment by chrisduerr** [comment]
Blurring is handled by the compositor, we just tell it what can be blurred.

**Comment by kchibisov** [comment]
macOS has blur radius if it matters, but it's rather macOS special setting.

I'm not sure you have any of that on any other platform.

**Comment by chrisduerr** [comment]
> I'm not sure you have any of that on any other platform.

KDE's Wayland protocol certainly doesn't. And I don't think it makes sense to go with anything but the default anyway.

**Comment by kchibisov** [comment]
There's no real default on macOS, we just picked some value that looks close kind of ok iirc, but we're not using the OS mechanism for blur and even apple themselves don't use them for their Terminal.app, since they are more involved and require putting subview behind your transparent view, etc, etc.

In general, we could allow setting blur radius and translate (non-zero to true for kde/etc), but given that it's macOS specific, I'd rather not for now.

**Comment by chrisduerr** [comment]
> In general, we could allow setting blur radius and translate (non-zero to true for kde/etc), but given that it's macOS specific, I'd rather not for now.

Yeah I agree with that. No interest in a config option for this.
