### ISSUE TITLE
Clear (cmd-k) doesn't clear the screen when using tail -f?

### ISSUE THREAD

**Issue by rbosch** [alacritty/alacritty#7750]
When I do the same with ITerm2, this works without any issue.

When I break (`ctrl-c`) the tail and then do `cmd-k` is clears the screen.

I also tried this within `tmux`, same issue.

_It does show a `^L` character on screen, while in `tail -f`_

### System

OS: MacOS 12.7.2
Version: alacritty 0.13.1 (fe2a3c5)

**Comment by kchibisov** [comment]
It's up to receiving program to handle `^L`.

**Comment by nixpulvis** [comment]
I wonder how hard it would be to write a little script that just handled ctrl-k / ^L and otherwise was just the same as tail -f.

Or could the script be written to generically wrap any program?

**Comment by pioz** [comment]
I am experiencing the same issue. I switched from the OSX Terminal app, where pressing ctrl+L or cmd+K would always clear the screen, even with `tail -f` or any running process. However, in Alacritty, this only works if there is no active process; otherwise, `^L` is printed to the screen. This is quite annoying. Why does this work consistently in Terminal but not in Alacritty?

**Comment by trymoto** [comment]
@rbosch thanks i'm using it without `display` and behaviour is what i expect it to be.
