### ISSUE TITLE
tab support in README and dynamic tab names

### ISSUE THREAD

**Issue by jeffreysbrother** [alacritty/alacritty#7780]
The README in GitHub says "...you won't find things like tabs ..." when clearly, Alacritty has tabs (command + T produces a new tab). I believe this just means the README needs to be updated.

It's also unclear why the following addition to `.zshrc` creates dynamic tab names, based on the current working directory, in iTerm2, but not with Alacritty:

```
DISABLE_AUTO_TITLE="true"

precmd() {
  echo -ne "\e]1;${PWD##*/}\a"
}
```

This terminal emulator appears to be one of the best, but the quirk about dynamic tab names is kind of a bummer (visual grep saves a lot of time). Does anyone know if there's an alternate way to set the title of each tab based on CWD/PWD?

### System

OS: macOS
Version: `alacritty --version` this produces no output for some reason. but I see `0.13.1` in "About alacritty"

**Comment by chrisduerr** [comment]
> The README in GitHub says "...you won't find things like tabs ..." when clearly, Alacritty has tabs (command + T produces a new tab). I believe this just means the README needs to be updated.

It does not. Alacritty doesn't have tabs, your operating system does. Alacritty just integrates operating system functionality where available.

> It's also unclear why the following addition to .zshrc creates dynamic tab names, based on the current working directory, in iTerm2, but not with Alacritty:

Probably because your escape is wrong? Setting the title is done with OSC 2, OSC 1 sets the *icon name* and OSC 0 would set both. See https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands.
