### ISSUE TITLE
random visual bug 

### ISSUE THREAD

**Issue by nazdridoy** [alacritty/alacritty#7803]
After clearing the screen, when I execute ./spectrum.sh, everything works fine without any visual issues. However, after some repeated executions, this issue randomly appears.

>  ./spectrum.sh

```bash
#!/usr/bin/env bash

# Author: crshd
# Source: http://crunchbang.org/forums/viewtopic.php?pid=128584#p128584

echo
for f in {0..6}; do
	echo -en "\033[$((f+41))m\033[$((f+30))m██▓▒░"
done
echo -en "\033[37m██\n"
echo
for f in {0..6}; do
	echo -en "\033[$((f+41))m\033[1;$((f+90))m██▓▒░"
done
echo -en "\033[1;37m██"
echo -e "\033[0m"
echo

```

steps to reproduce and screenshots:

![2024-03-04_09-14](https://github.com/alacritty/alacritty/assets/45564804/46a78d0c-b134-4a60-9bfc-0fba33dad3ec)

if you need any more info, do let me know.

### System

OS: Linux (archlinux)
Version: alacritty 0.13.1 (fe2a3c56)
Linux: X11, KDE, kwin

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size:Width: 1920, Height: 1022

**Comment by chrisduerr** [comment]
Working as expected.

**Comment by nazdridoy** [comment]
>Working as expected.

@chrisduerr Kitty seems to render it just fine. Can you tell me how I can fix this for Alacritty?

**Comment by kchibisov** [comment]
>Kitty seems to render it just fine

I'd suggest to test xterm/vte I'm pretty sure they do the same as alacritty, which is expected, since you don't reset the cursor, thus line clear will fill with chars.

```sh
echo
for f in {0..6}; do
	echo -en "\033[$((f+41))m\033[$((f+30))m██▓▒░"
done
echo -en "\033[37m██"
echo -e "\033[0m\n"
echo
for f in {0..6}; do
	echo -en "\033[$((f+41))m\033[1;$((f+90))m██▓▒░"
done
echo -en "\033[1;37m██"
echo -e "\033[0m"
echo
```

**Comment by nazdridoy** [comment]
> fill with chars.

but this behavior is not consistent. After I clear the screen and execute the script, everything seems normal for some time, and then randomly starts filling the line with "██".

**Comment by nazdridoy** [comment]
oh.. thanks for the clarification....

**Comment by j4james** [comment]
@chrisduerr In case you're interested, there is actually a mode that Alacritty could support that would let applications control this behaviour: `DECECM` (Erase Color Mode). When set, all the operations that would usually erase or fill with the active background color (which includes scrolling), will instead use the default background color.

**Comment by chrisduerr** [comment]
> In case you're interested, there is actually a mode that Alacritty could support that would let applications control this behaviour: DECECM (Erase Color Mode). When set, all the operations that would usually erase or fill with the active background color (which includes scrolling), will instead use the default background color.

Are you aware of anyone actually making use of this mode? As far as I'm concerned reducing the number of usable escape sequences and operating based on a general and common understanding is superior to supporting every escape under the sun and having applications do whatever.

**Comment by j4james** [comment]
> Are you aware of anyone actually making use of this mode?

No. I use it myself for personal scripts, but I don't think it's something you'd want to rely on for a mainstream application, because there aren't enough terminals that support it.

> As far as I'm concerned reducing the number of usable escape sequences and operating based on a general and common understanding is superior to supporting every escape under the sun and having applications do whatever.

In general I'd say that's a reasonable argument, but in this particular case there isn't a common understanding. For an application writing arbitrary text with a background color that could potentially wrap and scroll, there's no easy way to avoid that full line fill as seen in the screen shots above.

Some terminals won't be effected because they don't support bce at all (i.e. the equivalent of `DECECM` permanently set). Some use a heuristic to disable bce only in certain situations, which just makes their behavior unpredictable. Letting apps choose whether they want bce or not (i.e. supporting `DECECM`) seemed to me to be the best long term solution.

But it's not that big a deal. I just thought I'd mention it in case you were interested.

**Comment by chrisduerr** [comment]
> For an application writing arbitrary text with a background color that could potentially wrap and scroll, there's no easy way to avoid that full line fill as seen in the screen shots above.

But there is? The script can be easily fixed to not have this problem by resetting the color before writing a newline.

**Comment by j4james** [comment]
Sorry if I wasn't clear. I didn't mean that the example script in this issue was a problem - it's the case where you have *wrapping* that forces a scroll. For example, something like this:

```
printf "%*s\e[41mABCDEFGHIJ\e[m\n" $(($COLUMNS - 5)) ""
```

The `SGR` attributes are reset before the newline, but that's not where the problem lies - it's the newline that's triggered when the text *wraps*. If you're at the bottom of the page when that occurs, you're going to get the entire following line filled with red.
