### ISSUE TITLE
tput init clears the terminal (behaviour differs from other terminals)

### ISSUE THREAD

**Issue by prurigro** [alacritty/alacritty#7850]
On at least xterm, kitty, konsole and vte-based terminals, `tput init` initializes tput without causing the content to scroll or change. In alacritty it causes all history to push past the top of the terminal and puts the next line at the top of the terminal.

Steps to reproduce:

```
printf '%s\n%s\n%s\n%s\n' one two three four
tput init
```

On the aforementioned terminals you see the four numbers and then a new line after running tput init, but in alacritty it looks like you've run `clear` except for the fact that you can scroll up.

My personal use case for the more typical behaviour is with my notes script here https://github.com/prurigro/vnotes but I'm sure this probably affects other scripts out there.

Thanks for your time and the great terminal!

### System

OS: Linux
Version: alacritty 0.13.1 (fe2a3c56) as well as git master
Linux/BSD: gnome+wayland on x86_64 and sway on aarch64

### Logs

Font/Terminal size: 9
Keyboard and bindings: keyboard input doesn't appear to be a factor as the same behaviour occurs when `tput init` is run in a script.

these are my only configured bindings:

```
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "q"
mode = "Vi"
```

EDIT: I just tested on a vanilla, unconfigured alacritty and get the same results

**Comment by chrisduerr** [comment]
Just tested with URxvt and it behaves the same as Alacritty, as such I see no reason to be suspicious of Alacritty's behavior.

If you think there's something specific that should be changed, feel free to look into the individual escape sequences and open another bug report about which one you think behaves incorrectly.

**Comment by prurigro** [comment]
You're right, urxvt sort of behaves like alacritty, weird- I assumed it would function like xterm so I didn't test that one. I wonder why alacritty and urxvt behave differently than everything else.

Interestingly, I can get the typical behaviour in alacritty when running in tmux.

Fair enough though, thanks for taking a look.

**Comment by chrisduerr** [comment]
> I wonder why alacritty and urxvt behave differently than everything else.

Alacritty's behavior is largely based on URxvt.

**Comment by prurigro** [comment]
Interesting, I didn't know that- I used to use and love urxvt back in the 2010s (before wayland), and it occurs to me that a lot of what I liked about it carries over to alacritty :)

Knowing that this is correct behaviour in at least two terminals, I'll just correct the issue in my notes script instead. Thanks again for your time!

**Comment by j4james** [comment]
@prurigro In case you're interested, the reason why `tput init` clears the screen is because it resets private mode 3, aka `DECCOLM` (132-column mode). And in addition to resetting the terminal width to 80 columns, that mode is *supposed* to clear the screen.

The reason it *doesn't* clear the screen on some terminals, is because a lot of them have `DECCOLM` "locked" by default. You can often unlock it by setting private mode 40, i.e. something like `printf "\e[?40h"`. And once you've done that, you should find `tput init` will clear the screen on XTerm as well.

Rxvt is a bit different, in that it supports `DECCOLM`, but resetting that mode doesn't actually clear the screen (possibly intentionally). So the only reason `tput init` still clears the screen in rxvt is because their terminfo assignment for `is2` includes an explicit "erase display" sequence.

Alacritty is also a bit different, in that it doesn't actually support `DECCOLM` (in the sense of changing the terminal width), but it does still trigger some of the `DECCOLM` side effects, like clearing the screen.
