### ISSUE TITLE
Unicode text in NFD is displayed incorrectly

### ISSUE THREAD

**Issue by oschwald** [alacritty/alacritty#7890]
Unicode text that is decomposed to NFD is displayed incorrectly. For instance, the string "República Popular da China" is displayed as:

![image](https://github.com/alacritty/alacritty/assets/278835/ae33533a-72cd-47ea-8688-cbffade41765)

This does not happen in `gnome-terminal` when using the same font. If I normalize the string to NFC, it is displayed correctly.

### System

OS: Linux
Version: `alacritty 0.13.2`
Linux/BSD: Wayland with sway

### Logs

Font/Terminal size: Ubuntu Mono, size 12

**Comment by chrisduerr** [comment]
Alacritty does not do normalization and there's no necessity to do so. So just use a font that works, there are plenty that do.

**Comment by oschwald** [comment]
I am confused. As mentioned, this displays correctly in `gnome-terminal` when using the same font, Ubuntu Mono.

**Comment by kchibisov** [comment]
Font doesn't matter in any of that, what matters is how it's stored in unicode. alacritty is not doing any normalization so it relies on font to position marks correctly.

gnome-terminal likely does normalization, so the text you see is not actually the text that is stored, because you see the text after normalization.
