### ISSUE TITLE
shell config doesn't allow for relative paths starting with ~/

### ISSUE THREAD

**Issue by ameknite** [alacritty/alacritty#8008]
When I try to do this in the `alacritty.toml`. it doesn't work.

```toml
[shell]
program = "~/.cargo/bin/nu"
```

It only works if I use the absolute path.
```toml
[shell]
program = "/Users/ameknite/.cargo/bin/nu"
```

I think this is a bug because `import` works well with ./

this works:
```toml
import = ["~/.config/alacritty/alacritty-main/catppuccin-latte.toml"]
```

### System

OS: macOS 14.5 (23F79)
Version: alacritty 0.13.2 (bb8ea18)

### Logs
 ```
"Failed to spawn command '~/.cargo/bin/nu': No such file or directory (os error 2)"
```

**Comment by ameknite** [comment]
:/

**Comment by nixpulvis** [comment]
I had originally thought alacritty changed its behavior to expand `~` as the user's home directory myself, because I know it originally didn't (see #6887 and #5673), but as it turns out it just strips a leading `~/` from the imports to treat them as loaded relative to the user's home directory:

https://github.com/alacritty/alacritty/blob/cacdb5bb3b72bad2c729227537979d95af75978f/alacritty/src/config/mod.rs#L306

@ameknite a better solution might be to append `~/.cargo/bin` to your `PATH`?

**Comment by chrisduerr** [comment]
> I had originally thought alacritty changed its behavior to expand ~ as the user's home directory myself, because I know it originally didn't (see #6887 and #5673), but as it turns out it just strips a leading ~/ from the imports to treat them as loaded relative to the user's home directory:

Stripping `~/` and prefixing it with the user's home directory is the same as expanding `~` as the user's home directory, is it not?

**Comment by nixpulvis** [comment]
@chrisduerr stripping the `~/` makes it a relative path, so it would depend on what it's relative to. I believe it should always be true in the case linked above, but in general no.

I only mentioned it since it's not like we're substituting `~` with the home directory everywhere in the config file. Though I do think it might be nice to treat all paths within the config the same way.

**Comment by chrisduerr** [comment]
> stripping the ~/ makes it a relative path, so it would depend on what it's relative to. I believe it should always be true in the case linked above, but in general no.

Look at the line after the code you've linked to.

> I only mentioned it since it's not like we're substituting ~ with the home directory everywhere in the config file. Though I do think it might be nice to treat all paths within the config the same way.

I disagree. It's also never gonna be enough. First it's the home directory, then it's other user's home directories, then it's environment variables. It's a string, not a shell argument, it shouldn't be expanded. Especially for the shell you should have it in `PATH` anyway, relying on `~/` is just a bad idea.

**Comment by nixpulvis** [comment]
I agree that it's a somewhat slippery slope. I'm just saying that it would be nice for all strings that are paths to be treated the same. Users see imports allow `~` and assume they can use it in other places like the shell's program too.

**Comment by ameknite** [comment]
> I disagree. It's also never gonna be enough. First it's the home directory, then it's other user's home directories, then it's environment variables. It's a string, not a shell argument, it shouldn't be expanded. Especially for the shell you should have it in PATH anyway, relying on ~/ is just a bad idea.


I don't understand why made the exceptions for imports then, It's not consistence . You should stick with one to avoid confuse the user, if not it's just bad ux design.

Also even when I have `nu` in my PATH. this doens't work:

```toml
[shell]
program = "nu"
```

this is literally the only setting in all my config files where I need to specify the absolute path

**Comment by ameknite** [comment]
> That's because you have your PATH configured incorrectly. As I have said this request is indicative of a user error, not an actual missing feature.

Yeah, blame the user instead of fixing your bad design.
 
What a shame that a great project has someone like you

**Comment by nixpulvis** [comment]
@ameknite the problem with the `PATH` is that you need to set it in the environment before Alacritty launches. IIRC, setting the `[env]` configuration happens too late. Since you're on macOS, I'm not actually sure the best way to add something to the `PATH` before Alacritty launches, but it stands to reason there's a way to do it from a .plist file somewhere or something.
