### ISSUE TITLE
Alacritty won't open 

### ISSUE THREAD

**Issue by PrathmeshVishwakarma** [alacritty/alacritty#8013]
So I installed version 0.13.2, and when running alacritty in terminal I get 
`neither WAYLAND_DISPLAY nor WAYLAND_SOCKET nor DISPLAY is set` . Please help me out.
Thanks

**Comment by nixpulvis** [comment]
What desktop environment are you using?

**Comment by PrathmeshVishwakarma** [comment]
> What desktop environment are you using?

none, I am setting up hyperland but for proceeding it won't open

**Comment by nixpulvis** [comment]
Maybe try setting `WAYLAND_DISPLAY=wayland-0`?

**Comment by nixpulvis** [comment]
Also, can you confirm that these variables are in fact not set? If I understand correctly, hyperland should set them when it starts.

**Comment by PrathmeshVishwakarma** [comment]
Yes they were not set, in my .bashrc :(, I did put `export DISPLAY=:1` but leads to dead end, same error

**Comment by chrisduerr** [comment]
First of all ensure Hyperland is actually started first. Your previous comments didn't make it clear that you started hyperland.

Then you should start Alacritty through whatever mechanism hyperland has to launch applications, since Hyperland is responsible for exporting its Wayland socket. If you want to start it from a different tty or display server, you can probably make it work with `WAYLAND_DISPLAY=wayland-1 alacritty`, but that shouldn't be the default.

**Comment by PrathmeshVishwakarma** [comment]
> Then you should start Alacritty through whatever mechanism hyperland has to launch applications, since Hyperland is responsible for exporting its Wayland socket. If you want to start it from a different tty or display server, you can probably make it work with `WAYLAND_DISPLAY=wayland-1 alacritty`, but that shouldn't be the default.

Oh, so I cannot Alacritty directly from tty? I see.
But Super+Q won't open anything, so I was starting it directly from tty
