### ISSUE TITLE
Vim not using ttymouse=sgr automatically

### ISSUE THREAD

**Issue by louwers** [alacritty/alacritty#803]
While clicking and holding the mouse, the mouse position is not updated. This behavior is not consistent with how other terminal emulators work.

To demonstrate the issue, I created a screen recording of selecting in vim, GNOME terminal (bottom), Alacritty (top).

![Screen recording](https://user-images.githubusercontent.com/649392/30976872-3d16cbc8-a476-11e7-8743-13740f847808.gif)

**Comment by benoit-pierre** [comment]
I think you should change the title to include vim: the problem is with mouse reporting and vim, and I can reproduce it, but mouse support in other applications like tmux or emacs seem to work fine.

**Comment by benoit-pierre** [comment]
Although, when enabling mouse support in emacs (`M-x xterm-mouse-mode`), I get a warning when ending the selection: `<drag-mouse-4> is undefined`, and word-wise selection with double-clicking does not work right either.

**Comment by jwilm** [comment]
Seems like this an issue with vim. If I manually set `ttymouse=sgr` or `ttymouse=xterm2` the dragging works as expected.

Could you share the output of `set ttymouse` from vim in each terminal?

**Comment by louwers** [comment]
`sgr` for GNOME terminal
`xterm` for Alacritty

Should I close this and report it over at vim?
Or is there something that prevents vim from detecting the right ttymouse setting?

**Comment by jwilm** [comment]
@louwers it might be worth asking about on the vim issue tracker since someone there is likely to know how `ttymouse` is configured at startup. I don't personally know what would cause this. We should keep this issue open in the meantime.

Before you do that actually, what is the value for the `TERM` environment variable in each case?

**Comment by louwers** [comment]
In both cases  it's `xterm-256color`.

**Comment by Screwtapello** [comment]
For the record, Vim does a bunch of things to try and guess what mouse-protocol the current terminal supports, since it long predates the wide support of the SGR protocol. See the last few paragraphs of [the ttymouse docs](http://vimdoc.sourceforge.net/htmldoc/options.html#'ttymouse') for details. I wouldn't worry too much about supporting those hacks in Alacritty.

**Comment by chrisduerr** [comment]
This is a vim, not an Alacritty issue. Neovim for example works just fine.
