### ISSUE TITLE
neovim's icon's are breaking and cursor is flickering inside tmux

### ISSUE THREAD

**Issue by deekshith991** [alacritty/alacritty#8084]
when using neovim it works fine but when neovim is started in tmux the icons are breaking
![Screenshot from 2024-07-11 14-37-46](https://github.com/alacritty/alacritty/assets/109906616/7dcde491-4763-4c2f-8c21-ab382bc1b9dd)
![Screenshot from 2024-07-11 14-40-28](https://github.com/alacritty/alacritty/assets/109906616/97eb9955-7a63-4edc-9d79-53760d8590fa)

### System

OS: Ubuntu 24.04
Version: alacritty 0.13.2
Linux/BSD: Wayland

**Comment by chrisduerr** [comment]
If it works outside of tmux, it's probably not an Alacritty issue.

**Comment by kchibisov** [comment]
Could be messed up locale, so tmux thinks that it's not supporting utf8, so it just straight ignores them, since it sits between alacritty and neovim and has its own terminal grid.

You can easily check that by killing the old tmux and running new one with `tmux -u`, if that works fix your locale issue.
