### ISSUE TITLE
Question about Ctrl+Shift+ left/right arrow combination

### ISSUE THREAD

**Issue by Aleksander-Dorkov** [alacritty/alacritty#8227]
### System
OS: Linux/macOS
alacritty 0.13.2 (bb8ea18)

Is it possible in to change the behaviour of the combination of `Ctrl+Shift+left arrow` and `Ctrl+Shift+right arrow` to behave the same as it would in Visual Studio Code/IntelliJ IDEA (Jetbrains products) under windows/linux by editing my `alacritty.toml` file?

On my own I only managed to change the behaviour of Ctrl + left/right arrow.

```
[keyboard]
bindings = [
  { key = "Left", mods = "Control", chars = "\u001b[1;5D" },
  { key = "Right", mods = "Control", chars = "\u001b[1;5C" }
]
```

**Comment by kchibisov** [comment]
How these keys behave is entirely up to application you run inside alacritty, so for shell (e.g. bash) read its documentation to what you want. Alacritty just encodes characters the way it's defined by various standards and sends to application, the actual movement is done by the application.

**Comment by kchibisov** [comment]
Terminals can inject a bit of `shell` for them to source when loading, it's usually called a _shell integration_, but it's just terminals adding a bit more stuff for them to source.

Also, macOS has those bindings for left/right arrow, it's just not what you've defined in your config, since you've defined the way it's defined in alacritty/specs, but macOS wants something else.

Just run `cat` in terminal.app and press those keys, you'll see something else appear. I honestly don't remember what macOS uses by default for them, it's just something non-standard.

**Comment by Aleksander-Dorkov** [comment]
this is the output, if it is of any help, the first one is for ctrl+shift+left, the second one is for ctrl+shift+right

```
➜  ~ cat
^[[1;6D

^[[1;6C
```

**Comment by kchibisov** [comment]
Inside the `Terminal.app`? The output is correct for traditional encoding and what we send as well, so bind this to whatever action you want in your zsh.

Like

```
bindkey '^[[1;6C' forward-word
bindkey '^[[1;6D' backward-word
```
