### ISSUE TITLE
How to open Alacritty using OpenConsole.exe?

### ISSUE THREAD

**Issue by moyeh04** [alacritty/alacritty#8236]
related to issue (https://github.com/alacritty/alacritty/issues/8235)
As the title says, I can't find any guide on opening Alacritty using OpenConsole.exe, since I'm having rendering issues using conpty, or windows console host (conhost).
When trying to open OpenConsole.exe I get the following error
OpenConsole.exe: The term 'OpenConsole.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.

**Comment by moyeh04** [comment]
Update
```bash
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.20.11781.0_x64__8wekyb3d8bbwe> .\OpenConsole.exe alacritty
```
Opening alacritty using OpenConsole.exe doesn't fix the rendering issue

**Comment by chrisduerr** [comment]
I have never tried it myself, because I don't use Windows, but this comment seems to outline how it should work in general:

https://github.com/alacritty/alacritty/issues/1703#issuecomment-1788819655

Note that you should be able to just take these files from Windows Terminal too, same as what you did before with just slightly different execution.

Also no need to open new issues, we see comments on closed issues just like open ones.

**Comment by moyeh04** [comment]
Okay That works, Thanks.
I only had to do the first 2 steps
1. Get the latest Alacritty version

2. Copy the both "conpty.dll" and "OpenConsole.exe" from https://github.com/wez/wezterm/tree/main/assets/windows/conhost to Alacritty binaries dir, which are located at 
```bash
C:\Program Files\Alacritty
```
