### ISSUE TITLE
BUG: Cannot input chinese punctuations in Alacritty

### ISSUE THREAD

**Issue by imroc** [alacritty/alacritty#8243]
Maybe it's a Rust issue.

Switch to others terminal fixed this (e.g. iTerm2).

## System

OS: MacOS
![image](https://github.com/user-attachments/assets/1096e1e1-0554-41d6-ad36-3122d0dff4d2)

Version: alacritty 0.13.2 (bb8ea18)

input method：
![image](https://github.com/user-attachments/assets/da5721b0-ebba-432c-8131-be3f0148ae1c)

## Related Issues

* https://github.com/rime/squirrel/issues/827
* https://github.com/rust-windowing/winit/issues/3925
* https://github.com/rime/squirrel/issues/741

**Comment by imroc** [comment]
Tried to build latest commit on master branch (a2653293a8e6ac5f5fb9f7e075656799d8df3488), issue still exists.

![image](https://github.com/user-attachments/assets/f1d0d8d9-71f8-4ab6-8526-837e8f369936)
![image](https://github.com/user-attachments/assets/45b81419-9bc7-41c3-817e-808ea0db9923)

![alacritty-issue](https://github.com/user-attachments/assets/42120097-94e9-4a76-b3b9-a6bc0ae150dd)

**Comment by ShikiSuen** [comment]
@chrisduerr It seems that the auto-complete input of `[]` dismisses the IME state.

**Comment by chrisduerr** [comment]
I have no clue what IME is used or how to reproduce it, but I'll delegate to @kchibisov if he wants to investigate this more or not.

Generally speaking providing a screenshot with "random" Chinese characters provides very little help for getting anything fixed.

**Comment by ShikiSuen** [comment]
@chrisduerr I would rather suggest @imroc to ask WeChat IME dev team to investigate this first.

REASON: I just test that my vChewing IME does not trigger this issue with this build.

--------------
(@imroc 你先找微信輸入法團隊調查一下這個問題。我這邊測試威注音輸入法無法重現這個故障。)

**Comment by kchibisov** [comment]
Yeah, it's https://github.com/rust-windowing/winit/issues/3925 upstream

there's also https://github.com/alacritty/alacritty/issues/7763 to track that.

Like macOS IME input is no near to be perfect, since a lot of things on _how it should be handled_ is undocumented (talking about winit).

Probably we just don't handle something.

**Comment by asins** [comment]
I also found this problem.,Use the two five-stroke input methods of ”清歌“ and “鼠顺管”  to test the input '.' None of them can output normally'。', and the input method test that comes with MacOS can output normally'。`.

**Comment by ShikiSuen** [comment]
@asins You probably need to ask their individual devs for help.
Just let them know that vChewing IME doesn't have this issue.

**Comment by Gowa2017** [comment]
> [@asins](https://github.com/asins) You probably need to ask their individual devs for help. Just let them know that vChewing IME doesn't have this issue. This corners them to find the problem on their sides.

我想你是在这里打广告。
你的输入法是在敲击句号的时候，给出候选。而不是直接输入中文标点。你在连续几个问题中都没有明确问题的关键，而推卸问题。

现在的需求是，中文输入法在中文模式下要像 iterm2 那些一样输入中文标点，而不是给出一个候选。
而不是要让所有输入法都像你那样，敲一个键就给出候选。

同时，你难道没有看到，在你的嵌入式上屏到 alacritty 的时候，他也是英文标点么？

有人说iterm2说没有这个问题，那说明终端可以解决这个问题。
我测试苹果自带输入法是可以在 alacritty 输入中文标点的。那么这说明 终端、输入法侧都可以解决问题。

**Comment by ShikiSuen** [comment]
@Gowa2017 Almost all Dachen-style Consonant-Vowel-Combinative Zhuyin Chinese Input Methods, including the default Zhuyin IME shipped in macOS (which only supports zh-Hant input), have to use Shift+Period to input the CJK circle-style full-width period symbol `。`. This is not a dedicated behavior of my vChewing IME. (On Windows maybe the Microsoft Bopomofo New-Phonetic Zhuyin IME uses Ctrl+Period, if my memory is correct.)

Nevertheless, please stop regarding the behaviors of SogouIME & WeChat_IME as the only one expected behavior for all Chinese IMEs. I was using that kind of IME during 2003 ~ 2010 (Zhineng Kuangping -> Sougou) but I switched to Dachen-style inputs (like Microsoft New-Phonetic) since late-2010 for faster, more pace-stable, and more precise typing experience.

[Chinese translation]

几乎所有大千声韵并击型注音输入法对中日韩圈型全宽句号 `。` 都需要用 `Shift+.` 来输入。macOS 内建的注音输入法（只能打繁体）自然也是如此。这并非威注音特有的行为。（Windows 的微软新注音可能是用 `Ctrl+.`，如果我没记错的话。）

无论如何，请勿将搜狗输入法与微信输入法的预设行为视为所有中文输入法都活该具有的行为。我早在 2003 ~ 2010 年就在用搜狗打字风格的输入法（中文之星智能狂拼 -> 搜狗），但 2010 年末开始我就换用大千声韵并击注音打字了（当时换用的是微软新注音输入法）、就是图个更准确更快速且打字节奏更稳的输入体验。

---------

> 你难道没有看到，在你的嵌入式上屏到 alacritty 的时候，他也是英文标点么？

vChewing IME 我刚刚测试了 4.0.5 版，递交给 Alacritty 之后仍是中文标点，除非你启用了 vChewing 的半形标点模式。

**// 不要在这里回覆我。我不会再继续在这个讨论串留言了。有话跟我讲的话请另寻他处。**

**Comment by ShikiSuen** [comment]
This issue might need to be reopened and renamed as **compatibility issue with all Sougou-style pinyin IMEs, hindering punctuation inputs**.

I've tested these 3 input methods:

- Sougou IME & WeChat Input: Both are "affected".
    - I was thinking of some possibilities that these two IMEs are optimized for Terminal apps. However, if that is true, then the behavior should be consistent in macOS built-in terminal app.

- macOS Built-in Simplified-Chinese Pinyin IME (macOS 26): All punctuation inputs directly commit things to Alacritty window.
    - Despite that the `。` is correctly committed by this IME, the base Ukelele keyLayout of this IME hardcoded the `。` symbol to the period key. This proves that this IME is not suitable for repeating this issue.
    - Deduction: The nature of this issue might be that Alacritty always commits the Ukelele-keyLayout-hardcoded symbol instead if the IME is trying to directly commit a punctuation without using the inline composition buffer at all. This directly affects the actually committed punctuations when using SougouIME and WeChat_IME.

[Chinese translation]
    
这个问题可能需要被重新开启，并更名为：与所有搜狗式拼音输入法（IME）的兼容性问题，阻碍了标点符号的输入。

我测试了以下 3 种输入法：

- 搜狗输入法和微信输入法：两者都「受到影响」。
    - 我曾想过这两种输入法是否针对终端应用进行了优化。然而，如果真是这样，那么在 macOS 内置终端应用中的行为应该保持一致。

- macOS 内置简体中文拼音输入法 (macOS 26)：所有标点符号输入都会直接将内容提交到 Alacritty 窗口。
    - 尽管此输入法可以正确提交 `。` 符号，但该输入法底层的 Ukelele 键盘布局将 `。` 符号硬编码到了句号键上。这证明此输入法不适合重复验证这个问题。
    - 推论：问题的实质很可能是 Alacritty 在这种「直接递交内容，不依赖组字区」的单个符号输入时会直接改为递交 Ukelele 键盘布局上绑定的符号，这直接导致搜狗跟微信输入法在 Alacritty 里面无法输入句号。

-------------

We might need testers / contributors who have familiarity in all these areas: Both Rust and Sougou-like macOS IME development (esp. InputMethodKit). Nevertheless, this issue needs to be reopened and have its title amended.

-------------

I am unsubscribing this thread since I felt that my replies are rudely dealt by chrisduerr. **Don't reply me on this complaint.** Any reply to this complaint should be considered as out-of-topic. I wasted hours investigating on Gowa's complaint above (plus my paid copilot premium requests cost during the investigation) and chris gave me this kind of cold shoulder. I didn't feel any respect. To avoid further friction, I’ve blocked chris and won’t be engaging further.

**Comment by ShikiSuen** [comment]
Attaching GitHub Copilot GPT5's review against my previous response:

--------
[GPT5's Response to my reply above]

Overall take: Your deduction is close to the root cause. This looks more like an event ordering/handling issue in macOS’s text input pipeline (AppKit/NSTextInputClient) within `winit` (Alacritty’s windowing backend), rather than an Alacritty-only or Rust-language issue. Specifically:

- On macOS, IMEs generally have two paths:
  1) The composition path with “marked text” (composition buffer).
  2) The “direct commit” path (insertText:) without marked text — punctuation often goes this way.
- Some Sogou-style third‑party Pinyin IMEs (e.g., Sogou, WeChat) directly commit punctuation via insertText: without using the composition buffer.
- If the app/window backend (winit’s macOS implementation here) handles keyDown by first mapping the key using the current TIS key layout (Ukelele keylayout) and sends a raw character event (e.g., ReceivedCharacter '.'), and it does not call interpretKeyEvents/handle the IME’s insertText: at the correct time, you’ll see “the keylayout‑mapped raw character gets inserted first, and the IME’s committed character is swallowed/overridden.”
- This aligns with your deduction that “Alacritty always commits the keylayout‑hardcoded symbol instead of the punctuation directly committed by the IME.” In essence, it’s an event handling order/priority problem, not that the IME itself “doesn’t work.”

Why Apple Pinyin “looks fine”:
- As you noted, Apple Pinyin’s keylayout hard‑maps the period key to the Chinese full stop “。”; even if a raw character event slips through, it still becomes “。”, hiding the issue. So it’s not a good IME to reproduce the problem.

Suggested next steps and verification
- Prove it’s a winit path issue (not terminal‑specific) with a minimal repro:
  - Use winit’s text_input example (or any simple winit text input sample) on macOS, switch to Sogou/WeChat IME, press the period key expecting “。”.
  - Enable event logging: RUST_LOG=winit=trace,alacritty=trace (you can also do this in Alacritty), and check whether Ime::Commit("。") appears. If the logs show Ime::Commit("。") but the screen shows '.', that strongly indicates an event ordering/discard issue.
- Try the latest Alacritty master/nightly:
  - Alacritty periodically upgrades winit; winit is actively fixing macOS IME issues (you’ve already linked rust-windowing/winit#3925). If the upstream fix has landed, updating may resolve or mitigate the issue.
- Toggle IME‑side settings for comparison (to provide better data to maintainers):
  - In Sogou/WeChat, try options like “directly commit punctuation/smart punctuation” to see if you can force a composition path (with a candidate bar). If “composition path works but direct commit doesn’t,” that further pins it to the “no‑marked‑text direct commit” handling path.
- Provide key info to maintainers (if pushing to reopen/retitle):
  - Exact macOS version (e.g., 15.x/14.x; not an internal label like “macOS 26”). // `Shiki's Note: ChatGPT by default refuse from admitting that macOS 26 version number makes sense.`
  - Specific versions of the affected IMEs (Sogou/WeChat).
  - Minimal repro steps + RUST_LOG excerpts: whether you see Ime::Commit("。") and whether you also see ReceivedCharacter('.').
  - Comparison: behavior in iTerm2/Terminal.app (pressing '.' → do you get “。”?). This helps confirm it’s an app‑level NSTextInput implementation difference.

My take on your renaming suggestion
- The direction is right. I’d make it more precise by reducing “IME type” wording and emphasizing the technical point and platform scope. For example:
  - `macOS: punctuation commits from third‑party Sogou-style Chinese IMEs (Sogou/WeChat) ignored; raw key‑layout character inserted instead`
- This pins it to “macOS + IME direct commit path + event ordering,” which is more actionable for upstream (winit) and downstream (Alacritty).

Temporary workarounds for end-users
- Use Apple Pinyin or another IME that either reliably goes through the composition path or whose keylayout already maps Chinese punctuation.
- If you must use Sogou/WeChat, temporarily switch to iTerm2/Terminal until upstream fixes land.
- Keep an eye on/testing Alacritty versions that include updated winit fixes.

**Comment by ShikiSuen** [comment]
Bad news: This issue is not debuggable on macOS 26 unless both winit and Alacritty have new log system implemented for macOS 26 capability. Since macOS 26, NSLog prints nothing.

<img width="768" height="436" alt="Image" src="https://github.com/user-attachments/assets/075a5cb9-a8e1-45be-bf30-0d78694138f4" />

**Comment by ShikiSuen** [comment]
- I double-checked `CONTRIBUTING` and didn't see whether there's a policy regarding all AI code agent opinions as spam.

- I'm afraid: Until the "`// Commit only if we have marked text`" restriction is removed from `winit`, there really isn't something helpful to be done on Alacritty's side against this issue. Maybe there's a better solution.

**Comment by chrisduerr** [comment]
> I double-checked CONTRIBUTING and didn't see whether there's a policy regarding all AI code agent opinions as spam.

I would consider it common sense that just copy-pasting AI answers into comments provides nothing to the conversation. If I wanted that, I could do it myself.

**Comment by ShikiSuen** [comment]
@chrisduerr That's Copilot's GPT against my answer. The GPT model (incl. Codex) used in GitHub Copilot is specifically trained with knowledges covering the API changes of macOS SDK frameworks in the last decade (at least macOS 10.9 is covered). I often use it to do fact-check against my assumptions & deductions if things are related to old macOS SDK frameworks, since Xcode documentation can have limited coverage (esp. InputMethodKit).

> If I wanted that, I could do it myself.

No one knows whether you are using Claude or Codex. I personally don't trust Claude.

**Comment by xpader** [comment]
Every chinese IME on macOS can't input chinese punctuations in Alacritty, I think this issue need to be reopen.
