### ISSUE TITLE
how to make Alacritty accept function command on Mac OS

### ISSUE THREAD

**Issue by abbood** [alacritty/alacritty#8258]
I was going over the new [arrange window shortcuts](https://support.apple.com/en-al/guide/mac-help/mchl9674d0b0/15.0/mac/15.0) for Mac Sequoia and I liked this one:

	
	
<kbd>Fn</kbd><kbd>Control</kbd><kbd>Option</kbd><kbd>Shift</kbd><kbd>Left</kbd>:

> Move the active window to the left half of the desktop, move the second window to the top-right corner of the desktop, and move the third window to the bottom-right corner of the desktop.

the problem is that I use Alacritty as my terminal, and Alacritty doesn't play nice with the function key, when I do the above (or any other key that requires the function key) I get this on my terminal

```
8H;8F;8H;8H;8~;8F;8~;8~;8F;8F;8F;8H;8H;8H;8H;8H;8F;8F;8~;8~;8~
```

What can I do to make this shortcut work on Alacritty?

**Comment by abbood** [comment]
@chrisduerr nothing to fix here.. I'm just wondering how the function button can be recognized by the OS while in alacritty app. Are you saying that this isn't currently supported and won't be supported for the time being?

**Comment by chrisduerr** [comment]
> Are you saying that this isn't currently supported and won't be supported for the time being?

I don't know if it's supported and I have no interest in fixing weird macos binding bugs.

**Comment by nixpulvis** [comment]
I can't help a lot since I'm not running that version of macOS, but I suspect you could create a binding in your `alacritty.toml` which has an `action = "None"` for that key combination. I'm not sure if it's actually possible, since I don't know how the Fn key effects the actual keycodes that are sent, so you might need to play around with that. Perhaps a tool like Karabiner-Elements could help... but I've never played with it myself.

I just want to take a moment to reflect on the fact that macOS is really shipping default keybindings with four modifiers. Wild.

**Comment by saifulapm** [comment]
> I can't help a lot since I'm not running that version of macOS, but I suspect you could create a binding in your `alacritty.toml` which has an `action = "None"` for that key combination. I'm not sure if it's actually possible, since I don't know how the Fn key effects the actual keycodes that are sent, so you might need to play around with that. Perhaps a tool like Karabiner-Elements could help... but I've never played with it myself.
> 
> I just want to take a moment to reflect on the fact that macOS is really shipping default keybindings with four modifiers. Wild.

Not working.

Any solution for this ?
