### ISSUE TITLE
Support cursor colors

### ISSUE THREAD

**Issue by mathstuf** [alacritty/alacritty#826]
Which operating system does the issue occur on?

Linux/X11 using 6916537858d12e02478d618339d1b9f0e73a677a.

There doesn't seem to be support for changing the cursor color. This is done by echoing an escape sequence like:

```
_zle_ins="\033P\033]12;$_zle_ins_color\007\033\\"
```

**Comment by jwilm** [comment]
Haven't gotten around to implementing this OSC yet. Need to figure out a cross-platform solution for parsing color names.

**Comment by mathstuf** [comment]
OK, thanks. I imagine this is also behind `rxvt-unicode` having a stable cursor color when navigating in Vim and the like while `alacritty` colors it in the reverse of the text and background color.

**Comment by jwilm** [comment]
@mathstuf You can change the cursor color behavior in alacritty.yml; simply set `custom_cursor_colors: true`.

**Comment by mathstuf** [comment]
That fixes the stable cursor color at least, thanks.

**Comment by siiptuo** [comment]
This sequence is implemented in #757.

**Comment by jwilm** [comment]
@siiptuo thanks for the reminder. I would really like to get PR count back down to zero and keep on top of them...

**Comment by sodiumjoe** [comment]
Would this explain why in zsh vi-mode's normal mode, the cursor background doesn't show up at all? This makes it really difficult and sometimes impossible to tell where the cursor is.

For example, in this screenshot, the cursor is on the `a` in `baz`

![2017-10-16 at 8 03 pm](https://user-images.githubusercontent.com/845857/31644798-0e9b8032-b2ad-11e7-9774-8657b6421acb.png)

**Comment by alexanderjeurissen** [comment]
The issue that @sodiumjoe mentioned is also something i'm struggling with, I love the auto invert color cursor but in zsh vi-mode's normal mode the cursor background doesn't show up and in some terminal color schemes that can make the cursor almost invisible.

**Comment by sodiumjoe** [comment]
@alexanderjeurissen in my case, turning off the `cursor` highlighter fixed it

**Comment by alexanderjeurissen** [comment]
@sodiumjoe with cursor highlighter you mean the `custom_cursor_colors` ? as in:

```
# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: false
```

I'd like to keep that behaviour (meaning inverting of colours of the cursor) everywhere it seems to work just fine but in zsh vi-mode's normal mode it glitches out.

**Comment by amosbird** [comment]
hmm, how can I make it support 

```
\e[2 q
\e]12;DarkGoldenrod\007
```

**Comment by siiptuo** [comment]
@amosbird Currently only `#rrggbb` and `rgb:rr/gg/bb` syntaxes are supported. For better compability with other terminal emulators features of [XParseColor](https://linux.die.net/man/3/xparsecolor) could be replicated in [parse_rgb_color](https://github.com/jwilm/alacritty/blob/master/src/ansi.rs#L29). This includes support for [X11 color names](https://en.wikipedia.org/wiki/X11_color_names) listed [here](https://cgit.freedesktop.org/xorg/app/rgb/tree/rgb.txt).

**Comment by s-taylor** [comment]
> I'd like to keep that behaviour (meaning inverting of colours of the cursor) everywhere it seems to work just fine but in zsh vi-mode's normal mode it glitches out.

I have the same issue, cannot see the cursor when in vi-mode in zsh. i.e. when I start typing a command then either press `esc` or `ctrl+[` I can't then see the cursor.

**Comment by rawaludin** [comment]
Having this problem too. I can't see the cursor when I activate vi mode in zsh. For now, I just press `^x^e` to edit my long command in vim.

**Comment by softmoth** [comment]
It is working with my updated [zsh-vim-mode][]. In your .zshrc, put something like:
```zsh
unset RPS1 # If you want it to automatically add an indicator for you
source path/to/zsh-vim-mode.plugin.zsh # Or use your favorite plugin manager
ZSH_VIM_MODE_CURSOR_VICMD='#00ff00 bar'
ZSH_VIM_MODE_CURSOR_ISEARCH='#ff00ff underline'
```

At least on Linux X11 this is working fine. The 'blinking' attribute doesn't have any effect, and you have to use #RRGGBB format for specifying colors, but otherwise it's good.

[zsh-vim-mode]: https://github.com/softmoth/zsh-vim-mode

**Comment by jonhoo** [comment]
I have also observed that Alacritty sometimes reverts to reversing the cursor color even though a custom cursor color has been set (see https://github.com/neovim/neovim/issues/9962). This only happens after I've been using the terminal for a while though, so I'm not entirely sure what triggers the behavior. Has anyone else seen that happen?

**Comment by kchibisov** [comment]
The original escape sequence `echo -e "\033P\033]12;#ffffff\007\033\\"` works in the current alacritty.

**Comment by alexanderjeurissen** [comment]
Why was this issue closed ?

The issue  @sodiumjoe  raised with the inverse cursor not showing up in zsh Vi normal mode  is still present in the latest commit on master.

The echo statement that was posted by @kchibisov only works when the `inverse cursor color` option in alacrity is disabled, otherwise Alacritty's inverse cursor will take priority over any zsh or line-mode configured cursor color.

some options that I just tried to test this:

1. Setting the echo statement as specified by @sodiumjoe, with inverse cursor color disabled => Works, zsh configured color overwrites alacritty config specified cursor color.
2. Setting the echo statement as specified, with inverse color enabled => does not work
3. Registering a ZLE option to change the cursor based on keymap, with inverse color enabled => does not work.
