### ISSUE TITLE
ACS character alignment issue (has gaps between chars)

### ISSUE THREAD

**Issue by mathstuf** [alacritty/alacritty#827]
Which operating system does the issue occur on?

Linux/X11 using 6916537858d12e02478d618339d1b9f0e73a677a.

tmux draws split windows using ACS line-drawing characters. I'm seeing them not aligned properly (there are small gaps between adjacent lines. FWIW, it works in rxvt-unicode-256color.

Font: `xft:xos4 Terminus:size=7`
Screenshot (ignore the white rectangle; not sure what's up there):

![2017-10-09-132708_189x85_scrot](https://user-images.githubusercontent.com/97253/31350589-bf160b8e-acf5-11e7-9129-b3b8a1b92414.png)

**Comment by jwilm** [comment]
urxvt must have a different way of figuring out size for the line drawing face. In Alacritty's case, it will use whatever you specify for size. Since your main face is a bitmap font, the size you specify is being coerced by fontconfig to the nearest available. Thus, increasing the `size` in alacritty.yml by increments of 0.5 should change the line drawing font size appropriately while leaving Terminus untouched (until you hit some threshold). Not ideal, but maybe it will work.

I wonder if the underlying issue is that we're using the DPI from xrandr rather than Xft.dpi...

**Comment by mathstuf** [comment]
I don't have `Xft.dpi` set at all on my machine (everything goes through `xrandr`). I'll try out the size bumping thing.

**Comment by mathstuf** [comment]
7.5 fixes horizontal lines, but leaves a gap for vertical bars. 8.0 has a weird double-intensity at the bar overlaps.

![2017-10-09-133952_161x82_scrot](https://user-images.githubusercontent.com/97253/31351016-73563e42-acf7-11e7-8509-fa908270d5c1.png)

Looking closer, horizontal also has some double-drawing, but it is much less noticeable.

**Comment by jwilm** [comment]
@mathstuf the double-intensity is due to antialiasing. You could try disabling it for alacritty in fontconfig, but that might have other unintended consequences.

Relevant fontconfig:

```xml
	<match target="font">
		<test name="prgname">
			<string>alacritty</string>
		</test>
		<edit name="antialias" mode="assign">
			<bool>False</bool>
		</edit>
	</match>
```

**Comment by mathstuf** [comment]
I'll have to try that later. I took a peek at `rxvt-unicode` and didn't see any special handling for ACS characters :/ . But it may be hidden and/or uncommented and hard to find with simple `grep` patterns.

**Comment by jwilm** [comment]
I didn't mean to suggest it handles ACS characters specially. Rather, I expect there's a difference of how the fallback font size is chosen.

**Comment by mathstuf** [comment]
Ah, OK. I'll make a note to search for that.

**Comment by astier** [comment]
I have also issues with such gaps. I am not sure if this helps but maybe some inspirations to solve this issue could be taken from a patch for st called [boxdraw](https://st.suckless.org/patches/boxdraw/). It handles drawing of graphic lines and block characters such as those used by dialog, tree, tmux very nicely.

**Comment by chrisduerr** [comment]
> I have also issues with such gaps. I am not sure if this helps but maybe some inspirations to solve this issue could be taken from a patch for st called boxdraw. It handles drawing of graphic lines and block characters such as those used by dialog, tree, tmux very nicely.

Implementing our own fonts to work around shitty terminal fonts is not an option. We're supposed to render glyphs, not arbitrary data.

**Comment by mathstuf** [comment]
I agree that custom fonts is not a suitable solution here. It's more about "why is Alacritty rendering the same font differently from urxvt?". The font has the information available, but it doesn't seem to be used here? And Terminus is a terminal font and meant for it, so it having broken ACS would be surprising to me.

**Comment by chrisduerr** [comment]
There are a lot of different ways to render fonts, so some differences between terminals is not surprising at all. Alacritty's font size is in points for example, but I think URxvt uses pixel size. And size obviously matters here.

But you'd still be able to fix these issues by changing the glyph metrics/offsets in the Alacritty configuration file.

The only real actual problem here that Alacritty needs to fix is the aliasing of overlapped glyphs.

**Comment by mathstuf** [comment]
OK. An FAQ entry to point people to the metrics in the configuration would be nice as well (with an example?).

**Comment by kchibisov** [comment]
I guess you can read your config file and change things to your needs, this is not something hidden from you? Why do we need a `FAQ` entry for that? I also never had a font that leave gaps on my system with various font sizes. I feel like bitmap fonts don't have such glyphs most of the time you can try to test it by increasing font size for some time when such glyphs are shown, at some point your bitmap font won't grow anymore.

**Comment by mathstuf** [comment]
Right. I get about 4 font increases in urxvt before it stops (I need to recompile a modern alacritty to test it out again). It also only grows in discrete steps (e.g., 2 and 3 steps up are the same size). I've also never seen Terminus have gaps before: it's just alacritty that is doing it.

I guess I'm asking for guidance to be available when "my font works fine in another terminal, why is alacritty different?" (which seems to be the case here).

**Comment by avih** [comment]
> Implementing our own fonts to work around shitty terminal fonts is not an option.

While I completely agree that this should be the case, in practice alignment of box-drawing glyphs (U+25XX) is many times very far from "just works". It depends on fonts, and size, and scaling, and line/character spacing, and antialiasing, and rasterization hinting and so many factors that disregarding it as "shitty terminal fonts" doesn't do justice with this problem IMHO.

That's why various test files call it "alignment test", and that's why some terminal work around it (and it's definitely a workaround hack). VTE enables this hack by default, Konsole has an option to do it, st has a patch for it (which I wrote, because I really like that it aligns nicely, but i'm not willing to bend backwards with font selection and scaling etc to get it right), etc.

Dismissing it as a font issue might be technically correct, but users will keep wanting to have it rendered nicely, and you will have to keep fighting them and tell them to use different font/antialiasing/hinting/whatever. IMHO this will just never satisfy the users.

**Comment by chrisduerr** [comment]
> IMHO this will just never satisfy the users.

And there's absolutely no problem with that. Users are generally never satisfied, but they're free to pick their priorities and choose the best fit based on them.

**Comment by avih** [comment]
> And there's absolutely no problem with that.

That depends on your point of view, but sure, it's a very valid point of view.

**Comment by kchibisov** [comment]
>Dismissing it as a font issue might be technically correct, but users will keep wanting to have it rendered nicely, and you will have to keep fighting them and tell them to use different font/antialiasing/hinting/whatever. IMHO this will just never satisfy the users.

I've seen only a few fonts that don't align properly tbqh. Most fonts implement those chars in a way to align nicely, so they make those chars to overlap a bit, I don't see much reason to have our own builtin font to solve such task.

**Comment by chrisduerr** [comment]
I see no reason to keep this open though. There's already tracking issues for font fallback configuration (#957) and the text composition issues (#118). Other than that, there's no intention to change how box drawing characters are rendered.
