### ISSUE TITLE
Line-wrapping breaks URLs

### ISSUE THREAD

**Issue by aleksijuvani** [alacritty/alacritty#8321]
![image](https://github.com/user-attachments/assets/a3eee431-ef66-42f9-b316-a4d69259127e)

If line-wrapping causes an URL to be split into multiple lines, only the first line will be highlighted on hover. Clicking the URL doesn't work correctly either; it will navigate to an address corresponding to the highlighted part (i.e. it is also cut off).

### System

OS: Windows
Version: alacritty 0.14.0 (22a4475)

**Comment by kchibisov** [comment]
if line is not naturally wrapped, it'll happen, likely conpty just breaks things in-between since it's a multiplexer.

**Comment by aleksijuvani** [comment]
To clarify, there are no line break characters in that text; the text is wrapping because of the window size (and will reflow if I resize the window). So, as an end-user I don't really care if it's ConPTY that's causing the wrapping or whatever; what I'm experiencing is a program that makes links clickable for me, and when I click on a link, that link doesn't work.

**Comment by kchibisov** [comment]
conpty is a layer we can not control, if you don't want that, don't use windows. All windows bugs you may observe are due to it. We can not do anything with it since it's on microsoft side of things, since it's the way you get pty on it.

You can write heuristics or so to make multi-line matching, but it's wrong since you'll highlight incorrect things by doing so.
