### ISSUE TITLE
Setting custom keybinding with command not working

### ISSUE THREAD

**Issue by omagdy7** [alacritty/alacritty#8328]
I am trying to set a custom keybinding to run a custom script but it's not working here is how I am trying to do it.

[[keyboard.bindings]]
key = "F"
mods = "Control"
command = { program = "/bin/bash" ,args = ["-c", "$HOME/.scripts/tmux-sessionizer.sh"]}

and I also tried full path without $HOME

I am currently using this as a hack
[[keyboard.bindings]]
key = "F"
mods = "Control"
chars = "$HOME/.scripts/tmux-sessionizer.sh\r"

for whatever's worth I can't seem to make the simplest example work:
[[keyboard.bindings]]
key = "F"
mods = "Control"
command = { program = "/bin/echo" ,args = ["hello"]}

I have read the docs here: https://alacritty.org/config-alacritty.html and don't really no what I am doing wrong

### System
OS: Linux
Version: alacritty 0.14.0 (22a44757)
Linux/BSD: Wayland, Hyprland

**Comment by kchibisov** [comment]
Anything you spawn will be launched separately and not attached into your terminal session. Like if you want to run e.g. `/bin/echo` in your shell, you should really bind it in _shell_ instead, since you want to run it in it as interactive command.

The chars works since it kind of emulates typing-in into program you have in a foreground. Also, if you use tmux, you could have more like with tmux bindings directly as well (though, if you want them in bash, you need things bounded in bash).
