### ISSUE TITLE
Feature request: Command to copy selection as ANSI to clipboard

### ISSUE THREAD

**Issue by crumblingstatue** [alacritty/alacritty#8342]
As far as I can tell currently alacritty only supports copying plain text to the clipboard, but it would be cool if it supported copying the selection as ansi.

Discord for example supports ansi syntax highlighting, and with alacritty support, I could easily copy paste colored rustc diagnostics into Discord.

**Comment by nixpulvis** [comment]
I thought this was sorta a neat idea, can't find the duplicate. Was this already rejected, or is it just something nobody's coded up yet?

**Comment by chrisduerr** [comment]
> I thought this was sorta a neat idea, can't find the duplicate. Was this already rejected, or is it just something nobody's coded up yet?

It's complicated. There's an issue around for copying things both with and without escape sequences to pipe to external programs. There were also PRs around at some point, however the issue has mostly been around making this work for the scrollback since it takes a **very** long time to copy that data with 100k lines.

I'm too lazy to look for the issue, but it's something that would definitely be considered if it's clean enough. If someone actually wanted to get this merged they should probably look at the closed PR and maybe start with an implementation that only copies the bottom of the grid or visible area.
