### ISSUE TITLE
Optimize fontconfig fallback

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#965]
There's some ideas in #456 which are worth pursuing to improve fallback performance. Specifically, it added caching for results of various fontconfig operations like `font_sort`. Additionally, it might be a huge win to store a custom `FontSet` which is the set of all fonts which have so far been used for fallback.

**Comment by loveencounterflow** [comment]
IMHO I don't think fontconfig is a very good piece of software for a number of reasons. One purely practical reason to observe fontconfig font substitutions would be that they are so prevalent on Linux and 'somewhat work'; everything else that I know about fontconfig makes me want to rip it out of my system rather sooner than later. It's altogether a trainwreck built on wrong assumptions using a hellishly convoluted and poorly documented XML configuration that wants to cover everything but achieves very little. I'm not qualified to post a full-fledged rant here, but let me just point out that 

* you **cannot target single codepoints or ranges of codepoints** in fontconfig, meaning that wherever you insert a given font into the the font stack, all of its glyphs will share the same priority. This feature—named font selection by codepoint, for which see below—which is absolutely essential to build virtual fonts, has been requested by users for years but never got implemented.

* fontconfig is wrongly assuming that configured language is the primary point to decide about displaying a given codepoint using the one or the other set of rules. While this makes sane font selections ridiculously complicated, it **can never work from the get-go in most cases** because most environments lack that piece of data. Sure, you have your system configured to use the de_DE or the en_US locale, but what happens when you write an email in French? In practice, this assumption often leads to a jarring jumble of different fonts in different styles on Chinese and Japanese web pages, depending on what parts of what rules happened to be triggered by a given codepoint.

As a side effect of the above, writing your own fontconfig rules is extremely error prone, and even when you achieve what you wanted in some programs, you will likely mess up font display in other software.

Most terminal emulators that I have tested so far offer two choices for display: Use the system monospaced font, or select one from the dropdown. Disclosure: I managed to get like 85% what I wanted (each of 85.000 CJK codepoints in a font of my choice) using the system font choice and writing [my own `fonts.conf`](https://github.com/loveencounterflow/font-configuration), but I also messed up the display of quite a few webpages and less-important applications.

The alternative I see to using fontconfig is a font selection mechanism that is patterned on CSS3 `@font-face` and `unicode-range`. In fact, https://github.com/kovidgoyal/kitty#font-control promises to deliver exactly this (I'm installing dependencies as I'm writing, so I can't yet say whether it works). 

In fact, I think font selection should be done by a separate piece of software that offers the potential to be re-used across applications. A minimal viable solution could have the capability to identify fonts (optionally via filepaths to circumvent fontconfig interventions and the many, many vagaries that have been constructed around font-selection-by-name, what with true vs simulated italics and bold faces etc), link (ranges of) Unicode codepoints with fonts, and offer a way to stipulate whether a codepoint should be rendered as normal (aka 'half') or double (aka 'full') width.

**Comment by jwilm** [comment]
Interesting! Thanks for the detailed feedback about fontconfig. It seems that supporting something like `unicode-range` would actually be really straight-forward and could be added as part of the upcoming Alacritty font configuration changes: #957.

**Comment by loveencounterflow** [comment]
You're welcome! I'm ready to think more about this subject, as I have to do anyhow for my work where I'm faced with having to select the right font for the right codepoint in various applications, one of them being a MarkDown -> (Xe)(La)TeX -> PDF typesetting workflow, the other being text editors, web browsers and the command line. 

One of the most valuable tools that I've been using over the years is [BabelMap](http://www.babelstone.co.uk/Software/BabelMap.html), a Windows Unicode viewer that runs fine on Linux under Wine. For years this was virtually the only convenient tool I had to look up how exactly a given codepoint renders in a given font without being mislead by font substitions, and also vice versa to see what codepoints were supported by a given font. This unassuming free tool does it better than many fat and costly applications manage to, and it does so in very simple ways. I just opened it to have another look at its Composite Font Configuration dialog, where you can select Unicode block by block and assign a different font to each one from a selection list that has a figure for % coverage and a preview. If that wasn't enough, you can ex- and import your settings; turns out the author uses a simple XML format:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<CompositeFont unicode="10.0" lang="en">
	<Block start="0000" end="007F" name="Basic Latin">Sun-ExtA</Block>
	<Block start="0080" end="00FF" name="Latin-1 Supplement">Sun-ExtA</Block>
	<Block start="0100" end="017F" name="Latin Extended-A">Sun-ExtA</Block>
	<Block start="0180" end="024F" name="Latin Extended-B">Sun-ExtA</Block>
	<Block start="0250" end="02AF" name="IPA Extensions">Sun-ExtA</Block>
	<Block start="02B0" end="02FF" name="Spacing Modifier Letters">Sun-ExtA</Block>
	<Block start="0300" end="036F" name="Combining Diacritical Marks">Sun-ExtA</Block>
...
	<Block start="F0000" end="FFFFF" name="Supplementary Private Use Area-A">Aegyptus</Block>
	<Block start="100000" end="10FFFF" name="Supplementary Private Use Area-B">Samyak Devanagari</Block>
</CompositeFont>
```

I'm not into XML but I can totally live with *this* level of complexity. This is like 80 or 90 percent of what fontconfig should have ever been about. 

Basically what is needed in my opinion is the ability to name a 'display flavor' and then add physical fonts in a ranked listing where later mentions overrides earlier mentions (fontconfig got this one wrong which is why you always have to explicitly prepend your own rules to the set of existing rules; CSS got it right). The ranked listing should provide a way to specify single codepoints or ranges of codepoints; probably there should be an option to specify what to do with 'holes' in the font (i.e. with codepoints that provide no glyph; most of the time, but not always, you'll want missing glyphs to be filled in from fonts lower in the ranking). 

BTW over the years I've come to reject the whole idea of having one font with several 'styles' such as italic, bold or bold-italic. These terms largely only apply to Western typography anyway; what you really want is a sound collection of typefaces that go together well in the same document. Think of it like an oldskool typesetter: Whatever is put together in one case is a font; when you want to emphasize a word, set a quoted passage, or add a headline, you have to break out another case (another font, i.e. another file). One huge advantage of digital type, at least vector type, is that one 'master' may be used for any number of sizes; but, as in lead type, if you typeset in LucidFooRoman and there's no italics coming with that typeface, just go and grab another typeface that harmonizes. 

As far as terminal emulators are concerned, I think if you want styled type at all, then what you really want is configurable, named 'flavors' of type. In this thinking a whole layer of complexity that has never really worked satisfactorily is summarily done away with.
