### ISSUE TITLE
Background blur

### ISSUE THREAD

**Issue by chriskrycho** [alacritty/alacritty#972]
Which operating system does the issue occur on? **macOS 10.13.2**

If on linux, are you using X11 or Wayland? **N/A**

Transparent background works nicely; however, for many contexts this is essentially unusable; you also need a background *blur* setting (as Terminal.app and iTerm.app have on macOS).

**Comment by maximbaz** [comment]
Interesting request 🙂 
I was curious if this request applies to Linux too - apparently not, because compton already allows this:

-------

![image](https://user-images.githubusercontent.com/1177900/34395549-66837650-eb61-11e7-8909-c0c77bd4f918.png)

--------------

If you are interested to achieve similar results, play with compton's `--blur-background` and `--blur-kern` CLI arguments.

**Comment by unphased** [comment]
fwiw, this doesn't invalidate the issue in any way (I would love to have a blur option, in fact), but with iTerm2 I've found that I always end up setting no blur and leaving it to a low transparency setting so I can at least get some transparent effect at least: The blurring always incurs a substantial cpu load increase. If this can be done in a way that effectively leverages the GPU, it would be lightweight enough to not appreciably impact battery life. Otherwise, it's less attractive at least for me.

**Comment by mikelui** [comment]
Anyone looking at implementing this can also look at KDE's new blur implementation which is meant to be lightweight:
https://www.reddit.com/r/kde/comments/7szqqk/i_implemented_a_new_blur_effect_in_kde_it/ 

The technique used is described in: https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-26-50/siggraph2015_2D00_mmg_2D00_marius_2D00_notes.pdf

**Comment by diversario** [comment]
I'd like to support this (kinda vain, I admit it) request. It's a (very) nice to have.

**Comment by sandangel** [comment]
may I ask is there any update on this?

**Comment by chrisduerr** [comment]
If there is any progress on an issue, the issue will be updated. Asking about updates when there is none is unlikely to speed things up.

I also do not expect this to get fixed anytime soon, since it's very low priority for me. Unless someone else sends a simple PR which adds this, it's unlikely to be resolved in the near future.

**Comment by creikey** [comment]
Going to take a look at this... need it for my mac os i3 rice

**Comment by wucke13** [comment]
A side note: Comptons blur used to be quite expensive on the CPU side IIRC, so that is not really a viable option for mobile users. Also, compton != linux, there is a growing crowd of people using Wayland. As such, I as well would like this to be a capability of the terminal. Alacritty already uses the GPU for rendering, hence it might be easier to leverage shaders for the blur as well to get an useful yet efficient blur implementation.

**Comment by kchibisov** [comment]
>Alacritty already uses the GPU for rendering, hence it might be easier to leverage shaders for the blur as well to get an useful yet efficient blur implementation.

This is not how it works, alacritty can't possibly do blur because it doesn't know about contents you have on screen. That being said, blur is done by system's compositor on all display servers  I'm aware of. The only thing that alacritty can do is ask for blur your system's compositor, and hope that it blurs things.

**Comment by wucke13** [comment]
@kchibisov This is not 100% true, technically. There are ways to get some part of the screen buffer, and blur that. Similar as to how a magnifier application or a screenshot tool work. IIRC URxvt supports blur through that as well. It is quite ugly though, because the blur is not updated when the URxvt window moves. My hope would be that this can be improved a lot if the blur is done on the GPU. But an implementation in the compositor definitely is cleaner and can perform way better.

**Comment by kchibisov** [comment]
You can make blur, by making screen shot of the entire screen, sure, but you can't make it work cross platform that way. Also, this is the most stupid way to make blur you can imagine, and I only saw that on X11.

**Comment by DJN1** [comment]
Has anyone had luck getting the blur to work with the KDE Plasma blur? If so, what does the config file look like.

**Comment by master-of-zen** [comment]
^ Same

**Comment by yashank09** [comment]
+1 for Linux KDE plasma. Not to crowd comments but +1...

**Comment by chrisduerr** [comment]
There is no blur, that's why this issue is still open. Please don't reply to issues unless you have relevant comments.

**Comment by yashank09** [comment]
Found a hack for KDE blur! Not too sure about the implementation itself, but found it [here](https://www.reddit.com/r/kde/comments/6jzuwu/konsole_and_yakuake_blur/djilli2/) and tweaked it for Alacritty. 
Right when I was about to switch from this beautiful terminal! 
Add the following to your .zsh or .bash config, make sure you have xdotool and voila! 
```
if [[ $(ps --no-header -p $PPID -o comm) =~ '^alacritty$' ]]; then
        for wid in $(xdotool search --pid $PPID); do
            xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
```

Now I need to figure out if and how to mess with the blur opacity itself.. maybe messing with Alacritty's opacity would do.
If devs feel this implementation isn't too expensive(shouldn't be for the fastest terminal), maayybe this could be an opt-in feature for linux/KDE users? Maybe just mention in the docs?

**Comment by chrisduerr** [comment]
> If devs feel this implementation isn't too expensive(shouldn't be for the fastest terminal), maayybe this could be an opt-in feature for linux/KDE users?

The problem with this is that it's not a standard by a long shot. Implementing a feature for a single desktop environment across all platforms is not something I am interested in.

**Comment by Nishant0073** [comment]
To enable blur effect in Alacritty install Kwin script "Force Blur"  then add Alacritty in Force blur script setting and reboot your system you will be able to see transparent blur background in Alacritty !! .

**Comment by yashank09** [comment]
> To enable blur effect in Alacritty install Kwin script "Force Blur" then add Alacritty in Force blur script setting and reboot your system you will be able to see transparent blur background in Alacritty !!!

could you mention what the script looks like? For some reason that code I mentioned stopped working, maybe cause I recently integrated tmux? Your script would be helpful :smile:

**Comment by master-of-zen** [comment]
@yashank09 Thanks) worked right away!

**Comment by yashank09** [comment]
@master-of-zen we're probably pissing off the maintainers, but I'd suggest using @Nishant0073 's solution for KDE, specially if you have force-blur enabled already. Im sure it'll be less of a performance hit that way.

**Comment by Misko-2083** [comment]
Taking a screenshot of an area and blurring the image is possible, as you can see in my video [https://www.youtube.com/watch?v=ZOBBZv9B3Q8](https://www.youtube.com/watch?v=ZOBBZv9B3Q8)
The question is how to take a screenshot of an area behind the window?
In other words: is there a way to fetch an image of planes bellow the window and blur it?
However the image can not be refreshed, unless... of course, the window is closed and the screenshot is retaken.
We can even draw blurred image on a cairo surface: [https://www.youtube.com/watch?v=n6EyhoC5T9Y](https://www.youtube.com/watch?v=n6EyhoC5T9Y)
The brurmenu, as seen in the previous video, is here: https://github.com/Misko-2083/blurmenu
For blurring, stackblur algorhytm is ideal, very fast, a few milliseconds is required to blur entire desktop + it's multi-threaded.
Above all it gives very good image results.

**Comment by doctor-amaton** [comment]
By using [window-vibrancy](https://lib.rs/crates/window-vibrancy) I was able to `apply_blur` during `fn create_window` on `Processor`. This library also supports Acrylic but the performance when moving the window is very slow (I have an RTX 3070).

I haven't tested macOS but I could do so later today.

![image](https://user-images.githubusercontent.com/46565598/166973746-7c294a0c-92ba-44c8-bf04-ae2f3ae3becb.png)

**Comment by adamazing** [comment]
> By using [window-vibrancy](https://lib.rs/crates/window-vibrancy) I was able to `apply_blur` during `fn create_window` on `Processor`. This library also supports Acrylic but the performance when moving the window is very slow (I have an RTX 3070).

@doctor-amaton, I'm able and very keen to help you test on macos/windows!  

FWIW, I'd already started looking at this, but just starting out with Rust and [didn't get far](https://github.com/adamazing/alacritty/pull/1/files) 😅 . I've just pushed what little I've done to my own fork and created a PR on my own master branch so the diff is easy to see. I've been banging my head against a wall trying to build on Windows -- `cargo build` on master branch succeeds, `cargo build` on my spike branch fails to link.

**Comment by doctor-amaton** [comment]
@adamazing that's great! 

I'm not sure what issue are you running into for building on windows, but I'll try to build your branch and if I find something I'll update this comment. We're so close to a PR for this.

**Comment by Dakai** [comment]
I have achieved a nice transparent and blur effect with the config with xdtool script in the .zshrc file and a plugin from [xiyaowong/nvim-transparent](https://github.com/xiyaowong/nvim-transparent)

```
#alacritty hack for blur in zshrc

if [[ $(ps --no-header -p $PPID -o comm) =~ '^alacritty$' ]]; then
        for wid in $(xdotool search --pid $PPID); do
            xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
```
![2022-10-08_23-14](https://user-images.githubusercontent.com/1525214/194714776-305a2d31-eefe-4763-a4c9-37d4363c0dad.jpg)

My system is Manjaro with KDE Plasma

**Comment by swapneelb** [comment]
@chriskrycho @adamazing @yashank09  @Dakai  @doctor-amaton  has anyone been able to blur alacritty on macos?
If yes, could you please tell me how?

**Comment by sploders101** [comment]
> > By using [window-vibrancy](https://lib.rs/crates/window-vibrancy) I was able to `apply_blur` during `fn create_window` on `Processor`. This library also supports Acrylic but the performance when moving the window is very slow (I have an RTX 3070).
> 
> @doctor-amaton, I'm able and very keen to help you test on macos/windows!
> 
> FWIW, I'd already started looking at this, but just starting out with Rust and [didn't get far](https://github.com/adamazing/alacritty/pull/1/files) 😅 . I've just pushed what little I've done to my own fork and created a PR on my own master branch so the diff is easy to see. I've been banging my head against a wall trying to build on Windows -- `cargo build` on master branch succeeds, `cargo build` on my spike branch fails to link.

I just decided to try this because I've been working with that lib for one of my personal projects so I took a few minutes to hop around and find this function on my own. Unfortunately, it appears on MacOS, window vibrancy and OpenGL are mutually exclusive. If I enable vibrancy, I get no video. A pty is still allocated and I can interact with the console, verifying the commands ran with another working terminal, but I'm doing so blind because the OpenGL code doesn't make it to the display. I seem to recall having trouble with this when I used electron too, in which case that would explain it, since Chrome uses (or at least used) OpenGL for HW acceleration.

Then again, I could be totally off-base. I haven't done much work in the non-web-desktop-application space other than QML, so I'm not familiar with the APIs and limitations. If someone else wants to take a crack at it, I'm really hoping you can prove me wrong.

**Comment by kochie** [comment]
Alacritty should automatically support vibrancy settings on MacOS when https://github.com/rust-windowing/winit/issues/538 is complete as it uses `winit` to create and manage windows.

**Comment by MarijnS95** [comment]
For future reference, Windows Mica/Acrylic (two forms of background blurring, consistent with other themed apps) have been exposed in Winit in https://github.com/rust-windowing/winit/pull/3257. The PR author seems to have used Alacritty to test it, but I don't see a PR here that's calling into the new API yet.

**Comment by kchibisov** [comment]
Can't this API be wired to `set_blur` in winit?

**Comment by MarijnS95** [comment]
@kchibisov indeed, that's exactly what I proposed in https://github.com/rust-windowing/winit/pull/3257#issuecomment-2263938643.

**Comment by kchibisov** [comment]
Then once it's wired it'll just work in alacritty since we call generic blur API in winit.
