### ISSUE TITLE
keybindings/ forward keys support

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#985]
Which operating system does the issue occur on?

masOS 10.13.2

I discovered this while using/ trying [micro](https://github.com/zyedidia/micro)
they recommend iTerm cause Mac Terminal does not do a good job as well but alacritty is actually even worse as far as I've seen.

Wanted to bring this up here cause I actually use alacritty with tmux daily and would like to see this improved or at least hear someones opinion on this issue.

thanks 

## steps to reproduce
1. get micro
2. open a file/ type some text
3. alt+shift+(left/right) is supposed to select a word but alacritty just does strange things/ moves the word
3.1 or try `shift+(up/down)` to select lines (nothing happens, Mac Terminal just moves the courser)

to debug this further the [following statement](https://github.com/zyedidia/micro/issues/974#issuecomment-354831774) from a different context might help:
> Unfortunately most terminals do not differentiate between Shift-Backspace and Backspace so it is impossible for micro to know which was pressed. Micro just always assumes backspace is pressed. You can see this in micro if you use the nightly with the > raw command which will show the raw escape sequences micro is receiving. For shift-backspace and backspace, the escape sequence is the same.

[and](https://github.com/zyedidia/micro/issues/974#issuecomment-354878299)
> The issue is that in mac, alt+keys sends unicode characters instead of letting the application do whatever it wants (in this case send the escape sequences to micro). To fix this in iTerm2, go to Preferences->Profiles->Keys and select Esc+ for Left option key.

**Comment by giorgiga** [comment]
@monouser7dig

You can specify keybinding with multiple modifiers in `alacrtitty` by spearating modifiers with pipe characters. Try eg. `{ key: Left, mods: Shift|Control, chars: "characters to send" }`.

Key names are from https://github.com/jwilm/alacritty/blob/master/src/config.rs#L1614

Modifiers are `Super`, `Alt`, `Shift` and `Control`. You can also use `Command` and `Option` as aliases for `Super` and `Control`. (`Super` is the "Windows Key")

I have not tried all combinations required by `micro`, not investigated what they are, but what you require seems well within the capabilities of `alacritty`.

BTW: you bind arbitrary keystrokes in `Terminal.app` too - see "Preferences" and then "Keyboard"

**Comment by monouser7dig** [comment]
I am missing something here, I basically (think I) want to send `Alt` when I press `Alt` and so forth.
What characters am I supposed to send? And why would I send the same characters for two keys? (`Shift|Control`)

at least it seems like an user error, so easy to fix 😄 

thanks

**Comment by giorgiga** [comment]
My bad for mixing things up, sorry 😄 

You cite two (couples) of keypresses: alt+shift+(left/right) and shift+(up/down).

Shift+(up/down) are already mapped in the default alacritty cfg file ([linux](https://github.com/jwilm/alacritty/blob/master/alacritty.yml), [mac](https://github.com/jwilm/alacritty/blob/master/alacritty_macos.yml)) and currently send `\x1b[1;2A` and `\x1b[1;2B`.

Since apparently they don't work in `micro`, it must be expecting something else for those keypresses... so you'll have to change the mappings to whatever `micro` expects.

In order to add the four mappings you cite, open your `alacritty.yml` and, under `key_bindings:`, add the following four lines:

    - { key: Up,       mods: Shift,     chars: "shift+up pressed" }
    - { key: Down,     mods: Shift,     chars: "shift+down pressed" }
    - { key: Left,     mods: Alt|Shift, chars: "alt+shift+left pressed" }
    - { key: Right,    mods: Alt|Shift, chars: "alt+shift+right pressed" }

Also, scroll down and comment out (add a leading `#`) the existing mappings for Shift+(up/down):

    #  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
    #  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }

Now, if you restart alacritty, the four keypresses will print some text to the screen, showing they have been remapped.

After verifying the above works (now that I think of it, I've only checked on the current development head – so it might actually not work in the version you have installed), you'll have to find out what `micro` expects for the keypresses and configure it.

Prtotip: while dealing with control sequences, "escape" refers to the byte `00011011`, that, depending on what you are reading, you'll find referenced by the symbolic name `ESC`; by the hexadecimal `0x1B`, `\x1b` or `\x1B`; by the octal `\033`; or by the escape sequence `\e`.

Terminal applications do not receive "keypress" events from the OS. ("pardon" and "skip the rest" if you already know this)

What happens is that `alacritty` receives a keypress event from the OS,
it translates it to a sequence of bytes and then sends that sequence to `micro` (* in reality are only slightly more complicated, but that is essentially what happens).

Historically, each ([computer terminal](https://en.wikipedia.org/wiki/Computer_terminal)) had its own set of slightly incompatible special sequences; nowadays one may more or less assume that [xterm sequences](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html) are in use.

BTW: This is why applications like `alacritty` are referenced to as "terminal _emulators_": they emulate an actual terminal, either a physical one like the VT100 or an abstract one like xterm.

**Comment by monouser7dig** [comment]
that's a good explanation!

good news:
1. Shift+Up actually works in alacritty, I mixed something up (it does not work in tmux)
2. `- { key: Left,     mods: Alt|Shift, chars: "alt+shift+left pressed" }` prints the characters as you said

bad news
3. Shift+up does not work though tmux 😞 
4. I basically have no idea what micro expects as an alt key


> one may more or less assume that xterm sequences are in use.

that seems to be [what micro expects](https://github.com/zyedidia/micro#macos-terminal)
> For best keybinding behavior, choose xterm defaults under Preferences->Profiles->Keys->Load Preset.

maybe I should be able to find them in [here xfree86](https://www.xfree86.org/4.8.0/ctlseqs.html)...

feels a bit like 1984 trying to deal with these low level things

**Comment by giorgiga** [comment]
I'd try `\x1b[1;4` and then `A`/`B`/`C`/`D` for alt+shift+up/down/right/left.

_Disclaimer: I am not sure, I did not really read the xterm spec, I did not verify: actually I have no idea_

If all fails you can look into the documentation/source of `micro` (or the xterm documentation if you feel really brave). The `micro` devs can most probably help, too.

PS:
if you find out what the proper control sequence for the various alt+shift+arrows and similar is, I am  sure @jwilm will appreciate being informed/pointed to your source in order to add the sequences to the default mappings (if I were him I would like to know, at least)

**Comment by monouser7dig** [comment]
nice work!

```
  - { key: Right,     mods: Alt|Shift, chars: "\x1b[1;4C" }
  - { key: Left,       mods: Alt|Shift, chars: "\x1b[1;4D" }
```
actually works for selecting words now! and alt+backspace to delete the last word works as well btw.

It does not work in tmux though, although when I select to show the `raw output in micro nightly` I see that it receives the correct key-presses, but just does not act accordingly


 ### what is still missing/ not working are (from micro again)
```
// Emacs-style keybindings
    "Alt-f": "WordRight",
    "Alt-b": "WordLeft",
    "Alt-a": "StartOfLine",
    "Alt-e": "EndOfLine",
```
I do not use or endorse emacs but still....

more importantly 
```
// Multiple cursors bindings
    "Alt-n": "SpawnMultiCursor",
    "Alt-p": "RemoveMultiCursor",
    "Alt-c": "RemoveAllMultiCursors",
    "Alt-x": "SkipMultiCursor",
```

**I think if one could solve one of them, all of them should be solved?**
additionally any idea about the tmux weirdness? (although this seems like a secondary step to me)

I actually looked through some parts of the keybindings in the micro source but [did not find any cryptic symbols.](https://github.com/zyedidia/micro/blob/a814677b51504a118647b26307d565aefb74a385/cmd/micro/bindings.go#L25)

**Comment by giorgiga** [comment]
I can confirm `Alt+<letter>` are bindable and I guess this solves the issue for what concerns `alacritty`.

Finding out what specific control sequences are expected by `micro` seems to be an issue regarding `micro` more than `alacritty`, so I dared commenting in [this issue](https://github.com/zyedidia/micro/issues/974) and asking for help from the `micro` devs.

After we find out about the other control sequences, we might come back to `alacritty` and see if they should be added to the default config (or maybe only documented: for one, I would expect/prefer my Alt key on macOS to behave as usual and allow me to input extra characters).

Does this seem reasonable to you, @monouser7dig?

**Comment by monouser7dig** [comment]
> Does this seem reasonable to you, @monouser7dig?

yeah sure

> or maybe only documented: I would expect/prefer my Alt key on macOS to behave as usual and allow me to input extra characters

yes

> I can confirm Alt+<letter> are bindable

> Finding out what specific control sequences are expected by micro seems to be an issue regarding micro more than alacritty

3rd yes 😄 let's wait and see (hopefully)

and the funny tmux thing
> It does not work in tmux though, although when I select to show the raw output in micro nightly I see that it receives the correct key-presses, but just does not act accordingly

is also left as a mystery which maybe can be solved by someone from micro who probably is the very active owner

**Comment by kchibisov** [comment]
The most tihngs you've mentioned was due to the lack of default bindings your mentioned, they were added #2785

**Comment by webberwang** [comment]
Is there no way to send just the Modifier key to vim? Couldn't alacritty translate those modifiers and send it by itself
